### PR TITLE
Ref to getter function in docs/miscellaneous.rst

### PR DESCRIPTION
**Pull request by jamesray1**

### CODE REVIEW

**Comment by chriseth** [comment]
Wonderful, thanks a lot!

There is a test error because I think that the label you are referencing does not exist (they are not automatically generated for all headers).

I think you have to put

```
.. _getter_functions:
```

in the line above the "Getter Functions" header and then use the label like that.

**Comment by jamesray1** [comment]
Done, I made a pull request for 
`_getter_functions:`
above the Getter Functions header.

**Comment by jamesray1** [comment]
Sorry I don't know how to verify whether the reference will work. When I click on it in preview it just goes to the top of the page.

**Comment by jamesray1** [comment]
@chriseth

**Comment by chriseth** [comment]
The tests also fail for this pull request.

**Comment by jamesray1** [comment]
Sorry I assume you mean these tests, I will pay more attention to them in future.

2017-07-28 11_16_00-ref to getter function by jamesray1 pull request 2486 ethereum_solidity

**Comment by jamesray1** [comment]
This needs #2658 to be merged first.

**Comment by jamesray1** [comment]
@chriseth, the Travis CI build passed.

**Pull request merged**
