### PR TITLE
Fix merge conflicts

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by hrkrshnn** [comment]
I'll fix these conflicts

**Comment by chriseth** [comment]
Thanks! Please just force-push to this branch.

**Comment by hrkrshnn** [comment]
Weird that isoltest is successful now, yet soltest fails on a semantic test!

**Comment by chriseth** [comment]
that might be due to the "force abi v2" option (one recent pr merged from develop changed from "pragma experimental ABIEncoderV2" to "pragma abicoder v2")

**Review by hrkrshnn — APPROVED** [review]

**Comment by hrkrshnn** [comment]
Removing "compileToEwasm: also" option from 4 tests cases worked.

**Pull request merged**
