### PR TITLE
Yul interpreter: Out of bounds mloads return zero

### PR DESCRIPTION
**Pull request by bshastry**
fixes https://github.com/ethereum/solidity/pull/7324#issuecomment-527334631

### CODE REVIEW

**Review by ekpyron — APPROVED** [review]
Makes sense to me... any idea why this was ever explicitly written to not just return zero?

**Comment by bshastry** [comment]
> Makes sense to me... any idea why this was ever explicitly written to not just return zero?

I'm not sure. On a different note, we didn't run into this problem before #7324 because mloads were never optimized out.

**Comment by chriseth** [comment]
Interesting! This only happens for mloads at addresses of `u256(-31)` up to `u256(-1)`, i.e. when the load fetches data outside the addressable range. Is this behaviour even specified for the EVM?

**Comment by chriseth** [comment]
Interesting! Github also closes PRs if you only reference to fix a comment in the PR...

**Comment by ekpyron** [comment]
Hm - I should have actually looked into the implementation of ``accessMemory``... I'm actually not sure anymore if this is in fact a good fix...

**Pull request merged**
