### PR TITLE
Removed note on tightly packed properties

### PR DESCRIPTION
**Pull request by OTTTO**

### CODE REVIEW

**Comment by OTTTO** [comment]
I found this to not be true while testing gas use.  
Let me know if I am mistaken.
Thanks

**Comment by chriseth** [comment]
Can you provide an example? Also note that we recently fixed a bug that more or less disabled the optimizer in that case. The relevant pull request is not yet merged.

**Comment by OTTTO** [comment]
Struct definition
```
struct Curve {
    CurveType Type;
    uint128 Start;
    uint128 Multiplier;
}
```
inline initialization – gasUsed: 78140
```
function setCurve(...) {
    oracles[origin].curves[specifier] = Curve(curveType, curveStart, curveMultiplier);
}
```
individual initialization – gasUsed: 78372
```
function setCurve(...) {
    oracles[origin].curves[specifier].Type = curveType;
    oracles[origin].curves[specifier].Start = curveStart;
    oracles[origin].curves[specifier].Multiplier = curveMultiplier;
}
```

**Comment by chriseth** [comment]
Ah ok, but the difference in your example is not that big. The reason why the optimizer does not work properly here is because you do tons of other stuff, since you always re-access the storage item.

Have you tried
```
Curve storage c = oracles[origin].curves[specifier];
c.Type = curveType;
c.Start = curveStart;
c.Multiplier = curveMultiplier;
```

**Comment by OTTTO** [comment]
just tried, i saved 139 gas using that approach.

**Comment by chriseth** [comment]
@OTTTO So this can be closed? Please also try your gas consumption with the nightly build, it should be even better.

**Pull request closed without merging**
