### PR TITLE
[BREAKING] Disallow functions without implementation to use modifiers.

### PR DESCRIPTION
**Pull request by christianparpart**
another trivial one. tests passing locally (soltest, cmdlineTests.sh)

### CODE REVIEW

**Comment by ekpyron** [comment]
My guess would be that you need to fix the contracts in https://github.com/ethereum/solc-js/tree/master/test/DAO for the solcjs tests to pass.

**Review by chriseth — DISMISSED** [review]

**Comment by chriseth** [comment]
Yes, and please note that you have to update the DAO050 directory since there is some logic inside the solidity tests that rename that directory. Running tests locally will probably compile the other files.

**Comment by ekpyron** [comment]
I think the correct one is the ``DAO`` directory (in contrast to the ``DAO040`` directory) - currently the test scripts remove ``DAO040`` and copy ``DAO`` to ``DAO040``, so that the correct files are used as long as the version is not bumped to 0.5.0 (see ``test/solcjsTests.sh``).

**Comment by axic** [comment]
Are there 0.5.0 specific syntax tests for this? If so, are those obsolete?

**Comment by chriseth** [comment]
Please rebase.

**Comment by chriseth** [comment]
solc-js tests still have to be updated it seems.

**Comment by axic** [comment]
Added the solc-js changes: https://github.com/ethereum/solc-js/pull/241

**Comment by axic** [comment]
Rebased and added a changelog entry.

**Review by axic — APPROVED** [review]

**Pull request merged**
