### PR TITLE
fix build on windows

### PR DESCRIPTION
**Pull request by winsvega**
had conflict with existing devcore build on windows

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Why and where is this an issue, @winsvega?

Did you not do a clean build, or something similar?

I agree that looking at re-namespacing and other refactoring to normalize this code in with the rest of the Solidity codebase makes sense, but I don't understand why you would have any breakage right now.

**Comment by winsvega** [comment]
it says devcore already exists in original  repository here 
https://github.com/ethereum/libweb3core/tree/7100def6211338e790e1c124ace6a99079e68cd5/libdevcore

and could not create a target with the same name

**Comment by bobsummerwill** [comment]
What is "it"?   Is this for a local build?

I can only imagine you are seeing this when building on top of an existing "build" folder.

And it's not worth changing anything for that use-case, IMHO.

**Comment by chriseth** [comment]
The libdevcore here and the one in web3core should not overlap because they are never part of the same project. Did we already remove solidity from webthree-umbrella?

**Comment by winsvega** [comment]
```
CMake Error at solidity/libdevcore/CMakeLists.txt:10 (add_library):
  add_library cannot create target "devcore" because another target with the
  same name already exists.  The existing target is a shared library created
  in source directory "/home/wins/Ethereum/umbrella/libweb3core/libdevcore".
  See documentation for policy CMP0002 for more details.
```

**Comment by chriseth** [comment]
This is weird. Do library names need to be globally unique on windows? Are you sure you opened solidity as an unrelated project in your IDE?

**Comment by bobsummerwill** [comment]
It is very weird.    What you describe could ONLY happen if there were clashes within that same workspace.    It has to be a clean build issue, @winsvega.

Just created https://github.com/ethereum/webthree-umbrella/pull/691, to remove solidity from webthree-umbrella, @chriseth.

**Comment by chriseth** [comment]
After having thought more about this: This is actually needed if we want our debian packages to work, because they need globally unique library names. Another solution would be to not split into so many libraries in the first place, for example by deprecating lllc.

**Comment by bobsummerwill** [comment]
Could the content of the orphaned `libdevcore` just be pulled into `evmasm`?

And yes, in general, collapsing down into fewer libraries would make a lot of sense.    Same in 'cpp-ethereum'.    And I'm looking at static linkage too, which is best of all, IMHO.

**Comment by chriseth** [comment]
I will merge this now, we can think about reducing the number of libraries after we have our release.

**Pull request merged**
