### PR TITLE
Fixes broken layout due to misplacement of open-in-remix link in documentation

### LINKED ISSUE #13948: Link to open code blocks in remix breaks the layout of the documentation page on small devices.
## Page
When the documentation is opened in small devices the screen started overflow like this.

Screenshot (27)

https://docs.soliditylang.org/en/v0.8.18/introduction-to-smart-contracts.html

## Abstract

I think there is an issue in CSS file. I made some changes and it's gone, but the link arrow to remix IDE is not visible properly. We can move it besides heading to solve this problem maybe.
Screenshot (26)

Let me know how can we work on this 😊.

### PR DESCRIPTION
**Pull request by RupeshWadne**
Fixes https://github.com/ethereum/solidity/issues/13948.

I just made some changes in CSS file and the result looks like this.
Let me know is this enough or suggest me something better is needed.

Screenshot (28)

### CODE REVIEW

**Review by r0qs — CHANGES_REQUESTED** [review]
Hi @ShubhamWadne thank you very much for your contribution. I had a look at your changes and have some comments.

It seems that the hover over the button is bit out of place and kind of "expands" the button when showing the tooltip message, which is a bit strange. I think the message should appear on the top or bottom of the button as an independent popup (i.e. should not expand the button size). See the image below:

2023-02-09-130225_1920x1080_scrot

Also, the button is now overlapping some other parts of the layout, see the example below. It would be nice if it doesn't overlap it.
 
2023-02-09-130714_1920x1080_scrot

**Comment by RupeshWadne** [comment]
Ok Got it. I'll come back quick after fixing this.

**Comment by RupeshWadne** [comment]
I think that we should change the arrow icon to button with text "open in remix", this give direct action to user instead of after hovering over arrow. We can change the p tag into button also solves styling issues. But the code is written in python and I am not  familiar with python I'm a javascript coder. Can you suggest me what should I do now 😕.

**Comment by cameel** [comment]
Regarding changing how this looks, we should get an opinion from @franzihei and @NunoFilipeSantos.

> But the code is written in python and I am not familiar with python I'm a javascript coder. Can you suggest me what should I do now

The Python part is really not that complicated, we can help you change it but I don't think it will really be a big problem once we know *what to change it to*. And that's the actual issue here - note that we don't have direct control over the generated HTML but we're dealing with [docutils](https://docutils.sourceforge.io/docs/) API instead. And the API is defined in terms of an abstract document. This allows the docs to be easily rendered in other formats like PDF or ePUB as well. There may be no concept of anything button-like in these formats. See the list of [body elements](https://docutils.sourceforge.io/docs/ref/doctree.html#body-elements) you can use.

**Comment by NunoFilipeSantos** [comment]
How would a button look when exported to different formats?

**Comment by cameel** [comment]
It would be hidden in most of them. The extension I have written for rendering it specifically excludes everything that is not HTML. Also ePUB, which is technically HTML, but I just didn't want to spend time getting it exactly right there. As for other formats, we'd have to check which ones are also HTML-based but if it's rendering wrong, we can always exclude it. This is really meant only for HTML, but we still have to abide by the docutils API, which is more general than that.

**Comment by NunoFilipeSantos** [comment]
The docutils API supports buttons, right? If so, I don't see any impediment to changing it to a button.

**Comment by cameel** [comment]
I don't see any mention of buttons under [body elements](https://docutils.sourceforge.io/docs/ref/doctree.html#body-elements). I only did a quick search though. There could be something button-like in there.

**Comment by RupeshWadne** [comment]
Ok so I think that we should let the arrow as it is and we can do something
like giving the margin to the code box on the right side and putting that
arrow sign in that space.This can also solve the problem. Just show me
where I should make a change to give that code box margin-right.

**Comment by r0qs** [comment]
> But the code is written in python and I am not familiar with python I'm a javascript coder.

@ShubhamWadne, not sure if I follow, why would we need to do anything in python? I thought that you could just change the style of the link and its container, no? Like adjusting the `top` property and the margin/padding of the `remix-link-container` to position the link correctly in between paragraphs and changing the style of the `remix-link` like you did.

For reference, the generated HTML for that link looks like this:
```html
<p class="remix-link-container">
    <a class="remix-link reference external" href="https://remix.ethereum.org/...">
        <span class="link-icon"></span>
        <span class="link-text">open in Remix</span>
    </a>
</p>
```

> I think that we should change the arrow icon to button with text "open in remix", this give direct action to user instead of after hovering over arrow

About the tooltip message. I agree that it would not be necessary if we have a nice button saying `open in remix`. But this button should fit the layout of the docs. So if you have any idea for its design, please feel free to suggest it :)

If needed, I think you can add some custom javascript in [docs/_static/js](https://github.com/ethereum/solidity/tree/develop/docs/_static/js) and add a listener on the hover event. Not sure if it is worth though. Maybe a nicer `open in remix` button is better? Any opinions on it?

> There may be no concept of anything button-like in these formats.

@cameel we can make the `<a>` tag looks like a button for the `remix-link` class by only changing its css.

**Comment by cameel** [comment]
> not sure if I follow, why would we need to do anything in python?

To change the underlying HTML you'd have to change the Sphinx extension, which is written in Python.

Well, you could technically do that with some extra attached JS but I'd avoid adding another language to the mix. This is just a link, should not really need anything fancy other than styling.

> we can make the `<a>` tag looks like a button for the `remix-link` class by only changing its css.

I'll leave opinions about looks to the others, but just wanted to say I don't see anything wrong with this being styled as a link. Semantically it *is* a link. Things like being visited that apply to links, apply here too. Or with it being a link I'd normally middle-click it to open in a new tab, which is nice to have. With a button I wouldn't necessarily expect that I can do that.

**Review by RupeshWadne — COMMENTED** [review]
I just change the arrow into button. Give me your feedback on it. Is this enough to solve the issue.

**Comment by RupeshWadne** [comment]
I just changed the arrow into into button in this commit

**Comment by RupeshWadne** [comment]
I sorry for messing this up. Actually it's my first contribution and I don't know very much about this. I made my final changes but 2 checks are failing can anyone tell me what can I do now.

**Comment by r0qs** [comment]
> I sorry for messing this up. Actually it's my first contribution and I don't know very much about this.

Hi @RupeshWadne, no problem :)

>  I made my final changes but 2 checks are failing can anyone tell me what can I do now.

Don't worry, those tests are unrelated with your PR. The first one related with the `t_native_test_ext_gp2` test was fixed in the `develop` branch already. So you just need to rebase your branch onto the `develop` (check the git documentation [here](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) if you have never done that).

For the second failed test (`t_native_test_ext_zeppelin`) we need to investigate what is happening, but you don't need to worry with it.

**Comment by RupeshWadne** [comment]
Thank you @r0qs for helping 😊. All checks are successful.

**Comment by r0qs** [comment]
Hi @RupeshWadne thanks for the changes and sorry for the late reply, but the problems mentioned here: https://github.com/ethereum/solidity/pull/13951#pullrequestreview-1291038243 were not fixed. You can test it yourself by running `make html` under the `docs` directory and opening the docs in your browser, e.g. `chromium _build/html/index.html`

If it is the first time you build the docs locally, you can just run the script `docs/docs.sh` which will install the dependencies and build the docs as well.

Also, as mentioned here: https://github.com/ethereum/solidity/pull/13951#issuecomment-1425781032 we could just style it as links if that makes it easier to fix the problem.

**Comment by NunoFilipeSantos** [comment]
Hi @RupeshWadne ! 👋 are you planning to come back soon to this PR, or should we close it for now?

**Comment by minaminao** [comment]
Is it necessary to be able to use Remix on mobile devices in the first place? I don't think so and think it's better just to hide it on mobile devices. @r0qs

**Comment by r0qs** [comment]
> Is it necessary to be able to use Remix on mobile devices in the first place? I don't think so and think it's better just to hide it on mobile devices. @r0qs

Hum...as far as I'm aware Remix works on mobile as well, so I would say yes.

I'm fine to actually just do what @cameel suggested in this comment https://github.com/ethereum/solidity/pull/13951#issuecomment-1425781032:
```
I'll leave opinions about looks to the others, but just wanted to say I don't see anything wrong with this being styled as a link. 
```

And just make a link in the top right corner of the code block saying `open in remix` (or something like that) and we can move on with this PR.

**Comment by minaminao** [comment]
@r0qs I wanted to say that being multi-featured is not necessarily good. In other words, I wanted to discuss once whether it is really necessary, not whether it works. If there are only a couple of mobile users in the world using this Remix button, I think the user experience of the majority of other users should be a priority.

Anyway, I wasn't aware of the existence of this button until you shared this issue. This is a matter of appearance, as @cameel said. I'll make a prototype now with an `open in Remix` button :)

**Comment by minaminao** [comment]
image

I picked the style (color and margins) just fine. Is this how it should look? I'll open a PR when I've styled it more.

**Comment by NunoFilipeSantos** [comment]
@minaminao mobile can mean tablets as well. I personally know a lot of people that use a setup with a tablet for docs.
As you can notice, we don't track users for that info, but it is a fairly reasonable assumption.

**Comment by minaminao** [comment]
@NunoFilipeSantos You are right but sorry, mobile devices here refer to small devices such as iPhones and don't include tablets such as iPads. This is because this broken layout doesn't happen by the size of the tablets.

By the way, #14122 has already supported small devices. I just thought it would be easier to hide it for this issue, which is why I made that suggestion. :)

**Comment by NunoFilipeSantos** [comment]
I do understand that, but I wouldn't exclude that feature for now. Cheers!

**Comment by RupeshWadne** [comment]
I am really really sorry for this sir @r0qs . Actually I was hospitalized for 2 months for having health issues. But I am glad someone solves this issue. thank you @minaminao .

**Comment by r0qs** [comment]
> I am really really sorry for this sir @r0qs . Actually I was hospitalized for 2 months for having health issues. But I am glad someone solves this issue. thank you @minaminao .

HI @RupeshWadne, I'm sorry to hear that. Don't worry about this PR, focus on taking care of your health! I wish you all the best.

**Comment by minaminao** [comment]
@RupeshWadne Thanks to your contribution, I was able to create the PR easily for this issue. Wishing you good health!

**Comment by r0qs** [comment]
Closing in favor of https://github.com/ethereum/solidity/pull/14122

**Review by JamesonDiamond1 — COMMENTED** [review]
@JamesonDiamond1

**Pull request closed without merging**
