### PR TITLE
Change assert to unimplemented error.

### LINKED ISSUE #2095: Struct getter (public variable of struct) cannot handle more than 9 members
I'm trying to add more then 9 data in public struct it's showing me below error 

    Internal compiler error: Stack too deep, try removing local variables.

[![enter image description here][1]][1]

if I removed the public keyword from `User public user;` then works fine or I maintain 9 data in struct then works fine. 

    contract UserIndendity{
        
        struct User {
            address userAccount;
            address photo;
            string fName;
            string lName;
            address signature;
            string email;
            uint mno;
            string street;
            string city;
            string state;
            string country;
        }
        
        User public user;
        
        function UserIndendity(address _userAccount,address _photo,string _fName,string _lName,address _signature,string _email,uint _mno,string _street,string _city,string _state,string _country){

            user.userAccount=_userAccount;
            user.photo=_photo;
            user.fName=_fName;
            user.lName=_lName;
            user.signature=_signature;
            user.email=_email;
            user.mno=_mno;
            user.street=_street;
            user.city=_city;
            user.state=_state;
            user.country=_country;
        }
    }

any one have solution for above issue?

  [1]: https://i.stack.imgur.com/Tf4e2.png

### PR DESCRIPTION
**Pull request by Marenz**
fixes #2095

### CODE REVIEW

**Comment by chriseth** [comment]
"stack too deep errors" have always been regular assertions, not "unimplemented" assertions. It's not that some feature is missing or something, it's just a drawback of the architecture.

**Comment by Marenz** [comment]
Hmm then I misunderstood @axic 's comment at https://github.com/ethereum/solidity/issues/2095#issuecomment-381981418

How should this be solved?

**Comment by bshastry** [comment]
Independent of the normal assert vs unimplemented assert, I think it would be good to revise the assert text as in this PR, since that informs developers of a possible workaround.

**Comment by chriseth** [comment]
I'm actually not sure if the new abi encoder is better with that...

**Comment by Marenz** [comment]
Well, at the very least it compiles if you enable it, simply because it never reaches that assert (the `return` is earlier in the function when v2 is enabled)

**Comment by leonardoalt** [comment]
What's the conclusion then? `solAssert` or `solUnimplementedAssert`?

**Comment by chriseth** [comment]
As this is not about a missing but planned feature, I would propose `solAssert`. Also, we are using `solAssert` in all the other places.

**Comment by leonardoalt** [comment]
Any other opinions? Can we close it then?

**Comment by Marenz** [comment]
does that also mean we can close #2095?

**Comment by chriseth** [comment]
We could close it as "wontfix" (until the code generator has been rewritten).

**Comment by leonardoalt** [comment]
Closing after discussion.
Please reopen to restart the discussion

**Pull request closed without merging**
