### PR TITLE
Fix error message about accessing storage pointers.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Review by leonardoalt — DISMISSED** [review]

**Comment by chriseth** [comment]
Oh actually I think the message might have been correct. It was meant to mean "it can happen than this variable is returned without prior assignment".

**Comment by chriseth** [comment]
Maybe just leave it as it is and add `... which would lead to undefined behaviour`?

**Comment by leonardoalt** [comment]
Ah ok, right, I read it more like "it should not be return ..."

**Comment by leonardoalt** [comment]
Agree with https://github.com/ethereum/solidity/pull/7458#issuecomment-533137146

**Review by leonardoalt — APPROVED** [review]

**Pull request merged**
