### PR TITLE
Use string::starts_with()

### PR DESCRIPTION
**Pull request by ghost**
It makes more sense to use `string::starts_with()` rather than `string::find()`

### CODE REVIEW

**Review by cameel — COMMENTED** [review]
Looks good as long as it passes CI but unfortunately I think it won't. `starts_with()` is a C++20 extension and we still support C++17.

Using `start_with()` from boost would be fine too though.

**Comment by ghost** [comment]
> Looks good as long as it passes CI but unfortunately I think it won't. `starts_with()` is a C++20 extension and we still support C++17.
> 
> Using `start_with()` from boost would be fine too though.

I see ... well I better close this PR then 😞

**Comment by cameel** [comment]
You can try boost. It has that function too.

**Comment by ghost** [comment]
> You can try boost. It has that function too.

I know, I just saw an open issue of somebody trying to replace some boost functions with the STL equivalents. I'll open a new PR with more changes if necessary. For now I keep this PR closed.

**Comment by cameel** [comment]
If you're looking for an issue to contribute, maybe you'd like to try #10269?

**Pull request closed without merging**
