### PR TITLE
Enforce commas in tuple/array syntax

### PR DESCRIPTION
**Pull request by federicobond**
See #2713. Should I add a regression test for this?

### CODE REVIEW

**Comment by axic** [comment]
> Should I add a regression test for this?

Yes please, and a changelog entry.

**Comment by federicobond** [comment]
Done.

**Review by chriseth — APPROVED** [review]

**Comment by axic** [comment]
@federicobond can you please rebase instead?

**Comment by federicobond** [comment]
Yes, sorry, I did it lazily from the GitHub interface.

**Comment by axic** [comment]
Thanks!

**Pull request merged**
