### PR TITLE
Fix backslash bug

### LINKED ISSUE #3968: Windows: Backslash in a path to contract leads to solc crash
### Steps to reproduce:

1. Define two contracts:
```
contract A {}
```
```
import "./A.sol";
contract B {}
```

2. Run the following command:
`solc -o . --bin  .\A.sol B.sol`

### Expected result: 
Contracts to be compiled successfully

### Actual result: 
Solc crashed

ic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)
Dynamic exception type: class boost::exception_detail::clone_impl<struct dev::FileError>
std::exception::what: FileError
[struct dev::tag_comment * __ptr64] = Could not write to file: .\_\A_sol_A.bin

### solc version: 
`0.4.23+commit.124ca40d.Windows.msvc`
### platform: 
`win7`

### PR DESCRIPTION
**Pull request by asifmallik**
Fixes #3968 

Replaces #4070 as I was unable to squash the commits

### CODE REVIEW

**Comment by axic** [comment]
I think this may need to have a changelog entry.

**Comment by chriseth** [comment]
Looks good! :)

**Comment by chriseth** [comment]
Actually I think line 727 should also be changed to use `generic_string()`

**Review by chriseth — APPROVED** [review]

**Comment by asifmallik** [comment]
@gitcoinbot I have tried but was unable to do so. I was shown the following error:

> Because a staff member has had to remove you from a bounty in the past, you are unable to startmore work at this time. Please leave a message on slack if you feel this message is in error.

**Pull request merged**
