### PR TITLE
Update z3 to 4.11.0 in the docker files

### PR DESCRIPTION
**Pull request by leonardoalt**

### CODE REVIEW

**Comment by nikola-matic** [comment]
Might be unrelated to current failures, but `version` is set to `4.8.17` in `scripts/deps-ppa/static_z3.sh` as well.

**Comment by leonardoalt** [comment]
> Might be unrelated to current failures, but `version` is set to `4.8.17` in `scripts/deps-ppa/static_z3.sh` as well.

Yea that one isn't used automatically but needs to be updated too. I guess @Marenz did that locally

**Comment by leonardoalt** [comment]
The current failures are due the things that are done in https://github.com/ethereum/solidity/pull/13439 which this PR depends on

**Comment by Marenz** [comment]
> Might be unrelated to current failures, but version is set to 4.8.17 in scripts/deps-ppa/static_z3.sh as well.

If someone would just finally merge https://github.com/ethereum/solidity/pull/13422 ..

**Review by Marenz — APPROVED** [review]

**Pull request merged**
