### PR TITLE
Add some more abstract keywords in test to make sure the correct property is tested.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by ekpyron** [comment]
Hm... this is horrible to review... We basically have to roll back all the test updates of https://github.com/ethereum/solidity/pull/7358 and redo them with a proper review...

**Comment by ekpyron** [comment]
Maybe this should be two commits: one that indeed reverts all changes to the test directory made in the abstract contract PR and another one on top of them, updating them properly again? I think there are a few cases missing in this PR as it stands.

**Comment by chriseth** [comment]
Only `test/libsolidity/syntaxTests/nameAndTypeResolution/029_create_abstract_contract.sol` is excluded, but it does not hurt - it is actually even better to see that both errors are caught.

**Comment by ekpyron** [comment]
What about ``/test/libsolidity/syntaxTests/inheritance/override/implement_public_function_by_public_variable.sol``?

**Comment by chriseth** [comment]
Right, and test/libsolidity/syntaxTests/nameAndTypeResolution/029_create_abstract_contract.sol - but that's it - I promise! ;)

**Comment by chriseth** [comment]
Ah sorry, that's the one I was talking about above.

**Comment by ekpyron** [comment]
> Right, and test/libsolidity/syntaxTests/nameAndTypeResolution/029_create_abstract_contract.sol - but that's it - I promise! ;)

Yep, I checked, that's it ;-).

**Comment by chriseth** [comment]
Updated.

**Comment by ekpyron** [comment]
I think at least the 029_create_abstract_contract.sol one has wrong expectations now, doesn't it?

**Comment by chriseth** [comment]
Removed the `abstract` again.

**Review by ekpyron — APPROVED** [review]

**Comment by ekpyron** [comment]
> Removed the `abstract` again.

We could probably have removed the whole old test case, but it's fine this way - both cases are tested anyways.

**Comment by chriseth** [comment]
Also added something to the 0.6.0 changes file.

**Pull request merged**
