### PR TITLE
Updated in Gas artical

### PR DESCRIPTION
**Pull request by RISHABHAGRAWALZRA**
I think this better than previous one it gives more and clear information about Gas,
and I found this artical  i didn't make this, but i want to provide this knowledge(Gas artical) to all geek, enthusiast, Curious learner and beginner

### CODE REVIEW

**Review by leonardoalt — COMMENTED** [review]
Since this part of the documentation is only an introduction I wouldn't write all that.
Do you see anything wrong with the current text?

**Comment by Marenz** [comment]
Maybe we can add it somewhere else as own article/part? For the intro it does seem too much indeed

**Comment by RISHABHAGRAWALZRA** [comment]
Hii, @leonardoalt  and @Marenz  
I think you are right, it is more than enough for intoduction but you can edit this and use it somewhere else and also can attach a link for this article in intro for knowing more about Gas.
Thanks

**Comment by leonardoalt** [comment]
I'm closing the PR since we agreed it's a big too large for the documentation.
The text itself can still be used for some external document.
Please reopen otherwise.

**Pull request closed without merging**
