### PR TITLE
[Trivial] Forward declare Instruction enum in EVMVersion

### PR DESCRIPTION
**Pull request by Marenz**

### CODE REVIEW

**Comment by leonardoalt** [comment]
I don't think it's that trivial :p
main question is, why?

**Comment by Marenz** [comment]
Faster compilation due to less headers included in places where it isn't necessary?

**Comment by Marenz** [comment]
Also, headers included in the places where they are actually used and not indirectly through EVMVersion.h

**Comment by Marenz** [comment]
Both things I understood to be universally agreed...

**Comment by leonardoalt** [comment]
That may be true, but it could also have been written as the motivation in the first place.

**Comment by leonardoalt** [comment]
Especially because forward declarations are usually code smell.

**Comment by leonardoalt** [comment]
> Also, headers included in the places where they are actually used and not indirectly through EVMVersion.h

Therefore even though I agree with this specific point, I find the forward declaration worse and think it shouldn't be there.

**Comment by nikola-matic** [comment]
I guess the question now is whether we go forward with the forward declarations (lol), or close this as won't do? @Marenz if you were to benchmark this, would we see any significant gain in compilation times (doesn't have to be significant I guess, just noticeable)?

**Comment by chriseth** [comment]
I think it's good.

**Review by chriseth — APPROVED** [review]

**Pull request merged**
