### PR TITLE
Be more strict about values in the optimizer block in StandardJSON

### PR DESCRIPTION
**Pull request by axic**
Fixes 3 more bugs found by solfuzzer.

### CODE REVIEW

**Comment by axic** [comment]
Tbh it feels like we would be better off having a JSON schema and running a validator prior the StandardCompiler.

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
If we use json schema, we have to synchronize the schema with the way we access the data. At best, an expression like `optimizerSettings.get("enabled", Json::Value(false)).asBool();` would automatically generate the required checks and error messages.

**Comment by axic** [comment]
> At best, an expression like optimizerSettings.get("enabled", Json::Value(false)).asBool(); would automatically generate the required checks and error messages.

That's what we had, but it doesn't validate that if `enabled` is present it is a bool.

**Comment by chriseth** [comment]
Yes, but we could write such a tool: `optimizerSettings.getBool("enabled", false)`

**Pull request merged**
