### PR TITLE
[Yul] Add AZTEK code as test.

### PR DESCRIPTION
**Pull request by chriseth**
This still needs copyright clearance.

### CODE REVIEW

**Comment by chriseth** [comment]
@zac-williamson sorry for creating this pull request maybe a little early. We would like to use your extensive inline assembly code to tune our optimizer. It would be great if you could give us clearance to use it. If not, I will of course close this pull request and delete the branch.

**Comment by stackenbotten** [comment]
There was an error when running `test_check_style` for commit `5f9349e919ec7a01da1dab7a4989c0d95dc5241f`:
```
Error: Trailing whitespace found:
 test/libyul/yulOptimizerTests/fullSuite/aztec.yul:89: 
 test/libyul/yulOptimizerTests/fullSuite/aztec.yul:92: mstore(0x120, sub(gen_order, c)) 

```
Please check that your changes are working as intended.

**Comment by zac-williamson** [comment]
Hey there! No worries, we've happy for you to use our code to tune your optimizer 👍

**Comment by chriseth** [comment]
Thanks!

**Comment by stackenbotten** [comment]
There was an error when running `test_check_style` for commit `86bf921c19e123d720b75efe0b53d86bb96e5669`:
```
Error: Trailing whitespace found:
 test/libyul/yulOptimizerTests/fullSuite/aztec.yul:91: 
 test/libyul/yulOptimizerTests/fullSuite/aztec.yul:94: mstore(0x120, sub(gen_order, c)) 

```
Please check that your changes are working as intended.

**Comment by chriseth** [comment]
Changed `staticcall` to `call` so it works on all versions.

**Review by ekpyron — APPROVED** [review]
Since it looks like the tests will succeed now and I guess in fact there's not much else to be reviewed here apart from that: approved!

**Pull request merged**
