### PR TITLE
[DOCS] Split Function modifiers doc into smaller file

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
This PR partially closes #5396 and splits Function Modifiers section into smaller file.

### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [x] New tests have been created which fail without the change (if possible)
- [x] README / documentation was extended, if necessary
- [x] Changelog entry (if change is visible to the user)
- [x] Used meaningful commit messages

### CODE REVIEW

**Review by chriseth — DISMISSED** [review]

**Comment by ekpyron** [comment]
At a quick glance the test failure looks "wrong" - weird...

**Comment by ChrisChinchilla** [comment]
@ekpyron And it works locally. Quite confused 🤔

**Comment by ekpyron** [comment]
Maybe https://github.com/sphinx-doc/sphinx/issues/1668?

**Comment by ekpyron** [comment]
Locally the warning might not be treated as an error - but it may be the problem in the issue I linked, i.e. sphinx reading the included file as a "standalone" file as well - so we may want to exclude them in the sphinx config. I haven't looked into our sphinx config, though, so I may be wrong.

**Comment by ekpyron** [comment]
So it should be enough to rename all files to-be-included to ``*.inc`` instead of ``*.rst``, so that sphinx ignores them (apart from the include itself).

**Comment by ChrisChinchilla** [comment]
@ekpyron I'd like to avoid using .inc for a variety of reasons, but I'm going to see if I can find another solution, and use this as plan b.

**Review by chriseth — APPROVED** [review]

**Pull request merged**
