### PR TITLE
[WIP] Add debugging to see where Appveyor crashes

### PR DESCRIPTION
**Pull request by rocky**
This is just to narrow what's up with Appveyor. 

Note we don't have problems on any other CI or OS other that the Appveyor one. 

### Checklist
- [ ] Code compiles correctly
- [ ] All tests are passing
- [ ] New tests have been created which fail without the change (if possible)
- [ ] README / documentation was extended, if necessary
- [ ] Changelog entry (if change is visible to the user)
- [ ] Used meaningful commit messages

### CODE REVIEW

**Comment by rocky** [comment]
And now it works. Clearly this has something to do with the specific machine and its memory. 

There are a couple of options:

* Skip skip on Appveyor. (This might now even a Windows thing, so much as resources on the Windows box. 
* Have the test query resources and adjust the iteration count

@chriseth @leonardoalt @christianparpart @bshastry  - your thoughts?

**Comment by chriseth** [comment]
Did you base this on top of your parser changes?

**Comment by rocky** [comment]
I believe so.

**Comment by chriseth** [comment]
Closing since the other PR fixed it already.

**Pull request closed without merging**
