### PR TITLE
Suffix the "mod" version modifier using a dot.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by pirapira** [comment]
What motivated this change?

**Comment by pirapira** [comment]
Ah, I found [the reason](https://www.reddit.com/r/ethereum/comments/51rjkf/solidity_v040_released/d7eavdv).

**Comment by chriseth** [comment]
No, that is not the reason. Actually it is valid semver, but the convention is to separate fields by dots and not by hyphens.

**Comment by pirapira** [comment]
I'm trying to determine if this work nicely with the parser in #1070.

**Comment by pirapira** [comment]
But that does not change before/after this PR.  Looks good to merge.

**Pull request merged**
