### PR TITLE
Add Gitter notifications for nightly builds and tests

### LINKED ISSUE #7288: Nightly tests should send out notification
We're not getting notified in case one of the nightly build steps fails. This is particularly dangerous, since we don't get a notification about failing external tests (which are run nightly).

A quick brainstorming session with @Marenz resulted in a few options that we might have in order to implement a notification system:

1. Automated Gitter message: Hook up a `cURL` call to the `when`-attribute of a Circle step https://circleci.com/docs/2.0/configuration-reference/#the-when-attribute and https://developer.gitter.im/docs/rest-api

2. Create a simple Circle Orb that takes care of sending out a message to Gitter: https://circleci.com/docs/2.0/notifications/#notifications-with-orbs

### PR DESCRIPTION
**Pull request by erak**
Fixes https://github.com/ethereum/solidity/issues/7288.

### CODE REVIEW

**Review by chriseth — DISMISSED** [review]

**Comment by erak** [comment]
Great! It's working :) But there was a defect and the wrong message has been sent out. That's fixed now.

**Comment by erak** [comment]
The Gitter message will look like this:

solidity_nightly_gitter

**Review by chriseth — APPROVED** [review]

**Comment by axic** [comment]
> The Gitter message will look like this:

Is this going to `solidity-dev`?

**Comment by erak** [comment]
We need to change an env var in Circle and then it will :)

**Pull request merged**
