### PR TITLE
docstring: add missing space

### PR DESCRIPTION
**Pull request by come-maiz**

### CODE REVIEW

**Review by axic — CHANGES_REQUESTED** [review]
Can you move the test into a new directory `syntaxTests/natspec/` ?

**Comment by come-maiz** [comment]
Thanks for the review @axic. I've moved the two docstring tests to the natspec dir.

**Comment by axic** [comment]
Thanks! Can you also squash the two commits? :)

**Comment by come-maiz** [comment]
@axic sure, done. But may I suggest you to use the squash and merge button? That step should be applied by the maintainers, not by the contributors, IMO.

**Comment by axic** [comment]
> But may I suggest you to use the squash and merge button?

Too bad it removes the merge commit :(

**Review by axic — APPROVED** [review]

**Comment by come-maiz** [comment]
@axic I think that's good. the maintainer gets to choose the format and contents of the merge commit, so you can keep it consistent. But despite all appearances, I'm not trying to convince you, it was just a suggestion ;)

**Pull request merged**
