### PR TITLE
Yul AST cleanup

### PR DESCRIPTION
**Pull request by christianparpart**
### Please Note
This PR is based on top of #7386. Please only have a look at the **last three** commits.

### CheckList
* [x] remove FunctionInstruction
* [x] remove Instruction

### CODE REVIEW

**Comment by christianparpart** [comment]
Moving out of draft, even though it's prerequisite PR isn't merged yet. (Please **only** have a look at the last 3 commits. :-) )

**Comment by djudjuu** [comment]
Once these instructions have been removed, they will also need to be removed from the AsmJsonConverter (#7537) and from the AsmJsonImporter (#7153)

**Comment by Marenz** [comment]
@christianparpart you can rebase this now, your base PR has been merged

**Comment by christianparpart** [comment]
the replacement PRs have been created (and almost all merged).

**Pull request closed without merging**
