### PR TITLE
Reject constant modifier on the fallback function

### LINKED ISSUE #562: Strict fallback handling
I think it time to consider adding more safety mechanisms into Solidity. One good candidate is cleaning up the handling of the fallback method.

Situation now:
- If no fallback is defined in Solidity, the contract just returns.
- If a fallback is defined it is executed.

I propose the following:

1) Keyword to enable the fallback method: `fallback`.  A fallback body declaration is mandatory.

```
contract Test fallback {
}
```

2) A contract without the `fallback` keyword should fail compilation if the fallback method is present.

3) If no fallback is defined and no matching ABI signature is found, the contract should `throw`.

4) A library cannot have the `fallback` keyword.

5) Regarding the appropriate interface JSON, please see https://github.com/ethereum/solidity/issues/499
## 

Remark about input/output parameters to the fallback method:

1) Right now the language won't accept method parameters, but that can be circumvented by the user with using `msg.data`

2) Right now it allows defining return parameters which are encoded using the ABI. According to @chriseth this is unwanted. If it is removed, I would propose adding an option to return raw data by a singular `bytes` return value (which won't include the size field). Update: see #15, which proposes the same change.

### PR DESCRIPTION
**Pull request by axic**
Partially fixes #562

### CODE REVIEW

**Comment by chriseth** [comment]
What is the reasoning behind this? I would actually argue that a fallback function should rather be constant, because it usually does not have enough gas to modify storage.

**Comment by axic** [comment]
Actually this goes a bit further. `constant` would mean the state cannot be changed, but receiving value changes the state also (updates the balance). And that is the reason of existence of the fallback.

**Comment by chriseth** [comment]
But that would mean that payable and constant always exclude each other. I would actually not go that far, we have to yet defined what constant actually means.

**Comment by chriseth** [comment]
I would say this is now superseded by #665 - constant and payable are mutually exclusive. If you want a constant fallback function, it is still fine, I would say.

**Comment by axic** [comment]
I think, especially in the light of #992, neither `constant`, `view` or `pure` apply to fallback functions. The main point of `view` and `pure` are the ability to receive an output data, which the fallback function cannot do anymore (well, it can via inline assembly).

Therefore `constant` (even the old-world version) should be disabled for fallbacks.

**Pull request closed without merging**
