### PR TITLE
Align license to those in file headers.

### PR DESCRIPTION
**Pull request by chriseth**
According to our [general license guideline](https://github.com/ethereum/wiki/wiki/Licensing), Solidity has always been GPL-Licensed, which is also reflected in every single file header (apart from the files taken from the V8 project). This file ended up here accidentally during the repository split.

The origin of this file is the first commit, but these early commits were not Solidity related at all: https://github.com/ethereum/solidity/commits?page=148

### CODE REVIEW

**Comment by bobsummerwill** [comment]
The origin of that file is not that January 2nd 2014 commit:

https://github.com/ethereum/solidity/commit/780099223ca2028cc7d008c0f52743cb347536dc

It is this "initial commit" on the creation of the Solidity repo on 17th Aug 2015:

https://github.com/ethereum/solidity/commit/8b980c7541934aac84f30c46d7a7515ebd264611

**Comment by bobsummerwill** [comment]
See https://gitter.im/ethereum/cpp-ethereum-development?at=57588bae97e1b2d245e0f683.

**Comment by axic** [comment]
@chriseth @bobsummerwill the README still has this:

```
### External Contributors

I hereby place all my contributions in this codebase under an MIT
licence, as specified [here](http://opensource.org/licenses/MIT).
- *Name Surname* (**email@domain**)
```

**Comment by bobsummerwill** [comment]
Thanks for the spot, @axic.    I'll make a PR for that too.

CONTRIBUTING.md and CodingStandards.txt should actually be moved to http://ethdocs.org too (source in https://github.com/ethereum/homestead-guide/tree/master/source/ethereum-clients/cpp-ethereum.

**Comment by bobsummerwill** [comment]
See https://github.com/ethereum/webthree-umbrella/pull/569.

**Review by tlack29 — COMMENTED** [review]
ready

**Pull request merged**
