### PR TITLE
Add the Travis build status badge

### PR DESCRIPTION
**Pull request by pirapira**
This adds a Travis badge in README.

### CODE REVIEW

**Comment by chriseth** [comment]
I'm not sure if this adds any value. I almost never take a look at the main page and I would actually prefer to be notified by email if develop breaks...

**Comment by pirapira** [comment]
@chriseth probably not for you, though I've forgotten why I wanted to add it.  I noticed the badge is missing back in June, and the item was staying in my todo list for 12 weeks until now.

**Comment by chriseth** [comment]
Ok, I guess it does not hurt to merge.

**Comment by axic** [comment]
@pirapira @chriseth For some reason it seems to refer to the latest pull request.  It shows as "build: error" in the README and the link goes to #2881.

**Comment by pirapira** [comment]
Hmm.  That was not obvious to me.

**Pull request merged**
