### PR TITLE
minValue & maxValue Inline IF Init

### PR DESCRIPTION
**Pull request by khanrn**

### CODE REVIEW

**Review by axic — CHANGES_REQUESTED** [review]
Please use a better commit message.

**Comment by axic** [comment]
In these instances I think I do prefer the `if` statement for readability. There is a lot of parentheses and operators on the left condition.

**Comment by axic** [comment]
Why do you prefer the ternary operator over the if statement?

**Comment by khanrn** [comment]
@axic Yea, I thought about that too. But the point is, those two conditions seemed short enough to implement ternary operator, which will reduce the whole file vertical length a little bit without compromising too much readability. I found some other short conditions too where ternary operator can reduce 4-5 line each. This way the readability in a whole for the file can be increased. :slightly_smiling_face:

**Comment by chriseth** [comment]
I think the original version was much better readable. Vertical length is irrelevant in cpp files, as long as individual functions are short.

**Pull request closed without merging**
