### PR TITLE
Mark embedding options as advanced.

### PR DESCRIPTION
**Pull request by aarlt**

### CODE REVIEW

**Review by ekpyron — APPROVED** [review]

**Review by cameel — DISMISSED** [review]
Just doing a blank change request to prevent it from getting merged already, because I also had some suggestions for this from our previous discussion, but I have to run so I'll post specifics a bit later.

**Comment by ekpyron** [comment]
(And even if we want do deal with this in a completely different manner, we can still do this in a new PR, i.e. this PR is better than develop alone, so we merge it and anything beyond that we can do afterwards)

**Comment by cameel** [comment]
Here's the relevant bit from that previous discussion:

> I mean, rather than docs just better names would be nice. For example. `STRICT_JSONCPP_VERSION` sounds like it works like `STRICT_Z3_VERSION`. But instead it disables the version check completely. Why not something like `ANY_JSONCPP_VERSION` or `ENABLE_JSONCPP_VERSION_CHECK`?
>
> Or `USE_SYSTEM_LIBRARIES` is very broad and I'd expect it to cover all libs like Boost, Z3 etc. This name needs some qualifier. The description of the option does not clarify it either.
>
> Overall, this does not need to be extensively documented since I assume it's for development only, but at least names should be less ambiguous so that if you guess what it does, you have a chance to guess right :)

So basically, these options should just have a better names and descriptions.

[The whole discussion on Matrix was longer](https://matrix.to/#/!poXqlbVpQfXKWGseLY:gitter.im/$kPVp_DxORT67iHPfNrBd_4OT-k6mjVcntY0kgecTn-Q), and there were other things mentioned, including whether we need this feature in the first place, but ultimately if we do have it, that's the one thing that should be improved IMO.

**Comment by cameel** [comment]
Also, a link to the original PR: #14860. I wanted to find it and expected that I would be somewhere in here already but apparently not.

**Pull request merged**
