### PR TITLE
ErrorTag in inline assembly

### PR DESCRIPTION
**Pull request by axic**
Implement #1174.

### CODE REVIEW

**Comment by chriseth** [comment]
Please also add this to the documentation.

**Comment by axic** [comment]
Added docs.

**Comment by chriseth** [comment]
Please see this comment:https://github.com/ethereum/solidity/issues/1320#issuecomment-259379317
I'm not 100% convinced anymore we should call it `ErrorTag`.

**Comment by axic** [comment]
#1320 mentions `nonexistingLabel`. I would probably go for `invalidLocationLabel`.

Current "assembly" output uses `ErrorTag`. Are we planning to change that too?

**Comment by chriseth** [comment]
I would like to change the assembly output to be parseable by the assembly parser, but we can keep the old format and just add a new one, so not change the current string representation.

Concerning the name: What about `invalidLabel`? Location sounds like "source location".

**Comment by axic** [comment]
`invalidJumpLabel`? `panicLabel`?

**Comment by chriseth** [comment]
I'm fine with either `invalidJumpLabel`, `invalidLabel` or `invalidTag`.

**Comment by axic** [comment]
I think I'd go with `invalidJumpLabel` as it resembles it the closests.

**Comment by axic** [comment]
Changed to `invalidJumpLabel`, but still not entirely sure about the naming.

**Review by chriseth — APPROVED** [review]

**Pull request merged**
