### PR TITLE
Parse error explained

### PR DESCRIPTION
**Pull request by aj07**
https://github.com/ethereum/solidity/issues/3980

### CODE REVIEW

**Comment by axic** [comment]
What is the benefit of this change?

**Comment by aj07** [comment]
@axic Parse error will give better explanation why its happening

**Comment by axic** [comment]
I am not sure I understand, but this change is in the expectation section of a test case, which after the change fails.

**Comment by aj07** [comment]
yes, on my local build was successful. I am just loooking why CI error is there

**Comment by aj07** [comment]
@axic Please help me in understanding. In this issue, we need to make user understand why they are getting parse error right? As of now the statement we are getting is same for all types of error. So I made it more highlighted that its syntactical error

**Comment by axic** [comment]
I think this task requires quite a lot and big changes in the parser, so I would suggest to start with some issue, which is way smaller.

**Pull request closed without merging**
