### PR TITLE
 Use temporary fork of Gnosis/Zeppelin contracts

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by axic** [comment]
Created a fork and a branch (`solidity-050`) on both. Everyone has push access to that, but we could also create PRs on those repos merging into `solidity-050`.

**Comment by axic** [comment]
Can we merge this?

**Review by ekpyron — APPROVED** [review]

**Comment by axic** [comment]
@chriseth can we merge this?

**Comment by ekpyron** [comment]
At least I think we should merge this now.

**Comment by axic** [comment]
@chriseth I am merging this for now as it is blocking some other PRs. We can always roll it back.

**Pull request merged**
