### PR TITLE
Properly define the pragma directive in the grammar

### LINKED ISSUE #1389: grammar.txt: PragmaDirective
The following `PragmaDirective` (from **introduction-to-smart-contracts.rst**) can not be parsed:

`pragma solidity ^0.4.0;`

The problem seems to be that `^0.4.0` is not an expression, i.e. `^` is not an unary operator..

### PR DESCRIPTION
**Pull request by axic**
Fixes #1389.

### CODE REVIEW

**Comment by axic** [comment]
@walter-weinmann can you please check if this is valid?

**Comment by walter-weinmann** [comment]
Sorry - but I don't see how to process such an open expression with a lex /
yacc-like parser.

**Comment by axic** [comment]
@walter-weinmann `StringLiteral` is defined with similarly liberal rules: https://github.com/ethereum/solidity/blob/develop/libsolidity/grammar.txt#L96

**Comment by walter-weinmann** [comment]
Yes - but they are limited by quotes - this is a huge difference. The
current definition in pragma can not be recognised by the lexer as a  term on
its own.

**Comment by chriseth** [comment]
@walter-weinmann the pragma is limited by a semicolon and has no escaping rules - isn't that easier?

**Comment by walter-weinmann** [comment]
`(\^.+;) ` could be a solution - but unfortunately it clashes with the following operators: `^`, `^=`.

**Comment by chriseth** [comment]
I'm not sure I understand what you mean by `(\^.+;)` -  the current version `([^;]+)` allows anything up to the `;`.

**Comment by walter-weinmann** [comment]
I thought the pragma variable has to start with character `^`, so my definition was start with `^`, at least one other character and then terminate with the semicolon. But this doesn't work because of the `^`and `^=` operators.

The problem is that **lex** cannot create tokens based on an anything definition - it is not a problem like strings with the definition `" anything "`, but pure anything definitions can not be processed.

**Comment by chriseth** [comment]
I still don't see why `" <anything> "` is different from `Identifier <anything> ;`. If you want, you can also treat it like a comment - how does that work with lex?

**Comment by walter-weinmann** [comment]
I think I'll handle the whole pragma directive as a single token, something like:

`(((P|p)(R|r)(A|a)(G|g)(M|m)(A|a)\s)[^;]+;)`

This one works perfectly with my parser.

**Pull request merged**
