### PR TITLE
Remove coverage steps for circle ci

### PR DESCRIPTION
**Pull request by Marenz**
I don't know if this will interfere with the nightly builds..

### CODE REVIEW

**Comment by chriseth** [comment]
Please keep coverage for the develop branch.

**Comment by Marenz** [comment]
I have to admit, I don't exactly understand how to do that right now. I don't see branches mentioned anywhere in the circle ci file

**Comment by chriseth** [comment]
`test_x86_clang7_asan` only runs on develop, for example.

**Comment by erak** [comment]
We could create another step, e.g. `coverage_x86_linux`, that is basically copied from `test_x86_linux`. Then remove all the commands that are not needed and add it as a new job:
```
- coverage_x86_linux:
  filters:
      branches:
          only: develop
      requires:
          - build_x86_linux
```

**Comment by erak** [comment]
@Marenz We could also look into this together.

**Comment by chriseth** [comment]
I would prefer a solution that does not require too much copying...

**Comment by erak** [comment]
Yea, that makes sense. I'm wondering if we can get away without copying it at all. Filters could be also applied in the workflow section (`<<: *build_on_tags` seems to append the filter) but we would still need another configuration on `develop` then on the feature branches. We could try to generalize the commands used by `test_x86_linux` and then re-use them in the new one?

**Comment by Marenz** [comment]
@erak sure, I'd like that

**Comment by erak** [comment]
After talking to @Marenz, we'll close this for now since it will (most likely) be part of https://github.com/ethereum/solidity/pull/6610.

**Comment by christianparpart** [comment]
@erak @marenz, we can make coverage run in nightly builds on develop branch, IIUC @chriseth.

**Comment by erak** [comment]
@christianparpart Sounds good :)

**Pull request closed without merging**
