### PR TITLE
Make bytecode upload more robust and use date for directory name.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by chriseth** [comment]
This still needs the respective change for windows.

**Comment by axic** [comment]
Fails on Travis with
```
Checking out files: 100% (463/463), done.
fatal: bad object 057a32dd56248f2086d66f62e51bec709970e28e
```

**Comment by axic** [comment]
Can you please incorporate #2140 into this? (Or close it)

**Comment by axic** [comment]
Need to run `git` in the right directory (`$REPO_ROOT`) - fixed.

**Review by axic — APPROVED** [review]

**Review by axic — APPROVED** [review]

**Comment by axic** [comment]
Oh, I missed this is not finished for Windows. That is tracked in #2283.

**Pull request merged**
