### PR TITLE
[Docs] Added links to open example contracts in Remix

### LINKED ISSUE #11415: [Docs] Implement code examples to be opened/importable in Remix
It would be nice to be able to directly open the code examples in the Solidity documentation in Remix (e.g. by clicking "open in Remix").

We need to find out how that would be possible in Remix.

### PR DESCRIPTION
**Pull request by powdrild**
fixes #11415

### CODE REVIEW

**Review by hrkrshnn — COMMENTED** [review]
Thanks for the PR.

A problem with this approach is that the string needs to be updated every time the source changes. Perhaps it is possible to write a read the docs plugin to do this automatically?

**Comment by chriseth** [comment]
I think it would be nice to have an automated script (using either python or bash) that inserts / updates these links that is run at the beginning of `test/cmdlineTests.sh` and returns a failure condition if it had to change anything. This way, we can run it locally to update everything, but if we forget to run it, the test infrastructure will report a failure.

**Comment by cameel** [comment]
@powdrild Would you be willing to work on a more automated solution for #11415? We cannot accept this PR as is since it's not maintainable as it is now (the links will very quickly go out of sync with the code) but we do want these kinds of links to be there.

> that is run at the beginning of `test/cmdlineTests.sh`

I think that `scripts/docs.sh` might be a better place to run it.

**Comment by leonardoalt** [comment]
PR seems stalled. Should we take over or close or?

**Comment by cameel** [comment]
Since we got not answer from @powdrild, I think we should close it. Too bad we cannot accept it but doing it like this would add too much of a maintenance burden.

**Pull request closed without merging**
