### PR TITLE
Set release date for 0.8.21

### PR DESCRIPTION
**Pull request by nikola-matic**

### CODE REVIEW

**Comment by r0qs** [comment]
Shouldn't this have been done before create the tag?

**Comment by nikola-matic** [comment]
> Shouldn't this have been done before create the tag?

I don't know, why would it matter?

**Comment by r0qs** [comment]
Because the tagged commit of the release says `unreleased`: https://github.com/ethereum/solidity/blob/v0.8.21/Changelog.md

If you check previous releases, the changelog of the release should have the release date: https://github.com/ethereum/solidity/blob/v0.8.20/Changelog.md

**Comment by nikola-matic** [comment]
> Because the tagged commit of the release says `unreleased`: https://github.com/ethereum/solidity/blob/v0.8.21/Changelog.md
> 
> If you check previous releases, the changelog of the release should have the release date: https://github.com/ethereum/solidity/blob/v0.8.20/Changelog.md

Ugh, how do we solve this then?

**Comment by r0qs** [comment]
I mean, the only problem with this is that now the release tarball will not contain the release date in the changelog. I guess we could fix it by merging this PR and recreating the tag on top of it. But I don't know if there is some other consequence to recreate the tag. Maybe @cameel knows.

**Comment by nikola-matic** [comment]
> I mean, the only problem with this is that now the release tarball will not contain the release date in the changelog. I guess we could fix it by merging this PR and recreating the tag on top of it. But I don't know if there is some other consequence to recreate the tag. Maybe @cameel knows.

We can just delete the release and re-create it, but I'm not sure what happens with the tag though. Give me a sec.

**Review by r0qs — APPROVED** [review]

**Review by Cplus360 — COMMENTED** [review]
Viewed

**Pull request merged**
