### PR TITLE
Do not use internal types for event parameters.

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/489

### CODE REVIEW

**Comment by pirapira** [comment]
Yes, on this branch I see

```
[{"anonymous":false,
  "inputs":[{"indexed":false,"name":"e","type":"uint8"}],
  "name":"Event","type":"event"}]
```

Instead of the one reported in #489.

**Comment by pirapira** [comment]
The changes make sense. I saw the output change when the enum has 257 elements. I saw similar conversions for the interface functions.  Overall it seems good.

**Comment by chriseth** [comment]
@pirapira enums are converted to the smallest type where all their values fit, that is why you saw a uint16 for 257 elements.

There is already a proposal to add enums and structs to the ABI types, so that will change in the future.

**Comment by pirapira** [comment]
@chriseth I was not complaining.  I tried 257 elements because I saw a bug around that in a different project somewhere.

**Pull request merged**
