### PR TITLE
[BREAKING] Remove suicide and sha3 assembly instructions

### LINKED ISSUE #3003: Remove suicide/sha3 aliases from inline assembly

### PR DESCRIPTION
**Pull request by randomnetcat**
Closes #3003.

### CODE REVIEW

**Comment by randomnetcat** [comment]
Yes I know, tests. I'll let CI run, fix the failures, and add new ones.

**Comment by chriseth** [comment]
This way, it can only be merged with the 0.5.0 release. Can you add a deprecation warning and only remove them with 0.5.0?

**Comment by randomnetcat** [comment]
If you mean with V050 pragma, I can't without overhauling `dev::solidity::assembly::Parser` since that would require a context with access to pragmas. If you mean deprecate them here and open a separate PR at 0.5.0 time, then yes, I could do that.

**Review by axic — CHANGES_REQUESTED** [review]
Please rebase and remove the reference in the documentation (if there are any).

**Comment by axic** [comment]
Changed base to `develop`, anticipating the merge.

**Comment by axic** [comment]
This is failing because stringsutils still uses sha3.

**Review by axic — APPROVED** [review]

**Pull request merged**
