### PR TITLE
Validate array length in type checker

### LINKED ISSUE #2915: Crash with too large arrays
```
contract c {
	uint[8**90] ids;
}
```

```
contract c {
	struct Data { uint x; uint y; }
	Data[8**90] data;
}
```

results in

```
solidity/libsolidity/ast/Types.cpp(977): Throw in function virtual u256 dev::solidity::RationalNumberType::literalValue(const dev::solidity::Literal *) const
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: Integer constant too large.
[dev::tag_comment*] = Integer constant too large.
```

### PR DESCRIPTION
**Pull request by axic**
Fixes #2915.

### CODE REVIEW

**Review by chriseth — APPROVED** [review]

**Comment by axic** [comment]
@chfast any ideas? Is `msb` only in recent boost versions?

```
/home/travis/build/ethereum/solidity/libsolidity/ast/Types.cpp:995:32: error: no member named 'msb' in namespace 'boost::multiprecision'; did you mean 'lsb'?
 return boost::multiprecision::msb(bigintValue());
        ~~~~~~~~~~~~~~~~~~~~~~~^~~
                               lsb
```

**Comment by chfast** [comment]
> @chfast any ideas? Is msb only in recent boost versions?

It was added in 1.56: https://github.com/boostorg/multiprecision/commit/73210bb222949bf3d6823fca8bb45b6050385a4d.

**Comment by axic** [comment]
That is weird, the build uses 1.57:
```
7.45s. adding /home/travis/build/ethereum/solidity/boost_1_57_0 to cache
```

**Comment by chfast** [comment]
Try to include `<boost/multiprecision/integer.hpp>`.

**Pull request merged**
