### PR TITLE
Semantic tests for fixed point types

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `8a979557f2f90858893543ea91760c71715ee13a`:
```
Error: Trailing whitespace found:
test/libsolidity/semanticTests/fixedPoint/conversion.sol:11:    }   

```
Please check that your changes are working as intended.

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `51f0347818f973b264e46a00bf8c776665efef5f`:
```
Error: Trailing whitespace found:
test/libsolidity/semanticTests/fixedPoint/conversion.sol:11:    }   

```
Please check that your changes are working as intended.

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `22b93415a4391a2915b418080bc2ca5a599ba7d6`:
```
Error: Trailing whitespace found:
test/libsolidity/semanticTests/fixedPoint/conversion.sol:11:    }   

```
Please check that your changes are working as intended.

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `364c519d73995089c30389fc2566564c3a1f74fe`:
```
Error: Trailing whitespace found:
test/libsolidity/semanticTests/fixedPoint/conversion.sol:11:    }   

```
Please check that your changes are working as intended.

**Comment by chriseth** [comment]
Combined with #11704

**Pull request closed without merging**
