### PR TITLE
Cleanup test helper macros.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by axic** [comment]
What is the boost output like in case of an exception? Do we get the exception location (file and line)?

**Comment by chriseth** [comment]
I think uncaught exceptions are reported by line. Note that we never used those macros anyway...

**Comment by chriseth** [comment]
I mean only in very special tests.

**Comment by axic** [comment]
I mean it is useful to receive some kind of indication of the exception and if that is only possible with the old one then we should use that. I think we do get *some* information without those helpers so it should be fine.

**Review by axic — APPROVED** [review]

**Pull request merged**
