### PR TITLE
Revert "Disallow RETURNDATASIZE and RETURNDATACOPY in inline assembly blocks in pure functions"

### PR DESCRIPTION
**Pull request by matheusaaguiar**
This reverts commit f567eb1fb2a24dbd956fe65512d4b9015ba7f5ed.

### CODE REVIEW

**Comment by cameel** [comment]
To add some context to this PR: we're reverting #12861 because it turned out that there are projects that actually use `RETURNDATACOPY` in pure functions. We're going to merge that feature into `breaking` instead.

**Review by cameel — COMMENTED** [review]
Looks good. But please squash the corrections into the original commit. Our general practice is for each commit to be a single logical change, without changing things back and forth. This keeps history easier to understand.

**Comment by ekpyron** [comment]
> Looks good. But please squash the corrections into the original commit. Our general practice is for each commit to be a single logical change, without changing things back and forth. This keeps history easier to understand.

(I'd usually use ``git rebase -i develop`` for that, in case you're wondering; that'll open up an editor with some comments which explain the rest)

**Review by ekpyron — APPROVED** [review]

**Review by cameel — APPROVED** [review]

**Review by Sticknmove — COMMENTED** [review]
Thanks

**Comment by Sticknmove** [comment]
Thanks

**Pull request merged**
