### PR TITLE
Ensuring UTF-8 encoding for MSVC builds

### PR DESCRIPTION
**Pull request by shellygr**
Reopened from #5870

### CODE REVIEW

**Comment by axic** [comment]
> Re. your question - it's VS2017. Not sure this option existed before that.

Does that mean it will fail on earlier compilers? We do compile with VS2015, but automation is of Appveyor is not turned on for fork PRs.

**Comment by shellygr** [comment]
Isn't VS2017 a prerequisite according to the Solidity install guide?
In any case it should be fine though -
According to https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=vs-2015
this option did exist in VS2015.

**Comment by axic** [comment]
> Isn't VS2017 a prerequisite according to the Solidity install guide?

Sorry, you are correct, support was dropped in 0.5.2 (#5669).

**Review by chfast — COMMENTED** [review]
Ok to me.

**Review by chfast — APPROVED** [review]

**Review by axic — APPROVED** [review]

**Comment by axic** [comment]
@shellygr thanks!

**Comment by shellygr** [comment]
@axic and thank you for the the swift handling and the education!

**Pull request merged**
