### PR TITLE
[SMTLib2] Fix repeated declarations

### PR DESCRIPTION
**Pull request by axic**
Split off #3073.

### CODE REVIEW

**Comment by axic** [comment]
@leonardoalt I have just checked and Z3/CVC4 does the same as SMTLib did: keeps inserting double declarations.

Though in Z3/CVC4 it is a map and the last declaration overrides the earlier one. Should we do the same here?

**Comment by leonardoalt** [comment]
@axic Yes, should be easy to add it here. Do you have a small example where the repetitions happen? I'm actually curious why multiple declarations of the same variable are being requested.

**Comment by axic** [comment]
I'm not sure which makes sense, but all 3 interfaces should have matching behaviour.

**Comment by leonardoalt** [comment]
@axic Added for Z3 and CVC4

**Comment by axic** [comment]
@leonardoalt do you think it would make sense actually asserting against double declarations to find out where they are caused and investigate it at that point if it makes sense?

**Comment by leonardoalt** [comment]
I actually checked earlier today, and I think it's fine. The function names might be misleading though. The SMTChecker is just retrieving that SMT variable from the solver.

**Comment by axic** [comment]
As discussed this happens in `SolverInterface.h` when a variable is requested. Perhaps the naming is a bit off.

**Pull request merged**
