### PR TITLE
docker: Upgrade to evmone v0.4.0

### LINKED ISSUE #7936: [Testing] Upgrade to evmone 0.4.0
## Abstract

Needed because it (evmone 0.4.0) fixes #7776

### PR DESCRIPTION
**Pull request by bshastry**
Fixes #7936 #7776 

Revised docker images have been pushed to docker hub

CC @chfast

### CODE REVIEW

**Review by axic — DISMISSED** [review]

**Comment by axic** [comment]
Though I guess we shouldn't merge anything to `develop` now as we anticipate the 0.6.0 release?

**Comment by bshastry** [comment]
> Though I guess we shouldn't merge anything to `develop` now as we anticipate the 0.6.0 release?

Yeah, that sounds reasonable to me. In any case, this is not blocking fuzzing. I am fuzzing abi coder with upstream evmone locally and ossfuzz should be doing it as well.

**Comment by axic** [comment]
Disregard my comment given @chriseth started merging :)

**Review by axic — APPROVED** [review]

**Comment by axic** [comment]
This passes all the tests.

**Pull request merged**
