### PR TITLE
Do not export 'isStateVariable' anymore.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by leonardoalt** [comment]
Even though it can be derived from the scope I like these helpers

**Review by hrkrshnn — CHANGES_REQUESTED** [review]
Needs a rebase and updates for tests.

**Comment by chriseth** [comment]
@leonardoalt you are saying it should stay in the ast?

**Comment by leonardoalt** [comment]
@chriseth Yes I'd prefer that, otherwise I'll have to write my own helpers which well, not too hard, but still work :p

**Comment by chriseth** [comment]
Closing then.

**Pull request closed without merging**
