### PR TITLE
Combine value and loop depth

### PR DESCRIPTION
**Pull request by chriseth**
Depends on #7801

### CODE REVIEW

**Comment by chriseth** [comment]
This is weird, I thought the first commit would not be needed anymore....

**Comment by Marenz** [comment]
Tests are failing and needs rebasing

**Comment by chriseth** [comment]
For both these, we are waiting until after 0.6.0

**Comment by chriseth** [comment]
Rebased.

**Review by ekpyron — APPROVED** [review]

**Pull request merged**
