### PR TITLE
Style

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Review by leonardoalt — DISMISSED** [review]

**Comment by axic** [comment]
Can you also change it in `Sort`?

**Comment by chriseth** [comment]
Will do! Is it actually fine that `operator==` is not virtual? Can an operator be virtual?

**Comment by chriseth** [comment]
Updated.

**Comment by leonardoalt** [comment]
In this case it's fine that it's not virtual, but we can make it virtual. What would the advantage be?

**Comment by chriseth** [comment]
Why is it fine? Because you cannot have an array of functions or a function that takes arrays?

**Comment by leonardoalt** [comment]
Right now we can't, but we eventually will. I'd say we make it virtual.

**Comment by chriseth** [comment]
ok, but not in this PR :)

**Review by leonardoalt — APPROVED** [review]

**Pull request merged**
