### PR TITLE
Remove trailing whitespace in all contract files.

### LINKED ISSUE #4396: CRLF Line endings in test/compilationTests
Some of the contracts in ``test/compilationTests`` use Windows line endings (CRLF), e.g. ``test/compilationTests/announcementTypes.sol``. They should probably be updated to LF line endings.

### PR DESCRIPTION
**Pull request by ekpyron**
Closes #4396.

Removes all trailing whitespace in all ``*.sol`` files in the repository. Also, replaces CRLF with LF line endings.

``git diff -w develop..contractWhitespace`` is empty, so this PR is solely whitespace changes.

### CODE REVIEW

**Comment by ekpyron** [comment]
There's a trailing whitespace in some warnings due to https://github.com/ethereum/solidity/blob/a5608b31a759031377ec91300ad7a470d48bb1d2/libsolidity/analysis/StaticAnalyzer.cpp#L61.
This has to be fixed and the whitespace removed before merging this.

Edit: Done in #4400.

**Comment by chriseth** [comment]
I think this PR can wait a little for other large PRs to be merged...

**Comment by ekpyron** [comment]
@chriseth Yes - it's always easy to automatically recreate it.

**Comment by axic** [comment]
Though most of the time CRLF changes are automatically handled during rebasing, so it shouldn't be an issue to merge a subset of this.

**Comment by ekpyron** [comment]
Note that in the meantime there's one test whose source locations change due to a removed trailing space, so ``git diff -w`` will not be empty. I'll update this PR now and then (besides this one syntax test it's only a ``find -name "*.sol" -exec sed -e 's/[[:space:]]*$//' -i '{}' \;`` anyways) and we can decide when it makes sense to merge it.

**Review by axic — APPROVED** [review]

**Pull request merged**
