### PR TITLE
[SMTChecker] Add current input variables to the function summary

### PR DESCRIPTION
**Pull request by leonardoalt**
Ref https://github.com/ethereum/solidity/issues/9042
Depends on https://github.com/ethereum/solidity/pull/9159

Currently, function summaries have the form
`summary_f(pre_state, pre_input_vars, post_state, output_vars)`, which works fine.
However, when we have counterexamples, it would also be great to have the current values of the input vars as well in the summary of a function that reverted, so the model can be reported right away.
This PR changes the summaries to:
`summary_f(pre_state, pre_input_vars, post_state, post_input_vars, output_vars)`.

This PR does not affect any tests, it's done in preparation for counterexamples.

### CODE REVIEW

**Comment by mijovic** [comment]
Needs another rebase

**Comment by leonardoalt** [comment]
There is another problem, that the tests behave differently locally vs CI =/
I'm looking into that with the z3 devs

**Comment by leonardoalt** [comment]
It seems https://github.com/ethereum/solidity/pull/9159 does help against nondeterminism on this PR.

**Review by ekpyron — DISMISSED** [review]
Fine after rebase

**Comment by ekpyron** [comment]
Rebase :-)?

**Comment by leonardoalt** [comment]
@ekpyron ran into an exception after rebase, still debugging :p

**Comment by leonardoalt** [comment]
Rebased

**Review by ekpyron — APPROVED** [review]
Ok, so now the tests not being affected became actually true again :-)? Fair enough :-). Let's just hope it all stays deterministic :-).

**Comment by leonardoalt** [comment]
Determinism ftw!

**Pull request merged**
