### PR TITLE
Disallow empty source name in standard json

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Review by chriseth — APPROVED** [review]

**Comment by axic** [comment]
The reason for this change was that `outputSelection` would be confused, because empty source name refers to SourceUnit-level outputs (aka AST).

However, `jsonCompiler` needs to be amended, because the old `compile()` entry point has only a source code and uses an empty file name. The same applies to `compileJSON()` it allows empty file names. (Need to add test for this in solc-js just to be sure too.)

**Comment by chriseth** [comment]
What is the state of this PR?

**Comment by axic** [comment]
`jsonCompiler` needs to be reviewed how it fits in for the legacy use cases as there it might require right now the use of an empty file name.

I also have another change set which cleans this up in `CompilerStack`.

**Comment by axic** [comment]
> The reason for this change was that outputSelection would be confused, because empty source name refers to SourceUnit-level outputs (aka AST).

Revisited this again and empty source name is not an issue, empty contract name is.

**Pull request closed without merging**
