### PR TITLE
Make super unavailable in libraries.

### LINKED ISSUE #10485: [Typechecker] ICE in solidity::frontend::TypeType::makeStackItems()
## Description

```
library L {
  function f() public {
    (super);
  }
}
```

throws

https://github.com/ethereum/solidity/blob/d50676ecb0a15dff6cf9b106b9cb0422f9b62123/libsolidity/ast/Types.cpp#L3816

## Environment

- Compiler version: breaking

## Steps to Reproduce

```
$ solc test.sol
```

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/10485

### CODE REVIEW

**Review by ekpyron — DISMISSED** [review]

**Comment by ekpyron** [comment]
Main question is whether this PR should actually be considered "fixing" https://github.com/ethereum/solidity/issues/10485, since the issue will still remain on develop for now.

**Comment by ekpyron** [comment]
Not sure if we actually couldn't merge this to develop as well.

**Comment by chriseth** [comment]
Maybe we should try to fix this in develop, you are right.

**Comment by ekpyron** [comment]
Since we considered disallowing inheritance-related stuff (like using ``virtual``) in libraries bugfixes and thereby non-breaking in the past, I'd say it'd be fine to just rebase/retarget this to develop.

**Comment by chriseth** [comment]
Changed target to develop.

**Review by ekpyron — APPROVED** [review]

**Pull request merged**
