### PR TITLE
Removed non-strict JsonParse helpers

### LINKED ISSUE #5933: Remove unused jsonParse helper
Only `jsonParseStrict` is in use (with one exception, SMTChecker tests are incorrectly using `jsonParse`).

### PR DESCRIPTION
**Pull request by axic**
Fixes #5933.

### CODE REVIEW

**Comment by axic** [comment]
Seems to be working. I'll squash some commits, just tell me the preference (can squash all JSONs into one).

**Review by Marenz — DISMISSED** [review]

**Review by ekpyron — DISMISSED** [review]
One commit is enough I would way.

**Comment by Marenz** [comment]
I agwee

**Comment by axic** [comment]
@ekpyron @Marenz done

**Review by Marenz — APPROVED** [review]

**Pull request merged**
