### PR TITLE
Update to jsoncpp 1.9.2

### PR DESCRIPTION
**Pull request by axic**
Attempt to solve #5869, but couldn't find any reproducible test case with any compiler version. Any ideas @bshastry? The test case in the fuzzer issue is not reproducing it.

### CODE REVIEW

**Review by ekpyron — APPROVED** [review]
If all CI runs pass, I don't see a reason not to do this... Unfortunately json-cpp doesn't seem to have proper Changelogs, so we can't really check, if there's something problematic in there...

**Review by bshastry — APPROVED** [review]
Looks good to me if tests pass. I checked locally that the oss fuzz issue is no longer reproducible with this PR (jsoncpp 1.9.2) but was reproducible for jsoncpp 1.8.4 that we are currently depending on.

**Comment by bshastry** [comment]
> The test case in the fuzzer issue is not reproducing it.

I could reproduce the test failure with clang-6, UBSan enabled, jsoncpp v1.8.4, latest solidity develop commit but not with this PR.

**Comment by axic** [comment]
>  The test case in the fuzzer issue is not reproducing it.
>
> I could reproduce the test failure with clang-6, UBSan enabled, jsoncpp v1.8.4, latest solidity develop commit but not with this PR.

Hm, so no way to add a test case into our repo which would reproduce this without ubsan?

**Comment by bshastry** [comment]
> > The test case in the fuzzer issue is not reproducing it.
> > I could reproduce the test failure with clang-6, UBSan enabled, jsoncpp v1.8.4, latest solidity develop commit but not with this PR.
> 
> Hm, so no way to add a test case into our repo which would reproduce this without ubsan?

Sadly, yes. Unless we add a UBSan build and test CIs. I feel adding a UBSan may be an overkill for this though because as far as I remember this is the only bug that was found (in a dependency and not solidity) by UBSan.

**Comment by axic** [comment]
Is it with the test case from the issue? I can't fathom how that could lead into this. Is it due to some gas estimation field?

**Pull request merged**
