### PR TITLE
test copy_from_calldata.sol folder location update

### PR DESCRIPTION
**Pull request by KatyaPrusakova**
#13543 Semantic test for copying calldata structs placed in the wrong subdirectory
@cameel  could you help to see if I got the task correct?

### CODE REVIEW

**Comment by cameel** [comment]
1) Have you checked if there are any other non-struct tests in that dir?
2) The issue says to also add a proper struct-based test for this case.
3) There are many tests for copying calldata in the `array/copying/` dir so we should give this test a more specific name. How about `calldata_1d_array_into_2d_memory_array_element.sol`

**Comment by nikola-matic** [comment]
@KatyaPrusakova, bumping since you've been in active, and the PR would technically be considered stale? Do you plan on implementing the test @cameel suggested? I've checked, and `copy_from_calldata.sol` is the only tests in the `structs` directory that doesn't actually use a struct, so no other tests need to be moved.

**Comment by nikola-matic** [comment]
I've renamed the test as per @cameel's suggestion. The tests he requested however (copy calldata structs) already exist, so it's a no-op.

**Comment by cameel** [comment]
I'd squash the commits (no need to rename it twice :)) but other than that it looks fine.

**Review by nikola-matic — APPROVED** [review]

**Review by cameel — APPROVED** [review]

**Pull request merged**
