### PR TITLE
Warn if no visibility is specified on contract functions.

### PR DESCRIPTION
**Pull request by axic**
Part of #2608. Depends on #2857.

### CODE REVIEW

**Comment by axic** [comment]
Need to change test cases.

**Comment by chriseth** [comment]
Some other options: https://www.reddit.com/r/ethereum/comments/6vxbht/solidity_version_0416_released/dm4q0v7/

**Comment by axic** [comment]
How about the constructor? I think we had an issue it should only support `public` and as such it must also display the warning?

**Comment by axic** [comment]
We agreed that currently it does not make sense to enforce no-warnings on the end-to-end tests (and as such the specifiers should not be added above), because having "too pure" (as in up to latest standards) code would remove the possibility of getting old code tested.

**Comment by axic** [comment]
@chriseth please review

**Review by chriseth — APPROVED** [review]

**Pull request merged**
