### PR TITLE
LLL: fix variable (set/get/ref) handling

### LINKED ISSUE #2400: LLL: "set", "get" and "ref" expressions not compiling.
While writing some end-to-end tests for the built-in macros in LLL (yay!), it became apparent that the "set" expression (used in the first msg macro) no longer compiles. E.g.

    > echo '(set x 1)' | lllc
    ...blah...
    Symbol not found: set

The same goes for "get" and "ref".

SET, GET and REF are handled in the parser, *liblll/CodeFragment.cpp*. Parsing fails when the parser executes `m_asm.append((u256)varAddress(firstAsString()));`

`varAddress()` [line 174] tries to look up a string in the `_s.vars map`, defined in line 47 of *liblll/CompilerState.h*. But `vars` is always empty - nothing ever writes to it so this look up always fails.

I guess that at some stage variables were a thing in LLL and this functionality has since been removed, leaving "set", "get", "ref" and varAddress() as remnants. I was unable to find the commit that might have done this, however.

Anyway, I'm happy to make a PR to remove all of this and independently fix up the msg macro, but wanted to check with those more familiar with the code whether this is desirable, or if they should instead be fixed.  Any thoughts?

### PR DESCRIPTION
**Pull request by axic**
Fixes #2400.

### CODE REVIEW

**Comment by axic** [comment]
@benjaminion @zigguratt can you please double check this?

**Comment by benjaminion** [comment]
Looks good to me.

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
Conflict. Also I think this should be documented.

**Comment by axic** [comment]
What do you mean by documented? Unfortunately there is no documentation :)

The above fixes a bug introduced a commit in November.

**Pull request merged**
