### PR TITLE
LLL: Replace obsolete assembly code

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by axic** [comment]
@benjaminion @zigguratt can you please check the test cases in this PR?

**Comment by benjaminion** [comment]
Test cases look great.

[Just noticed you marked this WIP, so fair enough on the below!]

I'm sure you know this, but both `conditional-literal` and `conditional-seq` are failing on this commit with stack underflow.  The EVM code generated for `conditional-literal` looks like this:

```
0000 PUSH1 0x00
0002 CALLDATASIZE
0003 EQ
0004 PUSH1 0x0c
0006 JUMPI
0007 PUSH1 0x02
0009 PUSH10x0f
000b JUMP
000c JUMPDEST
000d PUSH1 0x01
000f JUMPDEST
0010 POP   <----- This is incorrect.
0011 PUSH1 0x00
0013 MSTORE
0014 PUSH1 0x20
0016 PUSH1 0x00
0018 RETURN
```

It's a regression - all the tests succeed against the current develop branch.

**Comment by axic** [comment]
@benjaminion fixed, can you please retest?

**Comment by benjaminion** [comment]
All working now.

**Comment by axic** [comment]
@chriseth review please

**Review by chriseth — APPROVED** [review]

**Pull request merged**
