### PR TITLE
Fix function type examples

### PR DESCRIPTION
**Pull request by axic**
This would be cleaner with #1410.

### CODE REVIEW

**Comment by axic** [comment]
The external example is not entirely fixed yet:
```
Untitled1:16:38: Error: Invalid type for argument in function call. Invalid implicit conversion from bytes memory to bytes storage pointer requested.
        requests[requestID].callback(response);
                                     ^------^
Untitled1:23:29: Error: Invalid type for argument in function call. Invalid implicit conversion from function (bytes memory) to function (bytes storage pointer) external requested.
        oracle.query("USD", oracleResponse);
                            ^------------^
```

After marking everything `memory` the next problem is the externalness:

```
Untitled1:23:29: Error: Invalid type for argument in function call. Invalid implicit conversion from function (bytes memory) to function (bytes memory) external requested.
        oracle.query("USD", oracleResponse);
                            ^------------^
```

Marking it `external` then triggers the problem of lookups:
```
Untitled1:23:29: Error: Undeclared identifier.
        oracle.query("USD", oracleResponse);
                            ^------------^
```

and `OracleUser.oracleResponse` results in:
```
Untitled1:23:29: Error: Member "oracleResponse" not found or not visible after argument-dependent lookup in type(contract OracleUser)
        oracle.query("USD", OracleUser.oracleResponse);
                            ^-----------------------^
```

and `this.oracleResponse` in:
```
Untitled1:23:29: Error: Invalid type for argument in function call. Invalid implicit conversion from function (bytes memory) external to function (bytes memory) external requested.
        oracle.query("USD", this.oracleResponse);
                            ^-----------------^
```

I think the first two cases are correct, it shouldn't work. The last case is the one which should work, but is bugged.

**Comment by chriseth** [comment]
Should be working now.

**Comment by chriseth** [comment]
@axic please merge if you are fine with it.

**Comment by axic** [comment]
Oh I had (notice the `external` keyword):

```
      function buySomething() {
        oracle.query("USD", this.oracleResponse);
      }
      function oracleResponse(bytes response)  external {
        if (msg.sender != address(oracle)) throw;
        // Use the data
      }
```

and this returns: 
```
Untitled1:23:29: Error: Invalid type for argument in function call. Invalid implicit conversion from function (bytes memory) external to function (bytes memory) external requested.
        oracle.query("USD", this.oracleResponse);
                            ^-----------------^
```

If this is not a bug, then the error message should be improved somehow, because from it seems that both types equal.

**Comment by axic** [comment]
@chriseth would merge, but there are no reviews. Also see the above comment.

**Review by pirapira — APPROVED** [review]
Looks good to me.

**Pull request merged**
