### PR TITLE
Update solidity-by-example.rst

### PR DESCRIPTION
**Pull request by mirgj**
highestBidder is the address.
it's highestBid that should be != 0 to be considered as pending return.

It's that right?

### CODE REVIEW

**Comment by chriseth** [comment]
Hm, does that make a difference? If you think it can be better understood this way, then we should change it.

**Comment by mirgj** [comment]
No it doesn't I just think is more readable. I rather would use address(0x0) to be explicit if I'm comparing an address. That's why when I saw the number I thought it was referring to the bid.

But, again, not much difference anyway. Maybe would be less confusing for beginners like me?

**Comment by chriseth** [comment]
Ok, thanks for the PR!

**Review by chriseth — APPROVED** [review]

**Comment by axic** [comment]
The change to require proper address literals will also fix this :)

**Pull request merged**
