### PR TITLE
yul proto fuzzer: Increase step limit for optimized code

### LINKED ISSUE #7472: [yul] optimizer may increase gas consumption in code containing many nested for loops that have msize, call etc. as loop condition
## Description

oss-fuzz: issue number 17643

```
{
  for {let i_0} lt(i_0,0x60) {i_0 := add(i_0,0x20)}
  {
    for {let i_1} lt(i_1,0x60) {i_1:=add(i_1,0x20)}
    {
      for {for {let i_2} lt(i_2,0x60) {i_2:=add(i_2,0x20)} { for{} msize() {} {}}} msize() {}
      {}
    }
  }
}
```

is optimized to 

```
{
    let i := 0
    for { } lt(i, 0x60) { i := add(i, 0x20) }
    {
        let i_1 := 0
        for { } lt(i_1, 0x60) { i_1 := add(i_1, 0x20) }
        {
            let i_2 := 0
            for { } lt(i_2, 0x60) { i_2 := add(i_2, 0x20) }
            {
                for { } 1 { }
                { if iszero(msize()) { break } }
            }
            for { } 1 { }
            { if iszero(msize()) { break } }
        }
    }
}
```

which increases code size and trips the fuzzer. The additional instructions are zeroing for-loop init variable, and folding the `msize()` builtin when used as a for-loop conditional into the for-loop via `iszero`

## Environment

- Compiler version: latest develop

### PR DESCRIPTION
**Pull request by bshastry**
fixes #7472 

depends on #7608

### CODE REVIEW

**Comment by chriseth** [comment]
Maybe wait whether #7519 would fix it, too.

**Comment by bshastry** [comment]
@chriseth #7519 does not fix it, sadly

**Comment by chriseth** [comment]
Can you post what the output was after #7519 ?

**Comment by bshastry** [comment]
@chriseth For the original code example in the issue, which is (five nested for loops, the third of which contains a bounded for loop within its pre block and a potentially infinite for loop inside the body of the for loop within the pre block)

```
{
  for {let i_0} lt(i_0,0x60) {i_0 := add(i_0,0x20)}
  {
    for {let i_1} lt(i_1,0x60) {i_1:=add(i_1,0x20)}
    {
      for {for {let i_2} lt(i_2,0x60) {i_2:=add(i_2,0x20)} { for{} msize() {} {}}} msize() {}
      {}
    }
  }
}
```

the optimized code post #7519 looks like so

```
{
        {                                                              
            let i := 0                                                 
            for { } lt(i, 0x60) { i := add(i, 0x20) }                  
            { 
                let i_1 := 0
                for { } lt(i_1, 0x60) { i_1 := add(i_1, 0x20) }
                {      
                    let i_2 := 0
                    for { } lt(i_2, 0x60) { i_2 := add(i_2, 0x20) }    
                    {                                                  
                        for { } 1 { }
                        {
                           // Additional block scope introduced by optimizer
                           if iszero(msize()) { break } 
                        }
                    }
                    for { } 1 { }
                    {
                        // Additional block scope introduced by optimizer
                        if iszero(msize()) { break }
                    }
                }
            }
        }
}
```

**Comment by chriseth** [comment]
I think the big problem here is that `msize` is not movable.

**Pull request merged**
