### PR TITLE
 LLL: terminate sequences with a STOP

### PR DESCRIPTION
**Pull request by axic**
Fixes a bug introduced by #4813.

This example uses two assemblies (the `(lll` part introduces a sub assembly):
```
{ (seq (CREATE2 0 0 (lll (seq (mstore 0 0x112233) (revert 0 32)) 0) 0) (SSTORE 0 (RETURNDATASIZE)) )}
```

In LLL there was no requirement for an explicit termination of a sub assembly, since it relied on the assembler to do that.

### CODE REVIEW

**Comment by axic** [comment]
Let me also add an endtoend test.

**Comment by winsvega** [comment]
is this only for (seq .... )  
or STOP is required for all LLL inside {}  ?

**Review by chriseth — DISMISSED** [review]
The LLL code is mostly opaque to me.

**Comment by axic** [comment]
This needs tests and some fixes. Doing it now.

**Comment by axic** [comment]
Seems like the assembly block was broken since #2457.

**Comment by axic** [comment]
This should me merged before release as LLL is broken now and the constantinople testing depends on this.

Will finish this today (wednesday), but running out of batter right now.

**Comment by winsvega** [comment]
I fixed the tests to have explicit STOP

**Comment by winsvega** [comment]
hm. just rebased on latest solidity develop. 
even having (STOP) is not working anymore.
could we merge this asap ? 

```
"{ (CREATE2 0 0 (lll (seq [[0]] (EXTCODEHASH 0xb94f5374fce5edbc8e2a8697c15331677e6ebf0b) [[1]] (EXTCODESIZE 0xb94f5374fce5edbc8e2a8697c15331677e6ebf0b) (STOP) ) 0) 0) }"
```

translates into 

`0x6000603280601060003960006000f5fe73b94f5374fce5edbc8e2a8697c15331677e6ebf0b3f60005573b94f5374fce5edbc8e2a8697c15331677e6ebf0b3b600155`

vmtrace
```
TRACE 10-11 15:30:16 testeth vmtrace  < 1 : @d89b2fe3… : #8 : 0031 : SSTORE : 284813 : -0 : 0x32 >
TRACE 10-11 15:30:16 testeth vmtrace 
    STACK
    MEMORY

TRACE 10-11 15:30:16 testeth vmtrace     STORAGE
0x0: 0x36712AA4D0DD2F64A9AE6AC09555133A157C74DDF7C079A70C33E8B4BF70DD73
0x1: 0x4

TRACE 10-11 15:30:16 testeth vmtrace  < 1 : @d89b2fe3… : #9 : 0032 : STOP : 264813 : -0 : 0x32 >
TRACE 10-11 15:30:16 testeth exec   Safe VM Exception. /home/wins/Ethereum/cpp-ethereum/libevm/LegacyVMCalls.cpp(50): Throw in function void dev::eth::LegacyVM::throwBadInstruction()
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::BadInstruction>
std::exception::what: BadInstruction
```

@axic

**Comment by winsvega** [comment]
sorry (STOP) in the code seems to work. I did smth wrong in previous code. 
this one works: 
```
"{ (seq (CREATE2 0 0 (lll (seq          [[0]] (EXTCODEHASH 0xb94f5374fce5edbc8e2a8697c15331677e6ebf0b) [[1]] (EXTCODESIZE 0xb94f5374fce5edbc8e2a8697c15331677e6ebf0b)            ) 0) 0) (STOP) )}"
```

**Comment by winsvega** [comment]
whats wrong in this line? 
```
            "code" : "{ (seq [[0]] 0 (CALL 100000 0xb000000000000000000000000000000000000000 0 0 0 0 0) (CREATE2 0 0 (lll (seq (SSTORE 0 0) (SSTORE 1 1) (STOP) ) 0) 0) ) }",
    
```

hmm this one works: 
```
                "code" : "{ (seq [[0]] 0 (CALL 100000 0xb000000000000000000000000000000000000000 0 0 0 0 0) (CREATE2 0 0 (lll (seq (SSTORE 0 0) (SSTORE 1 1) ) 0) 0) (STOP) ) }",
```

**Comment by chriseth** [comment]
Ok, tests are green now, ready for review, @axic.

**Comment by axic** [comment]
@chriseth renamed some of the commits and removed one useless test. I hope it still passes, I'm happy to have this merged.

**Comment by chriseth** [comment]
Rebased.

**Pull request merged**
