### PR TITLE
solc option for selecting yul optimisations

### PR DESCRIPTION
**Pull request by cameel**
Replaces #8619 (now with the correct branch).

Not finished yet but there are only two things remaining:
- [x] command-line tests via standard JSON
- [x] command-line parameter validation that rejects improperly nested parentheses

I'll mark it non-draft when it's ready for review.

### CODE REVIEW

**Comment by chriseth** [comment]
Is this properly rebased?

**Comment by cameel** [comment]
Not yet. I'm planning to get back to it and add the missing stuff when I'm done with the internal library call PR.

**Comment by cameel** [comment]
It's ready for review now.

**Review by chriseth — APPROVED** [review]
I'll merge it, but I think this still needs a changelog entry, and we actually should at least list all named optimizer steps somewhere in the documentation, with the goal to have a description for all of them.

**Pull request merged**
