### PR TITLE
Disallow fallback function to return values.

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/15

### CODE REVIEW

**Comment by axic** [comment]
@chriseth can we merge this first so I can rebase #665 against it?

**Comment by lastperson** [comment]
Hello @chriseth and @axic 
I propose you to reconsider this change one more time. Before it it was possible to do something like this:

```
contract Caller {
    function hello(address _to) returns(bool) {
        return Target(_to).hello();
    }
}

contract Target {
    bool val = true;
    function hello() returns(bool) {
        val = !val;        
        return val;
    }
}

contract ProxyTarget {
    address targetAddress = '0xTargetContractAddress';
    function () returns(bool) {
        return Target(targetAddress).hello();
    }
}
```

Then you deploy hem all and call it like this:

```
Caller.hello(TargetAddress) -> true;
Caller.hello(ProxyTarget) -> false;
Caller.hello(ProxyTarget) -> true;
```

Now it will be impossible to implement such behavior. Fix me if I'm wrong, please.

**Comment by redsquirrel** [comment]
Similarly, it seems like @Arachnid's `Upgradeable` approach would also become impossible if this were implemented: https://gist.github.com/Arachnid/4ca9da48d51e23e5cfe0f0e14dd6318f#file-upgradeable-sol-L75

**Comment by axic** [comment]
@lastperson: a value can still be returned via inline assembly:

```
function () {
    bytes memory ret = "test";
    assembly {
        return(add(ret, 32), 32)
    }
}
```

@redsquirrel: the linked code uses the exact semantics from above, so it should not be affected.

**Comment by redsquirrel** [comment]
@axic I am gruntled.

**Pull request merged**
