### PR TITLE
[CI] Reusable command for gitter notifications

### PR DESCRIPTION
**Pull request by cameel**
This is a simple refactor, extracted into a separate PR because I need it in more than one other PR.

It converts the existing notification step templates into a parameterized and reusable command. This reduces duplication and makes it easier to add new notifications (which is needed in #12181).

### CODE REVIEW

**Comment by hrkrshnn** [comment]
@cameel Was this tested by any chance? Looks good. Can approve if this was tested. We can also test in prod :)

**Comment by Marenz** [comment]
Yeah, I think the easiest is to test it in production, as it explicitly excludes PRs. Though of course you could add a test-commit that removes that exception so it runs on PRs as well.

**Review by Marenz — APPROVED** [review]
LGTM. I am okay with production testing, but a simple commit that removes the PR exclusion might also do the trick to test it

**Comment by cameel** [comment]
@hrkrshnn I did test it but not very extensively (I didn't want to spam the channel and also the variables are going to be different in non-PR runs anyway so it's not foolproof). I tested it together with #12181. Take a look at https://github.com/ethereum/solidity/pull/12181#issuecomment-949876968.

**Comment by cameel** [comment]
@Marenz I did that in #12181 (it was originally a part of that PR) and when it worked I removed the debug commits.

**Review by hrkrshnn — APPROVED** [review]

**Pull request merged**
