### PR TITLE
Update installing-solidity.rst on Gentoo Linux

### PR DESCRIPTION
**Pull request by AndreMiras**
Gentoo Linux solidity install instructions.

### CODE REVIEW

**Comment by pirapira** [comment]
Wow, do you maintain this package?  Thank you!

**Comment by pirapira** [comment]
I restarted the failing Travis build.

**Review by pirapira — APPROVED** [review]
Looks good to me.

**Comment by AndreMiras** [comment]
No I do not maintain it, but I've tried it and it works great so far.

**Comment by pirapira** [comment]
Thanks anyway; I don't have a gentoo installation at hand.

**Pull request merged**
