### PR TITLE
Initial translation.

### PR DESCRIPTION
**Pull request by chriseth**
This translation is somehow documented at http://wiki.jikexueyuan.com/project/solidity-zh/ and was started as https://github.com/twq0076262/solidity-zh

I tried to save as much as I could and converted it back to rst format.

My proposal would be to proof-read, clean this up, merge it and document roughly which commit it is based on. If we make changes to the english documentation later, we can more easily see what is missing.

### CODE REVIEW

**Comment by chriseth** [comment]
The page at http://wiki.jikexueyuan.com/project/solidity-zh/  also has a list of translators. We should include this here (and in the english version), but I did not know how to include it best.

**Comment by axic** [comment]
A generic problem I have with translations is that who's responsibility is to keep them up to date if the "main" part of the documentation changes?

Say someone makes a change to the code and appropriately documents it in the English version. Will the change not be merged because it doesn't touches a translation? Who will keep all the translations up to date?

**Comment by chriseth** [comment]
We do not require translations to be up to date, not for pull requests and not for releases. Still, I think it is beneficial to keep the translations in the official repository instead of just somewhere on the internet. The translations or translation files should indicate which commit they are up to date with.

**Comment by axic** [comment]
I think a commit number is easily omitted by the reader and just takes the fact it is in the official repo as the indicator that it **must be** up to date.

**Comment by chriseth** [comment]
@axic I think we can find a way, for example position a banner that is always visible at the top of the screen, which indicates that this is not up to date. Another option might be to always insert a diff of what still needs to be translated.

In any case, I think it is very important to break out of the english community.

**Review by pirapira — CHANGES_REQUESTED** [review]
The translation is not licensed under GPL or any other open source license.  A written permission from the copyright holders is necessary for a merge.

**Comment by pirapira** [comment]
Why can't we do it just like PostrgreSQL where local groups maintain their translations, e.g.: [Chinese](http://www.postgres.cn/docs/9.6/) [Japanese](https://www.postgresql.jp/document/current/html/).

**Comment by pirapira** [comment]
@chriseth they already have a repo, so we might just want to include this as a submodule https://github.com/twq0076262/solidity-zh

@twq0076262 if we create `ethereum/solidity-zh` repository, will you be a maintainer?

**Comment by chriseth** [comment]
This is not going to fly. Closing.

**Pull request closed without merging**
