### PR TITLE
Correct Yul test file extensions

### PR DESCRIPTION
**Pull request by DaniPopes**
Some test files in tests/libyul have a .sol file extension but are invalid Solidity code. Rename them to .yul.

Command used:
```bash
for f in $(fd -e sol . test/libyul); do mv $f $(basename $f .sol).yul; done
```

### CODE REVIEW

**Review by nikola-matic — APPROVED** [review]

**Comment by cameel** [comment]
WTF, this moves the test files to repo root. Why was this even merged?

**Comment by nikola-matic** [comment]
> WTF, this moves the test files to repo root. Why was this even merged?

Ooof, my bad, I didn't notice. I'll fix it.

**Comment by DaniPopes** [comment]
Oops it was late when I made this, sorry :(

**Comment by nikola-matic** [comment]
> Oops it was late when I made this, sorry :(

No worries, I opened a PR to move the tests back to appropriate dirs.

**Pull request merged**
