### PR TITLE
WIP: Fix makefiles to silence linker errors

### PR DESCRIPTION
**Pull request by lionello**
### Description

Made changes to several `CMakeLists.txt` files to fix build issues. The build was tested with Nix and the nix package was updated with the same changes: https://github.com/NixOS/nixpkgs/pull/51615

### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [ ] New tests have been created which fail without the change (if possible)
- [ ] README / documentation was extended, if necessary
- [ ] Changelog entry (if change is visible to the user)
- [x] Used meaningful commit messages

### CODE REVIEW

**Comment by chriseth** [comment]
Thanks for the pull request! Could you explain the purpose of these changes a little more? Note that we do not want to clutter a user's system with our header files when they use 'make install' - not sure if that is the case here.

**Comment by lionello** [comment]
NIX required the libs and headers to be installed (I'll have to dig into their build system more to understand why) so I removed those for now. But I got linker errors when linking `libyul` and those were fixed by including `evmasm` and `langutil` to `libyul/CMakeLists.txt`.

**Comment by ekpyron** [comment]
If ``libyul`` depends on symbols in ``evmasm``, resp. ``langutil`` (which is probably in fact the case), then we should add them here, so I think this PR is a good idea.

``make install`` won't be affected (we don't install any headers and this change won't change that).

**Comment by ekpyron** [comment]
Since we don't install any libraries and headers, I guess that our cmake project was just included in another one and then it was linked against the ``yul`` target - that's a perfectly good way to do things, so we should support that - but for that to work the ``yul`` target has to specify all its dependencies.

**Review by chriseth — APPROVED** [review]

**Pull request merged**
