### PR TITLE
Bool vars comparison

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/3811

### CODE REVIEW

**Review by ekpyron — APPROVED** [review]
Similarly to #4091, it may be possible to implement this as pragma 050 change, depending on #3879. Otherwise it should target the 050 branch instead of develop.

Apart from that this looks fine to me.

**Review by ekpyron — CHANGES_REQUESTED** [review]
Changed my review to "Request changes" to avoid merging this as long as it's targetting develop and not 050, although otherwise this looks fine.

**Comment by leonardoalt** [comment]
Thanks @ekpyron ! Gonna rebase and change the target

**Review by ekpyron — APPROVED** [review]

**Comment by chriseth** [comment]
Will rebase.

**Pull request merged**
