### PR TITLE
Bug fix: Add missing include in test/Options.h

### PR DESCRIPTION
**Pull request by bshastry**
### Checklist
- [ ] Code compiles correctly
- [ ] All tests are passing
- [ ] New tests have been created which fail without the change (if possible)
- [ ] README / documentation was extended, if necessary
- [ ] Changelog entry (if change is visible to the user)
- [ ] Used meaningful commit messages

### Description

The `test/Options.h` header file does not include `boost/core/noncopyable.hpp` that is necessary for the compiler to understand the definition of the `boost::noncopyable` object. This PR includes the said file.

### CODE REVIEW

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
Argh, this seems to be not compatible with older versions of boost. I actually thought about this but meged anyway...

**Comment by bshastry** [comment]
Oops, sorry about that. I should have clarified in the PR text that I was building against the upstream master of boost. Does this break stuff?

**Comment by chriseth** [comment]
No worries, I force-merged before all tests were complete, so we would have noticed if I had been a little more patient :)

**Comment by bshastry** [comment]
Okay :-)

For future reference, what boost version should I be linking Solidity against?

Thank you!

**Comment by chriseth** [comment]
@bshastry your version is fine, it is just that we are also using older versions that still had that file in a different directory.

**Pull request merged**
