### PR TITLE
Added Section about Scoping Behaviours

### PR DESCRIPTION
**Pull request by Denton-L**
Solidity handles this strangely as opposed to other C-based languages so I felt it would be good to have a section dedicated to this

### CODE REVIEW

**Comment by chriseth** [comment]
Thanks for the explanation! Could you please add a note that these are exactly the same rules as in javascript?

**Comment by Denton-L** [comment]
Does anyone have any idea why the builds are suddenly failing?

**Comment by chriseth** [comment]
Yes, but you don't have to care about it, docs are not built here.

**Comment by chriseth** [comment]
Nice writeup, thanks!

**Pull request merged**
