### PR TITLE
Change CompilerStack.reset() to have keepSettings flag

### LINKED ISSUE #3586: Evaluate whether CompilerStack::reset() should reset optimizer and evm version setting
reset should be called when adding a new source. It should reset the compiler state, but not the complier settings.

If this is done, some reset calls in the testing frameworks might get redundant.

### PR DESCRIPTION
**Pull request by axic**
Fixes #3586.

### CODE REVIEW

**Comment by axic** [comment]
I wonder if any of the source cleaning part could reduce the number of leaks we have.

**Comment by axic** [comment]
Also it turned out `reset` is only used by tests, not by StandardCompiler or the CLI.

**Comment by chriseth** [comment]
Is everything reset properly if I use the standard compiler from solc-js multiple times while not resetting the javascript environment?

**Review by chriseth — APPROVED** [review]

**Comment by axic** [comment]
> Is everything reset properly if I use the standard compiler from solc-js multiple times while not resetting the javascript environment?

StandardCompiler creates a new CompilerStack instance in every run.

**Pull request merged**
