### PR TITLE
Mark modifiers as internal

### LINKED ISSUE #2468: Modifiers are considered like public functions when they are always internal
The following code doesn't compile.
```
contract Foo {
    struct S { }
    
    modifier mod(S storage x) {
        _;
    }
}
```
```
Error: Location has to be memory for publicly visible functions (remove the "storage" keyword).
    modifier mod(S storage x) {
                 ^---------^
```

Modifiers are always called internally and so it looks to me like this should be possible.

### PR DESCRIPTION
**Pull request by axic**
Fixes #2468.

### CODE REVIEW

**Comment by axic** [comment]
With modifiers being public I guess reading from another contract could work `C.mod()`, but that is rejected by the parser anyway.

**Review by pirapira — APPROVED** [review]
Looks good to me.

**Comment by frangio** [comment]
@axic Could you expand on what you meant by "modifiers being public"? Isn't it exactly the purpose of this PR to leave that off the table?

I do think that modifiers should always be internal, but I wanted to clarify that if #2467 is fixed, `C.mod()` _will_ be valid syntax.

**Comment by axic** [comment]
It was only a remark that before this change, when modifiers were public, maybe one could have invoked them as `C.mod()`, but the parser rejects the `.` so it was not possible anyway.

It continues not to be possible after the change.

**Comment by frangio** [comment]
I understand now, thanks!

**Pull request merged**
