### PR TITLE
Properties of wasm builtins

### LINKED ISSUE #7008: Specify movability and side-effect-free-ness for ewasm builtins

### PR DESCRIPTION
**Pull request by chriseth**
Closes #7008

### CODE REVIEW

**Comment by leonardoalt** [comment]
Depends on #7002

**Comment by leonardoalt** [comment]
Tests failing

**Comment by leonardoalt** [comment]
Gonna take more time to review polyfill :p

**Comment by chriseth** [comment]
I hope we don't need to review but instead just automatically verify :)

**Review by leonardoalt — APPROVED** [review]

**Pull request merged**
