### PR TITLE
Prepare 0.7.0

### PR DESCRIPTION
**Pull request by erak**

### CODE REVIEW

**Comment by chriseth** [comment]
needs change in chagelog

maybe needs to run commandline tests (will update bug list)

**Comment by Marenz** [comment]
the failing tests are probably fixed once we merge https://github.com/ethereum/solidity/pull/8047 into breaking

**Comment by axic** [comment]
> the failing tests are probably fixed once we merge #8047 into breaking

I've already pushed develop to breaking (just pushed manually because we haven't merged anything into `breaking` yet), so they are in sync, before rebasing this PR.

**Comment by erak** [comment]
Updated. All tests are passing now.

**Review by chriseth — APPROVED** [review]

**Pull request merged**
