### PR TITLE
add z3 http wrapper

### PR DESCRIPTION
**Pull request by eelkevdbos**
Docker file source can be found at: https://github.com/eelkevdbos/z3-http/blob/master/Dockerfile

#2963

### CODE REVIEW

**Comment by chriseth** [comment]
I successfully managed to get an experimental version of remix working with your docker container! Wohoo! :-)

I'm still a bit uneasy about including binaries into docker files. Since in contrast to go, python is usually part of every base image of a distribution. Would it be possible to write the http wrapper in pyhton and include the script itself?

**Comment by eelkevdbos** [comment]
Nice! I'll try to supply a python version by tomorrow ;-)

**Comment by eelkevdbos** [comment]
Hi @chriseth, sorry for being away for a while, I've updated the image to a version based on python. Should be small (95 MB), CORS-enabled and based on python.

**Comment by chriseth** [comment]
Sorry, I'm closing this, we are not sure if this is the route we want to go. Thanks for you work anyway, we might pick it up in the future!

**Pull request closed without merging**
