### PR TITLE
Finish ERC20

### LINKED ISSUE #6478: [Yul] Implement Sol->Yul codegen for ERC20 Token
We should implement a version of https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC20/ERC20.sol where we do not need the library and using for because we do our own overflow checking.

The following still needs to be implemented:

 - [x] return statement - #6589
 - [x] storage variables - https://github.com/ethereum/solidity/pull/6646
 - [x] member access to storage mapping - https://github.com/ethereum/solidity/pull/6655
 - [x] assignment to member of storage mapping / lvalue - https://github.com/ethereum/solidity/pull/6655
 - [x] require - https://github.com/ethereum/solidity/pull/6639
 - [x] emit - https://github.com/ethereum/solidity/pull/6663
 - [x] `msg.sender` - https://github.com/ethereum/solidity/pull/6662
 - [ ] require with reason

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/6478

### CODE REVIEW

**Comment by leonardoalt** [comment]
Should https://github.com/ethereum/solidity/pull/6707 be reviewed before this?

**Comment by ekpyron** [comment]
Ah yeah - I just wanted to respond that this is a lot at once and lacking tests e.g. for multiplication, but those should be added to #6707 and then that one should be merged first - otherwise this looks good at a first glance!

**Comment by chriseth** [comment]
I'll remove the multiplication part.

**Review by leonardoalt — APPROVED** [review]
Do we want to merge this without StringLiteral tests?

**Pull request merged**
