### PR TITLE
[WIP] Added augur tests #3127

### PR DESCRIPTION
**Pull request by gilbertoalexsantos**
#3127

### CODE REVIEW

**Comment by chriseth** [comment]
Thanks a lot for the pull request!

The way you did it will unfortunately not work with our CI infrastructure - we do not have both soljson.js and solc at the same time. The file `scripts/test_emscripten.sh` is only run for soljson.js and `scripts/tests.sh` is run for `solc`.

Perhaps you can "split" `externalTests.sh` into a version that runs tests against soljson and another version that uses solc?

Also for the tests to work, you have to modify the augur source files silghtly. You have to replace all `pragma solidity 0.4.17;` with `pragma solidity ^0.4.17;` (or perhaps better replace all `pragma solidity [^;]*;` by `pragma solidity ^0.4.0;`).

**Comment by axic** [comment]
@gilbertoalexsantos can you make these changes?

**Comment by axic** [comment]
I think Augur moved onto truffle and doesn't need the python version anymore?

**Comment by axic** [comment]
@MicahZoltu would you be interested in finishing this? Is Augur stable enough yet to include it in our testing infrastructure?

**Comment by nuevoalex** [comment]
I can take a look at this in the coming days.

Going forward I'll be the point of contact for the Augur smart contracts since @MicahZoltu has finished his contract with us sadly. We're still using pyethereum for the majority of our tests and aren't planing to use truffle fwiw. The contracts and tests should be stable enough to include here IMO.

**Comment by axic** [comment]
@nuevoalex sad to hear that. Thank you for taking up this issue, please open a new PR once you get there.

**Comment by axic** [comment]
Closing this as the source repository was deleted and because of that there's no way to force push.

**Pull request closed without merging**
