### PR TITLE
Fix abi.decode returning single value.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by chriseth** [comment]
Also created https://github.com/ethereum/solidity/issues/4894 because the situation is really horrible.

**Review by ekpyron — APPROVED** [review]
Looks good! Maybe a Changelog entry would be nice, though.

**Comment by chriseth** [comment]
Changelog entries only concern releases, so if a bug is fixed that was never released, we do not add a changelog entry.

**Comment by ekpyron** [comment]
Right, I hadn't thought about it only being introduced just now. Tests are failing, though - partly solvable by a rebase.

**Review by ekpyron — CHANGES_REQUESTED** [review]
https://github.com/ethereum/solidity/blob/18629bbc5d9d89925fb5308b9e37037b7a166671/libsolidity/codegen/ExpressionCompiler.cpp#L1077 is no longer valid now.

**Comment by chriseth** [comment]
Updated.

**Review by ekpyron — APPROVED** [review]

**Pull request merged**
