### PR TITLE
Extended documentation about imports.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by VoR0220** [comment]
Moreso a question than a comment, but is it possible to import from other repositories? Not necessarily github? Is there a standard to follow? Perhaps some clarification on that may be helpful.

**Comment by chriseth** [comment]
@VoR0220 happy to accept implementations for importing from other source code providers. github will only be implemented for browser-solidity for now.

**Comment by VoR0220** [comment]
gotya. Just put a little bit in clarifying that and I think this will be good to go.

**Comment by chriseth** [comment]
Added clarification.

**Pull request merged**
