### PR TITLE
[0.6.0] Update from develop

### PR DESCRIPTION
**Pull request by erak**
### Description

This PR is meant to be merged regularly, but then kept open until we're not releasing 0.5.x anymore.

### CODE REVIEW

**Comment by ekpyron** [comment]
> ### Description
> 
> This PR is meant to be merged regularly, but then kept open until we're not releasing 0.5.x anymore.

And now it's merged and I don't see a way to re-open it :-).

**Comment by chriseth** [comment]
I think we have to create multiple ones, don't we? Another option is to merge the branch manually without the github interface.

**Comment by ekpyron** [comment]
Something like that... maybe a draft PR that stays open and a separate short-lived PR whenever we actually want to merge?

**Comment by chriseth** [comment]
Github will auto-close the PR when the branch is merged: https://github.com/ethereum/solidity/pull/7265

**Comment by ekpyron** [comment]
Yeah, well, then we probably have to open another once we merge one of these.

**Comment by ekpyron** [comment]
Ah, we can't do that either, because github doesn't let you create a PR, if there's nothing new to merge :-). Well, I don't know then :-).

**Pull request merged**
