### PR TITLE
`cmdlineTests.sh` adjusted to enter test case dir before running and exit after

### PR DESCRIPTION
**Pull request by kevin-allen-uf**
# PR for #13437 
### Changes
- `cmdlineTests.sh` adjusted to enter test case dir before running and exit after.
- Hard-coded test case names removed from all test case input and argument files.
- Expectations regenerated for all non-SMT test cases.

### Results
- 'cmdlineTests.sh' runs correctly for all non-SMT general commandline tests using --no-smt option.
- 'cmdlineTests.sh' runs correctly for all other script tasks except for last task Testing soljson via the fuzzer.

### Issues (HELP REQUESTED!)
- Have been building from source with Z3 and/or CVC4 and still cannot get SMT general commandline tests to run correctly so I can regenerate expectations.
- Getting new `xargs: /path/to/solidity/build/test/tools/solfuzzer: terminated by signal 11` error at script task Testing soljson via the fuzzer, see [here](https://github.com/kevin-allen-uf/solidity/blob/9b1e3421054f975ef401863ccb58d0d6450ab06e/test/cmdlineTests.sh#L690-L692).

### CODE REVIEW

**Comment by leonardoalt** [comment]
Re SMT: you need z3 4.11.0 and no cvc4 I think.

**Comment by kevin-allen-uf** [comment]
Thanks @leonardoalt , I will try rebuilding again when I have time soon with that Z3 version.

**Comment by cameel** [comment]
@kevin-allen-uf Did you manage to resolve your problems?

**Comment by kevin-allen-uf** [comment]
Hi cameel, I have not been able to figure out this PR's problems yet as I am busy with university work. Since I don't foresee being able to complete this PR in the near future, I am going to close it. I will reopen this PR if when I have time issue #13437 is still open and I figure the issue out entirely. Thank you and leonardoalt for your help!

**Comment by cameel** [comment]
Sure. Thanks for the effort anyway! Feel free to try when you have more time.

**Pull request closed without merging**
