### PR TITLE
Provide new account gas for low-level callcode/delegatecall

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by chriseth** [comment]
Hm, do we really want to do that?

**Comment by axic** [comment]
I think it should.

The right way to avoid creating the destination is by not emitting the call if the account is empty - this is deliberately switched off for the low-level version.

Without this change the account may or may not be created, but it entirely depends on the submitted gas by the caller of the contract (function). I think that is worse than a deterministic behaviour.

Also don't think the denial of creation should be attempted by adding a `.gas()` modifier - which the current method allows.

**Comment by chriseth** [comment]
This means, previous uses of call and delegatecall would throw an exception if the callee does not exist, now they will succeed and return true.

**Comment by axic** [comment]
If that would be true, #2679 woulnd't pass the tests.

**Review by chriseth — APPROVED** [review]

**Comment by axic** [comment]
@chriseth are you sure it supposed to work? Is the new account gas deducted from the caller and not part of the sent gas? If the code was supposed to be correct we may need to find out why it wasn't producing that result.

**Pull request merged**
