### PR TITLE
Fix gcc9 errors

### PR DESCRIPTION
**Pull request by Marenz**

### CODE REVIEW

**Comment by leonardoalt** [comment]
We should probably verify that gcc9 is indeed used by the arch build

**Comment by leonardoalt** [comment]
I reran the arch build with ssh and:
```
[root@6e9cb12ffd9b ~]# gcc --version
gcc (GCC) 8.3.0
```

**Comment by ekpyron** [comment]
I think someone moved *everything* including the archlinux build to docker images, which entirely defeats the purpose of the archlinux build run :-).

**Comment by leonardoalt** [comment]
Yea.. i'd say we merge this as soon as tests pass so arch ppl can compile again, and create a new PR to fix the arch build/tests

**Comment by ekpyron** [comment]
So far my build is happily running... I'm only convinced by this, if it fails :-).

**Comment by leonardoalt** [comment]
10 bucks it fails

**Review by ekpyron — DISMISSED** [review]
For reference: https://en.cppreference.com/w/cpp/language/rule_of_three and https://stackoverflow.com/questions/51863588/warning-definition-of-implicit-copy-constructor-is-deprecated.

Ok you were right :-).

**Review by ekpyron — APPROVED** [review]

**Pull request merged**
