### PR TITLE
Fix MultiSigWallet.sol order of functions

### PR DESCRIPTION
**Pull request by dtedesco1**
Aligned order of functions with [style guide](https://docs.soliditylang.org/en/v0.8.12/style-guide.html#order-of-functions): 
- Constructor should appear before receive function
- Public functions should appear before internal functions

### CODE REVIEW

**Comment by dtedesco1** [comment]
@fulldecent would you mind reviewing this fix?

**Comment by fulldecent** [comment]
@dtedesco1 This modifies a file in the test directory.

All tests are exempt from style guide updates.

Also please rebase, hopefully that will fix those pesky errors (I don't think you introduced them).

If you can fix errors then this is approved from me and then on the fence to core devs if they want this change or reject on account of not wanting to have any change on testing code.

**Comment by chriseth** [comment]
I think this can be closed because it only touches test code, isn't it?

**Comment by fulldecent** [comment]
I think we are good to update test code for typos and style fixed.

But if there is something in the test code that is specifically testing a typo or some thing that is against the style guide (such as some functions being defined in some order that against it) then that should be a comment and we will not change anything per those comments.

**Comment by dtedesco1** [comment]
Discovered some checks were failing due to additional issues that I'm fixing:
- executeTransaction function shadowed builtin tx. Replaced with a different name.
- isConfirmed returns bool but did not specify false result conditions. Added this condition.

**Comment by fulldecent** [comment]
Always be squashing

**Comment by cameel** [comment]
Please rebase on `develop`. It already has a fix for the failing CI jobs (#12868).

**Comment by dtedesco1** [comment]
Thanks @cameel.

Check passed and ready for approving review.

**Review by cameel — APPROVED** [review]

**Pull request merged**
