### PR TITLE
Winpipe

### PR DESCRIPTION
**Pull request by winsvega**
add Boost options parser for soltest (otherwise boost crash on custom options like --ipc on windows)
add windows pipe implementation for soltest 

test run 

```
soltest --ipc "\\.\pipe\geth.ipc"
Running 890 test cases...
L:/Ethereum/webthree-umbrella/solidity/test/libsolidity/Imports.cpp(85): error: in "SolidityImports/relative_import": check c.compile() has failed
*** 1 Error detected in a test module "Master Test Suite"
```

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Great!   Thanks for this, @winsvega.
The lack of options was also breaking macOS use of `--ipc`.    Let me see if we can starting using that on macOS now!

**Comment by winsvega** [comment]
Bob, I guess Christian would like at least to have a look at the code and propose some changes before the merge.

**Comment by bobsummerwill** [comment]
Already merged, and then fixed some issues.

The options changes let me do this, which was very nice:
https://github.com/ethereum/solidity/pull/803

The Windows code-paths are inactive.   I put some quick effort into trying to use them within Appveyor, but it needs more love.

**Comment by winsvega** [comment]
does this path invalid in appveyor? 
--ipc "\.\pipe\geth.ipc"

**Comment by chriseth** [comment]
@bobsummerwill @winsvega indeed, this PR has to be revisited.

**Comment by chriseth** [comment]
Please

1) do a proper review,
2) correct all style errors,
3) check that we are allowed to use the code copied from the microsoft website and
4) explain why the option parsing was changed.

**Comment by winsvega** [comment]
4) parsing was changed because boost test would fail if we pass manual argument as an option 
in our case it is --ipc ".\pipe\geth.ipc" would lead to a crash of boost parser. so like in testeth I first parse manual options then continue with boost.

**Comment by chriseth** [comment]
The way to pass manual options to boost tests is via `soltest -- --ipc "geth.ipc"` (boost internal options go before `--`, manual options go after).

**Comment by winsvega** [comment]
chriseth, I didn't knew that about boost!

**Comment by bobsummerwill** [comment]
I was also unaware of that syntax, so let's do that, eh?   Thanks, @chriseth.

Both solidity and cpp-ethereum repositories are now standalone, so simplifying that code can be done atomically as a PR.    Would you like to do that, @winsvega?

And we still have tracking the work remaining to finish this thread of work off, which I think is mainly down to working out how to get the Windows pipe configuration lined up correctly.

"Windows - Add Sockets code-paths and enable Windows unit-tests in Appveyor"
https://github.com/ethereum/solidity/issues/771

**Pull request merged**
