### PR TITLE
Fix Standard JSON ignoring library file names

### PR DESCRIPTION
**Pull request by cameel**
**This PR is based on #10289. Please don't merge until that one is merged.**

I have noticed that Standard JSON handles library references differently than CLI with the `--libraries` option (both the compiler and the linker). In Standard JSON the name of the file containing the library is completely ignored, and only the library name is taken into account. This has several bad consequences:
- Even if the name used inside the link reference in the code differs from the one inside the `libraries` key, it's still used;
- If you have multiple libraries with the same name (in different files) and you include both in `libraries`, one is used for all link references with that library name regardless of file name. The other is ignored.

This affects both Solidity and Yul linking alike.

The fact that linking works at all is due to a [workaround for old-style link references in `LinkerObject`](https://github.com/ethereum/solidity/blob/v0.7.4/libevmasm/LinkerObject.cpp#L78-L85) that strips file names from the link references found in the code if an exact match does not work. Basically, two symmetrical problems are canceling each other out. I think this workaround should be removed too but removing it causes a ton of test failures - looks like many tests rely on this behavior to omit the file name. It's an independent problem anyway so I reported it as a separate issue: #10298. 

The side-effect of this fix is that it's no longer possible to link Yul files containing (valid) link references that do not contain library file name and a colon (#10289) via Standard JSON. That's because the JSON structure requires specifying the file name and the library name separately. Due to this linking such files will only be possible using `--libraries` option unless we switch to a different structure for Yul input.

### CODE REVIEW

**Comment by leonardoalt** [comment]
Can you also add some failing tests?

**Comment by cameel** [comment]
@leonardoalt There are tests included in the PR. E.g. `linking_yul_same_library_name_different_files`. On `develop` it would link both references (rather than just one) and fail.

**Comment by leonardoalt** [comment]
@cameel Yes, I mean adding error tests. Is that possible?

**Comment by cameel** [comment]
@leonardoalt Not really because failure to link just means that the references remain in the bytecode (and are then listed under `linkReferences`).

The test I have is actually for both positive and negative case (i.e. one reference matches, the other does not and remains unlinked). I could split it into two separate ones if you think it's worthwhile.

**Comment by cameel** [comment]
Refactored into two separate tests.

**Review by leonardoalt — DISMISSED** [review]

**Review by leonardoalt — APPROVED** [review]

**Review by leonardoalt — CHANGES_REQUESTED** [review]
Wait, is this breaking actually?

**Comment by cameel** [comment]
Depends on if you consider it a feature or a bugfix :) I think it was just a bug because both `--libraries` and `--link` do not work that way.

If this affects your bytecode then either you were unintentionally linking your code with the wrong library of the same name - your code will stop linking but that might be better than continuing to link it with the wrong thing - or you were relying on the fact that you don't need to specify the correct name - you have to be less lazy and update your build system to use the right name.

There's a slight risk that some tools were relying on this buggy behavior too and will break. We could check Truffle and Brownie and post on Twitter about it if it turns out that it is actually a problem (I think it's likely that it's not).

**Review by leonardoalt — DISMISSED** [review]

**Comment by chriseth** [comment]
Needs rebase.

**Comment by cameel** [comment]
Rebased. Looks like I used the same name for different command-line tests in this PR and #10292.

**Review by chriseth — APPROVED** [review]

**Pull request merged**
