### PR TITLE
Bump z3 version to 4.8.13 in our docker files

### PR DESCRIPTION
**Pull request by leonardoalt**
Depends on https://github.com/ethereum/solidity/pull/12317

### CODE REVIEW

**Review by cameel — DISMISSED** [review]

**Comment by leonardoalt** [comment]
waittt

**Comment by cameel** [comment]
Oh, right. We now have the 4.8.12 check in CMakeLists.txt that needs to be updated as well.

**Comment by leonardoalt** [comment]
We still need to wait for the PPA update to finish the builds before running the docker updates

**Comment by leonardoalt** [comment]
This PR will only update the docker images. We'll use those hashes in another PR together with the test updates, and I'll update cmake stuff there as well.

**Comment by Marenz** [comment]
Arch test failing

**Comment by leonardoalt** [comment]
We need to fix the intx thing to build the final docker image that is missing here

**Comment by leonardoalt** [comment]
@bshastry is this the final version of the ossfuzz build?

**Comment by bshastry** [comment]
> @bshastry is this the final version of the ossfuzz build?

Yes. Turns out Hera (which caused the build failure) is redundant for fuzzing. Trimmed the dockerfile :-)

**Comment by leonardoalt** [comment]
Ok cool! The PRs can be merged then.

**Comment by leonardoalt** [comment]
@bshastry but do we want to keep the second last commit, regarding the clang warning flag?

**Comment by leonardoalt** [comment]
Depends on https://github.com/ethereum/solidity/pull/12317

**Comment by axic** [comment]
> Depends on #12317

Isn't it the reverse? #12317 depends on this, but this can be freely merged without issues.

**Comment by bshastry** [comment]
> @bshastry but do we want to keep the second last commit, regarding the clang warning flag?

No, that is not necessary now. Only the latest commit (removing build steps for Hera) is relevant.

**Comment by leonardoalt** [comment]
> > Depends on #12317
> 
> Isn't it the reverse? #12317 depends on this, but this can be freely merged without issues.

Well the other one depends on this one running,  just to update the docker images, but not necessarily to be merged. But yea at this point they're rather independent, unless we decide to remove the second last commit and re run the docker builds.

**Review by chriseth — APPROVED** [review]

**Pull request merged**
