### PR TITLE
Packed encoding for encoder V2.

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/4821

### CODE REVIEW

**Comment by chriseth** [comment]
It turns out that the packed encoding in encoder V1 *did* in fact pad array elements. This is a documented feature in the code, but not in the documentation.

My proposal is to replicate that behaviour. The question would be how to extend the behaviour to arbitrarily nested arrays and structs.

To stay compatible with "structs are just tuples with named elements", structs elements could be non-padded.

The question would be how to encode arrays of structs. I would say there are two options:
1. Encode struct elements without padding but add padding after the structs.
2. Switch to padded (but still "packed" - it does not contain array lengths) encoding inside arrays and keep it like that

The downside of option 1 is that for `struct S { uint8 x; }`, the type `S[2]` would be encoded differently than `uint8[2]` - since in the case of `S[2]`, the values would be left-aligned, while they would be right-aligned in `uint8[2]`.

I think the fact that packed encoding could be shorter in some cases does not really matter. If people want a compact encoding, they should use something completely different. Also, arrays have not been compact before.

Because of the two arguments above, I would propose to use option 2: Inside arrays, everything is padded (`bytes` and `string` might also be padded to multiples of 32 bytes, but only inside arrays), but we still encode data in-place without a length prefix.

**Comment by chriseth** [comment]
Actually, it simplify the implementation and also the encoding, I would propose the following:

 - no padding is only applied at the very top level of the encoding (i.e. only between individual arguments to `abi.encodePacked`)
 - `bytes` and `strings` are not padded if they appear at the very top
 - elements of arrays and structs are always padded, but they both encode their members in-place and without length prefix

**Comment by ekpyron** [comment]
Why do we need this encoding at all again? Especially, if its size doesn't matter :-)?

**Comment by chriseth** [comment]
We need this encoding because it is used for indexed events and exposed via `abi.encodePacked`.

**Comment by chriseth** [comment]
And it turned out to be a nice way to concatenate strings ;)

**Comment by ekpyron** [comment]
For concatenating strings we could write something else or extract and rename the needed bits :-). Indexed events sound like a good reason, though (EDIT: the fact that they use it, that is - not sure there's a good reason for them to use it, though :-)).

**Comment by chriseth** [comment]
Replaced by https://github.com/ethereum/solidity/pull/5839

**Pull request closed without merging**
