### PR TITLE
Ensure that the fractional digits of a fixed-point token fit into its total bits.

### LINKED ISSUE #4061: Fixed point type fractional digit limit
Currently the limit is set at maximum 80 digits, that means the largest number representable would be
`0.999999999999999999999999999999999999999999999999999999999999999999999999999999999` in the `ufixed256x80` type, while the largest number fitting 256 bits is `115792089237316195423570985008687907853269984665640564039457584007913129639936`.

`999999999999999999999999999999999999999999999999999999999999999999999999999999999`
is larger than
`115792089237316195423570985008687907853269984665640564039457584007913129639936`

It actually requires 266 bits (`log2(pow(10, 80) - 1)`). I think the proper limit is 77 digits.

Not to mention signed fixed point, where an extra bit must be reserved for the sign.

### PR DESCRIPTION
**Pull request by 0yi0**
Hello, this PR aims to fix #4061 at parsing time.

I've looked over #4064, and found that the checks were added at AST level. It will cause invalid fixed point types like `ufixed8x4` to fail (as an std::exception) at `FixedPointType` constructor.

I think that in addition to the checks added by #4064, we should also generate error messages for invalid fixed point types (eg.`ufixed8x4`) similar to invalid integer types (eg. `uint12`).

```
test.sol:3:5: Error: Identifier not found or not unique.
    uint12 a; a;
    ^----^
test.sol:3:5: Error: Identifier not found or not unique.
    ufixed8x4 b = 0.1234; b;
    ^--------^
```

Thanks in advance for any comments.

### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [x] ~New tests have been created which fail without the change (if possible)~ old tests are updated though
- [x] ~Changelog entry (if change is visible to the user)~ tell me if that is needed

### CODE REVIEW

**Comment by 0yi0** [comment]
I've checked #4765 but have no idea why the test `too_small_negative_numbers` was expected to pass previously.

The current error message is weird but I think it's better than no error.
```
TypeError: (31-38): Type rational_const -1 / 1000...(93 digits omitted)...0000 is not implicitly convertible to expected type fixed256x76. Try converting to type fixed8x80 or use an explicit conversion.
```
Any suggestions about this test case?

**Comment by chriseth** [comment]
@axic could you take a look here, please?

In my opinion, we don't really need this restriction at all. What is the idea behind wanting `1` to be part of the value range of a type?

**Comment by randomnetcat** [comment]
Ah, this issue again. This question has been asked and answered in the primary fixed point PR #3389. It was determined that 1 does not need to be in the range of the type for the type to be valid.

@chriseth

**Comment by chriseth** [comment]
Thanks! Closing then.

**Pull request closed without merging**
