### PR TITLE
Add flattened openzeppelin contract that triggers ICE via SMTChecker.

### PR DESCRIPTION
**Pull request by bshastry**
Virtual function resolution fails during SMT checking. Since the test is huge (and a pain to minimise), this draft PR has been created. If required, can be tracked in a separate issue.

### CODE REVIEW

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `68402ff1eda3b14c2d483ce568275efe745fb8e2`:
```
Error: Trailing whitespace found:
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:20:     * @dev Mints `initialSupply` amount of token and transfers them to `owner`.  
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:347:     * @dev Mints `initialSupply` amount of token and transfers them to `owner`.  
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:1988:        bytes32 typeHash = keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"); 
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:2936:  function version() public pure virtual returns (string memory); 
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:3292:// 
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:4823: * 
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:4826: * 
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:4832:     * 
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:4865:     * 
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:4892:     * 
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:5081: * 
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:5084: * 
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:5273:     * If `data` is nonempty, it's used as data in a delegate call to the implementation returned by the beacon. 
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:5384:     * 
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:5386:     * 
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:5399:     * 
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:5401:     * 
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:5414:     * 
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:5416:     * 
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:5425:     * 
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:5427:     * 
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:5437:     * 
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:5439:     * 
test/libsolidity/smtCheckerTests/inheritance/open_zeppelin_ICE.sol:7872:   * Accepts all token transfers. 

```
Please check that your changes are working as intended.

**Comment by axic** [comment]
I think there should be a more minimal example, this is 10000 lines :)

**Comment by bshastry** [comment]
> I think there should be a more minimal example, this is 10000 lines :)

I agree. Just a bit lost navigating the flattened source

**Comment by hrkrshnn** [comment]
> Virtual function resolution fails during SMT checking

How was this detected?

**Comment by bshastry** [comment]
> > Virtual function resolution fails during SMT checking
> 
> How was this detected?

Not sure I follow. What do you mean?

**Comment by cameel** [comment]
Here's a minimal repro for the same ICE:

``` solidity
pragma experimental SMTChecker;

contract Context {}

contract ERC20 is Context {
    function approve() public virtual { _approve(); }
    function _approve() internal virtual {}
}

contract __unstable__ERC20Owned is ERC20 {
    function _approve() internal override {
        if (true) {
            super._approve();
        }
    }
}
```

```
/solidity/test/boostTest.cpp(123): error: in "smtCheckerTests/inheritance/gsn": Exception during extracted test: /solidity/libsolidity/ast/AST.cpp(394): Throw in function virtual const solidity::frontend::FunctionDefinition& solidity::frontend::FunctionDefinition::resolveVirtual(const solidity::frontend::ContractDefinition&, const solidity::frontend::ContractDefinition*) const
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Virtual function _approve not found.
[solidity::util::tag_comment*] = Virtual function _approve not found.
```

`__unstable__ERC20Owned` is defined in `contracts/GSN/GSNRecipientERC20Fee.sol` in OpenZeppelin. Here I have removed everything that wasn't relevant and combined it with `ERC20` and `Context`.

Also, removing the empty `Context` contract triggers a completely different ICE:

``` solidity
pragma experimental SMTChecker;

contract ERC20 {
    function approve() public virtual { _approve(); }
    function _approve() internal virtual {}
}

contract __unstable__ERC20Owned is ERC20 {
    function _approve() internal override {
        if (true) {
            super._approve();
        }
    }
}
```

```
/solidity/test/boostTest.cpp(123): error: in "smtCheckerTests/inheritance/gsn": Exception during extracted test: /solidity/libsolidity/formal/SMTEncoder.cpp(2722): Throw in function solidity::frontend::SMTEncoder::functionCallToDefinition(const solidity::frontend::FunctionCall&, const solidity::frontend::ContractDefinition*, const solidity::frontend::ContractDefinition*)::<lambda(const auto:36*)> [with auto:36 = solidity::frontend::MemberAccess]
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Super contract not available.
[solidity::util::tag_comment*] = Super contract not available.
```

**Comment by bshastry** [comment]
> Also, removing the empty Context contract triggers a completely different ICE:

~~This~~ The second one looks like a dup of https://github.com/ethereum/solidity/issues/10926

**Comment by bshastry** [comment]
@cameel Thank you for reducing the test case to a few lines of code from 10000! Would you mind opening an issue for the first one? I will then close this draft PR.

Edit: Just wanted to add that my early attempt at a minimisation mostly revolved around playing around with an internal virtual function that is then overridden by calling super's version of it. This was not successful. So, there is something about the second approve function (that is public/virtual) although it seems to clearly have a different name. Also funny that the first ICE requires a dummy (empty) base contract to be triggered.

**Comment by cameel** [comment]
Done: #10957.

**Pull request closed without merging**
