### PR TITLE
Bump Boost version from 1.65.0 to 1.69.0

### PR DESCRIPTION
**Pull request by codebam**

### CODE REVIEW

**Comment by codebam** [comment]
This threw an error right as it hit 100% on my system. So the compile of `solc` was successful but I got this right at the very end.

```
[100%] Building CXX object solc/CMakeFiles/solc.dir/main.cpp.o
make[3]: *** No rule to make target '/usr/lib/libboost_program_options.a', needed by 'solc/solc'.  Stop.
make[2]: *** [CMakeFiles/Makefile2:622: solc/CMakeFiles/solc.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:629: solc/CMakeFiles/solc.dir/rule] Error 2
make: *** [Makefile:327: solc] Error 2
Error: error building at STEP "RUN apk --no-cache --update add build-base cmake boost-dev git                                                &&   sed -i -E -e 's/include <sys\/poll.h>/include <poll.h>/' /usr/include/boost/asio/detail/socket_types.hpp  &&   git clone --depth 1 --recursive -b boost-1.69.0 https://github.com/codebam/solidity                       &&   cd /solidity && cmake -DCMAKE_BUILD_TYPE=Release -DTESTS=0 -DSTATIC_LINKING=1                             &&   cd /solidity && make solc && install -s  solc/solc /usr/bin                                               &&   cd / && rm -rf solidity                                                                                   &&   apk del sed build-base git make cmake gcc g++ musl-dev curl-dev boost-dev                                 &&   rm -rf /var/cache/apk/*": error while running runtime: exit status 2
```

I used the Dockerfile that was provided from docker hub.

**Comment by codebam** [comment]
It looks like the builds for Ubuntu and some others succeeded so it might just be Fedora

**Comment by hrkrshnn** [comment]
> It looks like the builds for Ubuntu and some others succeeded so it might just be Fedora

What exactly is the problem that you are facing?

**Comment by codebam** [comment]
@hrkrshnn The Docker image doesn't work with the `--evm-version` command

**Comment by hrkrshnn** [comment]
Why would upgrading boost be a fix for that?

**Pull request closed without merging**
