### PR TITLE
Update GPG key URL for Centos install

### LINKED ISSUE #2391: Failed to run script "install_deps.sh" on CentOS
## Which version of Solidity
latest commit  on branch develop c99c1c76f

## What was the source code
File `scripts/install_deps.sh`, [Line 325~Line 366][line325]

## Which platform are you running on
* OS: CentOS 7.3
* Kernel: Linux x86_64 3.10.0-514.21.1.el7

## How to reproduce the issue
Clone the repo, fetch submodules
```sh
$ git clone https://github.com/ethereum/solidity.git
$ git submodule update --init --recursive
```
And
```sh
$ ./scripts/install_deps.sh
```

## What was the result of the issue
Retrieve GPG keys from remote failed 
```sh
This script will heavily modify your system in order to allow for compilation of Solidity. Are you sure? [Y/N]YLoaded plugins: axelget, fastestmirror
No metadata available for base
No metadata available for extras
No metadata available for updates
Loading mirror speeds from cached hostfile

Package epel-release-7-9.noarch already installed and latest version
Nothing to do
curl: (22) The requested URL returned error: 404 Not Found
error: http://ftp.scientificlinux.org/linux/scientific/5x/x86_64/RPM-GPG-KEYs/RPM-GPG-KEY-cern: import read failed(2).
```
## What the expected behaviour is
Successfully imported GPG keys and installed dependent packages.

[line325]: https://github.com/ethereum/solidity/blob/develop/scripts/install_deps.sh#L325

**So, will this issue be fixed? Any other advice on building solidity for CentOS?**

### PR DESCRIPTION
**Pull request by terasum**
Fixes #2391.

### CODE REVIEW

**Comment by chriseth** [comment]
Thanks for the change! Can you please justify why that key is the correct one? :)

**Comment by axic** [comment]
This seems to be the right key (at least it is from the same URL the packages are imported from): http://linuxsoft.cern.ch/cern/slc6X/i386/RPM-GPG-KEY-cern

This matches the one proposed in this PR. I'd however prefer to link to this one (as it is within the repo) or include the key verbatim in the script.

**Comment by terasum** [comment]
@chriseth I can't prove this GPG key file is correct one, I don't even know the original GPG key file content is. I just google it then got this url.I think  maybe including the key verbatim in the script is more acceptable as @axic said.

**Comment by chriseth** [comment]
Perhaps we could include the key fingerprint?

**Comment by terasum** [comment]
okey, I'll try this, but how can I get the origin fingerprint?

**Comment by axic** [comment]
Apparently ` gpg --with-fingerprint -v RPM-GPG-KEY-cern` gives you the fingerprint. Though it is not a nice interface.

Updated the URL to use the file from the same host (linux.cern.ch) as the packages.

**Review by axic — APPROVED** [review]

**Pull request merged**
