### PR TITLE
[WIP] Warn if using this in constructor

### LINKED ISSUE #583: warn about usage of `this` in constructor
This was originally a bug report that turned into a feature request:

The compiler should warn about calling functions on `this` in the constructor and any function called from the constructor. I think we will not be able to catch all cases (you also have to include modifiers, base classes and other things), but we could at least try.

---

This seems like a compiler bug to me, unless I have a misunderstanding here…

Consider the contract

``` js
contract PingPong {
    function PingPong() {
        this.foo(msg.sender, msg.value);
    }
    function () {
        this.foo(msg.sender, msg.value);
    }
    function foo(address originalSender, uint originalValue) {
        originalSender.send(originalValue);
    }
}
```

You can see this deployed on Morden here: [0x1689e1992bc3690383d74d439e4055c34a2640fe](http://testnet.etherscan.io/address/0x1689e1992bc3690383d74d439e4055c34a2640fe)

Upon contract creation, I was expecting the value sent with the tx to be bounced back to the sender. Instead, the contract ends up sending the ETH to itself in an internal tx: `msg.sender` was resolved to the address of the newly created contract _not_ the true sender.

(The default method works as expected: two internal txs, the second returning the ETH to the original sender.)

Lifting `msg.sender` to a local name makes no difference:

``` js
contract PingPong {
    function PingPong() {
        address originalSender = msg.sender;
        uint originalValue = msg.value;
        this.foo(originalSender, originalValue);
    }
…
```

Only an internal method call works as expected:

``` js
contract PingPong {
    function PingPong() {
        foo(msg.value, msg.sender);
    }
…
```

Is this a bug? Have I misunderstood something special about the constructor?

### PR DESCRIPTION
**Pull request by axic**
Fixes #583.

### CODE REVIEW

**Comment by chriseth** [comment]
I think both the changelog, the error description and the implementation should be changed to:

Warn only if `this.f()` is used, i.e. both `this` and `this.f` are fine. It would also be great to include functions called from the constructor (i.e. record function calls like `this.f()` while traversing the tree together with the function they are used in and then compile a report in the `endVisit` function of the contract).

**Comment by axic** [comment]
Rebased for good measure.

**Comment by axic** [comment]
@roadriverrail would you be interested in working on this?

**Comment by roadriverrail** [comment]
@axic Yes, I'll look into this soon

**Comment by roadriverrail** [comment]
With all my other stuff done or gated only on questions about style, I'm now actively working on this.  I'm late to the party, but it seems like we would like to do the following:

1) Identify all function calls made in constructor, and all function calls that those functions call, etc.
2) Determine if any of these functions ever perform a `this.foo( )` style call.
3) Report it as a warning.

Yes?

**Comment by axic** [comment]
@roadriverrail seems correct. The problem here is that while the contract address (`this)` and function types (`this.f)` are valid, but the contract at the destination is not yet present, so calling it results in failure. That is what we're warning for.

**Comment by roadriverrail** [comment]
@axic after talking with @chriseth earlier in the week, I'd effectively be building up a call graph for the contract for the purposes of implementing this analysis fully.  We really ought to have a general-purpose call graph and then make the "no `this` in constructor call tree" part implemented on top of that, rather than building up a call graph for a single purpose.  As such, and because there's a lot of enthusiasm for other things I'm working on, @chriseth and I agreed that I'd actually get this working for calls through `this` directly in the constructor and leave checking functions called by the constructor for later.  There are some commits already here, so I'll look into finishing them up and writing tests for them.  Perhaps we should break off the rest of the work to a separate issue in the issue tracker?

@chriseth please correct me if I'm wrong about any of that.

**Comment by roadriverrail** [comment]
Hey...the source branch for this PR is on the `ethereum/solidity` remote, which I can't push to.  I can push it over to my remote, but that will cause a separate PR.  Since I'm going to be leaving this work soon to work on other things, maybe I could just get push access to `ethereum/solidity` for a little while so I can put the clean up and rebase in?  There's not much else to do, if we're not going to work on things that require a call graph to do.

**Comment by axic** [comment]
@roadriverrail if you would like to work on this, feel free to open a new PR and we can close this one.

**Comment by roadriverrail** [comment]
Yes.  I've been meaning to

**Comment by roadriverrail** [comment]
Obviated by pull request #2605

**Pull request closed without merging**
