### PR TITLE
Update contracts.rst

### PR DESCRIPTION
**Pull request by ghost**
I've changed **msg,sender** to **tx.origin**, because there was no way to transfer the token. Double check it, please, because I've been learning solidity only for a couple of days now.

### CODE REVIEW

**Comment by Denton-L** [comment]
This makes your contract vulnerable to attacks. If you're using `tx.origin`, if you're calling another contract, they could, in turn, call back into an instance of `OwnedToken` which you own. Since `tx.origin` still is _you_, they can effectively manipulate `OwnedToken` to do whatever they want.

With `msg.sender`, if the malicious contract attempts to do this, `msg.sender` won't have your address. Instead, it'll have the address of the malicious contract. As a result, the usage of `msg.sender` here is correct.

**Comment by ghost** [comment]
@Denton-L, wow, didn't know that. What would such a callback look like? `OwnedContract.call(...)?`

**Comment by Denton-L** [comment]
~~There are no callbacks in Solidity. You could possibly simulate one but that would require something external to the blockchain watching at all times.~~

Sorry about that, I was half-asleep when I was typing that. Indeed, you can write callbacks using the `call` function. More information can be found [here](http://solidity.readthedocs.io/en/latest/types.html#address).

However, just because it _can_ be done, doesn't mean it _should_ be done. In my opinion, programming with callbacks in Solidity is an anti-pattern.

**Comment by chriseth** [comment]
@Denton-L callbacks will soon be necessary for asynchronous or cross-shard communication, but that's a special case.

**Pull request closed without merging**
