### PR TITLE
Documentation website revamp

### PR DESCRIPTION
**Pull request by wackerow**
## Background
Hey folks! Been working on a revamp for the Solidity website, with scope including the following pages:
- https://soliditylang.org (Currently [ethereum/solidity-portal](https://github.com/ethereum/solidity-portal))
- https://blog.soliditylang.org (Currently [ethereum/solidity-blog](https://github.com/ethereum/solidity-blog))
- https://docs.soliditylang.org (This repo, under `~/docs` folder)

The first two are being replaced with a new repo being migrated in parallel from [wackerow/solidity-website](https://github.com/wackerow/solidity-website) ([deploy preview here](https://solidity-website.vercel.app)) to `ethereum/solidity-website` (in progress). This update involved a complete revamp of the theming of those sites.

## PR Description
The documentation website, built using RTD, has been re-themed to match the core site and blog. The static site is still built using the base RTD config, but this heavily overrides the appearance of the resulting static site using JS and CSS.

All changes are confined to the `~/docs` folder.

Change highlights:
- Dark/light color mode theming updated to match core Solidity site and blog
- Fonts, styles, and spacing updated to similarly match new core site
- Header bar revamped to match new sore site

## Preview URL
Currently hosting a preview deploy of these changes on a personal RTD setup:
https://solidity-docs-dev.readthedocs.io/en/latest/

## Screenshot
image
image

## Timing
Some of the links are dependent upon the other half of this website upgrade. The `ethereum/solidity-website` repo should be merged and launched first, and ideally this follows closely afterward.

Setting this in draft mode for the time being.

cc: @NunoFilipeSantos @franzihei @nloureiro @minimalsm

### CODE REVIEW

**Comment by NunoFilipeSantos** [comment]
Thanks @wackerow ! 👍

**Comment by wackerow** [comment]
Hey folks! The core site at https://soliditylang.org just went live! :tada: It was just switched over to the GitHub Pages build over on [ethereum/solidity-website](https://github.com/ethereum/solidity-website).

With that, this PR is ready to go to complete the suite! cc: @NunoFilipeSantos @franzihei

**Review by NunoFilipeSantos — DISMISSED** [review]
That's great! Thank you!

**Review by minimalsm — APPROVED** [review]

**Comment by NunoFilipeSantos** [comment]
Feel free to squash and merge it.

**Comment by wackerow** [comment]
Great! Just noting that I don't have any write access here myself

**Comment by wackerow** [comment]
Oops, sorry about that, there was one last commit that I didn't realize wasn't pushed, accidentally dismissed the review.

**Comment by NunoFilipeSantos** [comment]
I think now you need to rebase this one.

**Comment by wackerow** [comment]
@NunoFilipeSantos Okay great, just rebased and squashed all of my commits. Should be good to go!

**Review by NunoFilipeSantos — APPROVED** [review]
Merging.

**Comment by wackerow** [comment]
@NunoFilipeSantos Everything okay?

**Pull request merged**
