### PR TITLE
[SMTChecker] Add CHCSmtLib2Interface

### PR DESCRIPTION
**Pull request by leonardoalt**

### CODE REVIEW

**Comment by leonardoalt** [comment]
I tested this with the callback stuff from https://github.com/ethereum/solidity/pull/7447 and it works fine. We can also wait for that to be merged first + the tests via solc-js and this on top if required.

**Comment by Marenz** [comment]
I think most people (including me) who want to review this have no idea what it is about and don't feel knowledgable enough to review this. Maybe explain it, here or in person?

**Comment by leonardoalt** [comment]
There are currently 2 model checking engines in the SMTChecker: BMC and CHC.

BMC uses SMT solvers, which here are: Z3Interface (via API), CVC4Interface (via API), and SmtLib2Interface, which creates the SMT queries as strings and can be solved by any solver (not via API).

CHC uses Horn solvers, which here are: CHCZ3Interface (via API) and CHCSmtLib2Interface, added by this PR, which similar to SmtLib2Interface is not connected via API and creates Horn queries as strings an can be solved by any solver that reads this format.

The interface followed by Z3Interface, CVC4Interface and SmtLib2Interface is SolverInterface, which is similar to `z3::solver`.
The interface followed by CHCZ3Interface and CHCSmtLib2Interface is CHCSolverInterface which should be similar to `z3::fixed_point`.

**Review by Marenz — DISMISSED** [review]
I can't speak for the correctness of the solver specific parts, but I saw no obvious defects or problems in the code

**Comment by chriseth** [comment]
Has conflicts.

**Comment by leonardoalt** [comment]
Rebased

**Comment by leonardoalt** [comment]
Fixed build

**Comment by leonardoalt** [comment]
@chriseth @Marenz

**Review by Marenz — APPROVED** [review]

**Pull request merged**
