### PR TITLE
Merge tags into develop.

### PR DESCRIPTION
**Pull request by 5chdn**
This is a zero diff pull request. It merges tags from `release` branch back into `develop` as explained in #1123 and is a suitable workaround now to keep the version numbers for intermediate releases up to date.

### CODE REVIEW

**Comment by chriseth** [comment]
I understand the effect of this PR on the repository, but what is the effect on packages, i.e. what is the problem you are solving?

**Comment by 5chdn** [comment]
The problem is that a package build from latest develop does not contain the tags `v0.4.1` and `v0.4.2`. The output of `git describe --tags` currently is:

```
v0.4.0-59-gf52634a
```

But it also includes the code of all changes up to `v0.4.2` and beyond. In the arch user repository it looks like that:

```
 $ pacaur -Ss solidity
aur/solidity 0.4.2-1 (1, 0.33)
aur/solidity-git v0.4.0.r59.gf52634a-1 (1, 0.33)
[...]
```

Which suggests the latest development build is lagging behind the official releases.

See also [git describe ignores tags](http://stackoverflow.com/a/39611938/1260906)

I'm sorry if this is confusing and I'm trying not to consume too much of your time on this, but I'm having a hard time to automatically extract valid build numbers.

**Comment by chriseth** [comment]
Ok, now I understand a bit better. We are currently using the tags only for github releases. The actual version number should be taken from `CMakeLists.txt` and the various packaging scripts also use `prerelease.txt` and `commit_hash.txt` to create the full version information. The idea is that when creating a package, we might not have `.git` available (this is the case for ppa, for example). We might make an effort to combine those scripts so that we only create the version string in one place.

Is that an option for arch?

 Please don't think that this consumes my time, you are providing your free time to create packages, so I'm consuming your time :-)

**Comment by 5chdn** [comment]
Yes, using CMakeLists.txt is an option for arch.

Will use the following now: 

```
 solidity $ grep -m1 "PROJECT\_VERSION" CMakeLists.txt | sed 's/[[:alpha:]|\_|(|[:space:]|)|\"]//g' | awk '{print "v" $1 "-git"}'
v0.4.3-git
```

**Comment by chriseth** [comment]
@5chdn would it make sense to include the arch scripts inside this repository?

**Comment by 5chdn** [comment]
Actually, it does make sense to add them. Like `ebuild` files for Gentoo, the `pkgbuild` files for arch allow anyone to build the package independently, locally.

If you tell me where I should place them, I can submit another PR.

**Comment by chriseth** [comment]
We have a generic directory called `scripts`, I think that's the place.

**Pull request closed without merging**
