### PR TITLE
Trigger error for arrays that require too much storage

### LINKED ISSUE #9099: [solc] ICE because "object too large for storage"
## Description

```
contract C {
    bytes1[8**80][1701455] a;
    bytes1[8**80][1701455] b;
}
```

throws

https://github.com/ethereum/solidity/blob/97cb091ada06080bfd8ad9f28413875490b52be0/libsolidity/ast/Types.cpp#L188

## Environment

- Compiler version: latest develop

## Steps to Reproduce

```
$ solc <input.sol>
```

### PR DESCRIPTION
**Pull request by Marenz**
fix #9099

### CODE REVIEW

**Comment by ekpyron** [comment]
I'm not quite happy with the duplication of the stuff ``Type::validForLocation`` does for arrays and structs and ``structureSizeEstimate``. Can you improve ``Type::validForLocation`` to cover all these cases instead? Annoying thing is that mappings don't inherit from ``ReferenceType``...
That would probably mean moving ``validForLocation`` from ``ReferenceType`` to ``Type`` and implementing it for mappings as well, which would raise the question what to have it do for value types...

The other direction, i.e. moving what ``validForLocation`` does to the static analyzer is not good either - we had ICEs because of such checks happening too late...

Any good ideas in that direction :-)?

**Comment by chriseth** [comment]
Is this obsolete now?

**Comment by Marenz** [comment]
The test case in this PR still fails (causes an assert) with current develop

**Comment by ekpyron** [comment]
It overlaps with https://github.com/ethereum/solidity/pull/9062/, though, doesn't it?

**Comment by Marenz** [comment]
Ah, I thought we merged that already. Yes they overlap and the test works correctly with the linked PR (just checked)

**Comment by Marenz** [comment]
replaced by #9062

**Pull request closed without merging**
