### PR TITLE
Move modelCheckerSettings out of settings in StandardCompiler

### PR DESCRIPTION
**Pull request by leonardoalt**

### CODE REVIEW

**Comment by chriseth** [comment]
Can you add a test that shows that this is not part of the metadata?

**Comment by leonardoalt** [comment]
@chriseth How do I do that

**Comment by leonardoalt** [comment]
Ah managed

**Comment by leonardoalt** [comment]
@chriseth add a commit with the requested info

**Review by chriseth — APPROVED** [review]

**Comment by axic** [comment]
What was the reason behind moving it out? In fact I think it made more sense under `settings`, given every other setting is grouped there.

**Comment by leonardoalt** [comment]
Metadata

**Comment by ekpyron** [comment]
I was just wondering the same as @axic, while thinking about https://github.com/ethereum/solidity/issues/9583#issuecomment-737102636, for which this change makes things a lot less nice...
And as for the metadata argument: ``outputSelection`` is just as well part of ``settings`` and will never end up in the metadata, so there is in no way a real direct correspondence between standard-json input ``settings`` and metadata ``settings``.

In fact, I'd really vote for reverting this change before it becomes set in stone due to being released for too long of a time - 0.8 would be a good chance.

**Comment by ekpyron** [comment]
Looking at the timing of this change, to me this seems a bit like a last-minute pre-release panic-change that wasn't entirely thought through and I don't think we should let it dictate the standard-json interface for all eternity ;-).

**Comment by ekpyron** [comment]
One alternative would be to radically move in the other direction and deprecate all standard-json ``settings`` that won't end up as they are in the metadata (like ~~``settings.metadata``,~~ ``settings.stopAfter``, ``settings.outputSelection``) as well as ``modelCheckerSettings`` and move all of them to a new top-level key called ``options``.

**Comment by ekpyron** [comment]
Created https://github.com/ethereum/solidity/issues/10470 for this.

**Comment by leonardoalt** [comment]
Yes, it was a pre-release hot fix move. I agree with your points though, but I think I prefer the outer `options` idea.

**Comment by axic** [comment]
> One alternative would be to radically move in the other direction and deprecate all standard-json settings that won't end up as they are in the metadata (like settings.metadata, settings.stopAfter, settings.outputSelection) as well as modelCheckerSettings and move all of them to a new top-level key called options.

I'm not sure why there is a need for `settings` to match the metadata, and what is the difference between `settings` and `options`, intuitively without knowing about the metadata.

**Comment by ekpyron** [comment]
Yeah... ``options`` are optional stuff that doesn't affect the "relevant, fixed" output, i.e. bytecode - and ``settings`` are setting fixed stuff that is then set in stone in bytecode ;-)... but yeah, it's a stretch and maybe it's not that good of an idea after all and we should just move ``modelCheckerSettings`` back to ``settings``...

**Comment by chriseth** [comment]
Please create an issue about it and schedule it into the project.

**Comment by haltman-at** [comment]
I only just saw this... was this done in a breaking fashion?  Will `modelCheckerSettings` no longer work?  Could it be possible for both to work (with I guess the preferred one overriding the other one)?

**Comment by chriseth** [comment]
Just for the record: Yes, it can be considered breaking, but it is an interface change and the feature was only introduced one release ago, so our recommendation would be to just not support the old location of the setting at all.

**Comment by haltman-at** [comment]
Yeah, I realized after writing this that actually we can just foist this problem off on our own users, so I don't think it's really a problem after all.  Thanks!

**Pull request merged**
