### PR TITLE
Remove trailing spaces from JSON output

### LINKED ISSUE #7373: Trailing spaces in JSON output
Came up in https://github.com/ethereum/solidity/pull/7372.

Our JSON AST output (and potentially other json output) has trailing spaces, which required a workaround in our check_style script for the recovery_ast_constructor commandline test and for all ASTJSON tests.

The whitespace is needlessly generated by json-cpp, so we need to postprocess its output.

The task is to adjust ``ASTJsonConverter`` to remove all trailing whitespace generated by json-cpp before printing.
A possible approach would be to change ``ASTJsonConverter::print`` to write to a temporary ``std::stringstream`` first. Then the contents of that can be read back line by line, stripped of whitespace and written to the desired ``std::ostream``.

### PR DESCRIPTION
**Pull request by ghallak**
Use `jsonPrettyPrint` for printing JSON AST, so that trailing spaces are not added in JSON output.

Closes #7373

### CODE REVIEW

**Comment by chriseth** [comment]
Nice! Can you please squash the changes to the expectation files into a single commit?

**Comment by ghallak** [comment]
> Nice! Can you please squash the changes to the expectation files into a single commit?

Done.

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
Ah, sorry! I just noticed after merging that it was against the wrong branch.

**Comment by ghallak** [comment]
Isn't `develop_060` the right branch to merge against? I thought that the issue was introduced in `develop_060` according to this comment https://github.com/ethereum/solidity/issues/7373#issue-490285021.

The test file that was causing the issue is not excluded in the branch `develop`, so I assumed that this issue is not happening in the `develop` branch.
https://github.com/ethereum/solidity/blob/f35458b2ff35aa1927f28dd0ef15c09fd63dc672/scripts/check_style.sh#L9

**Comment by chriseth** [comment]
"Came up in #7372" just referred to that we realized it while discussing/working on #7372.

**Pull request merged**
