### PR TITLE
Build in release mode.

### PR DESCRIPTION
**Pull request by chriseth**
RelWithDebugInfo:
```
solidity/test/compilationTests/corion# time solc *.sol
real	0m1.697s
user	0m1.688s
sys	0m0.004s
```

Release:
```
solidity/test/compilationTests/corion# time solc *.sol
real	0m0.199s
user	0m0.172s
sys	0m0.024s
```

### CODE REVIEW

**Comment by chriseth** [comment]
Not sure how we actually distribute binaries, but I get a 10x speed increase just using the Release binary.

**Comment by axic** [comment]
Why is the debug info causing such a slowdown? Does this also affect emscripten?

**Comment by axic** [comment]
Ok this only affects CI runs. Travis is not changed and as a result releases are not actually affected.

**Comment by chriseth** [comment]
@axic we will release from circleci starting from the upcoming release.

**Comment by chriseth** [comment]
emscripten has always been built in Release mode.

**Comment by chriseth** [comment]
The RelWithDebugInfo has almost three times the size, even if both are stripped.

**Review by axic — APPROVED** [review]

**Pull request merged**
