### PR TITLE
Do not include public variables in internal function overload resolution.

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/4417

 - [ ] tests

### CODE REVIEW

**Comment by axic** [comment]
Any way to have a proper error and not an assertion?

**Comment by chriseth** [comment]
Perhaps we can also just remove the assertion. It was meant as an actual assertion but now I'm not sure anymore if this is the only situation.

**Comment by axic** [comment]
@ekpyron @chriseth is this in conflict with #4508 ?

**Comment by ekpyron** [comment]
I think this still can be merged, even though #4508 also fixes the underlying issue.

**Comment by chriseth** [comment]
Were all tests added already in #4508? I would be happy for @ekpyron to take this over, I think I need more time to get into the matter again.

**Comment by ekpyron** [comment]
@chriseth  OK, I can take over this one. I need to think about whether this PR is actually still necessary or useful or whether we can even use stronger asserts here after #4508 is merged myself, though.

**Comment by ekpyron** [comment]
After #4508 the original assertion should always work again, so this PR is superfluous.

**Pull request closed without merging**
