### PR TITLE
Add SPDX license identifier if not present already in source file

### LINKED ISSUE #9220: Add SPDX license identifier to the compiler source code
Since we advocate for this in Solidity programs, we should bite the bullet and also include it in all the compiler source code 🙊

### PR DESCRIPTION
**Pull request by sacgrover**
Fixes: #9220

### CODE REVIEW

**Comment by hrkrshnn** [comment]
I think the original issue meant adding `// SPDX-License-Identifier: GPL-3.0` to all `.cpp` and `.h` files in solidity (maybe even more!) provided that that file has a `GPL-3.0` license already.

Currently, we have the following to indicate the license.

> 
> /*
> 	This file is part of solidity.
> 
> 	solidity is free software: you can redistribute it and/or modify
> 	it under the terms of the GNU General Public License as published by
> 	the Free Software Foundation, either version 3 of the License, or
> 	(at your option) any later version.
> 
> 	solidity is distributed in the hope that it will be useful,
> 	but WITHOUT ANY WARRANTY; without even the implied warranty of
> 	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
> 	GNU General Public License for more details.
> 
> 	You should have received a copy of the GNU General Public License
> 	along with solidity.  If not, see <http://www.gnu.org/licenses/>.
> */

If we are adding the SPDX license identifier, we could even remove the license boilerplate. @axic Is that what you had in your mind?

**Comment by sacgrover** [comment]
@hrkrshnn  My bad. Sorry, I understood it wrongly.

**Comment by sacgrover** [comment]
@hrkrshnn @axic @chriseth  Please review it.

**Comment by chriseth** [comment]
Unfortunately, the SPDX-identifier cannot be a replacement for the license header, so please do not remove it and just add the SPDX-line after it.

**Comment by leonardoalt** [comment]
Hi @sacgrover , any updates here?

**Comment by sacgrover** [comment]
@leonardoalt I think, we can close this PR because I have modified all files as per last discussion but as per latest review by chriseth . It would be hard for me to visit all files manually and append text as per GPL or MIT licence.

**Comment by leonardoalt** [comment]
@sacgrover It doesn't have to be done manually: the same way this here was done automatically to `replace GPL text by SPDX line`, it could automatically `replace GPL text by (GPL text and SPDX line)`. I'd say it doesn't need to include MIT for now because most of our C++ files are GPL anyway.

**Comment by sacgrover** [comment]
@leonardoalt  So In that case... That text has been already replaced with that line in this PR.  isn't this correct?

**Comment by leonardoalt** [comment]
@sacgrover no, the SPDX line would be appended to the existing GPL text. I meant that one way to do that would be to do the same thing you did automatically, but instead of replacing "GPL text" by "SPDX line", you would replace "GPL text" by
"GPL text"
"SPDX line"
which would have the append effect in the end

**Comment by sacgrover** [comment]
@leonardoalt so It will be for CPP file only or other files as well ? I want to be more clear to avoid back and forth.

**Comment by leonardoalt** [comment]
@sacgrover I guess for whichever files have the GPL header that is currently replaced in this PR. I'm aware of the `.h` and `.cpp` we have in the codebase with that header, but there might be others as well.

**Comment by sacgrover** [comment]
Okay

**Comment by sacgrover** [comment]
Raised new PR https://github.com/ethereum/solidity/pull/9440

**Pull request closed without merging**
