### PR TITLE
Allow simplification patterns to signal failure

### PR DESCRIPTION
**Pull request by Marenz**
split out uncontroversial parts of #6160

### CODE REVIEW

**Review by chriseth — DISMISSED** [review]

**Comment by axic** [comment]
The first commit should be removed.

**Comment by Marenz** [comment]
I assume you mean `Replace shifts by larger than 255 with 0` (the second)

**Comment by Marenz** [comment]
removed

**Comment by Marenz** [comment]
I didn't really consider that commit controversial, though.

**Comment by axic** [comment]
> I assume you mean Replace shifts by larger than 255 with 0 (the second)

Github showed it as first. Well it was an optimiser rule, that we should handle with more care.

**Comment by Marenz** [comment]
> Github showed it as first

Yeah, github prefers using the authored time instead of the actual child/parent of commits. It creates confusion.

**Review by axic — APPROVED** [review]

**Pull request merged**
