### PR TITLE
Force install python3.12 for Window bytecode compare job

### PR DESCRIPTION
**Pull request by nikola-matic**

### CODE REVIEW

**Review by cameel — APPROVED** [review]
This sucks, but I guess it's still marginally better than just having a symlink that randomly breaks, so we can accept it as a temporary hotfix. At least this way we won't have to bump version each time they update the image.

In terms of timing it's not as bad as I expected. Seems to add ~15 sec to the running time, so we can live with it until a proper fix.

**Comment by r0qs** [comment]
Rebase and merge :)

**Comment by nikola-matic** [comment]
> Rebase and merge :)

Why rebase though, I can just merge it straight away, no? You hardhat PR's not been merged yet, right?

**Comment by r0qs** [comment]
> Why rebase though, I can just merge it straight away, no? You hardhat PR's not been merged yet, right?

As you wish :)
No, not yet. Please take a look at it.

**Pull request merged**
