### PR TITLE
Update evmone and boost download links in docker images.

### PR DESCRIPTION
**Pull request by ekpyron**
Build the required docker images for https://github.com/ethereum/solidity/pull/11286/

### CODE REVIEW

**Comment by axic** [comment]
How is this different from the other PR?

**Comment by ekpyron** [comment]
> How is this different from the other PR?

It's not really. I'm just building the docker images here separately to get the new hashes to be used in the other PR.
It's not really possible to both build and use new docker images in the same PR: I only know the docker image hashes after the docker builds went through, but if I then use the same PR to update the hashes in the CircleCI config, the image builds are triggered again. One could cancel those new builds, but it's easier to just use two PRs, especially if the change to the docker images doesn't break solc builds.

**Comment by axic** [comment]
I understand that we need to merge separately, that was discussed already :wink:

**Comment by ekpyron** [comment]
> I understand that we need to merge separately, that was discussed already wink

Then I don't understand the problem :-).
In any case, let's just wait for the images here to be built, then I can have a look at them and if and where evmone ends up in them.

**Comment by axic** [comment]
The "problem" I guess is that we are just keep rebuilding the images and not investigating why the built evmone lib is not visible to soltest 🤷

**Comment by ekpyron** [comment]
> The "problem" I guess is that we are just keep rebuilding the images and not investigating why the built evmone lib is not visible to soltest shrug

I *will* investigate that with the new images here :-). I'm also updating the boost download links here, so we needed newly built images anyways.

**Comment by ekpyron** [comment]
Hm... it seems to end up in /usr/lib/x86_64-linux-gnu/libevmone.so
Which makes sense, but that's not in our search path... and it's not so nice to add it by hard-coding, since it's platform specific...

**Comment by axic** [comment]
Hera release can be found here: https://github.com/ewasm/hera/releases/tag/v0.3.2-evmc8

Still waiting for the binaries to be built.

**Comment by axic** [comment]
It is done:
- https://github.com/ewasm/hera/releases/download/v0.3.2-evmc8/hera-0.3.2+commit.dc886eb7-darwin-x86_64.tar.gz
- https://github.com/ewasm/hera/releases/download/v0.3.2-evmc8/hera-0.3.2+commit.dc886eb7-linux-x86_64.tar.gz

**Review by axic — APPROVED** [review]

**Pull request merged**
