### PR TITLE
Rephrase detail in ir breaking changes docs.

### PR DESCRIPTION
**Pull request by ekpyron**
Fixes https://github.com/ethereum/solidity/pull/10497/files#r537390821

### CODE REVIEW

**Review by bshastry — APPROVED** [review]
LGTM

**Comment by ekpyron** [comment]
Actually, I added a second commit that not only fixes the repetition, but also rephrases this slightly to something that is a bit more idiomatic I think. But we can also drop the second commit, as you like.

**Comment by bshastry** [comment]
> Actually, I added a second commit that not only fixes the repetition, but also rephrases this slightly to something that is a bit more idiomatic I think. But we can also drop the second commit, as you like.

I like the second commit better :-)

**Review by mijovic — APPROVED** [review]
I think second option sounds better.
Looks good, maybe just squashing into one commit?

**Review by chriseth — APPROVED** [review]

**Comment by ekpyron** [comment]
> I think second option sounds better.
> Looks good, maybe just squashing into one commit?

Ah, sorry - I was too quick to merge now - probably should have been squashed, yes.

**Pull request merged**
