### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by Denton-L**

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Thanks!

**Comment by bobsummerwill** [comment]
Hey @Denton-L,

You might also like to look at:
- https://github.com/ethereum/cpp-ethereum/pull/3225
- https://github.com/ethereum/homestead-guide/pull/312

And consider what kind of "front-door" we might need for encouraging external contributions within Solidity, now that we have split cpp-ethereum from solidity.

Looks like you are doing a lot of writing, and might be the best person to do that :-)   Thanks!

**Comment by Denton-L** [comment]
Sorry, what do you mean by that?

**Comment by bobsummerwill** [comment]
There was previously a CONTRIBUTING.md in webthree-umbrella.   That got moved to cpp-ethereum and then today I moved it into ethdocs.

What all that means is that we don't have a matching "How to contribute" docs for Solidity, I don't think.

Just suggesting that you might be a good person to write that, or suggest edits to the existing Solidity docs to ensure that there is something similar.

Make sense?

**Comment by bobsummerwill** [comment]
Edits to existing docs rather than a cut-and-paste might make most sense.

The webthree-umbrella -> cpp-ethereum RST content is:

https://github.com/ethereum/homestead-guide/blob/master/source/ethereum-clients/cpp-ethereum/contributing.rst

**Comment by Denton-L** [comment]
Alright, I'll add that to my list of things to do! I'll probably get it done on Monday.

**Pull request merged**
