### PR TITLE
Added various contracts for testing.

### PR DESCRIPTION
**Pull request by chriseth**
This is just a random selection of some contracts out there. The CORION contracts fail on 0.4.11.

All repositories either state that the source code is MIT or GPL-licensed.

### CODE REVIEW

**Comment by axic** [comment]
There should also be a script which creates a standard json for each directory and runs that through `--standard-json`.

**Comment by chriseth** [comment]
@axic do you want to do that (create a script that converts the files to standard json)?

**Comment by axic** [comment]
I haven't thoroghly checked  but are all of them MIT/GPL licensed and do all of them contain a LICENSE file? (I know a few of them definitely do.)

**Comment by chriseth** [comment]
Yes, all of them do, although I heard that a LICENSE file in a directory is completely irrelevant...

**Pull request merged**
