### PR TITLE
[docs]: Add Solidity favicon

### PR DESCRIPTION
**Pull request by kuzdogan**
Changes the default readthedocs icon into Solidity's logo

Before
image

After
image

### CODE REVIEW

**Comment by cameel** [comment]
Nice!

Maybe it would be better to serve a PNG though? The icon in the PR is 32x32 and 15 kB while [the one at soliditylang.org](https://soliditylang.org/favicon.png) is 16x16, 613 bytes. So it seems to me that with PNG we could have a lighter icon of the same pixel size or a larger pixel size at the same weight.

Not sure how big the favicons are expected to be these days though.

**Comment by cameel** [comment]
[The favicon on the blog](https://blog.soliditylang.org/favicon.png) is 192x192 PNG at 3 kB. So maybe we could just take it?

It's also non-transparent, which normally I'd take as a con but looking at the screenshots, looks like the transparent favicon has very low contrast in dark themes.

**Comment by kuzdogan** [comment]
Agree with both. Replaced it with a gray background 32x32 png. I think there's no need for a 192x192 icon 

image
image

**Review by cameel — COMMENTED** [review]
Looks good!

Please just squash the review fixes and we can merge.

**Comment by kuzdogan** [comment]
@cameel squashed into a single commit

**Review by cameel — APPROVED** [review]

**Pull request merged**
