### PR TITLE
Workaround open-zeppelin expectRevertCustomError bug

### PR DESCRIPTION
**Pull request by r0qs**
See https://github.com/OpenZeppelin/openzeppelin-contracts/issues/4349 for more info.

### CODE REVIEW

**Review by pgebal — APPROVED** [review]
That's ok as a quick fix, but please open an issue, so we remember to remove those lines after OZ fixes their stuff.

**Comment by nikola-matic** [comment]
> That's ok as a quick fix, but please open an issue, so we remember to remove those lines after OZ fixes their stuff.

He already did, no?

**Comment by r0qs** [comment]
> > That's ok as a quick fix, but please open an issue, so we remember to remove those lines after OZ fixes their stuff.
> 
> He already did, no?

I guess he meant on Solidity repo. But we don't need to. The one in the OZ is sufficient and I already added the comment in the external test script.

**Comment by pgebal** [comment]
> > That's ok as a quick fix, but please open an issue, so we remember to remove those lines after OZ fixes their stuff.
> 
> He already did, no?

@nikola-matic I mean in solc repo.

**Comment by pgebal** [comment]
> > > That's ok as a quick fix, but please open an issue, so we remember to remove those lines after OZ fixes their stuff.
> > 
> > 
> > He already did, no?
> 
> I guess he meant on Solidity repo. But we don't need to. The one in the OZ is sufficient and I already added the comment in the external test script.

Ok

**Comment by Amxx** [comment]
> so we remember to remove those lines after OZ fixes their stuff

Just to be clear, the OZ helpers fail when the `via-ir` flag is turned on because hardhat does not recognize the custom errors when this flag is on. I would argue its hardhat the should fix their stuff !

We are just parsing string to try and detect if the custom error we defined were emitted correctly. How is OZ responsable if the custom error was emitted but the tooling doesn't reflect taht in the error string ?

**Comment by r0qs** [comment]
> > so we remember to remove those lines after OZ fixes their stuff
> 
> Just to be clear, the OZ helpers fail when the `via-ir` flag is turned on because hardhat does not recognize the custom errors when this flag is on. I would argue its hardhat the should fix their stuff !
> 
> We are just parsing string to try and detect if the custom error we defined were emitted correctly. How is OZ responsable if the custom error was emitted but the tooling doesn't reflect taht in the error string ?

Definitely, the major issue is on Hardhat error heuristics with via IR, not on the OZ side :)

**Pull request merged**
