### PR TITLE
Try running all SolidityEndToEndTests also via yul.

### PR DESCRIPTION
**Pull request by ekpyron**

### CODE REVIEW

**Comment by ekpyron** [comment]
SolidityEndToEndTest/shift_bytes_cleanup
SolidityEndToEndTest/bare_call_return_data
SolidityEndToEndTest/abi_encode_with_signature
SolidityEndToEndTest/abi_encode_with_signaturev2
SolidityEndToEndTest/uninitialized_internal_storage_function
SolidityEndToEndTest/strip_reason_strings

... and some more weird ones ... throwing in CompilerStack... not sure what's going on there yet, might be spurious...

**Comment by ekpyron** [comment]
``internal_constructor``, ``copying_bytes_multiassign``, ``abi_encodePacked`` are the throwing ones.

**Comment by axic** [comment]
SolidityEndToEndTest/abi_encode_with_signature and SolidityEndToEndTest/abi_encode_with_signaturev2 should probably moved with #10776

**Comment by ekpyron** [comment]
Closing this - the CI runs should stay accessible and the list is posted as comments.

**Pull request closed without merging**
