### PR TITLE
[Yul] Support unassigned variables in the SSA value tracker and the data flow analyzer.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by chriseth** [comment]
Why does this not replace the variable by `0` in https://github.com/ethereum/solidity/blob/develop/test/libyul/yulOptimizerTests/fullSuite/abi_example1.yul#L502 ?

**Comment by chriseth** [comment]
OK, it seems to have to do with the fact that the common subexpression eliminator cannot really handle this.

It is probably best to
 - introduce a step that explicitly initializes each variable
 - avoid creating variable declarations without value in the optimizer

**Comment by leonardoalt** [comment]
Are you going to do that in this PR or a new one?

**Comment by chriseth** [comment]
Sorry, the comment above was not too much related to this PR. Created new issue for it: https://github.com/ethereum/solidity/issues/5645

**Review by leonardoalt — APPROVED** [review]

**Pull request merged**
