### PR TITLE
Correct package name for installing solc on Arch

### PR DESCRIPTION
**Pull request by Legogris**

### CODE REVIEW

**Comment by axic** [comment]
Double checked: https://www.archlinux.org/packages/community/x86_64/solidity/

**Review by axic — APPROVED** [review]
Double checked: https://www.archlinux.org/packages/community/x86_64/solidity/

**Comment by axic** [comment]
@tensor5 I think you are the maintainer of the archlinux package. I've noticed it depends on jsoncpp, but for a while we're using a built in version of it. Can you remove the dependency?

**Comment by tensor5** [comment]
@axic, thank you for taking a look at Arch's solidity package. What's the reason for using a built in version? Is it custom patched?

**Comment by axic** [comment]
Distributions had a wide variety of old versions and the package is small enough to be included. We're using stock jsoncpp 1.7.7 (the latest at the time).

**Comment by tensor5** [comment]
Arch is currently using 1.8.1. Do you plan to upgrade, or require a minimum version with cmake? The general consensus in Linux distros is to use system packages whenever possible, but if you think there might be an incompatibility between the latest jsoncpp and 1.7.7 I'll switch version.

**Comment by axic** [comment]
@tensor5 it is a fixed version downloaded during make, should have no impact on the distribution.

**Pull request merged**
