### PR TITLE
Docs: Payment channels

### PR DESCRIPTION
**Pull request by DennisBPeterson**
By request of RJ on gitter/solidity, for the micropayment channel example I added my blog entry:
http://www.blunderingcode.com/a-lightning-network-in-two-pages-of-solidity/

Made a few minor changes so it's more like documentation than blog.

### CODE REVIEW

**Comment by chriseth** [comment]
@konradkonrad could you take a look here, please?
In general, regarding style, I would prefer to not have contractions in written text.

**Comment by heikoheiko** [comment]
Maybe a simpler payment channel (instead of payment channel network) example, is more suitable: e.g. this https://github.com/obscuren/whisper-payment-channel

**Comment by chriseth** [comment]
Yes, I actually thought about a much simpler example here, too. It is meant as an introductory text and not as a collection of libraries.

**Comment by chriseth** [comment]
Sorry, closing this for now.

**Pull request closed without merging**
