### PR TITLE
Fixes travis deployment failings (emscripten related)

### PR DESCRIPTION
**Pull request by VoR0220**
attempts to fix deployment errors that are currently happening for Solidity. 

Signed-off-by: RJ Catalano <rj@monax.io>

### CODE REVIEW

**Comment by chriseth** [comment]
This is run inside a docker container. How was this error introduced?

**Comment by VoR0220** [comment]
Not positive. Ive just noticed that deploy is erroring out on this line. Or...maybe not?

**Comment by VoR0220** [comment]
Changed...it's not related to that at all. It's literally something we missed when merging I believe the docker PR for the script deploy for emscripten...hence why every deploy is clouded with js.

**Comment by axic** [comment]
```
-      script: test $TRAVIS_EMSCRIPTEN != On || scripts/release_emscripten.sh
+      script: test $SOLC_EMSCRIPTEN == On || scripts/release_emscripten.sh
```

Seems to be correct, it was introduced with 503cf4ea.

**Review by axic — APPROVED** [review]

**Pull request merged**
