### PR TITLE
[WIP] Prevent block.blockhash from being used without calling it

### LINKED ISSUE #2977: Unknown magic member assertion
```
contract C {
    function f() {
        block.blockhash;
    }
}
```

```
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/codegen/ExpressionCompiler.cpp(1150): Throw in function virtual bool dev::solidity::ExpressionCompiler::visit(const dev::solidity::MemberAccess &)
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: Unknown magic member.
[dev::tag_comment*] = Unknown magic member.
```

### PR DESCRIPTION
**Pull request by federicobond**
Fixes #2977

### CODE REVIEW

**Comment by axic** [comment]
I think actually the simplest fix is just putting this into the switch in codegen to be ignored: https://github.com/ethereum/solidity/blob/develop/libsolidity/codegen/ExpressionCompiler.cpp#L1112

**Comment by federicobond** [comment]
You mean fail silently inside the ExpressionCompiler? I think we should try to emit these errors in earlier passes.

**Comment by axic** [comment]
Why is it a failure? it is just an empty expression. We should ensure though that it works when assigned as a function type:
```
function (uint) view returns (bytes32) blockhash = block.blockhash;
blockhash(5);
```

**Comment by federicobond** [comment]
Not sure I follow you. What would be the expected code/errors to be emitted in this case?

```javascript
func(block.blockhash, 2, 3);
```

**Comment by axic** [comment]
Put some detail into #2996. My above example cannot be easily fixed due to our limitations in `FunctionTypes`, but at least assigning it as `var` should work:
```
var blockhash = block.blockhash;
blockhash(5);
```

In your example what is `func`?

**Comment by federicobond** [comment]
Ah ok, I assumed getting a value out of the `block.blockhash` expression wasn't expected to work. `func` was just a placeholder for any contract function.

I have no idea how blockhash is stored in a variable. Does the rest of the code support this case?

**Comment by axic** [comment]
You're right it doesn't have a stack representation yet. Right now this is the only real exception, but with #2980 there will be two more.

I guess we have a couple of options:
- a) copy how the exceptions of `Kind::SetValue` (`.value()`) and `Kind::SetGas` are implemented
- b) change the stack representation of `internal` (which currently uses 4 bytes as a jump address) to include the kind
- c) create an internal function which is used by every instance and calls the opcode internally (with the IR this is likely how it will end up being like)
- d) add/reuse a helper to mark types as valid as `RValue` and restrict them in the typechecker if they are not (basically the same as this PR, but more generic)

**Comment by federicobond** [comment]
I was thinking something along the lines of your c) proposal, where we desugar `block.blockhash` to an internal function if it's referenced without immediately calling it. Thus we avoid any kind of overhead when it's not being used that way.

**Comment by axic** [comment]
I think #3725 supersed this?

**Comment by chriseth** [comment]
Yes.

**Pull request closed without merging**
