### PR TITLE
Move test tools to the subdirectory test/tools and adjust CMakeLists

### PR DESCRIPTION
**Pull request by ekpyron**
Came up as part of #3674 when adding new test tools.

### CODE REVIEW

**Comment by axic** [comment]
@chfast can you double check this?

**Comment by chfast** [comment]
This is quite hackish. I'd recommend following independent changes:

1. Instead of GLOBing all files and then removing some, try to glob individual dirs, you don't want to add each file manually (recommended).
2. Add another CMakeLists.txt in test/tools to be included by `add_subdirectory(tools)`. The definition of the fuzzer target should be moved there.

**Comment by chriseth** [comment]
@chfast's suggestions are always good :)

In the medium term, we should also remove the globs in the other CMake files.

**Comment by ekpyron** [comment]
OK - the previous solution was hackish as well, but this is indeed a good opportunity to clean it up at least somewhat.

Moving the solfuzzer target to a CMakeLists.txt in a subdirectory changes its path in the build directory, though - I hope I caught all uses of solfuzzer in the scripts and adjusted them correctly.

Actually I'd usually prefer listing all files individually in CMakeLists.txt, since any globbing (recursive or not) may result in build failures for example if new files are added and cmake is not run again afterwards - but this is actually a separate discussion and so far globbing seems to be used everywhere.

**Comment by ekpyron** [comment]
squashed

**Review by chfast — APPROVED** [review]
It looks better now. 

I'm also for not using GLOB, but it's usually quite a lot of work to replace GLOBs if they were used. That's not for this PR.

Adding files to a single target also can be split into dirs using [target_sources()](https://cmake.org/cmake/help/v3.11/command/target_sources.html).

**Comment by axic** [comment]
I was wondering if it should be moved out of `test/tools/` into `tools/`, but fuzzing is really just for testing so it is better there.

**Review by axic — APPROVED** [review]

**Review by chriseth — APPROVED** [review]

**Pull request merged**
