### PR TITLE
Fix event parsing. Refs #3175

### LINKED ISSUE #3175: Event not emitted
The following contract is supposed to emit 2 events on creation, however, only 1 event is emitted.

EXP: 2 events emitted.
ACT: 1 event emitted.

Using Ethereum Wallet 0.9.2 for the contract deployment.
The contract is on Ropsten. 

pragma solidity ^0.4.16;

contract EventBug {
  event NotEmitted;
  event Emitted();

// Ropsten TxHash: 0xc9dbde78f19a2463af505a44bd16e56084cb3da3f5aa96aea832550eba2a2f4b
// Notice that only 1 event is emitted, as opposed to 2.
  function EventBug() {
     NotEmitted; // <-- No error as well
     Emitted();
  }
}

### PR DESCRIPTION
**Pull request by federicobond**
Fixes #3175.

### CODE REVIEW

**Comment by axic** [comment]
Please don't forget a changelog entry (in the bug section)

**Comment by axic** [comment]
@chriseth well, it seems that this was so by design in the parser, but the grammar always understood it with a parameter list. I guess regarding the initial intention it made sense, but since we try to make this less prone to error I'd argue this is the better way.

**Comment by federicobond** [comment]
@axic right, done.

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
So we ignore that this might be seen as a breaking change for some?

Please adjust some more test cases.

**Comment by axic** [comment]
> So we ignore that this might be seen as a breaking change for some?

We can postpone it to the breaking release, but I'm yet to see such a contract (I wasn't even aware of it and the documentation doesn't give it as an example).

**Comment by axic** [comment]
Seems like Zeppelin fails:
```
Starting our own testrpc instance
Error parsing /tmp/tmp.SSInTQ7ujt/contracts/Bounty.sol: Warning: This is a pre-release compiler version, please do not use it in production.
Compilation failed. See above.
```

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
I restarted the zeppelin tests. Shall we merge as is, or perhaps rebase so that the "prerelease" warning is fixed?

**Comment by axic** [comment]
@chriseth the tests seem to be passing?

**Comment by axic** [comment]
@federicobond needs to be rebased and the changelog entry be moved. (Also no need to have the issue reference in the commit message).

**Comment by pirapira** [comment]
Seems to have been rebased.  The ChangeLog entry appears in the right place.

**Comment by axic** [comment]
@pirapira the last release was 0.4.19. We are now in 0.4.20 unreleased.

**Comment by pirapira** [comment]
So, why didn't I get a merge conflict?

**Comment by axic** [comment]
Github only cares if the merge commit applies without conflicts and in that case it did (because the previous release had no bugfix entries). There is a separate option in Github to enforce that every PR has to point to the `HEAD` but that is quite annoying because requires a rebase after every single merge. This is a tradeoff, but requires us to be a bit more careful.

**Comment by pirapira** [comment]
Oh, I see.  Whenever the new changelog entry is far away from `... (unreleased)`, there is no protection.  Sorry.

**Comment by pirapira** [comment]
Here I'm trying to fix that https://github.com/ethereum/solidity/pull/3312

**Pull request merged**
