### PR TITLE
Fix compiler error.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Review by ekpyron — APPROVED** [review]
I wonder how much weird stuff is hidden in merge commits to breaking...

**Comment by ekpyron** [comment]
How did the error ID clash come to pass? That cannot have happened randomly can it?

**Comment by chriseth** [comment]
@hrkrshnn @a3d4 any idea about how the error id clash happened?

**Comment by hrkrshnn** [comment]
This is the relevant PR for the second change: https://github.com/ethereum/solidity/pull/9039/files#diff-b59e90af07a5bfbe4dcad2c8eaa50776

My guess is that the `m_errorReporter.error(...)` was copy-pasted from few lines below and the error id was not changed :)

For the first one, I think, 1878 was the error id generated when running the script in breaking. Later in develop, 1878 was generated elsewhere.

**Comment by a3d4** [comment]
**Adventures of 1878**

**breaking** 0be56a0abf4266247cefe2b8248cfc88e791b28f Merge remote-tracking branch 'origin/develop' into breaking
1878_error "Library functions cannot be \"virtual\"."

**develop** 6f04664cfa1d64c00a30760b643e1c17fcc44514 Disallow array slicing for arrays with dyanmically encoded base types.
1878_error "Index range access is not supported for arrays with dynamically encoded base types."

**develop** 3872a1f000f7aa19b05b003d99a82f17c73e98ff  Add support for SPDX license identifiers.
1878_error "Index range access is not supported for arrays with dynamically encoded base types."
1878_error "SPDX license identifier not provided in source file. ...."

**breaking** 257bc6a4166e624a055f667a4853d137c3009e10 Merge remote-tracking branch 'origin/develop' into breaking
1878_error "Library functions cannot be \"virtual\"."
1878_error "Index range access is not supported for arrays with dynamically encoded base types."
1878_error "SPDX license identifier not provided in source file. ...."

**develop** 21e34d7ca9412691df47b89f5d598d6dfc8ca922 Fixed seed for randomness, fixed conflicts in errorids
2148_error "Index range access is not supported for arrays with dynamically encoded base types."
1878_error "SPDX license identifier not provided in source file. ...."

**breaking** 894478ff8c9c0a6d5ffa091fe66adf560e9c6437 Merge pull request #9038 from ethereum/develop
1878_error "Library functions cannot be \"virtual\"."
2148_error "Index range access is not supported for arrays with dynamically encoded base types."
1878_error "SPDX license identifier not provided in source file. ...."

**breaking** 894478ff8c9c0a6d5ffa091fe66adf560e9c6437 Merge pull request #9038 from ethereum/develop
7801_error "Library functions cannot be \"virtual\"."
2148_error "Index range access is not supported for arrays with dynamically encoded base types."
1878_error "SPDX license identifier not provided in source file. ...."

**Comment by a3d4** [comment]
Error codes can be used for error coverage, but current infrastructure does not guarantee their persistence. Maybe we should improve it.

**Comment by chriseth** [comment]
@a3d4 I think this can be solved by adding the error ID into the error reports of the syntax tests.

**Pull request merged**
