### PR TITLE
Use more R string literals in tests

### PR DESCRIPTION
**Pull request by federicobond**
Makes the tests much more readable and easy to copy-paste. I did not convert all files because it takes time, but I can do the rest if there is interest.

### CODE REVIEW

**Comment by VoR0220** [comment]
Might need to examine that *one* error...other than that I'd say lets merge this. I've been wanting this to happen for a while.

**Comment by federicobond** [comment]
The error appears unrelated. Can you trigger a rebuild to see if it goes away?

**Comment by pirapira** [comment]
@federicobond I scheduled a rebuild.

**Comment by federicobond** [comment]
Great! All green now.

**Review by chriseth — APPROVED** [review]

**Pull request merged**
