### PR TITLE
Upgrade to jsoncpp 1.9.5

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by axic** [comment]
I pushed this branch last September and not sure what happened to it. Will rebase now to see.

**Comment by r0qs** [comment]
The error in the windows build is due to failing to link the jsonccp:
```
circleci@packer-62f2a351-716f-548b-6ad8-257cea95429e  ~/project/build/solc/Release (jsoncpp-1.9.5)
$ ./solc.exe
C:/Users/circleci/project/build/solc/Release/solc.exe: error while loading shared libraries: jsoncpp.dll: cannot open shared object file: No such file
 or directory
 ```
 
 Sadly `powershell` does not show such error, so you need to login via ssh on the CI and try to run solc through bash.
 ```
 PS C:\Users\circleci\project> file .\build\solc\Release\solc.exe
.\build\solc\Release\solc.exe: PE32+ executable (console) x86-64, for MS Windows
PS C:\Users\circleci\project> .\build\solc\Release\solc.exe
PS C:\Users\circleci\project>
```

**Comment by ekpyron** [comment]
Setting ``BUILD_SHARED_LIBS`` to ``OFF`` in json-cpp cmake config may fix that... they probably broke things with the vague release note mention of "Minor bug-fixes (including for cmake)" :-).

**Comment by ekpyron** [comment]
I'm a bit torn on this one by the way - on the one hand, it's kind of a unnecessary distraction - on the other hand I'm in general 100% behind keeping dependencies up-to-date and this has been way overdue, so :-)...

**Comment by axic** [comment]
This is the diff: https://github.com/open-source-parsers/jsoncpp/compare/1.9.3...1.9.5

Changes for 2020 and 2021.

New CMake additions:
```cmake
option(JSONCPP_STATIC_WINDOWS_RUNTIME "Use static (MT/MTd) Windows runtime" OFF)
option(BUILD_SHARED_LIBS "Build jsoncpp_lib as a shared library." ON)
option(BUILD_STATIC_LIBS "Build jsoncpp_lib as a static library." ON)
option(BUILD_OBJECT_LIBS "Build jsoncpp_lib as a object library." ON)
```

I wouldn't spend days on this, but perhaps time boxing to a few hours tops could be useful to avoid more follow distance to jsoncpp.

It does have a few other C++ improvements, so perhaps it may be faster.

**Pull request closed without merging**
