### PR TITLE
EVMHost: Support warm coinbase

### PR DESCRIPTION
**Pull request by axic**
Part of #14073.

### CODE REVIEW

**Comment by cameel** [comment]
Is it normal that [EIP-3651: Warm COINBASE](https://eips.ethereum.org/EIPS/eip-3651) is still in the "last call" state even after the fork? Should we ping someone to switch the status?

**Review by cameel — APPROVED** [review]
The change looks reasonable and straightforward.

Is there a way to add a test for its effects though? As is, I trust that you tested that manually.

**Comment by axic** [comment]
> Is there a way to add a test for its effects though?

I think so, but we likely don't even have specific tests for the other two warm addresses.

The test probably has to measure gas and:
```
function f() {
  // call cold address once
}

function g() {
  // call cold address twice
}

function h() {
  // call warm address once
}

function i() {
  // call warm address twice
}
```

**Comment by cameel** [comment]
Ah, ok. I assumed we'd have to somehow know a coinbase address and have it hard-coded. But now I realized we can of course use `block.coinbase`. I think it would be a good idea to have these things tested at least in a minimal way.

**Pull request merged**
