### PR TITLE
Remove macOS Sierra note from install_deps.sh

### PR DESCRIPTION
**Pull request by federicobond**
All relevant issues have been closed and I was able to compile without any problems.

### CODE REVIEW

**Comment by federicobond** [comment]
Ok, there are some issues with `eth` installed from Homebrew, but not with the compiled `solc`. I will investigate further and see what can I do.

**Comment by axic** [comment]
@federicobond since cpp-ethereum and solidity have their separate trees (and separate brews?) this shouldn't be a reason not to merge this?

**Comment by chriseth** [comment]
@axic eth is installed together with solidity for testing

**Comment by VoR0220** [comment]
Can we merge this in yet? Or no?

**Comment by chriseth** [comment]
The author says no.

**Comment by federicobond** [comment]
Solidity compiles and runs tests just fine with macOS Sierra. `cpp-ethereum` installed via Homebrew still has problems, but you can use a precompiled binary easily.

I am happy to merge this change if others agree.

**Review by chriseth — APPROVED** [review]

**Pull request merged**
