### PR TITLE
Add Error Handling to Scanner, re #5141

### PR DESCRIPTION
**Pull request by ghost**
### Description

First draft of an error-reporting for the scanner. The rationales can be found within #5141 

The finished work would lay the foundation to assess if its possible/worth to move the code over to the parser (which would be another issue).

(ignore details at this point)

### CODE REVIEW

**Comment by ghost** [comment]
@chriseth , introducing the scanner-errors uncovered some weaknesses in the test-code. 

I' had a hard time with the terminology, "ILLEGAL" should become "INVALID" (or "ERROR"), at least in context of the Scanner Errors.

The many commits became finally 3, which should remain, to simplify future code review.

If this can go in, let me know, thus I make one more detail pass before review.

**Comment by chriseth** [comment]
I'm wondering whether introducing tons of different tokens for error conditions in the scanner is such a good idea. Perhaps we should rather allow the scanner to generate a user-readable error string and return a single illegal token.

**Comment by chriseth** [comment]
Perhaps to expand on this: Splitting up the illegal token only makes sense if it is to be processed programmatically. And currently (unless i'm mistaken), the only programmatic processing is generating the error string, so that could just be done earlier at the point where we still have context for verifying whether the error string makes sense.

**Comment by ghost** [comment]
I decided to go this way as it was the least-intrusive and fully backwards-compatible solution. The original (v8) code remains essentially unaltered, the test-code was easily adapted.

The ILLEGAL tokens 
* are for internal use only,
* work now(!), 
* work nicely with existent tests
* uncover defects in the code now(!)
* can be removed later with a more advanced solution (if necessary).

> we still have context for verifying whether the error string makes sense.

the context is usually clearly given from the code (that's why I was able to name the error-tokens).

> Perhaps we should rather allow the scanner to generate a user-readable error string and return a single illegal token.

Would be fine, too (although the testing would become more difficult).

>> thus I make one more detail pass before review.

did this already, this one is essentially "out of my mind" already.

**Comment by christianparpart** [comment]
I actually do like the idea of having better error messages (as we can nicely see in the adapted tests). 
However, here's my proposal to fix this:

* Stick with `Token::Illegal`, and return that as done before but store a hint locally indicating the type of error.
* Introduce an `enum class ErrorCode` (as shown below) and use that as a hint for operating on lexical errors when printing out human readable errors.

```cpp
class Scanner {
public:
    // ....

    /// Represents the class of errors that can cause a Token value to become Token::Illegal.
    enum class ErrorCode {
        IllegalHex,
        IllegalCommentTerminator,
        IllegalStringEscape,
        IllegalStringEndQuote,
        IllegalNumberSeparator,
        IllegalHexDigit,
        IllegalOctalNotAllowed,
        IllegalExponent,
        IllegalNumberEnd
    };;

    /// returns the last lexical error that happened or an undefined value if no error occurred.
    ErrorCode lastError() const noexcept { return m_lastError; }

private:
    ErrorCode m_lastError;
};
```

Already implicitly seen in my code snipped above: that's a nice way of eliminating even `Token::IllegalHex` and uniformly using `Token::Illegal` on any illegally recognized token. The tests in SolidityScanner.cpp should then be adapted accordingly, too.

**Comment by chriseth** [comment]
Yep, introducing specific scanner error codes makes a lot of sense to me, instead of merging error codes and token types.

**Comment by ghost** [comment]
>> work nicely with existent tests

works now(!) with 0 changes to the underlying logic.

>> can be removed later with a more advanced solution (if necessary).

The "ErrorCode" suggestion is fine, but feels still like a workaround. And a more elegant solution needs some time and effort.

(Note that I'm off-code now, so feel free to close/change this and proceed as you see fit)

**Comment by christianparpart** [comment]
Hey. Why would that be a workaround and to what?

What would be the more elegant way?

**Comment by ghost** [comment]
No idea (subconscious/gut-feeling assessments)

**Comment by ghost** [comment]
Just for the sake of completeness, I've updated the code to reflect latest changes.

Closing, as it seems that this will remain un-merged.

**Comment by ghost** [comment]
The Process would have been:

* merge this
* update this with the suggested enhancements in #5494

This ensures that the repository properly attributes the work done, and preserves the development-history, e.g. for later code-review.

(no worries, I won't cry...)

**Comment by christianparpart** [comment]
Hey @lazaridiscom.

I apologize for not having based my work right on top of yours. My reasoning was, that it would be easier to just start from scratch. However, I've now rebased my work on top of your branch, which preserves your authorship of the original commit, which should give you the deserved attribution, and in case of future squashing, your name will be preserved, too.

Have a nice weekend,
Christian.

**Comment by ghost** [comment]
No worries @christianparpart.

This was more about the general dev-process.

Be fine!

**Pull request closed without merging**
