### PR TITLE
Update contract creation example using web3

### LINKED ISSUE #2123: Documentation: Creating contracts example using web3.js doesn't seem right
Why is the abiArray mentioned in that example if it is not used in the code?

See the first code example at http://solidity.readthedocs.io/en/develop/contracts.html

```
// Need to specify some source including contract name for the data param below
var source = "contract CONTRACT_NAME { function CONTRACT_NAME(unit a, uint b) {} }";

// The json abi array generated by the compiler
var abiArray = [
    {
        "inputs":[
            {"name":"x","type":"uint256"},
            {"name":"y","type":"uint256"}
        ],
        "type":"constructor"
    },
    {
        "constant":true,
        "inputs":[],
        "name":"x",
        "outputs":[{"name":"","type":"bytes32"}],
        "type":"function"
    }
];

var MyContract_ = web3.eth.contract(source);
MyContract = web3.eth.contract(MyContract_.CONTRACT_NAME.info.abiDefinition);
// deploy new contract
var contractInstance = MyContract.new(
    10,
    11,
    {from: myAccount, gas: 1000000}
);
```

### PR DESCRIPTION
**Pull request by nrchandan**
Fixes #2123

### CODE REVIEW

**Comment by axic** [comment]
I think the example should be changed to not use `web.eth.compile` as we're trying to move away from that.

**Comment by nrchandan** [comment]
How do you do that without compiling? Sorry, I am new to Solidity/Ethereum.

**Comment by pirapira** [comment]
Please rebase.

**Comment by nrchandan** [comment]
Rebased.

**Comment by pirapira** [comment]
@axic I'm also interested in the proper way to compile things in this context.

**Comment by axic** [comment]
@nrchandan @pirapira for example using `solc-js` directly in Javascript. By using `eth.compile`, the source code is transmitted via RPC to the node, which will somehow compile it and send back the result.

**Comment by axic** [comment]
@chriseth I think we should remove the web3 example entirely as it is out of scope and really outdated. Need to explain though "external creation", because that section talks about creating contracts externally and from within Solidity.

**Comment by chriseth** [comment]
Ok!

**Comment by axic** [comment]
@nrchandan thanks for the contribution, we have merged a different approach (explaining creation on the high level).

**Pull request closed without merging**
