### PR TITLE
Suggest the experimental ABI encoder if using structs as function parameters

### LINKED ISSUE #3069: Error returning struct with 0.4.17
```
pragma solidity ^0.4.17;
pragma experimental ABIEncoderV2;

contract Person {
    mapping(uint256 => Document) documents;
    
    struct Document {
        uint256 value;
        uint256 value2;
    }
    
    function getDocument(uint256 _document) public returns (Document) {
        return documents[_document];
    }
}

contract Service
{
    function getPersonalDocument(Person _person, uint256 _document) public {
        Person.Document memory document = _person.getDocument(_document);
    }
}
```

error received "InternalCompilerError: Static memory load of more than 32 bytes requested.".

FWIW changing struct to single value compiles correctly.

### PR DESCRIPTION
**Pull request by axic**
Fixes #3069.

### CODE REVIEW

**Comment by axic** [comment]
Separately this could be raised for nested arrays, but structs are the biggest new feature.

**Comment by chriseth** [comment]
Hope this fixes the error.

**Comment by axic** [comment]
Should add some of the test cases from #3069.

**Comment by axic** [comment]
@chriseth can you review this please?

**Review by chriseth — APPROVED** [review]

**Pull request merged**
