### PR TITLE
Add error IDs to OverrideChecker, BMC and ContractLevelChecker

### PR DESCRIPTION
**Pull request by a3d4**
This is a continuation of PR #8680, PR #8879 journey.

### CODE REVIEW

**Review by hrkrshnn — COMMENTED** [review]
LGTM. Passing two error_id's in BMC.cpp was counterintuitive for me. I guess there is no other way to do it?

**Comment by a3d4** [comment]
@hrkrshnn 
> LGTM. Passing two error_id's in BMC.cpp was counterintuitive for me. I guess there is no other to do it?

I do not like it either. The issue here is that for the same `_description` we have two potential cases:
`_description + " happens here"` and `_description + " might happen here"`.

Would something like `_errorHappens` and `_errorMightHappen` be better than `_error1` and `_error2`?

**Comment by hrkrshnn** [comment]
@a3d4 I like your suggestion for new names.

**Comment by a3d4** [comment]
@hrkrshnn 
BTW, the formatting issue you mentioned in https://github.com/ethereum/solidity/pull/8864#discussion_r421289923 is fixed :).

**Review by chriseth — DISMISSED** [review]

**Review by hrkrshnn — APPROVED** [review]

**Pull request merged**
