### PR TITLE
Fix Z3 version in docs

### PR DESCRIPTION
**Pull request by leonardoalt**

### CODE REVIEW

**Review by ekpyron — APPROVED** [review]
End-to-End-Tests are failing :-D. We should really do sth about those random failures :-D.

**Comment by leonardoalt** [comment]
Doesn't seem random anymore, it simply always fails.

**Comment by ekpyron** [comment]
Still random in that it's a different one each time :-).

**Comment by ekpyron** [comment]
I wonder what could have made this worse (it was clearly less annoying two weeks ago)...

**Pull request merged**
