### PR TITLE
Update frequently-asked-questions.rst with a ref to getter functions

### PR DESCRIPTION
**Pull request by jamesray1**

### CODE REVIEW

**Review by jamesray1 — COMMENTED** [review]
Changed getter function refer to refer to getter functions rather than visibility and getters.

**Comment by jamesray1** [comment]
@chriseth

**Comment by chriseth** [comment]
The tests also fail for this  pull request.

**Comment by jamesray1** [comment]
This needs #2658 to be merged first.

**Comment by jamesray1** [comment]
@chriseth, the Travis CI build passed.

**Pull request merged**
