### PR TITLE
Add solidity style guide

### PR DESCRIPTION
**Pull request by pipermerriam**
### What problem does this try to solve.

Solidity currently does not have a style guide.  Many developers are writing solidity code in different styles.  This is not a situation which is inherently bad, but there are benefits to a community having a recommended way to write code.
- Consistency is important within a codebase.  Without an agreed upon set of recommendations, many different styles will emerge which can cause annoyances when working on multiple codebases with styles that differ widely.
- A common style improves readability both by declaring conventions that are known to improve the ease of reading code, as well as it being easier to read code written in a style you are familiar with.
- Things like naming conventions (not covered yet by this pull request) can convey semantic meaning about code which makes it easier to read.
- Code that is easier to read is easier to understand.  In a world where applications are verifiable, it is important for people to be able to audit contract code and understand what it is doing.  A common style that promotes readability can assist in making this process easier.
### How was it implemented.

I have long looked to python's [pep8](https://www.python.org/dev/peps/pep-0008/) as a well executed style guide.  I say this not to say that it's content is perfect, but that pep8 is an example of a community that has embraced some level of agreement on how code should be written.

The actual guidelines were influenced by the following sources.
- The structure, as well as many of the recommendations were heavily influenced by pep8.
- Examples currently in the documentation.
- contracts written by @chriseth in the dapp-bin
- Code that other projects have open sourced and that has been posted as examples.
- Code that I have written.
### What this PR Covers

This PR attempts to create a set of guidelines for code layout.
### Feedback

If you disagree with any of the recommendations I would ask that we try to keep the discussion centered around the following things.
- What helps readability.
- What are other languages doing.
- What clear (objective) benefits does a style provide over another.
### Reaching Consensus

Style guides are sometimes polarizing issues.  Programmers have strong opinions about writing code and style guides are an easy topic to discuss [ad infinitum](https://en.wikipedia.org/wiki/Ad_infinitum).  

Chances are that we **will not** be able to find a set of recommendations that everyone can agree on.

My hope is that we **can** agree that it is useful for us to have a set of recommendations, even if they are not all things that we individually agree on.

Please be courteous in the discussion of this PR and remember that we're all trying to make Solidity an amazing language to write contracts with.
### Next Steps

Once this PR has been resolved, if the style guide moves forward, then Naming Conventions would be my suggested next topic.  I chose to leave it as a TODO as I expect it to be somewhat more controversial and would like to limit the scope of the discussion as much as possible.
#### Cute animal picture.

monkey-parrot_1743_3218284k

> When you have something particularly difficult to discuss, it can be helpful to soften the mood a bit with a cute animal picture.  I highly recommend you try it with your pull requests.

### CODE REVIEW

**Comment by LefterisJP** [comment]
Hehe .. code styling can be controversial for many people. I personally like the style described in the document. Since solidity is a curly braces language what you describe and what we have been coding in solidity is pretty much the [K&R style](https://en.wikipedia.org/wiki/Indent_style#K.26R_style).

The problem with enforcing a style as a community is that as much as I may personally like this style, there are other people who may fervently prefer (and strongly argue for) a different indentation style. Style enforcement is not easy.

[PEP 8](https://pypi.python.org/pypi/pep8) which you mentioned, just like [gofmt](https://golang.org/cmd/gofmt/) for Golang are a bit more succesfull since they are also accompanied by a formatting tool to take the style management out of the equation.

With that in mind it would be nice whatever the outcome of such a discussion is, to also have an automatic formatting tool.

**Comment by VoR0220** [comment]
One thing that you may need to touch on is resolving declaration of a struct. I have two ways, one so that I can fit everything in and read it well (this still ends up looking ugly) and the other way which is the conventional method.

**Comment by VoR0220** [comment]
oh and don't forget this talk:

```
address [][] something;
vs.
address[][] something;
```

**Comment by pipermerriam** [comment]
@VoR0220 

> One thing that you may need to touch on is resolving declaration of a struct. I have two ways, one so that I can fit everything in and read it well (this still ends up looking ugly) and the other way which is the conventional method. 

Can you provide examples of what you are talking about?  I'm not sure I follow.

**Comment by pipermerriam** [comment]
@VoR0220 c1fa464 - array declaration styling

**Comment by VoR0220** [comment]
something like this:

```

struct neverEndingStuff { 
     string this;
     string shit;
     string never;
     string seems;
     string to;
     string stop;
}
var something = neverEndingStuff(
                              {
                                  this: this,
                                  shit: shit,
                                  never: never,
                                  seems: seems,
                                  to: to,
                                  stop: stop,
                              }
                          );

```

**Comment by VoR0220** [comment]
as opposed to more traditionally declared structs

**Comment by chriseth** [comment]
I'm not sure the animal picture is really cute. The parrot looks rather distressed.
Besides, there is no cat in the picture.

**Comment by chriseth** [comment]
Especially with functions having multiple modifiers, I think it is better to put the opening brace on the next line. If you do not you have to indent the modifiers twice and it is not so easily visible where the function starts.

```
function f()
        mod1
        mod2
        mod3 {
    do_something
}
```

```
function f()
    mod1
    mod2
    mod3
{
    do_something
}
```

**Comment by rabbit** [comment]
I'm in line with the document so far.

Here is how I do mappings:

```
contract A {

    // document the entire mapping
    mapping (address => // first key name
    mapping (address => // second key name
        uint)) myNumber;

}
```

That probably conflicts with the indention style but I prefer the readability of columns. The annotations can name the keys. I follow through with the same key names where I can (ie: `myNumber[firstKeyName][secondKeyName]`)

I figured modifiers can be easily overlooked with the function prototype so I always split out with at least one line (also constructor):

```
contract A is B, C, D {

    function A(uint param1, uint param2, uint param3, uint param4, uint param5)
    B(param1)
    C(param2, param3)
    D(param4) {
        // do something with param5
    }

    function foo() {
    }

    function foo()
    constant returns (bool) {
    }

    function foo()
    several mods atonce constant returns (bool) {
    }

    function foo()
    one two three four five six
    constant returns (bool) {
    }

}
```

I've not settled on how to break out long list of params but this is probably ok

```
contract A {
    function A(uint param1, uint param2, uint param3, uint param4,
               uint param5, uint param6) {
    }

    function withModifiers(uint param1, uint param2, uint param3, uint param4,
                           uint param5, uint param6)
    constant returns (bool) {
         // a little wonky for sure.
    }
}
```

**Comment by rabbit** [comment]
Might be a good idea to recommend consistent ordering of modifiers.

**Comment by VoR0220** [comment]
@rabbit I find that mapping style a little confusing but interesting. Why not this?

```
contract A {

    // document the entire mapping
    mapping (address => // first key name
        mapping (address => // second key name
            uint)) myNumber;

}
```

**Comment by pipermerriam** [comment]
Removed, see comment below about TODO items added for funcion modifiers.

**Comment by pipermerriam** [comment]
@rabbit @chriseth @VoR0220 I've added TODO items for function modifiers and Mappings.  I would like to try and limit the scope of this initial PR so it's easier to have a meaningful discussion around single topics.  

Does that sound like an ok plan?  Can we limit the scope of the discussion to things currently present in the document?

**Comment by pipermerriam** [comment]
@LefterisJP 

> With that in mind it would be nice whatever the outcome of such a discussion is, to also have an automatic formatting tool.

I think the long term success of a style guide involves having automated tooling that identifies things that don't conform to the recommendations.  I however don't think the creation of a style guide hinges on that tool being created immediately.

**Comment by pipermerriam** [comment]
@LefterisJP 

> The problem with enforcing a style as a community is that as much as I may personally like this style, there are other people who may fervently prefer (and strongly argue for) a different indentation style. Style enforcement is not easy.

I want to be really clear that this guide is only meant to be a set of recommendations for writing solidity code and that enforcement is outside of the scope of this document.  Each project and codebase can choose what styles (if any) they wish to use for their project as well as how they choose to enforce them (if at all).

The goal is not to command people to use this style, or to claim these styles are the best.  The goal is to have a set of styles that help reduce the inconsistencies between separate codebases.  It also can serve as a helpful tool for developers new to the language to adopt an established style rather than inventing their own.

**Comment by LefterisJP** [comment]
> I think the long term success of a style guide involves having automated tooling that identifies things that don't conform to the recommendations. I however don't think the creation of a style guide hinges on that tool being created immediately.

No definitely not. It's a really good idea to have a style guide and I am all for it.

**Comment by VoR0220** [comment]
Alright...let's push this one up and then continue the discussion in another PR?

**Comment by LefterisJP** [comment]
yeah

**Comment by pipermerriam** [comment]
As soon as this is merged, I'll get another iteration open with some of the next things in it.  Going to post this PR one more time in various channels (reddit, slack) to give community another ping that this is happening if they want to provide feedback.

**Comment by rabbit** [comment]
@VoR0220 makes sense. doubtful anyone would have enough levels to break 80 col.

I'm good with whatever shakes out. Ping me if you ever want me to weigh in.
🐰👍

**Pull request merged**
