### PR TITLE
Fix UTF-8 validation for high codepoints (>10000)

### LINKED ISSUE #2383: Issue with UTF-8 failing to decode hex bytes
Given the following raw hex string:<br>
`public constant notValid = hex"F09FA684";`
Solidity throws the following error:  

> Type literal_string (contains invalid UTF-8 sequence at position 3) is not implicitly convertible to
> expected type string memory.

However, given the valid series of UTF-8 encoded bytes `\xF0\x9F\xA6\x84`, Solidity should decode it to get the unicorn emoji: 🦄, a valid UTF-8 decoded character.

You can verify the desired behavior [here](https://mothereff.in/utf-8),
entering \xF0\x9F\xA6\x84 into the **UTF-8-encoded** box.<br>
This issue was discovered as the result of a StackExchange question, which you can find [here](https://ethereum.stackexchange.com/questions/17670/solidity-and-the-mystery-of-the-unicode-unicorn) .<br>

Solidity 0.4.11
Related Files: 
/libdevcore/UTF8.cpp [1071] - where error is thrown
/libsolidity/ast/Types.cpp [31] - validateUTF8() improperly returns false
OS: Ubuntu 16.04

### PR DESCRIPTION
**Pull request by axic**
Fixes #2383.

### CODE REVIEW

**Review by chriseth — COMMENTED** [review]
I don't think this is correct, it seems to be more complicated: https://stackoverflow.com/questions/6555015/check-for-invalid-utf8

**Comment by 0xcaff** [comment]
This check isn't complete but at least it works for larger codepoints.

**Comment by chriseth** [comment]
Ok, will fix the problem later: https://github.com/ethereum/solidity/issues/2412

**Comment by 0xcaff** [comment]
Aww yeah! We're going to have so many emojis in everything now! 💯💥🦄⚡🔥🌈⭐Thanks guys!

**Pull request merged**
