### PR TITLE
Update aleth to version 1.6.0-rc.1.

### PR DESCRIPTION
**Pull request by ekpyron**
Another one of these...

### CODE REVIEW

**Comment by axic** [comment]
Can we wait till next week for the final 1.6.0 release?

**Comment by ekpyron** [comment]
@axic That was the original plan - but we're having storage related gas test failures again and a good explanation for those would be that 1.5.2 is pre-petersburg - that's why we wanted to check whether this helps and are considering to update early...
EDIT: actually not really a "good explanation" :-)... The failures occur for any EVM version at random...

**Review by erak — APPROVED** [review]
Verfied this fix with: https://github.com/ethereum/solidity/pull/6500

**Comment by axic** [comment]
@chfast @gumb0 how far out is the stable 1.6.0 release? :)

**Comment by chfast** [comment]
Done now.

**Pull request merged**
