### PR TITLE
grammar.txt: Add optional trailing comma to NameValueList rule

### PR DESCRIPTION
**Pull request by federicobond**

### CODE REVIEW

**Comment by axic** [comment]
Should `{ x: 1, y: 2, }` be valid or should we restrict the parser?

**Comment by pirapira** [comment]
It makes the diff cleaner when we remove the last element from here
```
  {
    x : 1,
-   y : 2,
  }
```

If we don't allow the trailing comma, the comma after `x` needs to be removed, and the diff looks more complicated.
```
  {
-   x : 1,
-   y : 2
+   x : 1
  }
```


Another solution is the Haskell way, but that's not popular:
```
  { x : 1
- , y : 2
  }
```

**Comment by chriseth** [comment]
Commas are separators, semicolons are terminators, so I would not introduce optional trailing commas. Plus, trailing commas actually have a meaning in tuples and tuple match expressions.

**Comment by federicobond** [comment]
Oh, I thought it was expected behavior. I find trailing commas usually comfortable and I don't think they clash with the tuple case, but it ultimately comes down to the feel you want to give to the language.

**Comment by federicobond** [comment]
Relevant source code: https://github.com/ethereum/solidity/blob/develop/libsolidity/parsing/Parser.cpp#L1337-L1340

**Comment by chriseth** [comment]
Ah thanks for the pointer to the source code! In this case, I would prefer to change the source code, actually. Trailing commas have a meaning at other parts of the code, so I would not want to introduce flexibility here.

**Comment by pirapira** [comment]
I created an issue about forbidding the trailing comma: https://github.com/ethereum/solidity/issues/2385

Thanks @federicobond for noticing the inconsistency between the code and the documentation.

**Pull request closed without merging**
