### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by GoodDaisy**

### CODE REVIEW

**Review by nikola-matic — DISMISSED** [review]
Please squash the commits into one. Otherwise, it's good to merge.

**Comment by GoodDaisy** [comment]
@nikola-matic I have squashed. Thank you very much for your review.

**Comment by matheusaaguiar** [comment]
@GoodDaisy , thanks for the PR. I have rebased it. 
For the future, please use `rebase` rather than `merge` when squashing commits and also it is better to create another branch (with a meaningful name) in your repo instead of using your `develop` branch.

**Review by matheusaaguiar — APPROVED** [review]

**Comment by GoodDaisy** [comment]
@matheusaaguiar thank you very much for your review and best practice!

**Pull request merged**
