### PR TITLE
Dropping AppVeyor CI (as we've moved Windows tests to CircleCI)

### PR DESCRIPTION
**Pull request by christianparpart**
This drops AppVeyor CI (basically just removing the appveyor.yml it seems). No other references found.

I think we should make sure AppVeyor is gone from Github CI after merge.

### CODE REVIEW

**Comment by cameel** [comment]
So I guess this means that we're switching to adding `exe`s to `solc-bin` in this release?

**Comment by chriseth** [comment]
@cameel we already did that for 0.7.2: https://github.com/ethereum/solc-bin/tree/gh-pages/windows-amd64

**Review by chriseth — APPROVED** [review]

**Comment by cameel** [comment]
Oh, how did I miss that?! But well, that's good :)

**Comment by leonardoalt** [comment]
Amazing!!

**Pull request merged**
