### PR TITLE
Fix cmdline tests that depended on metadata.

### LINKED ISSUE #6747: Commandline tests fail on Release version
If the `prerelease.txt` file is present in the repository, the commandline tests fail due to differing metadata hash.

### PR DESCRIPTION
**Pull request by ekpyron**
As far as I can see this closes https://github.com/ethereum/solidity/issues/6747.

There's no need to actually check the bytecode in these tests, is there?

### CODE REVIEW

**Comment by chriseth** [comment]
I'm not sure, I would actually think that these test changes do not verify the fix - can you check, please? The reason is beacuse `isRequestedContract` is used to check if we need to generate bytecode or not.

Perhaps we could use something like `gas` that also needs the bytecode but does not output it.

**Comment by ekpyron** [comment]
True, this is in fact not enough to test #6606. Unfortunately, then there is no good way to test this - almost everything that requests binaries does depend on the metadata:
 - anything in ``evm.bytecode.*`` or ``evm.deployedBytecode.*`` will output the whole bytecode/deployedBytecode object including the actual bytecode
 - ``gasEstimates`` will vary significantly with varying metadata as well
 - ``assembly`` and ``legacyAssembly`` do contain the metadata itself as well

That leaves ``ir`` and ``irOptimized``, which has the disadvantage that they are experimental and more likely to change a lot. I still changed this to ``ir`` for now, but we don't really have a good solution for this at the moment...

**Comment by ekpyron** [comment]
I'm wondering whether there's a good way around the metadata dependency in standard json in general... but I guess we precisely don't want a switch to disable the metadata... a "fake release" switch like for the gas test won't really work either... so I'm not sure.
At some point I guess ``ir`` and ``irOptimized`` won't work either, because once they are complete I guess they will also contain the metadata as part of the constructor code...

**Comment by chriseth** [comment]
It might be best to turn this into a non-commandline test.

**Comment by ekpyron** [comment]
Yeah ok - I can turn them into ``StandardCompiler.cpp`` tests.

**Comment by ekpyron** [comment]
Ok, I now moved them to ``StandardCompiler.cpp`` and merely verify that the ``contracts`` and ``sources`` fields in the output have the correct keys without looking at the actual contents.

**Review by chriseth — APPROVED** [review]

**Pull request merged**
