### PR TITLE
Fix incorrect CMAKE_SOURCE_DIR usage

### PR DESCRIPTION
**Pull request by junaire**
When using solidity as a third-party library (include it into our project using FetchContent), we encountered a strange compilation error. For some reason, cmake considers the root directory of the project as the root directory of the dependency (solidity). This is because solidity is incorrectly using CMAKE_SOURCE_DIR variable, which should be PROJECT_SOURCE_DIR (The former one refers to the top-level source directory that contains a CMakeLists.txt, while the latter refers to the source directory of the most recent project() command)

I've created a repo for demonstration (https://github.com/junaire/test-solidity-fetch-content)

### CODE REVIEW

**Review by r0qs — DISMISSED** [review]
Oh! Nice, thanks a lot @junaire :)

**Comment by junaire** [comment]
> Oh! Nice, thanks a lot @junaire :)

Thanks for the review, can we merge it? :D

**Comment by r0qs** [comment]
Hi @junaire I see no problem in merging it, but I will tag @ekpyron and @cameel so they can also have a look at it :)

**Review by cameel — APPROVED** [review]
Looks fine to me.

**Pull request merged**
