### PR TITLE
Fix merge conflict resolution.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by leonardoalt** [comment]
Is this also lacking the test changes? Or are those from elsewhere?

**Comment by chriseth** [comment]
The external tests are failing because I already updated them for #8992

**Comment by chriseth** [comment]
The syntax tests are untouched because there was no merge conflicts in them, and I only incorrectly resolved the merge conflict in the docstringanalyzer.

**Review by leonardoalt — APPROVED** [review]

**Review by ekpyron — APPROVED** [review]
I hope this is not just the tip of a huge iceberg of weird stuff happening during the merges...

**Pull request merged**
