### PR TITLE
Don't add empty local entries for Wasm functions with no local variables

### PR DESCRIPTION
**Pull request by cameel**
~Based on #9140 for convenience (I want to put #8240 on top of both). Can be rebased on `develop` if needed.~ Now it's directly on `develop`.

### CODE REVIEW

**Comment by axic** [comment]
This one looks okay, though it is only an optimisation. I expect this part of the code change quite a bit anyway once supporting types properly. Please just merge it into `develop`.

**Review by axic — APPROVED** [review]

**Comment by cameel** [comment]
> I expect this part of the code change quite a bit anyway once supporting types properly. 

It will. I actually already have that changed in #8240 but it would get lost in the other changes and I wanted you to take a look specifically at this. I was a bit concerned about whether I can even set it to zero - it was failing for me but in the end I realized it was the alignment causing problems.

**Comment by axic** [comment]
> I was a bit concerned about whether I can even set it to zero - it was failing for me but in the end I realized it was the alignment causing problems.

The first number is the number of entires in the vector. It can be 0.

Now the second number, the actual "RLE compression" part I am not sure whether it can be 0 or must be >0, but we avoid that problem. Parsing wise it definitely can be 0, but validation wise I need to check.

**Comment by cameel** [comment]
> Now the second number, the actual "RLE compression" part I am not sure whether it can be 0

Even if it couldn't, it would no longer be a problem after this PR since the whole point is no longer have empty sections :)

So if the first one being zero is fine, it's all good. I was having doubts mostly due to the problems I encountered and I just wanted to be extra careful with this.

**Pull request merged**
