### PR TITLE
Remove Safe Remote Purchase

### PR DESCRIPTION
**Pull request by ghost**
If the seller doesn't send the item, then the buyer faces a choice: 
    1. leave things as they are and keep waiting, hoping that the seller will send the item so they can get their 2x ETH back (+ x ETH from the buyer), or 
    2. decide that the seller really won't send the item, and either 
        A. leave the money in the contract to spite the seller, or 
        B. get half of their money back by confirming the delivery. 

Of course, confirming the delivery would also send x ETH of the buyer's money to the seller. So, overall, the seller stands to gain x ETH just by not sending the item.

### CODE REVIEW

**Comment by ekpyron** [comment]
Thank you very much for raising this issue!

As far as I'm concerned, the contracts in the documentation are rather meant to demonstrate language features *inspired* by some real world use case, rather than showcasing contracts that you could or should *actually* use for the given purpose.

The main point of this particular one is the modifiers restricting functions to specific addresses and states of the contract.

It's a bit tricky - on the one hand I think it's helpful for these examples to have some real-world context to explain concepts of solidity, on the other hand that carries the danger of people considering it to be complete, ready-to-be-used contracts (like *what can go wrong - that contract even came from the language docs*) - and that can be pretty dangerous...

So you're right - we can't just leave it as it stands, because it really looks a bit like this is meant as a good, ready-to-be-used real-world contract (or at least contract template) and we should generally abstain from such claims or even the appearance of such claims (I would say).

@ChrisChinchilla What do you think about this? We should *at least* have some description explaining all this like for the Voting contract on the top of that section.

**Comment by ghost** [comment]
In my analysis, the simplest escrow contract, where a buyer deposits x ETH and confirms delivery, is safe except against a buyer who wants to spite a seller (by not confirming the delivery) or a seller who wants to spite a buyer (by not sending the item), rather than either wanting to gain for themselves. Perhaps that contract would be a suitable replacement, if you agree with that analysis?

**Comment by chriseth** [comment]
@willnwhite I don't think this problem can be solved by a smart contract in all cases to everyone's satisfaction without having a trusted third party. We might want to add this to the example. This example came out of a talk at devcon1, which might have more explanation: https://www.youtube.com/watch?v=seU7DykOxfc&feature=youtu.be

**Comment by ChrisChinchilla** [comment]
@willnwhite @ekpyron @chriseth I feel like it would be better to add explanation than remove it completely, if you want to make a new PR with that explanation, then I'll be happy to review it. Or I'll add it my todo list. Equally, the option you mention in https://github.com/ethereum/solidity/pull/7725#issuecomment-554375403 would also be welcome as a PR if you have time to make it.

**Comment by ghost** [comment]
There's something I hadn't considered. As the seller you have no guarantee that the buyer will fold and send their money to you any time soon. Eventually, buyer may need their 1ETH, but for the time being the seller has to be prepared to lock up 2ETH, knowing that they can get it back (+1ETH from buyer) sooner if they send the item. Just as the buyer might need their 1ETH, the seller might need their 2ETH. I guess it comes down to how wealthy the seller is compared to the buyer. Can seller afford to keep their 2ETH locked up longer than buyer can afford to keep their 1ETH locked up? As neither will necessarily know how wealthy the other is, does it just make more sense for both sides to follow the rules?

I found the [original paper](https://github.com/oleganza/bitcoin-papers/blob/master/JointEscrow.md) mentioned in the linked talk. I don't think there's an answer to this in the paper, so I'm thinking about either contacting its author, or learning more about the Nash equilibrium!

**Comment by chriseth** [comment]
Added some explanation here: https://github.com/ethereum/solidity/pull/7780

**Comment by adwulfran** [comment]
Hello
I don't understand why the seller has to send twice (or once) the value of the item into the contract. 
@willnwhite  I agree your analysis where you suggested only the buyer send money to the contract. It should be like real online marketplace where money is locked until buyer received item. I have never seen a online marketplace where seller has to put the value of the item he sell.

**Pull request closed without merging**
