### PR TITLE
faq typo

### PR DESCRIPTION
**Pull request by bernardpeh**
a typo in faq?

### CODE REVIEW

**Comment by pirapira** [comment]
The failure in Appveyor looks unrelated.

**Comment by pirapira** [comment]
It seems some information is lost by the edit.  @chriseth ?

**Comment by chriseth** [comment]
Local variables are in the stack but reference storage.

**Comment by axic** [comment]
This change is not correct.  It must be extended to reflect the actual truth.

**Comment by bernardpeh** [comment]
sentence updated

**Pull request merged**
