### PR TITLE
Remove use of `using namespace` in header file (`ASTAnnotations.h`)

### PR DESCRIPTION
**Pull request by tylerfxn**
#12743

> 2. Update [CommonSyntaxTest.cpp](https://github.com/ethereum/solidity/blob/develop/test/CommonSyntaxTest.cpp) so it has only one local definition of "isDigit" function.

I'm not sure that this is actually a need. `isdigit` is a native function and not being defined elsewhere.

### CODE REVIEW

**Comment by wechman** [comment]
Thank you for the heads-up! Indeed `isdigit` is not there yet. This part can be addressed after #12740 merge. I already updated #12743 description.

**Comment by wechman** [comment]
Hi @tfire! You are going in the right direction with your changes, but there are still things to be addressed:
1) Tests are failing so require update.
2) There is no need to have [using namespace directive](https://github.com/ethereum/solidity/pull/12746/files#diff-c94fd953390e50182709ef3eea4b17c1b46a078b345e1b8d6befeb29d3ab0b8bR30) when [fully qualified names](https://github.com/ethereum/solidity/pull/12746/files#diff-c94fd953390e50182709ef3eea4b17c1b46a078b345e1b8d6befeb29d3ab0b8bR133) are in use.

**Comment by tylerfxn** [comment]
got it building locally @wechman

**Comment by wechman** [comment]
#12740 is already merged so if you like you can also address [CommonSyntaxTest.cpp](https://github.com/ethereum/solidity/blob/develop/test/CommonSyntaxTest.cpp) related part.

**Comment by tylerfxn** [comment]
@wechman will be done later, merge from latest introduced a bunch of calls that aren't qualified

**Comment by tylerfxn** [comment]
@wechman should be done! 🙂

**Review by ekpyron — APPROVED** [review]

**Pull request merged**
