### PR TITLE
Transitive closure.

### PR DESCRIPTION
**Pull request by chriseth**
Part of https://github.com/ethereum/solidity/issues/7078

### CODE REVIEW

**Review by ekpyron — COMMENTED** [review]
I'm pretty this can be done with quadratic instead of cubic worst case runtime (e.g. DFS starting from each vertex), but I'm not sure we care too much...

**Comment by ekpyron** [comment]
sorry, didn't read careful enough in the train, it's not that bad actually

**Comment by ekpyron** [comment]
Actually, I think this might not even be correct, e.g. for a long enough tree of max degree 1...
EDIT: no, it's probably actually correct - but not optimal.

**Comment by chriseth** [comment]
It seems this is not needed for now.

**Pull request closed without merging**
