### PR TITLE
Fix error tag usage in lll.

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/1440

### CODE REVIEW

**Comment by axic** [comment]
@chriseth added the test case which should fail if not fixed

**Review by axic — APPROVED** [review]

**Comment by axic** [comment]
@zigguratt good news! :)

**Comment by zigguratt** [comment]
@axic excellent! and it looks like it was a pretty easy fix. of course, the hard part is usually finding _where_ to fix it, not the fix itself. well done, sir!

**Comment by axic** [comment]
Funny enough I had a very similar change in my branch:
```
-               if (i.type() == Tag || i.type() == PushTag)
+               if ((i.type() == Tag || i.type() == PushTag))// && i.data() != 0)
```

Just wasn't sure it is the right one. It was, almost 😉

**Pull request merged**
