### PR TITLE
Remove deps git submodule

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
Does the script `create_source_tarball.sh` still work?

**Comment by chriseth** [comment]
also `release_ppa.sh`?

**Comment by chfast** [comment]
@chriseth I've added back the location of jsoncpp source in `<source tree>/deps/downloads` (so not change in this case). The `create_source_tarball.sh` works (I left git submodules update step, but it is noop now). I'm not sure I can test `release_ppa.sh`.

**Comment by chriseth** [comment]
I'm testing the ppa

**Comment by chriseth** [comment]
ppa seems to be working!

**Comment by chfast** [comment]
Merging then?

**Pull request merged**
