### PR TITLE
[Optimizer] Use shift directly instead of multiplication in constant optimizer.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Review by ekpyron — DISMISSED** [review]

**Comment by chriseth** [comment]
This might need an update for the gas costs test.

**Comment by ekpyron** [comment]
Does anyone generally understand why the gas cost test is not at all constant across systems and runs? Earlier I thought the reason might be the constantinople storage stuff, but that should be removed now, shouldn't it? And the test is still fluctuating...

**Comment by chriseth** [comment]
I always thought it was aleth not reporting the gas costs properly.

**Comment by ekpyron** [comment]
Probably...

**Review by axic — DISMISSED** [review]

**Review by ekpyron — APPROVED** [review]
Looks good!

**Pull request merged**
