### PR TITLE
Edit function name 'send' in Coin contract

### PR DESCRIPTION
**Pull request by apraka16**
Edit in function name of Coin contract (from 'send' to 'sendCoins'), 'send' interferes with the reserved function 'send', rendering this function call to result in Error, viz. 'Sender doesn't have enough funds', most times.

### CODE REVIEW

**Comment by axic** [comment]
Thanks, it shouldn't conflict. Do you have some test cases where it does?

**Comment by apraka16** [comment]
Actually, it is conflicting when I am using it with testrpc.
Code used exactly as given in the documentations. 
In case I change the function to sendCoins, this function works, otherwise not. 

_**send**_
```
truffle(development)> Coin.deployed().then(function(instance) { CN = Coin.at(instance.address) })
truffle(development)> CN.balances(web3.eth.accounts[0])
{ [String: '0'] s: 1, e: 0, c: [ 0 ] }
truffle(development)> CN.balances(web3.eth.accounts[1])
{ [String: '0'] s: 1, e: 0, c: [ 0 ] }
truffle(development)> CN.balances(web3.eth.accounts[2])
{ [String: '0'] s: 1, e: 0, c: [ 0 ] }
truffle(development)> CN.mint(web3.eth.accounts[1], 10000)
{ tx: '0xbccd01efccc7c5a97b506be5026b4fe43a537344d8806a2e5c8c12477f0475b2',
  receipt:
   { transactionHash: '0xbccd01efccc7c5a97b506be5026b4fe43a537344d8806a2e5c8c12477f0475b2',
     transactionIndex: 0,
     blockHash: '0xfebedf2a43aeea307d2533b58b3543575d1c0067955c0ba965fc69e37fb484db',
     blockNumber: 22,
     gasUsed: 43447,
     cumulativeGasUsed: 43447,
     contractAddress: null,
     logs: [] },
  logs: [] }

truffle(development)> CN.send(web3.eth.accounts[2], 1000, { from: web3.eth.accounts[1] })
Error: sender doesn't have enough funds to send tx. The upfront cost is: 559619484054951692505385377824345378830193875398 and the senders account only has: 99349481500000000000
```
_**sendCoins**_

```
truffle(development)> Coin.deployed().then(function(instance) { CN = Coin.at(instance.address) })

truffle(development)> CN.mint(web3.eth.accounts[1], 10000)
{ tx: '0xb86add18d33857fa630cfaa319912bc9a7de5990c295621c5fa065ce40953c1e',
  receipt:
   { transactionHash: '0xb86add18d33857fa630cfaa319912bc9a7de5990c295621c5fa065ce40953c1e',
     transactionIndex: 0,
     blockHash: '0x77caace8998136f09cbd7228b30f3f76490364f6f136de8228192661d62c4942',
     blockNumber: 28,
     gasUsed: 43469,
     cumulativeGasUsed: 43469,
     contractAddress: null,
     logs: [] },
  logs: [] }
truffle(development)> CN.sendCoins(web3.eth.accounts[2], 1000, { from: web3.eth.accounts[1] })
{ tx: '0x95128f9a87f5693c434810a88d5b6fcd28eba7bd010d137a8ea7a75f27fab293',
  receipt:
   { transactionHash: '0x95128f9a87f5693c434810a88d5b6fcd28eba7bd010d137a8ea7a75f27fab293',
     transactionIndex: 0,
     blockHash: '0x4eff24a45c66798bad9332cb0db2b8bfab9a10bf87c79e30b6a8554e82207d70',
     blockNumber: 29,
     gasUsed: 50210,
     cumulativeGasUsed: 50210,
     contractAddress: null,
     logs: [ [Object] ] },
  logs:
   [ { logIndex: 0,
       transactionIndex: 0,
       transactionHash: '0x95128f9a87f5693c434810a88d5b6fcd28eba7bd010d137a8ea7a75f27fab293',
       blockHash: '0x4eff24a45c66798bad9332cb0db2b8bfab9a10bf87c79e30b6a8554e82207d70',
       blockNumber: 29,
       address: '0xd8e12da9f7a924a7ee6e35067a64989b1af8ca4a',
       type: 'mined',
       event: 'Sent',
       args: [Object] } ] }
```

**Comment by axic** [comment]
That is a conflict in `web3.js` and such outside the realm of Solidity.

**Comment by apraka16** [comment]
Apologies, seems like an issue with web3.js after all, thanks.

**Pull request closed without merging**
