### PR TITLE
Test batcher.

### PR DESCRIPTION
**Pull request by chriseth**
Related to #12388

### CODE REVIEW

**Comment by chriseth** [comment]
It seems we do not have nice control over the boost test tree. We can (and already do) remove high-level set suites. If we manage to get a list of all high-level test suites (and we can cross-check that `with master_test_suite().size()`), we can at least selectively enable the high-level test suites depending on the batch.

Note that the same mechanism should also be added to isoltest.

Then, furthermore, we should change our scripts that a number of batches should run in parallel on the same machine depending on the number of CPUs / CPU cores.

**Comment by chriseth** [comment]
Tests that take longer than 10 seconds:
```
smtCheckerTests/array_members/push_as_lhs_3d.sol(0): Leaving test case "push_as_lhs_3d"; testing time: 10889941us
smtCheckerTests/array_members/push_storage_ref_unsafe_length.sol(0): Leaving test case "push_storage_ref_unsafe_length"; testing time: 33262941us
smtCheckerTests/control_flow/return_2_fail.sol(0): Leaving test case "return_2_fail"; testing time: 12725182us
smtCheckerTests/userTypes/conversion.sol(0): Leaving test case "conversion"; testing time: 12054165us
smtCheckerTests/types/array_branch_3d.sol(0): Leaving test case "array_branch_3d"; testing time: 27502499us
smtCheckerTests/types/struct/struct_recursive_3.sol(0): Leaving test case "struct_recursive_3"; testing time: 11288135us
smtCheckerTests/types/struct/struct_array_struct_array_storage_unsafe_1.sol(0): Leaving test case "struct_array_struct_array_storage_unsafe_1"; testing time: 15496321us
smtCheckerTests/types/struct/array_struct_array_struct_storage_safe.sol(0): Leaving test case "array_struct_array_struct_storage_safe"; testing time: 90707004us
smtCheckerTests/types/struct/struct_array_struct_array_storage_safe.sol(0): Leaving test case "struct_array_struct_array_storage_safe"; testing time: 11103784us
smtCheckerTests/types/struct/array_struct_array_struct_memory_safe.sol(0): Leaving test case "array_struct_array_struct_memory_safe"; testing time: 11621116us
smtCheckerTests/types/array_branches_3d.sol(0): Leaving test case "array_branches_3d"; testing time: 54830744us
smtCheckerTests/types/array_aliasing_memory_1.sol(0): Leaving test case "array_aliasing_memory_1"; testing time: 26906150us
smtCheckerTests/types/array_mapping_aliasing_2.sol(0): Leaving test case "array_mapping_aliasing_2"; testing time: 12860771us
smtCheckerTests/types/array_branches_3d_show_unproved.sol(0): Leaving test case "array_branches_3d_show_unproved"; testing time: 53786148us
smtCheckerTests/special/tx_data_immutable_fail.sol(0): Leaving test case "tx_data_immutable_fail"; testing time: 28209337us
```

Tests that take longer than 1 second:
```
/solidity/test/libsolutil/IpfsHash.cpp(82): Leaving test case "test_largest_one_level"; testing time: 1107683us
/solidity/test/libsolutil/IpfsHash.cpp(91): Leaving test case "test_smallest_multi_level"; testing time: 1097617us
/solidity/test/libsolutil/IpfsHash.cpp(100): Leaving test case "test_multi_level_tree"; testing time: 1139514us
/solidity/test/libsolidity/ABIEncoderTests.cpp(587): Leaving test case "bytesNN_arrays"; testing time: 3591903us
/solidity/test/libsolidity/ABIEncoderTests.cpp(632): Leaving test case "bytesNN_arrays_dyn"; testing time: 3602355us
/solidity/test/libsolidity/SolidityEndToEndTest.cpp(2563): Leaving test case "short_strings"; testing time: 2229884us
/solidity/test/libsolidity/SolidityEndToEndTest.cpp(3577): Leaving test case "abi_encodePacked_from_storage"; testing time: 2706538us
semanticTests/array/copying/array_nested_memory_to_storage.sol(0): Leaving test case "array_nested_memory_to_storage"; testing time: 1328455us
semanticTests/array/copying/storage_memory_packed_dyn.sol(0): Leaving test case "storage_memory_packed_dyn"; testing time: 1013223us
semanticTests/array/copying/array_nested_calldata_to_storage.sol(0): Leaving test case "array_nested_calldata_to_storage"; testing time: 1080818us
semanticTests/array/copying/array_copy_clear_storage_packed.sol(0): Leaving test case "array_copy_clear_storage_packed"; testing time: 1071096us
semanticTests/externalContracts/snark.sol(0): Leaving test case "snark"; testing time: 2991563us
semanticTests/externalContracts/strings.sol(0): Leaving test case "strings"; testing time: 1369129us
semanticTests/externalContracts/deposit_contract.sol(0): Leaving test case "deposit_contract"; testing time: 1620504us
semanticTests/externalContracts/prbmath_unsigned.sol(0): Leaving test case "prbmath_unsigned"; testing time: 2864170us
semanticTests/externalContracts/prbmath_signed.sol(0): Leaving test case "prbmath_signed"; testing time: 2959454us
semanticTests/abiEncoderV2/abi_encode_calldata_slice.sol(0): Leaving test case "abi_encode_calldata_slice"; testing time: 1542007us
semanticTests/abiEncoderV2/dynamic_nested_arrays.sol(0): Leaving test case "dynamic_nested_arrays"; testing time: 1739106us
semanticTests/abiEncoderV2/calldata_array_static_dynamic_static.sol(0): Leaving test case "calldata_array_static_dynamic_static"; testing time: 2055305us
semanticTests/abiEncoderV2/calldata_array_dynamic_static_dynamic.sol(0): Leaving test case "calldata_array_dynamic_static_dynamic"; testing time: 2489762us
semanticTests/abiEncoderV1/abi_encode_calldata_slice.sol(0): Leaving test case "abi_encode_calldata_slice"; testing time: 1473076us
smtCheckerTests/array_members/push_push_no_args_1_fail.sol(0): Leaving test case "push_push_no_args_1_fail"; testing time: 1797610us
smtCheckerTests/array_members/push_as_lhs_and_rhs_1d.sol(0): Leaving test case "push_as_lhs_and_rhs_1d"; testing time: 2004979us
smtCheckerTests/array_members/push_as_lhs_and_rhs_2d_2.sol(0): Leaving test case "push_as_lhs_and_rhs_2d_2"; testing time: 1366898us
smtCheckerTests/array_members/push_as_lhs_and_rhs_bytes.sol(0): Leaving test case "push_as_lhs_and_rhs_bytes"; testing time: 2153896us
smtCheckerTests/array_members/push_as_lhs_1d.sol(0): Leaving test case "push_as_lhs_1d"; testing time: 1920881us
smtCheckerTests/array_members/storage_pointer_push_1.sol(0): Leaving test case "storage_pointer_push_1"; testing time: 1799717us
smtCheckerTests/array_members/push_as_lhs_and_rhs_2d_1.sol(0): Leaving test case "push_as_lhs_and_rhs_2d_1"; testing time: 4102510us
smtCheckerTests/array_members/push_storage_ref_safe_aliasing.sol(0): Leaving test case "push_storage_ref_safe_aliasing"; testing time: 2539747us
smtCheckerTests/array_members/push_as_lhs_2d.sol(0): Leaving test case "push_as_lhs_2d"; testing time: 5171818us
smtCheckerTests/array_members/push_as_lhs_bytes.sol(0): Leaving test case "push_as_lhs_bytes"; testing time: 1875158us
smtCheckerTests/array_members/push_as_lhs_bytes_2d.sol(0): Leaving test case "push_as_lhs_bytes_2d"; testing time: 5095788us
smtCheckerTests/array_members/push_storage_ref_unsafe_aliasing.sol(0): Leaving test case "push_storage_ref_unsafe_aliasing"; testing time: 2114207us
smtCheckerTests/array_members/length_same_after_assignment_3.sol(0): Leaving test case "length_same_after_assignment_3"; testing time: 1287275us
smtCheckerTests/array_members/push_2d_arg_1_unsafe.sol(0): Leaving test case "push_2d_arg_1_unsafe"; testing time: 1617027us
smtCheckerTests/array_members/length_same_after_assignment_2_fail.sol(0): Leaving test case "length_same_after_assignment_2_fail"; testing time: 5015359us
smtCheckerTests/array_members/length_same_after_assignment_3_fail.sol(0): Leaving test case "length_same_after_assignment_3_fail"; testing time: 5214498us
smtCheckerTests/array_members/push_push_no_args_2_fail.sol(0): Leaving test case "push_push_no_args_2_fail"; testing time: 3784589us
smtCheckerTests/array_members/array_push_string_literal.sol(0): Leaving test case "array_push_string_literal"; testing time: 1318221us
smtCheckerTests/array_members/length_same_after_assignment_2.sol(0): Leaving test case "length_same_after_assignment_2"; testing time: 1275900us
smtCheckerTests/array_members/push_function_return_value.sol(0): Leaving test case "push_function_return_value"; testing time: 1003225us
smtCheckerTests/control_flow/branches_inside_modifiers_2.sol(0): Leaving test case "branches_inside_modifiers_2"; testing time: 1985112us
smtCheckerTests/control_flow/return_2.sol(0): Leaving test case "return_2"; testing time: 2419204us
smtCheckerTests/control_flow/branches_inside_modifiers_4.sol(0): Leaving test case "branches_inside_modifiers_4"; testing time: 1948400us
smtCheckerTests/control_flow/branches_inside_modifiers_1.sol(0): Leaving test case "branches_inside_modifiers_1"; testing time: 1249202us
smtCheckerTests/control_flow/branches_with_return/constructor_state_variable_init.sol(0): Leaving test case "constructor_state_variable_init"; testing time: 4934665us
smtCheckerTests/control_flow/branches_with_return/constructor_state_variable_init_diamond.sol(0): Leaving test case "constructor_state_variable_init_diamond"; testing time: 7369214us
smtCheckerTests/control_flow/branches_with_return/branches_in_modifiers_2.sol(0): Leaving test case "branches_in_modifiers_2"; testing time: 5315642us
smtCheckerTests/control_flow/branches_with_return/nested_if.sol(0): Leaving test case "nested_if"; testing time: 1177339us
smtCheckerTests/control_flow/branches_with_return/simple_if_array.sol(0): Leaving test case "simple_if_array"; testing time: 1584273us
smtCheckerTests/control_flow/branches_with_return/constructors.sol(0): Leaving test case "constructors"; testing time: 1039709us
smtCheckerTests/control_flow/return_1_fail.sol(0): Leaving test case "return_1_fail"; testing time: 5019897us
smtCheckerTests/control_flow/branches_inside_modifiers_3.sol(0): Leaving test case "branches_inside_modifiers_3"; testing time: 1020866us
smtCheckerTests/control_flow/return_1.sol(0): Leaving test case "return_1"; testing time: 1201818us
smtCheckerTests/control_flow/short_circuit_or_inside_branch.sol(0): Leaving test case "short_circuit_or_inside_branch"; testing time: 1310218us
smtCheckerTests/userTypes/in_parenthesis.sol(0): Leaving test case "in_parenthesis"; testing time: 1014461us
smtCheckerTests/userTypes/fixedpoint.sol(0): Leaving test case "fixedpoint"; testing time: 8270841us
smtCheckerTests/userTypes/multisource.sol(0): Leaving test case "multisource"; testing time: 1489803us
smtCheckerTests/userTypes/wrap_unwrap_via_contract_name.sol(0): Leaving test case "wrap_unwrap_via_contract_name"; testing time: 4869688us
smtCheckerTests/userTypes/in_parenthesis_2.sol(0): Leaving test case "in_parenthesis_2"; testing time: 1384996us
smtCheckerTests/userTypes/simple.sol(0): Leaving test case "simple"; testing time: 1377496us
smtCheckerTests/userTypes/multisource_module.sol(0): Leaving test case "multisource_module"; testing time: 1720707us
smtCheckerTests/out_of_bounds/array_2d_3.sol(0): Leaving test case "array_2d_3"; testing time: 1211483us
smtCheckerTests/out_of_bounds/array_1.sol(0): Leaving test case "array_1"; testing time: 3744594us
smtCheckerTests/out_of_bounds/array_2d_4.sol(0): Leaving test case "array_2d_4"; testing time: 6201054us
smtCheckerTests/out_of_bounds/array_2d_2.sol(0): Leaving test case "array_2d_2"; testing time: 1072527us
smtCheckerTests/loops/while_nested_break_fail.sol(0): Leaving test case "while_nested_break_fail"; testing time: 3302839us
smtCheckerTests/loops/for_1_fail.sol(0): Leaving test case "for_1_fail"; testing time: 3695369us
smtCheckerTests/loops/while_loop_array_assignment_storage_storage.sol(0): Leaving test case "while_loop_array_assignment_storage_storage"; testing time: 7198787us
smtCheckerTests/loops/for_loop_array_assignment_memory_storage.sol(0): Leaving test case "for_loop_array_assignment_memory_storage"; testing time: 1344876us
smtCheckerTests/loops/while_nested_continue_fail.sol(0): Leaving test case "while_nested_continue_fail"; testing time: 1183062us
smtCheckerTests/loops/for_1_false_positive.sol(0): Leaving test case "for_1_false_positive"; testing time: 2029319us
smtCheckerTests/blockchain_state/balance_receive_4.sol(0): Leaving test case "balance_receive_4"; testing time: 5154653us
smtCheckerTests/blockchain_state/balance_spend_2.sol(0): Leaving test case "balance_spend_2"; testing time: 2101168us
smtCheckerTests/imports/imported_fail_2.sol(0): Leaving test case "imported_fail_2"; testing time: 1080724us
smtCheckerTests/imports/ExtCall.sol(0): Leaving test case "ExtCall"; testing time: 1379449us
smtCheckerTests/imports/import_as_module_2.sol(0): Leaving test case "import_as_module_2"; testing time: 1187035us
smtCheckerTests/typecast/upcast.sol(0): Leaving test case "upcast"; testing time: 1725185us
smtCheckerTests/typecast/bytes_to_fixed_bytes_1.sol(0): Leaving test case "bytes_to_fixed_bytes_1"; testing time: 3764489us
smtCheckerTests/typecast/downcast.sol(0): Leaving test case "downcast"; testing time: 1183993us
smtCheckerTests/typecast/same_size.sol(0): Leaving test case "same_size"; testing time: 1835461us
smtCheckerTests/functions/constructor_hierarchy_diamond_3.sol(0): Leaving test case "constructor_hierarchy_diamond_3"; testing time: 1610982us
smtCheckerTests/functions/internal_multiple_calls_with_assertion_1_fail.sol(0): Leaving test case "internal_multiple_calls_with_assertion_1_fail"; testing time: 1799846us
smtCheckerTests/functions/internal_call_with_assertion_1_fail.sol(0): Leaving test case "internal_call_with_assertion_1_fail"; testing time: 2142750us
smtCheckerTests/functions/this_external_call_sender.sol(0): Leaving test case "this_external_call_sender"; testing time: 1704094us
smtCheckerTests/functions/constructor_hierarchy_diamond.sol(0): Leaving test case "constructor_hierarchy_diamond"; testing time: 1037576us
smtCheckerTests/functions/functions_external_2.sol(0): Leaving test case "functions_external_2"; testing time: 2550002us
smtCheckerTests/functions/function_inside_branch_modify_state_var_3.sol(0): Leaving test case "function_inside_branch_modify_state_var_3"; testing time: 1484756us
smtCheckerTests/functions/constructor_hierarchy_diamond_2.sol(0): Leaving test case "constructor_hierarchy_diamond_2"; testing time: 1087270us
smtCheckerTests/functions/constructor_hierarchy_mixed_chain_with_params.sol(0): Leaving test case "constructor_hierarchy_mixed_chain_with_params"; testing time: 1328927us
smtCheckerTests/functions/internal_call_with_assertion_inheritance_1_fail.sol(0): Leaving test case "internal_call_with_assertion_inheritance_1_fail"; testing time: 1408788us
smtCheckerTests/functions/getters/function.sol(0): Leaving test case "function"; testing time: 1145485us
smtCheckerTests/functions/getters/struct_with_reassignment.sol(0): Leaving test case "struct_with_reassignment"; testing time: 1004016us
smtCheckerTests/functions/getters/nested_arrays_mappings_8.sol(0): Leaving test case "nested_arrays_mappings_8"; testing time: 1157506us
smtCheckerTests/functions/getters/nested_arrays_mappings_5.sol(0): Leaving test case "nested_arrays_mappings_5"; testing time: 2667845us
smtCheckerTests/functions/getters/struct_3.sol(0): Leaving test case "struct_3"; testing time: 2043953us
smtCheckerTests/functions/getters/nested_arrays_mappings_3.sol(0): Leaving test case "nested_arrays_mappings_3"; testing time: 3410367us
smtCheckerTests/functions/getters/array_2.sol(0): Leaving test case "array_2"; testing time: 1373708us
smtCheckerTests/functions/getters/nested_arrays_mappings_2.sol(0): Leaving test case "nested_arrays_mappings_2"; testing time: 2133286us
smtCheckerTests/functions/getters/nested_arrays_mappings_10.sol(0): Leaving test case "nested_arrays_mappings_10"; testing time: 2018780us
smtCheckerTests/functions/getters/nested_arrays_mappings_1.sol(0): Leaving test case "nested_arrays_mappings_1"; testing time: 1023279us
smtCheckerTests/functions/getters/nested_arrays_mappings_4.sol(0): Leaving test case "nested_arrays_mappings_4"; testing time: 1598640us
smtCheckerTests/functions/constructor_hierarchy_mixed_chain_with_params_2.sol(0): Leaving test case "constructor_hierarchy_mixed_chain_with_params_2"; testing time: 1167700us
smtCheckerTests/functions/internal_multiple_calls_with_assertion_1.sol(0): Leaving test case "internal_multiple_calls_with_assertion_1"; testing time: 1546789us
smtCheckerTests/functions/super_function_assert.sol(0): Leaving test case "super_function_assert"; testing time: 2735485us
smtCheckerTests/inheritance/constructor_hierarchy_base_calls_with_side_effects_4.sol(0): Leaving test case "constructor_hierarchy_base_calls_with_side_effects_4"; testing time: 2340736us
smtCheckerTests/inheritance/constructor_state_variable_init_chain_run_all.sol(0): Leaving test case "constructor_state_variable_init_chain_run_all"; testing time: 2202626us
smtCheckerTests/inheritance/diamond_super_1.sol(0): Leaving test case "diamond_super_1"; testing time: 1595226us
smtCheckerTests/inheritance/fallback.sol(0): Leaving test case "fallback"; testing time: 1088611us
smtCheckerTests/inheritance/base_contract_assertion_fail_9.sol(0): Leaving test case "base_contract_assertion_fail_9"; testing time: 2119501us
smtCheckerTests/inheritance/constructor_hierarchy_base_calls_with_side_effects_1.sol(0): Leaving test case "constructor_hierarchy_base_calls_with_side_effects_1"; testing time: 1163859us
smtCheckerTests/inheritance/constructor_hierarchy_base_calls_inheritance_specifier_1.sol(0): Leaving test case "constructor_hierarchy_base_calls_inheritance_specifier_1"; testing time: 1155577us
smtCheckerTests/inheritance/constructor_hierarchy_base_calls_inheritance_specifier_2.sol(0): Leaving test case "constructor_hierarchy_base_calls_inheritance_specifier_2"; testing time: 1295938us
smtCheckerTests/inheritance/constructor_hierarchy_base_calls_with_side_effects_5.sol(0): Leaving test case "constructor_hierarchy_base_calls_with_side_effects_5"; testing time: 2384303us
smtCheckerTests/inheritance/constructor_state_variable_init_asserts.sol(0): Leaving test case "constructor_state_variable_init_asserts"; testing time: 4323455us
smtCheckerTests/inheritance/constructor_hierarchy_base_calls_with_side_effects_2.sol(0): Leaving test case "constructor_hierarchy_base_calls_with_side_effects_2"; testing time: 1637508us
smtCheckerTests/inheritance/constructor_hierarchy_mixed_chain_with_params.sol(0): Leaving test case "constructor_hierarchy_mixed_chain_with_params"; testing time: 1321989us
smtCheckerTests/inheritance/functions_3.sol(0): Leaving test case "functions_3"; testing time: 3005943us
smtCheckerTests/inheritance/constructor_state_variable_init_chain_tree.sol(0): Leaving test case "constructor_state_variable_init_chain_tree"; testing time: 2679635us
smtCheckerTests/inheritance/diamond_super_3.sol(0): Leaving test case "diamond_super_3"; testing time: 2469642us
smtCheckerTests/inheritance/diamond_super_2.sol(0): Leaving test case "diamond_super_2"; testing time: 2303160us
smtCheckerTests/external_calls/internal_library_external_call_3.sol(0): Leaving test case "internal_library_external_call_3"; testing time: 1369545us
smtCheckerTests/external_calls/internal_library_external_call_1.sol(0): Leaving test case "internal_library_external_call_1"; testing time: 1675240us
smtCheckerTests/external_calls/external_call_with_value_2.sol(0): Leaving test case "external_call_with_value_2"; testing time: 2983209us
smtCheckerTests/external_calls/external_safe.sol(0): Leaving test case "external_safe"; testing time: 1210546us
smtCheckerTests/external_calls/external_single_inc.sol(0): Leaving test case "external_single_inc"; testing time: 1969939us
smtCheckerTests/external_calls/external_call_with_value_3.sol(0): Leaving test case "external_call_with_value_3"; testing time: 2184412us
smtCheckerTests/external_calls/external_hash_known_code_state_unsafe.sol(0): Leaving test case "external_hash_known_code_state_unsafe"; testing time: 2206051us
smtCheckerTests/external_calls/external_hash_known_code_pure.sol(0): Leaving test case "external_hash_known_code_pure"; testing time: 1383210us
smtCheckerTests/external_calls/call_with_value_3.sol(0): Leaving test case "call_with_value_3"; testing time: 1824512us
smtCheckerTests/external_calls/call_with_value_1.sol(0): Leaving test case "call_with_value_1"; testing time: 1388801us
smtCheckerTests/external_calls/call_with_value_2.sol(0): Leaving test case "call_with_value_2"; testing time: 1230341us
smtCheckerTests/external_calls/external_inc.sol(0): Leaving test case "external_inc"; testing time: 2516246us
smtCheckerTests/external_calls/external_hash_known_code_state_reentrancy_2.sol(0): Leaving test case "external_hash_known_code_state_reentrancy_2"; testing time: 2148248us
smtCheckerTests/external_calls/external_hash_known_code_state_reentrancy_indirect.sol(0): Leaving test case "external_hash_known_code_state_reentrancy_indirect"; testing time: 2293339us
smtCheckerTests/try_catch/try_string_literal_to_fixed_bytes.sol(0): Leaving test case "try_string_literal_to_fixed_bytes"; testing time: 1875103us
smtCheckerTests/operators/delete_array_push.sol(0): Leaving test case "delete_array_push"; testing time: 1704746us
smtCheckerTests/operators/integer_new.sol(0): Leaving test case "integer_new"; testing time: 1583038us
smtCheckerTests/operators/shifts/shift_cleanup.sol(0): Leaving test case "shift_cleanup"; testing time: 8484480us
smtCheckerTests/operators/shifts/shift_right_negative_lvalue.sol(0): Leaving test case "shift_right_negative_lvalue"; testing time: 3499536us
smtCheckerTests/operators/shifts/shift_right_negative_lvalue_int8.sol(0): Leaving test case "shift_right_negative_lvalue_int8"; testing time: 2965223us
smtCheckerTests/operators/shifts/shift_right_negative_lvalue_int16.sol(0): Leaving test case "shift_right_negative_lvalue_int16"; testing time: 3084279us
smtCheckerTests/operators/shifts/shift_left.sol(0): Leaving test case "shift_left"; testing time: 2566823us
smtCheckerTests/operators/shifts/shift_right_negative_lvalue_int32.sol(0): Leaving test case "shift_right_negative_lvalue_int32"; testing time: 3591858us
smtCheckerTests/operators/shifts/shift_right_negative_literal.sol(0): Leaving test case "shift_right_negative_literal"; testing time: 3385167us
smtCheckerTests/operators/shifts/shift_left_uint32.sol(0): Leaving test case "shift_left_uint32"; testing time: 2125010us
smtCheckerTests/operators/shifts/shift_overflow.sol(0): Leaving test case "shift_overflow"; testing time: 2449290us
smtCheckerTests/operators/shifts/shift_right_uint32.sol(0): Leaving test case "shift_right_uint32"; testing time: 2066527us
smtCheckerTests/operators/shifts/shift_right.sol(0): Leaving test case "shift_right"; testing time: 2032726us
smtCheckerTests/operators/compound_bitwise_or_uint_1.sol(0): Leaving test case "compound_bitwise_or_uint_1"; testing time: 1477256us
smtCheckerTests/operators/conditional_assignment_statevar_1.sol(0): Leaving test case "conditional_assignment_statevar_1"; testing time: 1192897us
smtCheckerTests/operators/assignment_module_contract_member_variable.sol(0): Leaving test case "assignment_module_contract_member_variable"; testing time: 1219047us
smtCheckerTests/operators/delete_array_index_2d.sol(0): Leaving test case "delete_array_index_2d"; testing time: 1194612us
smtCheckerTests/operators/slice_default_start.sol(0): Leaving test case "slice_default_start"; testing time: 2117736us
smtCheckerTests/operators/bytes_new.sol(0): Leaving test case "bytes_new"; testing time: 1550330us
smtCheckerTests/operators/compound_bitwise_or_int_1.sol(0): Leaving test case "compound_bitwise_or_int_1"; testing time: 4632752us
smtCheckerTests/operators/delete_multid_array.sol(0): Leaving test case "delete_multid_array"; testing time: 2555585us
smtCheckerTests/operators/assignment_contract_member_variable_array_3.sol(0): Leaving test case "assignment_contract_member_variable_array_3"; testing time: 1450866us
smtCheckerTests/operators/compound_assignment_right_shift.sol(0): Leaving test case "compound_assignment_right_shift"; testing time: 1260095us
smtCheckerTests/abi/abi_decode_simple.sol(0): Leaving test case "abi_decode_simple"; testing time: 1335320us
smtCheckerTests/abi/abi_encode_with_selector_simple.sol(0): Leaving test case "abi_encode_with_selector_simple"; testing time: 1154885us
smtCheckerTests/abi/abi_decode_array.sol(0): Leaving test case "abi_decode_array"; testing time: 3911160us
smtCheckerTests/file_level/constants_at_file_level_referencing.sol(0): Leaving test case "constants_at_file_level_referencing"; testing time: 4167880us
smtCheckerTests/file_level/module_constants_functions_1.sol(0): Leaving test case "module_constants_functions_1"; testing time: 1674059us
smtCheckerTests/types/array_branches_2d.sol(0): Leaving test case "array_branches_2d"; testing time: 1078609us
smtCheckerTests/types/array_mapping_aliasing_1.sol(0): Leaving test case "array_mapping_aliasing_1"; testing time: 1767097us
smtCheckerTests/types/array_static_mapping_aliasing_2.sol(0): Leaving test case "array_static_mapping_aliasing_2"; testing time: 2367346us
smtCheckerTests/types/struct/struct_recursive_indirect_2.sol(0): Leaving test case "struct_recursive_indirect_2"; testing time: 1573910us
smtCheckerTests/types/struct/struct_array_struct_array_memory_unsafe_1.sol(0): Leaving test case "struct_array_struct_array_memory_unsafe_1"; testing time: 2693271us
smtCheckerTests/types/struct/struct_recursive_2.sol(0): Leaving test case "struct_recursive_2"; testing time: 2424418us
smtCheckerTests/types/struct/struct_state_var_array_pop_2.sol(0): Leaving test case "struct_state_var_array_pop_2"; testing time: 1966869us
smtCheckerTests/types/struct/struct_array_struct_array_memory_unsafe_2.sol(0): Leaving test case "struct_array_struct_array_memory_unsafe_2"; testing time: 2451026us
smtCheckerTests/types/struct/struct_array_struct_array_memory_safe.sol(0): Leaving test case "struct_array_struct_array_memory_safe"; testing time: 2822070us
smtCheckerTests/types/struct/struct_recursive_5.sol(0): Leaving test case "struct_recursive_5"; testing time: 1089929us
smtCheckerTests/types/struct/struct_state_var_array_pop_1.sol(0): Leaving test case "struct_state_var_array_pop_1"; testing time: 1995482us
smtCheckerTests/types/struct/struct_recursive_6.sol(0): Leaving test case "struct_recursive_6"; testing time: 2706874us
smtCheckerTests/types/array_static_3_fail.sol(0): Leaving test case "array_static_3_fail"; testing time: 1481726us
smtCheckerTests/types/mapping_aliasing_2.sol(0): Leaving test case "mapping_aliasing_2"; testing time: 5862334us
smtCheckerTests/types/fixed_bytes_1.sol(0): Leaving test case "fixed_bytes_1"; testing time: 1090396us
smtCheckerTests/types/mapping_as_local_var_1.sol(0): Leaving test case "mapping_as_local_var_1"; testing time: 1087425us
smtCheckerTests/types/array_literal_6.sol(0): Leaving test case "array_literal_6"; testing time: 1802382us
smtCheckerTests/types/array_aliasing_storage_3.sol(0): Leaving test case "array_aliasing_storage_3"; testing time: 4467622us
smtCheckerTests/types/array_static_aliasing_storage_5.sol(0): Leaving test case "array_static_aliasing_storage_5"; testing time: 3046472us
smtCheckerTests/types/array_aliasing_storage_2.sol(0): Leaving test case "array_aliasing_storage_2"; testing time: 5152388us
smtCheckerTests/types/array_literal_7.sol(0): Leaving test case "array_literal_7"; testing time: 2241883us
smtCheckerTests/types/array_aliasing_memory_2.sol(0): Leaving test case "array_aliasing_memory_2"; testing time: 4434774us
smtCheckerTests/types/array_dynamic_2.sol(0): Leaving test case "array_dynamic_2"; testing time: 1007354us
smtCheckerTests/types/fixed_bytes_access_3.sol(0): Leaving test case "fixed_bytes_access_3"; testing time: 3465049us
smtCheckerTests/types/struct_array_branches_2d.sol(0): Leaving test case "struct_array_branches_2d"; testing time: 7341874us
smtCheckerTests/special/tx_data_immutable.sol(0): Leaving test case "tx_data_immutable"; testing time: 1929210us
smtCheckerTests/special/range_check.sol(0): Leaving test case "range_check"; testing time: 1657734us
smtCheckerTests/special/many.sol(0): Leaving test case "many"; testing time: 3206540us
smtCheckerTests/special/block_vars_chc_internal.sol(0): Leaving test case "block_vars_chc_internal"; testing time: 1040398us
smtCheckerTests/special/msg_data.sol(0): Leaving test case "msg_data"; testing time: 1920023us
smtCheckerTests/special/time_units.sol(0): Leaving test case "time_units"; testing time: 1573728us
smtCheckerTests/special/many_internal.sol(0): Leaving test case "many_internal"; testing time: 3756885us
smtCheckerTests/special/msg_sig.sol(0): Leaving test case "msg_sig"; testing time: 1812033us
smtCheckerTests/function_selector/function_types_sig.sol(0): Leaving test case "function_types_sig"; testing time: 1783240us
smtCheckerTests/invariants/aon_blog_post.sol(0): Leaving test case "aon_blog_post"; testing time: 1676373us
smtCheckerTests/invariants/loop_nested_for.sol(0): Leaving test case "loop_nested_for"; testing time: 1678482us
```

**Comment by chriseth** [comment]
The windows machine has 4 CPUs, so we should parallelize the tests there as well.

**Comment by chriseth** [comment]
It should also be easy to run the cli tests in parallel

**Comment by chriseth** [comment]
Creating the bytecode artefacts takes 8 minutes on all architectures, but it's two runs, so at least that should go down to 4

**Comment by chriseth** [comment]
t_archlinux_soltest could be parallelized

**Comment by chriseth** [comment]
If the above are implemented, we should be able to go down to 20 minutes for a full run.

**Comment by chriseth** [comment]
Turns out we can even use parallelism on windows...

**Comment by chriseth** [comment]
osx seems to run into "concurrency limit'. I'm reducing the concurrency for this PR, we can take a look another time.

**Comment by chriseth** [comment]
Interesting: CircleCI shows failed tests but does not flag the run as failed: https://app.circleci.com/pipelines/github/ethereum/solidity/21361/workflows/0c1f2e54-46b0-4016-8ed5-df5f03fdc7fe/jobs/937218

**Comment by chriseth** [comment]
This is now working as expected and ready for review.

**Review by ekpyron — APPROVED** [review]

**Pull request merged**
