### PR TITLE
Add missing word to examples doc explainer

### PR DESCRIPTION
**Pull request by jbn**

### CODE REVIEW

**Review by leonardoalt — APPROVED** [review]
Thanks!

**Review by leonardoalt — CHANGES_REQUESTED** [review]
Ah, the style checker is complaining about trailing whitespaces in all lines but the last one. Could you remove them?

**Comment by jbn** [comment]
Oops. Sorry about that. Force pushed the compliant update.

**Review by leonardoalt — APPROVED** [review]
Thanks again!

**Pull request merged**
