### PR TITLE
Make memory addresses wrap in interpreter.

### LINKED ISSUE #7336: [yul] Undefined behavior for loads to and stores from u256(-31) to u256(-1)?
## Description

Please see https://github.com/ethereum/solidity/pull/7330#issuecomment-527377730

Should there be an exception thrown (or some form of user visible error/warning message) when the machine or hand-written code like the following 

```
{
  mload(0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
  mstore(0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
  sload(0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
  sstore(0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)
}
```

I suppose sstores and sloads are fine because storage is a key value store? The yul interpreter "writes" and "reads" zeroes to and from bytes outside the addressable range.

Essentially 

https://github.com/ethereum/solidity/blob/dce52509b4be05fe090c6cf5702b04159946c930/test/tools/yulInterpreter/EVMInstructionInterpreter.cpp#L451

the `accessMemory` ceils `msize` to `u256(-1)` and tells the caller that the memory is **not** accessible. Subsequently, most callers return zero.

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/7336

### CODE REVIEW

**Review by ekpyron — COMMENTED** [review]
I guess it's not too important, but I just had a look at the yellowpaper... it looks to me like memory size is stored as word count there - and the msize opcode returns 32 times that word count modulo 2^256... so strictly speaking setting msize to -1 is not the same... should we reproduce that?

**Comment by ekpyron** [comment]
For that matter, they also wrap memory around to zero instead of extending beyond 2^256...

**Comment by ekpyron** [comment]
Hm... I think the yellowpaper might actually not be entirely precise for this case...

**Comment by chriseth** [comment]
It looks a little weird to me, but wrapping could also be compatible with the optimizer, since it checks for `abs(a-b) < 32`.

**Comment by ekpyron** [comment]
Ah, the yellowpaper is hard to read there, but it is in fact precise - if I understand it correctly, then MSIZE would actually return 32 after such a write and the memory offsets would warp around to zero. However, the gas cost is still based on their mu_i, which is a word count and therefore can't wrap (for a moment I thought the gas calculation was wrong in the yellowpaper in this case, but it was me who was wrong there). We should probably do the same and internally keep the current word count instead of msize directly, but return ``(32*bigint(word_count)) & (bigint(1) << 256 - 1)`` as MSIZE? And of course use offsets modulo 2^256 for the memory writes and reads?

**Comment by chriseth** [comment]
I don't think we need to be that precise with msize, but I can change the store-behaviour to wrapping.

**Comment by chriseth** [comment]
Updated to add wrapping.

**Review by ekpyron — COMMENTED** [review]
Why not be precise about ``msize``? It'd actually simplify the code, wouldn't it?
```
bool EVMInstructionInterpreter::accessMemory(u256 const& _offset, u256 const& _size)
{
        m_state.msize = (bigint(_offset) + bigint(_size) + 31) / 32;
        return _size <= 0xffff;
}
```
No need to return false in the wrapping case, right?
And
```
case Instruction::MSIZE:
  return (bigint(m_state.msize) * 32) & u256(-1);
```
isn't too bad either, is it?
Or would that have any other side effects?


I'm fine with merging either way in any case, though.

**Comment by chriseth** [comment]
I mainly don't think that `msize` should return 32 if we `mstore` to `u256(-31)`.

**Review by ekpyron — APPROVED** [review]
Ok well - that's a fair point - we should probably fix the yellow paper in that regard then, though (resp. at least file an issue) - it's merely academic anyways, since no client even stores memory size with more than 64 bits and gas costs will prevent any of that from ever happening anyways...

**Review by bshastry — APPROVED** [review]
LGTM

**Pull request merged**
