### PR TITLE
Update picosha2 from upstream

### LINKED ISSUE #8119: Update libdevcore/picosha2.h
The upstream version https://github.com/okdshin/PicoSHA2/blob/b699e6c900be6e00152db5a3d123c1db42ea13d0/picosha2.h has some changes we might want to use.

### PR DESCRIPTION
**Pull request by Marenz**
fixes #8119

### CODE REVIEW

**Comment by stackenbotten** [comment]
There was an error when running `chk_coding_style` for commit `08b58db70f2a5cd901f69df61dbe81876b4dc2fd`:
```
Coding style error:
 libsolutil/picosha2.h:197:void bytes_to_hex_string(const InContainer& bytes, std::string& hex_str)
 libsolutil/picosha2.h:211:std::string bytes_to_hex_string(const InContainer& bytes)
 libsolutil/picosha2.h:321:inline void get_hash_hex_string(const hash256_one_by_one& hasher, std::string& hex_str)
 libsolutil/picosha2.h:328:inline std::string get_hash_hex_string(const hash256_one_by_one& hasher)
 libsolutil/picosha2.h:393:void hash256(const InContainer& src, OutIter first, OutIter last)
 libsolutil/picosha2.h:399:void hash256(const InContainer& src, OutContainer& dst)
 libsolutil/picosha2.h:430:inline void hash256_hex_string(const std::string& src, std::string& hex_str)
 libsolutil/picosha2.h:436:void hash256_hex_string(const InContainer& src, std::string& hex_str)
 libsolutil/picosha2.h:442:std::string hash256_hex_string(const InContainer& src)
 libsolutil/picosha2.h:42:static const size_t k_digest_size = 32;
 libsolutil/picosha2.h:273: private:
 libsolutil/picosha2.h:348: OutIter last2, int buffer_size, std::input_iterator_tag)
 libsolutil/picosha2.h:407: std::vector<uint8_t> ret(32);
 libsolutil/picosha2.h:408: hash256(_src.begin(), _src.end(), ret.begin(), ret.end());
 libsolutil/picosha2.h:409: return ret;

```
Please check that your changes are working as intended.

**Comment by leonardoalt** [comment]
It somehow looks different from mainstream?

**Comment by Marenz** [comment]
I adjusted for our code style and formatting and I added one wrapper function that we used but that didn't exist in upstream (anymore?). I don't recall which one that was, though

**Comment by Marenz** [comment]
I also reordered things like headers to cause the smallest possible diff

**Comment by chriseth** [comment]
Please don't adjust imported files for coding style.

**Comment by Marenz** [comment]
well, the existing file was also adjusted so I just kept that tradition. If we don't adjust it then we need to specifically exclude it from the check script

**Comment by Marenz** [comment]
Added the file as little modified as possible now. Only change is that I added a wrapper function:
```
template <typename RaContainer>
std::vector<uint8_t> hash256(RaContainer const& _src)
{
       std::vector<uint8_t> ret(32);
       hash256(_src.begin(), _src.end(), ret.begin(), ret.end());
       return ret;
}
```
Modified the check script to skip that file

**Review by chriseth — APPROVED** [review]

**Pull request merged**
