### PR TITLE
DOCS: Docs split

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
This PR closes https://github.com/ethereum/solidity/issues/5396 and splits some longer docs into smaller files.

Reflects latest changes, although the diff of course is vastly different as there are new files. Probably easiest to checkout locally and test a build. I took a logical section approach to splitting, some are longer than others, and I left other files that are already not that long. It may be that we split more in the future, or split more now.

I am happy to communicate these changes to translators, active forks etc, and handle merging any pull requests that come in after these changes.

### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [x] New tests have been created which fail without the change (if possible)
- [x] README / documentation was extended, if necessary
- [x] Changelog entry (if change is visible to the user)
- [x] Used meaningful commit messages

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
Wasn't getting these errors before. Investigating

**Comment by ChrisChinchilla** [comment]
My tests now passing, not sure about AppVeyor.

**Comment by chriseth** [comment]
Could you please split one file per commit? The first commit just adds files without removing somewhere, and thus this might make it hard to track changes.

**Comment by ChrisChinchilla** [comment]
OK @chriseth unpicking things and re-comitting got slightly messy, but I think this is it. I also re-added changes from https://github.com/ethereum/solidity/commit/af3e6db038c0ef2ce847537129e19deaec3c906a that came in after I last pushed here, which is the reason behind that conflict showing. In this case, it's hard to resolve it as things change so much.

**Comment by chriseth** [comment]
The first commit still only contains additions.

**Comment by chriseth** [comment]
What about creating one pull request per file to split?

**Comment by ChrisChinchilla** [comment]
@chriseth I tried removing those first commits and they kept coming back, will try again.

I had a feeling you might ask for seperate PRs for each change, that's going to need a lot of unpicking and generate a lot of PRs, but it's possible.

**Comment by ChrisChinchilla** [comment]
@chriseth After attempting to fix a lot of merge conflicts, I think I will just start these PRs again afresh.

**Pull request closed without merging**
