### PR TITLE
[BREAKING] Version 0.5.0

### PR DESCRIPTION
**Pull request by chriseth**
This PR will be updated with breaking changes to be merged when version 0.5.0 is ready.

### CODE REVIEW

**Comment by chriseth** [comment]
I'm fine to either merge this to develop or fast-forward develop to this now. The former would create a multi-merge, the latter not.

**Comment by axic** [comment]
Good news everyone: we've finally agreed on today's meeting and pulled the trigger to merge the first 0.5.0 changes to `develop`. This officially starts the release cycle for 0.5.0. Hooray! 😉

**Comment by axic** [comment]
@chriseth can you delete the `050` branch? It won't le me to do it for some reason.

**Comment by chriseth** [comment]
"there is an open pull request that depends on it"

**Comment by axic** [comment]
Yeah, but there's none I could find.

**Comment by axic** [comment]
Found it, it was #4158

**Pull request merged**
