### PR TITLE
[SolYul] Copy byte arrays from storage to storage.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by mijovic** [comment]
Nice. 
Do you think we should maybe add more tests maybe structs containing `bytes` array.
It activated only one tests, it's a bit suspicious?

Also, you will need to change `yul_unimplemented` test in Command line tests, as this was used as unimplemented test so far

**Comment by chriseth** [comment]
I'll finish all the other "copy to storage" functions first, then we'll see if we need more tests.

**Comment by chriseth** [comment]
It could also be that some of these tests are still in EndToEndTests.

**Comment by mijovic** [comment]
I think, once `yul_unimplemented` test is changed this can be merged. 

Also, some of the test that will be moved from end to end will be probably activated, but it can be done when moving those tests. Also, maybe some of tests from #10287 can be already activated.

**Comment by chriseth** [comment]
Changed the unimplemented test.

**Comment by chriseth** [comment]
Now hopefully really fixed.

**Comment by chriseth** [comment]
Activated 3 more tests and fixed the commandline test stripping of file names.

**Review by mijovic — APPROVED** [review]

**Pull request merged**
