### PR TITLE
Validate each tuple literal

### LINKED ISSUE #2913: Crash with unused large value in tuple assignment
```
contract C {
	function f() {
		uint x;
		(x, ) = (1, 1E1112);
	}
}
```

crashes with

```
solidity/libsolidity/ast/Types.cpp(977): Throw in function virtual u256 dev::solidity::RationalNumberType::literalValue(const dev::solidity::Literal *) const
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: Integer constant too large.
[dev::tag_comment*] = Integer constant too large.
```

### PR DESCRIPTION
**Pull request by axic**
Fixes #2913.

### CODE REVIEW

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
We cannot check each tuple element, because in intermediate expressions, rational numbers are allowed to be outside of the valid range. Since each parenthesized expression is a tuple (violating the `A` part in AST), we can only do that for actual tuples, and even that is not the best solution. Ideally, we only check at the point where we go from rational number or rational number inside tuple to non-rational number.

**Comment by axic** [comment]
Yep, we discussed this. I started moving this to expression visitor, but ran into issues. I can push the half baked code.

**Comment by chriseth** [comment]
@axic I would say the current state of the PR is still an acceptable solution. What do you think?

**Comment by axic** [comment]
I see now the changes. I cannot accept it since I've created the PR.

**Pull request merged**
