### PR TITLE
Update ossfuzz's README.md

### PR DESCRIPTION
**Pull request by haoyang9804**
This update is based on this discussion: https://github.com/ethereum/solidity/issues/15068
cc @bshastry

### CODE REVIEW

**Review by bshastry — APPROVED** [review]
LGTM, thank you :+1:

**Comment by bshastry** [comment]
@haoyang9804 Could you please rebase on upstream develop?

**Comment by haoyang9804** [comment]
> rebase on upstream develop?

done. I have synced with the latest upstream.

**Comment by r0qs** [comment]
The CI error is unrelated, so I'm merging it :)

**Pull request merged**
