### PR TITLE
Merge develop to breaking

### PR DESCRIPTION
**Pull request by hrkrshnn**

### CODE REVIEW

**Comment by cameel** [comment]
This fails in `t_ubu_ossfuzz`:
```
Running: /tmp/solidity-fuzzing-corpus/solc_ossfuzz_seed_corpus/test_sol/test_78d1e5d3481129a9db788794ffedcfce09d62feab62584ac80b2c1c74866496e_testsmt_sol.sol
libc++abi: terminating with uncaught exception of type std::out_of_range: map::at:  key not found
```
```
    #13 0x15e1fb0 in solidity::frontend::smt::BlockchainVariable::member(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const /root/project/libsolidity/formal/SymbolicState.cpp:56:47
```

I think it's the bug reported in #11587.

I wonder why `t_ubu_ossfuzz` is running here though. In the CircleCI config it's set to run nightly and even then only on `develop_060` and `develop`.

**Comment by hrkrshnn** [comment]
@cameel I think for some reason the CI checks are the same as the nightly. All the tests (except t_ubu_ossfuzz) were passing immediately after creating the PR.

**Review by cameel — APPROVED** [review]

**Comment by cameel** [comment]
Looks like auto-merge does not get triggered due to the `This branch is out-of-date with the base branch` warning. Merging manually.

**Comment by cameel** [comment]
Wait, I can't even merge manually :)

**Pull request merged**
