### PR TITLE
Introduce IndentedWriter

### PR DESCRIPTION
**Pull request by axic**
Split off #2233.

### CODE REVIEW

**Comment by axic** [comment]
@chriseth do you want to change this PR the way you'd like it to work?

**Comment by chriseth** [comment]
Sorry, what is this about?

**Comment by axic** [comment]
See #2233, it is used to write the web assembly output.

**Comment by axic** [comment]
Though thinking about it could also be used in Assembly `streamAsm`.

**Review by chriseth — APPROVED** [review]

**Pull request merged**
