### PR TITLE
Some well-formedness checks for the Yul AST.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Review by axic — CHANGES_REQUESTED** [review]
Any tests? :)

**Comment by chriseth** [comment]
We usually do not test assertions. Do you really want to add that?

**Comment by chriseth** [comment]
Or do you want me to add some source code that would violate the assertion and check that it is properly reported earlier?

**Comment by axic** [comment]
> We usually do not test assertions. Do you really want to add that?

That is correct, however I feel this is a slightly different scenario since we have so many parts (aka all the optimiser stages) which can generate Yul AST, it would make sense verifying these assertions actually work properly.

> Or do you want me to add some source code that would violate the assertion and check that it is properly reported earlier?

We should have a good coverage of that but verifying that all of these are caught by the parser would be a good task.

**Review by leonardoalt — APPROVED** [review]

**Pull request merged**
