### PR TITLE
[Docs] Fix operator docs to use an actually convertible type when describing how common type is chosen

### LINKED ISSUE #13144: [Docs] Incorrect example in Operators section of Types
## Page

https://docs.soliditylang.org/en/v0.8.14/types.html#operators

## Abstract

Given example is incorrect as it doesn't compile. `uint8` doesn't implicitly convert to `int32`.

## Pull request

Can make type of `z` to be `uint32`.

### PR DESCRIPTION
**Pull request by vdusart**
Fixes #13144

### CODE REVIEW

**Comment by wechman** [comment]
@cameel We did want to revisit implicit type conversions rules, didn't we?

**Comment by cameel** [comment]
Yeah. Though in the short term, we should update the docs to reflect the current rules. As is the docs are apparently wrong.

**Comment by wechman** [comment]
@vdusart Please link PR to the issue. You can do that by putting "fixes #13144" to the PR description.

**Comment by cameel** [comment]
@wechman We should have an issue for tweaking the implicit conversion rules. Could you create one and summarize the current discussion there (including any open questions that still need decisions)?

**Comment by vdusart** [comment]
@wechman Yes, I do that

**Comment by wechman** [comment]
@vdusart  Thank you!
@cameel Sure, I will create an issue.

**Review by wechman — APPROVED** [review]
LGTM

**Pull request merged**
