### PR TITLE
DOCS: Add new resource section to learn Solidity

### PR DESCRIPTION
**Pull request by treyhuffine**
### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [x] New tests have been created which fail without the change (if possible)
- [x] README / documentation was extended, if necessary
- [x] Changelog entry (if change is visible to the user)
- [x] Used meaningful commit messages

### Description
The Solidity documentation is fantastic, but I felt a little unsure on where to go next to learn more Solidity / web3.js. This commit adds a resource to give developers a path to easily continue studying and continue their momentum without getting lost searching for additional materials.

ref: https://github.com/ethereum/solidity/pull/5330

### CODE REVIEW

**Comment by erak** [comment]
Thanks for the contribution! Unfortunately, I don't think that we should link external tutorials in the Solidity documentation (for now). There're several reasons for that, but first and foremost users could simply search the internet for tutorials. Secondly, adding random learning platforms such as gitconnected.com, could lead to future discussions about why not to add one or the other to this list. I also do think that referring to platforms that offer paid tutorials is not the right way to go for an open-source project that aims for inclusiveness.

On the other hand, I do like the idea of linking to learning resources in general, but only if they're being created and maintained by either the Solidity team or people working in the Ethereum ecosystem. This would also lead to a more cohesive experience for the users. There is an idea flowing around of creating a learning tour for Solidity in the fashion of https://nixcloud.io/tour/. But this might need some effort to be put in.

**Comment by treyhuffine** [comment]
Thanks @bit-shift, that's a ton of great points. Based on my personal experience, I definitely think having some guide to provide insight on what resources are available is essential, so I’m excited to hear that is coming. I personally spent hours searching the internet for resources when I first started learning Solidity, and I think not being able to find content is a huge barrier of entry to many developers.

It looks like the nixcloud tour is similar to the Go tour https://tour.golang.org/welcome/1 which I found very valuable as a starting point. I think it's a great introduction, but those tours do leave some questions on what to do after learning the basics of the a language - how do you use it in a practical setting, how can to use a smart contract as a data store for decentralized applications, how do you connect client code to a smart contract, etc.

I think having a user-controlled resource tends to provide the best results such as a wiki-style or like gitconnected.com where solidity developers can submit tutorials and vote them. From my experience, when you rely on one person or a small team of people to maintain a list, it tends to be slow to adapt and update, and it can often lead to the resources being outdated and a bad experience for the people that need them.

I appreciate the thoughtful response and consideration for the PR. I think there's an immediate need for guidance on learning Solidity, so my personal opinion would be provide this as a short term solution to see how it goes. Then as things progress, the Solidity team can assess if it's a beneficial experience to use an outside resources such as this, or bring the learning resources inside the Solidity ecosystem to be maintained.

**Comment by erak** [comment]
@treyhuffine I can definitely see the need for an intermediate solution, but I'm still not convinced that we should add resources from random providers to our documentation. 
For now I'd propose to add 2 links:

1. https://ethernaut.zeppelin.solutions/
This tutorial is maintained by OpenZeppelin and created out of contributions by the community. It provides everything you need for getting started with web3 / Solidity development.

2. https://truffleframework.com/tutorials/pet-shop
This is one of the tutorials that they provide and I think it can also be a good starting point to get started with dApp development.

What do you think? I picked these because both Zeppelin and Truffle are closely connected to / part of the ecosystem.

P.S.: I kicked of this: https://github.com/bit-shift/solidity-tour/. As of now it is just a prototype that could help us to assess the requirements of such a tour. The most important design goal was to make task contribution easy. As soon as some major performance bottlenecks are fixed, I'd really like to share this with more people from the community and see how it will be perceived. Would you be interested in participating?

**Comment by erak** [comment]
@treyhuffine Do you have more opinions on the Zeppelin / Truffle resources? I think those are the only external ones that I could imagine to add to the documentation.

**Comment by treyhuffine** [comment]
@bit-shift the Zeppelin and Truffle tutorials are great, I think it makes a lot of sense to include them given their connection to the community. I think the one thing that still may lacking is showing how you can build modern web/JavaScript apps by using Ethereum as the backend. I'm biased because I am a web developer by trade, but once I discovered the power of Eth, it's what really got me excited to start diving into Solidity (and where I found the lack of clear understanding of how to learn it). When I was able to build a React application and plug it into the EVM for my data/business logic, that's when I finally understood the true potential for the technology and became a big supporter. I totally understand your reasoning for being cautious about what to include in the official docs, and I won't debate you there because I think your reasoning is valid. However, I just think the potential users is very large if they can be reached and they understand what they can learn and how to get there. I want to find a way to make it easy for developers to make the same discovery that I did about the technology. If people have a better understanding of what they are able to build and how to learn it, I think adoption from developers will increase and ultimately create more practical applications/products using Ethereum. I'm not saying this is the perfect solution, but I'm not really sure what would be better at the moment.

**Comment by chriseth** [comment]
@treyhuffine thanks for your understanding! The main problem I see with the linked site is that it is a meta site with only few tutorials. I think we should rather curate the tutorials here. Also, the most "upvoted" link by far on that site is a tutorial on a website that throws 3 big banners at me and urges me to buy at a discout with only "one day left" and the discount in "89%". I really don't want to recommend sites that have such discount policies.

**Pull request closed without merging**
