### PR TITLE
Rename asm json import command-line tests

### PR DESCRIPTION
**Pull request by aarlt**
See https://github.com/ethereum/solidity/pull/14612#discussion_r1493850913

### CODE REVIEW

**Comment by nikola-matic** [comment]
@aarlt can you fetch fresh develop and rebase - the fix for `win_pyscripts` went in last week I believe.

**Review by nikola-matic — DISMISSED** [review]

**Comment by nikola-matic** [comment]
@aarlt feel free to merge if there's no dependencies.

**Comment by ekpyron** [comment]
Too late for merging - now it needs a rebase or sth :-). It does pay of to just merge "clearly harmless" stuff like this right with approving, resp. setting it to auto-merge (don't overdo that, but just test-renaming is safe-enough...)

**Comment by GAMECHANGE** [comment]
k

**Review by GAMECHANGE — COMMENTED** [review]
nive

**Comment by cameel** [comment]
If you're renaming these tests it would probably make sense to also rename the `standard_import_evmasm_...` ones to `standard_import_asm_json_...` since they're testing the same feature, just via Standard JSON.

**Review by cameel — APPROVED** [review]

**Pull request merged**
