### PR TITLE
Run ASAN on all PRs and also run commandline tests.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by chriseth** [comment]
Disabled for PRs again, but added `cmdlinetests.sh` as additional run.

**Comment by bshastry** [comment]
The ASAN tests CI is currently disabled?

**Comment by chriseth** [comment]
Just re-activated the run on this PR again because @christianparpart found out that the previous failure seems to be due to a wrong binary being used.

**Comment by chriseth** [comment]
Argh, it turned out it was not properly rebased onto develop :)

**Review by bshastry — APPROVED** [review]
LGTM

**Pull request merged**
