### PR TITLE
Fix literals with exponents with mantissa of zero.

### LINKED ISSUE #4477: Incorrect way of processing data calculation leading solc dos hang
Incorrect way of processing data calculation leading solc dos hang
data calculation liking a=0e123456789
[0e12345678_hang_compiler.zip](https://github.com/ethereum/solidity/files/2183697/0e12345678_hang_compiler.zip)

### PR DESCRIPTION
**Pull request by ekpyron**
Fixes #4477.

### CODE REVIEW

**Comment by ekpyron** [comment]
I also renamed ``base`` to ``mantissa`` here, since it's not a base, but a mantissa. Do you think we need a Changelog entry for this?

**Comment by ekpyron** [comment]
I also split the long test case into a succeeding and a failing one in the second commit.

**Comment by chriseth** [comment]
Looks good! I think we should add a changelog entry, though.

**Comment by ekpyron** [comment]
@chriseth Added a changelog entry.

**Review by chriseth — APPROVED** [review]

**Comment by lazaridiscom** [comment]
e8e5e12 - bugfix, renaming, refactoring, redesign: all within one(!) commit.

This is far too dense.

**Comment by chriseth** [comment]
I would say it is totally fine if the diff still easily fits one page.

**Comment by lazaridiscom** [comment]
> I would say it is totally fine if the diff still easily fits one page.

This is not about fitting or not, its about

* allow others to understand the intentions of the programmer.
* allow others to fully understand without much effort.
* avoid introducing new hidden bugs.

Or differently: You simply don't compress so much change into one chunk, this makes reviewing/understanding difficult, and additionally it can introduce new (hidden) flawed behaviour.

**Pull request merged**
