### PR TITLE
On the hunt for the gas test failure

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by chriseth** [comment]
Locally, I get `Used gas: 129829` - on circle it is `Used gas: 129765`. The output code is identical, but I may be using a different version of aleth.

**Comment by chriseth** [comment]
Difference in gas cost is 64. In some other run I had a difference of 128.

**Comment by chriseth** [comment]
Version of aleth locally and on circleci is identical.

**Comment by chriseth** [comment]
Ok, this seems to be connected to the metadata hash - each zero byte is exactly 64 gas.

**Comment by chriseth** [comment]
Locally:
```
CREATE e694556e2986c6732c6a749a4569755744440604:
 in:      6080604052348015600f57600080fd5b5061011a8061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806326121ff014602d575b600080fd5b60336035565b005b60405162461bcd60e51b8152600401604b906054565b60405180910390fd5b6020808252605b908201527f4e6f7420417574686f72697a65642e20546869732066756e6374696f6e20636160408201527f6e206f6e6c792062652063616c6c65642062792074686520637573746f64696160608201527f6e206f72206f776e6572206f66207468697320636f6e74726163740000000000608082015260a0019056fea365627a7a723058207f4eca77d136356708db2ee0c393279fd1911770818c52c0e0fe5f867a36fbb06c6578706572696d656e74616cf564736f6c63430005090040
 out:     6080604052348015600f57600080fd5b506004361060285760003560e01c806326121ff014602d575b600080fd5b60336035565b005b60405162461bcd60e51b8152600401604b906054565b60405180910390fd5b6020808252605b908201527f4e6f7420417574686f72697a65642e20546869732066756e6374696f6e20636160408201527f6e206f6e6c792062652063616c6c65642062792074686520637573746f64696160608201527f6e206f72206f776e6572206f66207468697320636f6e74726163740000000000608082015260a0019056fea365627a7a723058207f4eca77d136356708db2ee0c393279fd1911770818c52c0e0fe5f867a36fbb06c6578706572696d656e74616cf564736f6c63430005090040
 tx hash: 0x99879104cef343c02d575515049e1a060387b8aaa179c85b1b16ac0f90e685cf
```

CircleCI:
```
CREATE b08c63cf007329ed0d26405f0e560ce2487e7390:
 in:      6080604052348015600f57600080fd5b5061011a8061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806326121ff014602d575b600080fd5b60336035565b005b60405162461bcd60e51b8152600401604b906054565b60405180910390fd5b6020808252605b908201527f4e6f7420417574686f72697a65642e20546869732066756e6374696f6e20636160408201527f6e206f6e6c792062652063616c6c65642062792074686520637573746f64696160608201527f6e206f72206f776e6572206f66207468697320636f6e74726163740000000000608082015260a0019056fea365627a7a72305820b7a7c986deb46b330f4320dc31725059fb9ee7f4a6d5b7c61a8607e100f2daa86c6578706572696d656e74616cf564736f6c63430005090040
 out:     6080604052348015600f57600080fd5b506004361060285760003560e01c806326121ff014602d575b600080fd5b60336035565b005b60405162461bcd60e51b8152600401604b906054565b60405180910390fd5b6020808252605b908201527f4e6f7420417574686f72697a65642e20546869732066756e6374696f6e20636160408201527f6e206f6e6c792062652063616c6c65642062792074686520637573746f64696160608201527f6e206f72206f776e6572206f66207468697320636f6e74726163740000000000608082015260a0019056fea365627a7a72305820b7a7c986deb46b330f4320dc31725059fb9ee7f4a6d5b7c61a8607e100f2daa86c6578706572696d656e74616cf564736f6c63430005090040
 tx hash: 0x3d995aced9317ed6c593cf0a928e6cab04d8c7fc620978d973439b7f0d677198
```

The difference is an additional zero byte in the `auxdata`, which I think is the cbor-encoded metadata hash.

**Comment by ekpyron** [comment]
The difference is in the ``bzzr0`` hash - if it's expected that the input differs, then we can't do anything about random zeros, but I expect this *should* actually be deterministic (what's the point otherwise?) I'll try adding some more output here...

**Comment by ekpyron** [comment]
Ok - it's ``VersionStringStrict`` that ends up in the input for the ``bzzr0`` hash, which then might randomly contain different numbers of zeros. I think the best solution to this is to take into account the numbers of zeros in the ``bzzr0`` hash in the gas estimation rather than trying to fake the ``VersionStringStrict`` of a release (that's probably impossible, since ``VersionStringStrict`` will contain the commit hash of the release commit).

**Pull request closed without merging**
