### PR TITLE
Upgrade evmone to 0.2.0 and remove manual install of ethash/intx in the docker image

### PR DESCRIPTION
**Pull request by axic**
I'm still wondering why were the ethash/intx downloads needed? Didn't evmone 0.1.0 properly download them?

### CODE REVIEW

**Comment by Marenz** [comment]
So you're saying they are part of the evmone submodules?

**Comment by axic** [comment]
> So you're saying they are part of the evmone submodules?

They are downloaded by cmake via hunter.

**Comment by bshastry** [comment]
> I'm still wondering why were the ethash/intx downloads needed? Didn't evmone 0.1.0 properly download them?

iirc, the evmone build system uses a cmake plugin called hunter which makes it difficult to control build flags passed to deps (such as ethash and intx). At the time I wrote these lines for the docker image, I couldn't find a way to cleanly install evmone and all its deps via a single cmake command so I decided to do it manually as it is done.

@chfast I remember we had a discussion on gitter about this. Please correct me if I'm wrong.

**Comment by axic** [comment]
Isn't it all statically linked so that none of the deps need to be installed?

**Comment by bshastry** [comment]
> Isn't it all statically linked so that none of the deps need to be installed?

iirc, at least for 0.1.0 this is not the case. That might explain why I had to link the deps manually here

https://github.com/ethereum/solidity/blob/52a9de83f320680a2fd58b4b497dfed26b9c3e5d/test/tools/ossfuzz/CMakeLists.txt#L74

**Comment by bshastry** [comment]
Tested this PR locally: I can confirm that neither `intx` nor `ethhash` is installed by evmone's cmake invocation (in the prefix location e.g., `/usr`) if the evmone shared library is built. Here we need to stick to the shared library build because `soltest` requires it.

What we need imo is something like this (see https://github.com/ruslo/hunter/issues/274) so that deps built by hunter are also installed in `CMAKE_INSTALL_PREFIX`

**Comment by ekpyron** [comment]
[the SMT failures should vanish, if this is rebased... I hope :-)]

**Comment by leonardoalt** [comment]
Not yet ;) need to merge https://github.com/ethereum/solidity/pull/7694

**Comment by ekpyron** [comment]
> Not yet ;) need to merge #7694

This targets develop, so it should be fine even before #7694 :-).

**Review by christianparpart — APPROVED** [review]
I actually wrote the first Dockerfiles for CircleCI, and I included those because evmone complained that those where missing. It may be totally possible that I forgot to check whether they were also present as git submodules, but I just picked them quickly via some git-clone's.

@axic, apart from the evmone 0.2.0 version bump (LGTM), thanks for the cleanup!

**Comment by ekpyron** [comment]
By the way: does stock ubuntu clang really not work against stock ubuntu boost and we *have* to build it from source here?

**Comment by bshastry** [comment]
Closing this PR because #7700 supersedes it

**Pull request closed without merging**
