### PR TITLE
Added a couple of resources

### PR DESCRIPTION
**Pull request by johnfawole**

### CODE REVIEW

**Comment by nikola-matic** [comment]
Whilst I'm not against having a resources section, I am against putting links to third party youtube/written tutorials, as I really don't think the language docs are a place for that. Let's see what the rest of the team thinks.

**Comment by johnfawole** [comment]
> Whilst I'm not against having a resources section, I am against putting links to third party youtube/written tutorials, as I really don't think the language docs are a place for that. Let's see what the rest of the team thinks.

Oh, I only added the resources because I read above that they can be included. It's fine if you do not want them.

But the Solidity by Example documentation is officially endorsed. Maybe we can limit it to just that.

Let me hear your thoughts.

**Comment by nikola-matic** [comment]
> > Whilst I'm not against having a resources section, I am against putting links to third party youtube/written tutorials, as I really don't think the language docs are a place for that. Let's see what the rest of the team thinks.
> 
> 
> 
> Oh, I only added the resources because I read above that they can be included. It's fine if you do not want them.
> 
> 
> 
> But the Solidity by Example documentation is officially endorsed. Maybe we can limit it to just that.
> 
> 
> 
> Let me hear your thoughts.

I'm but one of many on the team, so let's wait to see what the others think.

Keep in mind that we might only get back to you in a week or two, since most of us are at Devcon.

**Comment by johnfawole** [comment]
Oh, that's true.

Take your time, and enjoy the conference. Haha.

**Comment by ekpyron** [comment]
Thank you very much for your effort, but as @nikola-matic already said, we don't endorse third-party links in the documentation (we don't have the resources to curate such a list properly, so we cannot start making exceptions). So I'm closing this PR.

**Pull request closed without merging**
