### PR TITLE
Fix iter_swap build issue

### LINKED ISSUE #12027: Compile ASTJsonConverter.cpp failed to "error C3861: 'iter_swap': identifier not found" and "error C2672: 'ranges::iter_swap': no matching overloaded function found"
Compile ASTJsonConverter.cpp failed to "error C3861: 'iter_swap': identifier not found" and "error C2672: 'ranges::iter_swap': no matching overloaded function found", can you help look? Thank you very much

**Environment**
- Compiler version: VS2019 (16.11.2)
- Operating system: Windows server 2016

**Reproduce steps:**
1. git clone https://github.com/ethereum/solidity
2. cd solidity
3. mkdir build_amd64
4. cd build_amd64
5. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DBoost_INCLUDE_DIR="F:\tools\boost_1_67_0\x64" ..
6. msbuild /p:Configuration=Release;Platform=x64 solidity.sln /t:Rebuild /m

**Error log:**
[msbuild_x64.log](https://github.com/ethereum/solidity/files/7231141/msbuild_x64.log)

**Error info:**
1. F:\solidity\build_mad64\deps\include\range/v3/algorithm/sort.hpp(92,25): error C3861: 'iter_swap': identifier not found (compiling source file F:\solidity\libsolidity\ast\ASTJsonConverter.cpp) [F:\solidity\build_mad64\libsolidity\solidity.vcxproj]
2. F:\solidity\build_mad64\deps\include\range/v3/algorithm/sort.hpp(92,25): error C2672: 'ranges::iter_swap': no matching overloaded function found (compiling source file F:\solidity\libsolidity\ast\ASTJsonConverter.cpp) [F:\solidity\build_mad64\libsolidity\solidity.vcxproj]

**Note:**
These errors is due to compile ASTJsonConverter.i (cl /EHsc /permissive- /std:c++20 /TP ASTJsonConverter.i) 
[ASTJsonConverter.i.zip](https://github.com/ethereum/solidity/files/7231159/ASTJsonConverter.i.zip)

### PR DESCRIPTION
**Pull request by Pospelove**
fixes #12027

Hey! Idk if you strictly require using range-v3 sorting, but I hope you don't cause this simple fix can help MSVC users a lot

### CODE REVIEW

**Comment by ekpyron** [comment]
Thank you very much for the PR!

This seems to overlap with https://github.com/ethereum/solidity/pull/12802 (for which we still need to investigate some test changes due to having to update boost). However, there I actually need some additional changes...

Against which version of MSVC have you checked this? Our CI runs against MSVC 2019 and works, while https://github.com/ethereum/solidity/pull/12802 attempts to fix builds for MSVC 2022.

https://github.com/ethereum/solidity/issues/12027 we never got to reproduce, but if you can confirm that this happens for MSVC 2019 as well and that https://github.com/ethereum/solidity/pull/12802 fixes this, we can try to speed up https://github.com/ethereum/solidity/pull/12802.

**Comment by Pospelove** [comment]
Hey! Thanks for your answer! I use MSVC 2022 and yes #12802 seems to help. The main issue was with ASTJsonExporter.cpp and I see #12802 handles it the same way my small PR does.

please let me know if you need more info like exact compiler version ,etc

**Comment by ekpyron** [comment]
Alright, in that case I'd prefer https://github.com/ethereum/solidity/pull/12802 over this PR, since it actually makes sure this will keep working with a CI run.

The only thing left to do there is to check that some of the changes the newer boost version seems to trigger in our filesystem tests are harmless (that's the main reason that for https://github.com/ethereum/solidity/pull/12802 not being merged yet).

**Comment by ekpyron** [comment]
Actually, we can also go ahead and merge this PR, while waiting for the further analysis in https://github.com/ethereum/solidity/pull/12802.

**Review by ekpyron — APPROVED** [review]

**Comment by Pospelove** [comment]
Many thanks for your help!

**Pull request merged**
