### PR TITLE
[circleci] add t_ubu_asan_constantinople_clang

### PR DESCRIPTION
**Pull request by aarlt**

### CODE REVIEW

**Comment by chriseth** [comment]
Compile error.

**Comment by aarlt** [comment]
@chriseth I'm not sure about the error shown by asan. The strange thing is that the problem seem to be only happening with the used clang. I didn't checked the actual version, but the config use `ubuntu1904-clang-5` - if this means clang v5, the compiler is quite old. Also the `soltest` crashes are only happening with the clang compiled versions. Probably we just see a compiler bug here: we never see any problems with `gcc` and newer versions of `clang` seem to not detect any problems via `asan`. 

edit: ok.. `ubuntu1904-clang-5` is just the revision of the used docker image. however, could make sense to update `clang`.

**Comment by aarlt** [comment]
@leonardoalt @cameel what is your opinion about this?

**Comment by cameel** [comment]
It looks weird.

It reports that the memory was allocated somewhere inside `Scanner::reset(CharStream)`. The only allocation that happens there is `make_shared<CharStream>()`. But it says that the memory gets deallocated by `Object`'s destructor when its `shared_ptr<Block>` gets deleted - so by a completely different object. And this happens twice which is the direct cause of the error.

It all happens inside a test called `many_variables_few_uses` in `CompilabilityChecker.cpp`. The test calls a local `check()` function which, somewhere down the line, creates an instance of `AssemblyStack` and gives it a `Scanner` instance. `Scanner` allocates the `CharStream` as mentioned above. At first I suspected that it might be a `move()` gone wrong - a situation where `shared_ptr<CharStream>` gets moved but the original instance is still in use. But this does not seem to be the case. The only object that holds a `Scanner` here is `AssemblyStack` and it does not store it inside `Object`.

It's hard to figure out just with this output. Too bad I can't just run it locally and track down the part that causes it by commenting out parts of the test.

So I don't know if the error is spurious or not but I wouldn't write it off that easily. I did have a situation in yul-phaser where I was moving things wrong but it worked fine on GCC and was only caught on Clang in CI.

**Comment by aarlt** [comment]
@cameel I also had the impression that something is moved wrong. But I don't understand why this problem is not detectable with `gcc`'s `asan`, and also `asan` of newer versions of `clang` seem not detect anything.

**Comment by cameel** [comment]
And which clang version was used in this test?

**Comment by aarlt** [comment]
It should be the one shipped with ubuntu 19.04. I think its `clang version 8.0.0-3`. But I'm not very sure, because its a docker image that is used.

**Comment by leonardoalt** [comment]
Are we still using this PR/CI run to investigate the crash?

**Comment by leonardoalt** [comment]
ping @aarlt @cameel /\

**Comment by cameel** [comment]
That's a question to @aarlt. I try to look at it and provide some useful input if something new regarding those crashes comes up but I'm not actively working on it.

**Comment by aarlt** [comment]
@leonardoalt @cameel I didn't continue the investigations yet. But I found out that the problem seem to be clang8 related. I installed clang8 on my machine and if compiled with `asan`, the problem is always reproducible. I'm wondering why we see the problem only with clang8. Newer versions don't detect anything. It's probably a compiler problem - but the probability is super low from my point of view. Or we introduced somehow somewhere "undefined behaviour"  - and different compilers behave differently because of this.

**Comment by aarlt** [comment]
@leonardoalt after we fixed the underlying issue, we should add this to the our CI.

**Comment by leonardoalt** [comment]
> @leonardoalt @cameel I didn't continue the investigations yet. But I found out that the problem seem to be clang8 related. I installed clang8 on my machine and if compiled with `asan`, the problem is always reproducible. I'm wondering why we see the problem only with clang8. Newer versions don't detect anything. It's probably a compiler problem - but the probability is super low from my point of view. Or we introduced somehow somewhere "undefined behaviour" - and different compilers behave differently because of this.

But what compiler was the one used when we had these random `soltest` crashes?

**Comment by aarlt** [comment]
@leonardoalt clang8

**Comment by leonardoalt** [comment]
> @leonardoalt after we fixed the underlying issue, we should add this to the our CI.

@aarlt well, if it's a problem with `clang8` itself (since it works with newer versions), I don't think we should

**Comment by aarlt** [comment]
@leonardoalt probably we should update clang in our ci?

**Comment by aarlt** [comment]
@chriseth it looks like that the `soltest` crash is only related to clang8, so probably it may be a good idea to just update to a newer version of clang.

@bshastry would it be possible to update the docker image to include a newer version of clang?

**Comment by leonardoalt** [comment]
Needs rebase. Then we'll see what changes

**Review by leonardoalt — APPROVED** [review]
The tests pass now.
I'm personally in favor of adding the CI jobs, so I'm approving.
If anyone disagrees please dismiss my approval and comment.

**Pull request merged**
