### PR TITLE
Push bytecode of all test contracts to remote repository.

### PR DESCRIPTION
**Pull request by chriseth**
Still to do:
 - [x] tests for the optimizer

### CODE REVIEW

**Comment by chriseth** [comment]
The emscripten build seems to have a different metadata hash. I also had this problem locally, it was caused by a dirty checkout, so there was a `.mod` suffix in one of the versions.

**Comment by axic** [comment]
Can we change the report into a JSON? Would be easier to process from the outside.

**Comment by chriseth** [comment]
@axic actually I think "unix-style" formatted files are better, then you can use plain `diff` to process and do not have to parse them.

**Comment by axic** [comment]
Depends on the tool processing the output. What will be that tool?

**Comment by chriseth** [comment]
The tool is already in place: https://travis-ci.org/ethereum/solidity-test-bytecode/builds/212095113

**Comment by axic** [comment]
Can you squash some of the commits? Things like *try again*.

**Comment by chriseth** [comment]
@axic of course, once it is working.

**Comment by chriseth** [comment]
The only missing problem is that `emscripten` has a line
```
test_83f0aa75b311a45c431c12e757e19c7739832c9910b7cceac5a1660bb623d14d.sol: ERROR
```
while the others don't have that line.

**Comment by chriseth** [comment]
@axic ok, this should be the final version. We might still have a problem that windows and travis end up with different commit hashes, but that should be solved once we run this not on a pull request but on an actual repo push.

**Comment by chriseth** [comment]
Ah, the optimizer!

**Comment by chriseth** [comment]
OMG, it's working!

**Comment by chriseth** [comment]
@axic can this be merged?

**Review by axic — APPROVED** [review]

**Pull request merged**
