### PR TITLE
Copying structs and arrays from calldata to memory.

### LINKED ISSUE #8210: Experimental ABIEncoder fails to pass fixed-size calldata array to internal function
The basic scenario seems to require that an external function pass its fixed-size calldata to an internal function. One workaround is to use a public function instead of an external function.

Originally encountered on 0.5.13. Also happens on 0.5.16 and 0.6.2.

Minimum repro:
```
pragma solidity ^0.5.13;

pragma experimental ABIEncoderV2;

contract Parent {
    function internalFn(bytes[2] memory signatures) internal returns (bytes memory) {
    }
    function externalFn(bytes[2] calldata signatures) external returns (bytes memory) {
        return internalFn(signatures);
    }
}
```

The error is `InternalCompilerError: Variable size and position mismatch.`

This issue seems to be similar to https://github.com/ethereum/solidity/issues/7929.

Curiously, if you instead supply
```
pragma solidity ^0.6.2;

pragma experimental ABIEncoderV2;

contract Parent {
    function internalFn(bytes[2] memory signatures) internal {
    }
    function externalFn(bytes[2] calldata signatures) external {
        internalFn(signatures);
    }
}
```
then the error becomes
```
InternalCompilerError: I sense a disturbance in the stack: 1 vs 2
```

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/8210

### CODE REVIEW

**Comment by chriseth** [comment]
This is probably wrong because we might not know the base offset pointer, at least for statically-encoded types.

**Comment by ekpyron** [comment]
I may still be confused here... but for statically-encoded types ``abiDecode`` will just expect them to be encoded in place at the given offset - so that should work, right?
For dynamically-encoded types, however, on the stack we already followed the tail pointers, but (ABIFunctions.cpp:L226) will expect a pointer at the offset (relative to base offset zero) and try to follow that (which it shouldn't), right?
So for dynamically-sized types we'd at least need to use something like ``ABIFunctions::abiDecodingFunction`` directly, right? But that's not exactly right either - e.g. ``abiDecodingFunctionArray`` still expects the offset of the length on stack, but we're already past that and have both a pointer to the tail and a length on stack...
So what we basically need is (ABIFunctions.cpp:L1157+), with ``offset`` and ``length`` taken from stack, right?
I think what we need is *almost* abi decoding, but not exactly...
But yeah, I have to think through this properly tomorrow, I may still be talking garbage right now, I'm still a bit confused :-).

**Comment by ekpyron** [comment]
On the other hand, I still think this *should* be rather feasible, if we extract the suitable snippets from the ABIEncoderV2 code (maybe we can then actually have the ABIEncoderV2 code call this shared code).

**Comment by mijovic** [comment]
I plan to implement array copying in #9725 and just use in old codegen for unimplemented things.
Maybe we can close this one?

**Pull request closed without merging**
