### PR TITLE
Issue warning for unitialized for-loop initialization expression

### PR DESCRIPTION
**Pull request by StrongerXi**
A simple check that addresses #13214.

New tests are added.

### CODE REVIEW

**Review by hrkrshnn — DISMISSED** [review]
Thanks!

**Comment by hrkrshnn** [comment]
Actually, can you add a changelog as well? @StrongerXi

**Comment by StrongerXi** [comment]
> Actually, can you add a changelog as well? @StrongerXi

Totally, done.

**Review by hrkrshnn — APPROVED** [review]
I'm okay with this warning. However, it seems that we don't currently have warnings for uninitialized variable elsewhere (except for storage pointers), so it's a small deviation from how code works now.

Some users are vocal about warnings that they don't agree with. If that is a concern, we have something a bit gentler, which are info messages. We could convert this into an info message.

Anyway, I'll vote to merge this. But I'll wait for others in the team to chime in.

**Review by chriseth — CHANGES_REQUESTED** [review]
Thank you for your contribution!
I'm not really convinced we need this warning - it is perfectly fine to just use `uint i`.
Also, what is special about loop variables?
In general, I think the compiler only warns about really bad situations and things that could be fine or could be bad should be warned about by additional tools like slither.

**Comment by ekpyron** [comment]
We discussed this in our meeting today and decided that we don't want the underlying issue implemented, so I'm closing the PR.

**Pull request closed without merging**
