### PR TITLE
Add clang build and test CIs

### LINKED ISSUE #7476: [Build Infra] Add clang build and test CIs
## Abstract

At the moment, we rely on the fuzzer build CI to catch compiler warnings/errors that should be otherwise caught by clang (see https://github.com/ethereum/solidity/pull/7473#issuecomment-534534163).

Now that we have a dedicated clang docker image (see #7248 ), we can use it for this purpose.

### PR DESCRIPTION
**Pull request by bshastry**
fixes #7476

### CODE REVIEW

**Comment by bshastry** [comment]
The new clang docker image has been pushed to docker hub. It is called `ubuntu1904-clang`

**Comment by aarlt** [comment]
Cool thats interesting! We should see some errors.. I guess its not a macOS vs Linux issue.. its an clang vs. gcc thing.. but lets see :) https://github.com/ethereum/solidity/issues/7468 https://github.com/ethereum/solidity/pull/7464

**Comment by chriseth** [comment]
Or a boost version issue?

**Comment by chriseth** [comment]
Or libc++/libstdc++?

**Comment by aarlt** [comment]
I can highly recommend to build everything with as many different compilers as possible and run all resulting tests including its sanitized versions. It may also be useful to build the stuff with different standard libraries.

**Comment by bshastry** [comment]
I'm not sure why CI runs are still pending.

**Comment by bshastry** [comment]
Ah, there was a deadlock in the workflow :-)

**Comment by bshastry** [comment]
@erak Hope I got the soltest configuration for the clang build right :-)

**Comment by bshastry** [comment]
@chriseth in the clang docker image, boost version is higher but it doesn't use libc++.

**Review by chriseth — APPROVED** [review]

**Pull request merged**
