### PR TITLE
DOCS: Add link between functions in contract structure and more details

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
### Description

Something got really mixed up with git history in this PR (https://github.com/ethereum/solidity/pull/5531#discussion_r237292143) so it seemed easier to start again here. This PR adds a link between explanation of functions in the structure of a contract document and where the reader can find more details.

### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [x] New tests have been created which fail without the change (if possible)
- [x] README / documentation was extended, if necessary
- [x] Changelog entry (if change is visible to the user)
- [x] Used meaningful commit messages

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
There is no duplicate value, not sure why build errors

**Comment by erak** [comment]
@ChrisChinchilla Circle reports this: ``WARNING: undefined label: function-parameters-return-variables (if the link has no caption the label must precede a section header)`` (which is a warning but treated as error). That section seems to be part of ``contracts.rst``, but is the first subsection in <functions>.

**Comment by ChrisChinchilla** [comment]
@bit-shift Weird, I had a different error locally, fixed now.

**Comment by ChrisChinchilla** [comment]
Rebased and squashed

**Review by chriseth — APPROVED** [review]

**Pull request merged**
