### PR TITLE
Add dYdX tests.

### PR DESCRIPTION
**Pull request by chriseth**
Adds https://github.com/dydxprotocol/protocol as part of the test suite.

### CODE REVIEW

**Comment by axic** [comment]
Seems like the web3 dependency they use is broken:
```
Error: Cannot find module 'websocket'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/tmp.6p40y3uzsl/node_modules/web3-providers-ws/src/index.js:38:10)

```

**Comment by axic** [comment]
Once fixed I am fine with merging this.

**Comment by axic** [comment]
Rebased, let's see.

**Comment by axic** [comment]
Still broken.

**Comment by chriseth** [comment]
I contacted the team but have not yet received an answer.

**Comment by axic** [comment]
@AntonioJuliano @BrendanChou would you be interested in having dydx contracts be compiled & tested against with each Solidity change? If so, would you commit to keeping `master` in a working (non-breaking) state? Or is this too early?

**Comment by BrendanChou** [comment]
@axic 

We actually had this problem at one point with CircleCI and the web3 npm package. Not exactly sure what's wrong, but breaking the CircleCI cache seemed to work (using a new cache).

**Comment by axic** [comment]
```
> @dydxprotocol/protocol@0.1.4 test /tmp/tmp.7rlyUDDOc4
> truffle test

Error parsing /tmp/tmp.7rlyUDDOc4/contracts/external/0x/ZeroExProxy.sol: ParsedContract.sol:110:9: ParserError: The state mutability modifier "constant" was removed in version 0.5.0. Use "view" or "pure" instead.
        constant
        ^------^
Compilation failed. See above.
```

@BrendanChou it does seem to work now, however uses old syntax. `pure`/`view` has been out for ~10 0.4.x releases, do you want to upgrade your codebase?

Sorry, I see it is an upstream imported contract, but still, the problem is there.

**Comment by BrendanChou** [comment]
@axic thanks for pointing that out. using `pragma experimental "v0.5.0";` didn't seem to catch it during compilation. We updated our master branch with the change if you want to try again

**Comment by axic** [comment]
This was one of the few examples which we couldn't (or didn't) catch properly in the experimental mode.

**Comment by axic** [comment]
Thanks for the change, restarted!

**Comment by axic** [comment]
It is failing with this:
```
,zeppelin-solidity/contracts/ECRecovery.sol:71:12: TypeError: Wrong argument count for function call: 2 arguments given but expected 1. This function requires a single bytes argument. Use abi.encodePacked(...) to obtain the pre-0.5.0 behaviour or abi.encode(...) to use ABI encoding.
    return keccak256(
           ^ (Relevant source part starts here and spans across multiple lines).
```

Have a look at the changelog on `develop`, it should have these explained.

**Comment by BrendanChou** [comment]
Such is the nature of using Open-Zeppelin libraries. Thanks for your patience. They just released an updated npm package 2 days ago to fix that problem. I'll update and let you know when we made the change on master

**Comment by BrendanChou** [comment]
@axic the specific problem is now fixed and I tried to verify by hand that there are no other problems by following the changelist. Is there some way for me to run some linter/compiler for v0.5.0 rather than having you keep retrying by pulling our master?

**Comment by axic** [comment]
I think with truffle 4.x it is hard, but truffle 5.x has an option to select a solc version at runtime and there you could use one of the latest 0.4.25 nightly, which is the current "0.5.0".

**Comment by BrendanChou** [comment]
Sorry for the dumb question, but how do you get truffle 5.x? The npm version at least seems to be at 4.1.13.

**Comment by axic** [comment]
`npm install truffle@next` IIRC

**Comment by BrendanChou** [comment]
@axic Thanks! Finally got Truffle5 with the nightly solc up and running locally. It seems to throw no more errors if you want to try pulling our master again!

(although there is one warning for an open-zeppelin contract that we use)

**Comment by axic** [comment]
While compilation passes now with dxdy, unfortunately at the end there's still this error:
```
Error: Cannot find module 'websocket'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/tmp.E9nO9NIZnQ/node_modules/web3-providers-ws/src/index.js:38:10)
    at Module._compile (module.js:652:30)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .js] (/tmp/tmp.E9nO9NIZnQ/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/tmp.E9nO9NIZnQ/node_modules/web3-core-requestmanager/src/index.js:53:24)
    at Module._compile (module.js:652:30)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .js] (/tmp/tmp.E9nO9NIZnQ/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/tmp.E9nO9NIZnQ/node_modules/web3-core/src/index.js:26:22)
    at Module._compile (module.js:652:30)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .js] (/tmp/tmp.E9nO9NIZnQ/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/tmp.E9nO9NIZnQ/node_modules/web3/src/index.js:32:12)
    at Module._compile (module.js:652:30)
    at Module._extensions..js (module.js:663:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @dydxprotocol/protocol@0.1.4 test: `truffle test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @dydxprotocol/protocol@0.1.4 test script.
```

> It seems to throw no more errors if you want to try pulling our master again!

Great!

> (although there is one warning for an open-zeppelin contract that we use)

What is the warning? Can you submit a fix to zeppelin?

**Comment by BrendanChou** [comment]
They accepted my PR to fix the warning. Should be in next release https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1122

Let me look into the web socket thing

**Comment by BrendanChou** [comment]
@axic This seems to be a bug with either web3 or node/npm getting things directly from GitHub. I have now added `websocket` explicitly into our `package.json` if you want to try again.

If that still fails, upgrading node or npm might work, but I'm not sure

**Comment by chriseth** [comment]
Rebased to retrigger the tests.

**Comment by axic** [comment]
Okay it is failing now due to recent changes:
```
,zeppelin-solidity/contracts/ownership/CanReclaimToken.sol:22:39: TypeError: Invalid type for argument in function call. Invalid implicit conversion from contract CanReclaimToken to address requested.
    uint256 balance = token.balanceOf(this);
                                      ^--^
,/tmp/tmp.iW9x3rzxXD/contracts/margin/external/ERC20/ERC20LongCreator.sol:54:16: TypeError: Return argument type contract ERC20Long is not implicitly convertible to expected type (type of first return variable) address.
        return new ERC20Long(
               ^ (Relevant source part starts here and spans across multiple lines).
,/tmp/tmp.iW9x3rzxXD/contracts/margin/external/ERC20/ERC20ShortCreator.sol:54:16: TypeError: Return argument type contract ERC20Short is not implicitly convertible to expected type (type of first return variable) address.
        return new ERC20Short(
               ^ (Relevant source part starts here and spans across multiple lines).
,/tmp/tmp.iW9x3rzxXD/contracts/margin/external/SharedLoanCreator.sol:88:9: TypeError: Type contract SharedLoan is not implicitly convertible to expected type address.
        address sharedLoanAddress = new SharedLoan(
        ^ (Relevant source part starts here and spans across multiple lines).
```

**Comment by BrendanChou** [comment]
I'll make the changes on our side for that, and I also submitted a PR to OpenZeppelin for their stuff, but will probably have to wait for their next release

**Comment by axic** [comment]
It is weird if you had to submit to Zeppelin as we keep them updated, since we run it in the CI.

I wonder how it was triggered and it is not triggered in the regular tests. We just git clone their master and run `npm run test` within.

**Comment by BrendanChou** [comment]
We use their npm package, so it may not match their master, but I don't think some of those changes were even in their master yet, so I'm not sure why it's not triggering on theirs

**Comment by axic** [comment]
> but I don't think some of those changes were even in their master yet, so I'm not sure why it's not triggering on theirs

Oh right, we have a fork (but submit all our changes) to speed up our merge process. It is a good trigger that we should update our fork now 😉

**Comment by chriseth** [comment]
I don't think this has a chance of succeeding. We can re-add it when 0.5.0 has stabilized.

**Pull request closed without merging**
