### PR TITLE
[Sol->Yul] Move name functions from IR context to the new `Common` module (refactor)

### PR DESCRIPTION
**Pull request by cameel**
Refactoring changes extracted from #8943 (and before that from #8797). Does not affect functionality.
Related to #6788 and #8485.

### CODE REVIEW

**Review by chriseth — APPROVED** [review]
In a subsequent PR, we could also move the naming scheme for local variables here, then everything is in one place.

**Comment by cameel** [comment]
OK. I'll add it when I'm done with splitting this.

Now rebasing the other PRs on this merge.

**Comment by cameel** [comment]
Or maybe I'll leave them as they are to avoid retriggering the checks. There's no other new code in `develop` anyway.

**Comment by cameel** [comment]
> In a subsequent PR, we could also move the naming scheme for local variables here, then everything is in one place.

Done: #8955

**Pull request merged**
