### PR TITLE
Fix deploy script.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by axic** [comment]
```
 # This file is assumed to be the product of the build_emscripten.sh script.
 cp ../soljson.js ./bin/"soljson-$FULLVERSION.js"
 node ./update
 cd bin
 git add .
 git add ../soljson.js
 git commit -m "Added compiler version $FULLVERSION"
 git push origin gh-pages
```

Why is this script adding `../soljson.js` too? That should be already in the repo and handled by the update script.

**Comment by chriseth** [comment]
update does not touch git, so we need to add `../soljson.js`.

**Comment by axic** [comment]
> update does not touch git, so we need to add `../soljson.js`.

@chriseth As long as it changes the file, it will be detected by `git commit`?

**Comment by chriseth** [comment]
no, only by `git commit -a`.

**Comment by axic** [comment]
True, I think it should be like this:

``` diff
 # This file is assumed to be the product of the build_emscripten.sh script.
 cp ../soljson.js ./bin/"soljson-$FULLVERSION.js"
 node ./update
-cd bin
-git add .
-git add ../soljson.js
-git commit -m "Added compiler version $FULLVERSION"
+git add ./bin/"soljson-$FULLVERSION.js"
+git commit -m "Added compiler version $FULLVERSION" -a
 git push origin gh-pages
```

This leaves control over the other files to the update script and makes #1149 easier.

See https://github.com/ethereum/solidity/tree/solc-bin-publish-update

**Pull request merged**
