### PR TITLE
Move UndefMacros from libdevcore to libsolidity/parsing

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by axic** [comment]
Actually after having a look at `Token.h` this file might not even be needed.

**Comment by axic** [comment]
Should be ready.

**Comment by chriseth** [comment]
Are you sure you can remove that from some of the files? I'm not too confident about our platform coverage here.

**Comment by axic** [comment]
It is only enabled on Windows and we have appveyor for that. There was one conflicting identifier in the tests (`interface`).

**Review by chriseth — APPROVED** [review]

**Pull request merged**
