### PR TITLE
emit shift opcodes

### PR DESCRIPTION
**Pull request by gcolvin**
Minimum changes so that shift opcodes get emitted.

### CODE REVIEW

**Comment by axic** [comment]
Thanks for this @gcolvin, but it already exists as #2541 which also has optimisations (though I need to update it to swap operands).

**Comment by gcolvin** [comment]
Aha.  #2541 has been hanging out since July.  I have the code ready to implement these, will make a PR after I sleep.  It requires the Solidity changes to have anything to run, so if you aren't going to have #2541 merged soon we might just merge this one now.  I don't think it will conflict with yours or cause any problems @axic

**Comment by gcolvin** [comment]
I see - we need your experimental opcode test before the new opcodes get merged.

**Comment by gcolvin** [comment]
Anyway, I'm having trouble with SAR.  It's not clear boost's right shift operator does what we want.  The cpp_int class uses sign-magnitude representation.  So my PR will be delayed.

**Comment by axic** [comment]
Sorry I cannot follow you well?

One of the reasons the PR wasn't merged is that shift opcodes were not agreed for a hardfork, since 2-3 meetings ago it was agreed to be Constantinople I think it can be merged soon when some of the actual tests are implemented.

**Comment by axic** [comment]
I'll close this here given it is a duplicate of #2541

**Comment by gcolvin** [comment]
Closing it is fine, @axic thanks.  I need some way to generate these opcodes for testing, but I can keep working on this branch with this patch until #2541 is merged.

**Comment by axic** [comment]
@gcolvin note: you can also check out the other branch locally. `git checkout origin/asm-bitshift`

**Comment by gcolvin** [comment]
Thanks.  I've got a stable environment, so will concentrate on getting SAR right.

**Pull request closed without merging**
