### PR TITLE
[DOCS] Require, revert, assert clarification

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
### Description

In reference to https://github.com/ethereum/solidity/issues/6689 this PR attempts to clarify the different functions, and why you might want to use them.

### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [x] New tests have been created which fail without the change (if possible)
- [x] README / documentation was extended, if necessary
- [x] Changelog entry (if change is visible to the user)
- [x] Used meaningful commit messages

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
You may find it easier to run a local copy to see changes with this PR instead of just looking at diff, not sure.

**Comment by chriseth** [comment]
This PR contains too many changes - it actually looks like a failed rebase.

**Comment by ChrisChinchilla** [comment]
Fixed now @chriseth

**Comment by chriseth** [comment]
It is still the case.

**Comment by ChrisChinchilla** [comment]
@chriseth Not where I am looking, I can just see one file change. 

As noted in a comment above, I rearranged things a bit, is that what you mean? In which case I'm not sure how best to create these changes as multiple PRs might be even more confusing.

**Review by chriseth — APPROVED** [review]

**Pull request merged**
