### PR TITLE
[WIP] Limit recursion depth of constant optimizer.

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by axic** [comment]
We should review test and close if it is not worth. At least there will be proper history and just a loose branch.

**Comment by axic** [comment]
@chriseth what about this one?

**Comment by chriseth** [comment]
I think it did not have the effect I thought it would have.

**Comment by axic** [comment]
I think the limit 8 probably is never triggered as it is unlikely to successfully break up a 256bit number in the form of `a * 2**b` where `a` or `b` is also in the same format >8 times, with lower gas usage.

**Comment by axic** [comment]
@chriseth I vote not to merge it because then we can find an unlikely case if it exists.

**Comment by chriseth** [comment]
Yes, I'm not keen on keeping this.

**Pull request closed without merging**
