### PR TITLE
pass a literal with correct length

### PR DESCRIPTION
**Pull request by ssi91**

### CODE REVIEW

**Review by hrkrshnn — APPROVED** [review]

**Review by cameel — APPROVED** [review]
Looks good. It's clearly not a test for narrowing casts so the longer value must have been a mistake.

**Comment by cameel** [comment]
Tests are failing but this looks like something unrelated to this PR. Probably another thing that broke on `breaking`.

It's our detector for tests that work with the new Yul-based backend but are not marked as such. Apparently `test/libsolidity/semanticTests/arithmetics/check_var_init.sol` did not work with that backend but now does.

All you have to do is to add this in that test (look how other tests in the same directory do it):
```
// ====
// compileViaYul: also
```

**Comment by cameel** [comment]
Here's the commit that added that test: c9ef727136a5aed0b2e1fec787abdbdd6bd57b0a

You can see how some tests have `compileViaYul: also` while others don't.

**Comment by cameel** [comment]
Thanks @ssi91!
It's merged. Now you can rebase #10409 on it.

**Pull request merged**
