### PR TITLE
Breaking: Reserve keyword assert

### PR DESCRIPTION
**Pull request by axic**
Reserve keyword for #1130.

### CODE REVIEW

**Comment by chriseth** [comment]
I don't see much point in this pull request, it is actually quite dangerous and will stay open for some time.

**Comment by axic** [comment]
Depends on how #1130 is implemented - do we allow contracts to overwrite the `assert` keyword/function.

**Comment by chriseth** [comment]
Sorry, the comment was not referring to the pull request per se, but making the pull request at this point in time.

**Comment by pirapira** [comment]
The documentation has a list of reserved keywords.  Please add `assert` there as well.

**Comment by chriseth** [comment]
But `assert` is currently not a reserved keyword.

**Comment by pirapira** [comment]
@chriseth This pull-request only changes the code but not the documentation.  The current status in `develop` is fine because neither the code nor the documentation says `assert` is reserved.  This pull-request is in a lesser state because only the code says `assert` is reserved while the documentation does not.

**Comment by chriseth** [comment]
@pirapira oh I'm sorry, I did not see that this is a pull request, I thought it was just an issue. In this case, yes, the pull request should update the documentation and the code at the same time.

**Comment by axic** [comment]
Closing this for the moment. Let us reopen when the time comes.

**Pull request closed without merging**
