### PR TITLE
Simplify inline assembly resolver, alternative.

### PR DESCRIPTION
**Pull request by a3d4**

### CODE REVIEW

**Comment by Marenz** [comment]
Does this PR fix a specific issue?

**Comment by chriseth** [comment]
Hm, a lambda inside a lambda?

**Comment by chriseth** [comment]
I tried to combine the two lambdas locally, but there still remains the problem that we would also have to return the kind of error (declaration, type, ...). So I think the solution where we directly emit the error is better.

**Comment by a3d4** [comment]
@Marenz 
> Does this PR fix a specific issue?

The root PR is 9189, here is an alternative implementation.

@chriseth 
> still remains the problem that we would also have to return the kind of error (declaration, type, ...)

I thought we can consider all errors as type errors. Anyway, I'm closing this PR then.

**Pull request closed without merging**
