### PR TITLE
Fix validation error causing ICE with isoltest --test 

### PR DESCRIPTION
**Pull request by ywon0925**
Fixes issue #13070

Add a `catch` to handle the exception.
Rename `boostTest.cpp` to `soltest.cpp` &  Edit `CMakeLists.txt` accordingly to make sure it builds properly

### CODE REVIEW

**Comment by Marenz** [comment]
Could you put the rename in a separate commit?
And the whitespace fixes + catch in one commit? 

And one rebase to fix the conflicts and then this should be good to go

**Comment by ywon0925** [comment]
I made the changes you've asked.

Please let me know if I messed up something :)

**Comment by Marenz** [comment]
Looks good to me. The CI failures are unrelated to your changes (some network problem). I restarted the CI tests, maybe that'll fix them.

**Comment by ywon0925** [comment]
Okay, now I should wait for a review?

**Review by Marenz — APPROVED** [review]

**Comment by Marenz** [comment]
I just forgot to click the review button ;)
Thank you for the contribution!

**Pull request merged**
