### PR TITLE
Add specific web3 example for getStorageAt

### PR DESCRIPTION
**Pull request by slothbag**
It took me a LONG time to figure out how to get this working in web3.js, there is no documentation or examples of how to do it.

This would have made things a lot easier :)

### CODE REVIEW

**Comment by VoR0220** [comment]
I think this would better fit in the documentation for web3, no?

**Comment by slothbag** [comment]
Up to you guys, I can move it to https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgetstorageat no problem

**Comment by VoR0220** [comment]
@chriseth what say you? Do we add this or suggest he go to web3 with his example?

**Comment by chriseth** [comment]
I think it is a good idea to have some more web3.js examples, but this one should be extended to say what the result of the query is.

**Comment by chriseth** [comment]
Closing due to inactivity.

**Pull request closed without merging**
