### PR TITLE
Disable FixedBytesType(0) aka bytes0

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by axic** [comment]
Looked at all the instances of creating a `FixedBytesType` in the code and couldn't find a single place where it is possible to receive 0.

**Review by chriseth — CHANGES_REQUESTED** [review]
Please remove the function `FixedBytesType::smallestTypeForLiteral(std::string const& _literal);` which would generate such a type.

**Comment by axic** [comment]
Oh, nice catch, it's not even used.

**Comment by axic** [comment]
@chriseth fixed

**Comment by axic** [comment]
@chriseth ok to merge?

**Review by chriseth — APPROVED** [review]

**Pull request merged**
