### PR TITLE
Enable nightly tests for 0.6.0

### PR DESCRIPTION
**Pull request by erak**

### CODE REVIEW

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
Hm, doesn't this need to be merged to develop instead of develop_060?

**Comment by erak** [comment]
Superseded by https://github.com/ethereum/solidity/pull/7459.

**Comment by erak** [comment]
@chriseth Yeah, you're right. It should target develop. Created a new PR.

**Comment by axic** [comment]
> @chriseth Yeah, you're right. It should target develop. Created a new PR.

Btw, it is possible to "change base" next to the title, so there's no need to create new PRs.

**Pull request closed without merging**
