### PR TITLE
[Docs] Include explanation of how indexed dynamic-length event args are encoded

### PR DESCRIPTION
**Pull request by swaldman**
Assuming [this stackoverflow answer](https://ethereum.stackexchange.com/a/7170/1970) is correct, it seems like a good idea to have the behavior documented in the spec. This is an attempt to do that.

### CODE REVIEW

**Comment by chriseth** [comment]
Wonderful, thanks! Could you also add a comment that people can of course provide arguments twice, once for an indexed parameter and once for a non-indexed parameter?

**Comment by swaldman** [comment]
Sure. I hadn't thought of that, but I'm glad to add it!

**Comment by swaldman** [comment]
(I've added a sentence to this effect.)

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
Thanks!

**Comment by swaldman** [comment]
Thank you! This has to be my most prompt and painless pull-request experience ever.

**Comment by chriseth** [comment]
Glad to have been part of it :)

**Pull request merged**
