### PR TITLE
External test for Bleeps

### PR DESCRIPTION
**Pull request by cameel**
Part of #5956.
**Depends on #12530. Don't merge until that PR is merged.**

This adds an external test for [Bleeps](https://github.com/wighawag/bleeps).

The project has an unusual structure compared to the others we have integrated so far (it's a monorepo with `pnpm` as the recommended package manager) so it was a bit tricky to get just the part we need to build and tests to run. The `main` branch also seems to be broken right now (https://github.com/wighawag/bleeps/issues/1). Fortunately there's a tag close to the top commit (`bleeps_migrations`) so I'm using that for now.

Note that the extra parameters my PR adds to `neutralize_package_json_hooks` are not used. I originally needed them for the `common-lib` library in the repo but in the and I was able to drop that. They may come in handy later though so I want to keep that change anyway.

### CODE REVIEW

**Comment by ekpyron** [comment]
FYI: (probably trivial) merge conflicts to be resolved after I merged the first one

**Comment by cameel** [comment]
Conflicts solved. As I said in, https://github.com/ethereum/solidity/pull/12530#issuecomment-1013492792, I'm going to put this PR on top of #12530 now.

**Comment by ekpyron** [comment]
Wait, why does the commit of [#12350](https://github.com/ethereum/solidity/pull/12530) still show up here after that's merged? Ah, I guess that's what happens, if you don't also switch the base branch on github? Anyways, the test run seems to fail, so I'll have another look next week.

**Comment by cameel** [comment]
Yeah, sorry looks like I did forget to switch the base branch :)

It's fails because the maintainer fixed https://github.com/wighawag/bleeps/issues/1 and I pushed a commit to switch it to `main`, hoping that it now passes tests. I think it would if not for the fact that the project now contains one 0.4.19 contract that won't compile with 0.8.11 :(

So back to the tag we go. I'll revert it to the previous version.

**Comment by cameel** [comment]
Fixed. It should pass tests now.

**Review by hrkrshnn — APPROVED** [review]

**Pull request merged**
