### PR TITLE
Minor cleanup in syntax tests for function types

### PR DESCRIPTION
**Pull request by cameel**
Related to #11000. Minor refactor before my actual PR for #10516.

- I moved some related syntax tests out of `nameAndTypeResolution/` and gave them more descriptive names.
- There are actually two tests that were duplicated version of others, with a typo in their names.

### CODE REVIEW

**Comment by chriseth** [comment]
Which are the duplicated tests?

**Comment by cameel** [comment]
The ones I deleted: `042_functions_with_stucts_of_non_external_types_in_interface_2.sol` and `043_functions_with_stucts_of_non_external_types_in_interface_nested.sol`.

**Comment by chriseth** [comment]
Sure, but which files are they duplicates of? :)

**Comment by cameel** [comment]
`042_functions_with_stucts_of_non_external_types_in_interface_2.sol` vs `042_functions_with_structs_of_non_external_types_in_interface_2.sol`

`043_functions_with_stucts_of_non_external_types_in_interface_nested.sol` vs
`043_functions_with_structs_of_non_external_types_in_interface_nested.sol`

Note the `stucts` part.

**Comment by cameel** [comment]
BTW, these are the files I'm renaming in this PR.

**Review by chriseth — APPROVED** [review]

**Pull request merged**
