### PR TITLE
Do not use -Og for debug mode (won't work on Mac/clang)

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by chriseth** [comment]
Oh I'm sorry, this slipped in from one of my changes. The thing is: `-O0` does not work for g++ 4.8.4 on linux...

**Comment by axic** [comment]
`-O0 -g` won't work on gcc 4.8.4?

**Comment by chriseth** [comment]
Why did we change from `-Og` to `-O0` in the first place? @chfast?

**Comment by chriseth** [comment]
What about not specifying any `-O`?

**Comment by axic** [comment]
I guess not having any optimisation level works, that should default to `-O0`.

Note, from clang:
```
       -g, -gline-tables-only, -gmodules
              Control  debug  information  output.  Note that Clang debug information works best at -O0.
```

**Comment by chfast** [comment]
`-Og` increases performance over `-O0` for debug builds, having the same debugging experience (however, from my experience that's not true -- I had troubles debugging some code with `-Og`).  For sure works for GCC 4.8 (https://gcc.gnu.org/onlinedocs/gcc-4.8.4/gcc/Optimize-Options.html#Optimize-Options) but might not for some old clangs.

Going back to `-O0` is fine.

Option `-g` is not related.

**Comment by chriseth** [comment]
Ok, this is really weird. I'm not getting the same problems I had before. Let's merge this...

**Review by chriseth — APPROVED** [review]

**Comment by axic** [comment]
> Option `-g` is not related.

@chfast, it is kind of related:

> Note that Clang debug information works best at -O0.

And my clang doesn't have `-Og`:
> Apple LLVM version 8.0.0 (clang-800.0.38)
> Target: x86_64-apple-darwin15.6.0

**Pull request merged**
