### PR TITLE
Fix "breaking" branch

### PR DESCRIPTION
**Pull request by Marenz**

### CODE REVIEW

**Comment by chriseth** [comment]
Can you rebase this on top of breaking? Why did you not just merge develop into breaking without changes?

**Comment by Marenz** [comment]
Well, because otherwise the CI tests failed. I had to do some version adjustments

**Comment by Marenz** [comment]
Now that the tests work I would push this directly to breaking if I have your ok

**Comment by chriseth** [comment]
I was able to create a PR without conflicts: https://github.com/ethereum/solidity/pull/9759
If it turns out to make tests fail, then please create a fixing PR.

**Comment by Marenz** [comment]
Yep, the tests failed for your PR: https://app.circleci.com/pipelines/github/ethereum/solidity/8039/workflows/13c0c956-e4cd-483d-9b13-00b0d688caf9/jobs/431980

**Comment by Marenz** [comment]
I turned this into the fixing PR

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
Weird, I thought I updated the version numbers in the documentation. So the tests were failing all the time?

**Comment by Marenz** [comment]
Yeah. As far as I can tell, the last successful build for `breaking` was 2 months ago: https://app.circleci.com/pipelines/github/ethereum/solidity?branch=breaking

**Pull request merged**
