### PR TITLE
Corrected case for Solidity library entry in CMake file.

### PR DESCRIPTION
**Pull request by bobsummerwill**

### CODE REVIEW

**Comment by LefterisJP** [comment]
This won't work. The library name is actually case-sensitive. And thus as you can see from the Jenkins results it tries to find `-lsolidity` but can't because you changed its name. Why do you want to capitalize it?

```
ld: library not found for -lsolidity
```

**Comment by bobsummerwill** [comment]
Right!    That was to address inconsistencies between this CMake file and the other modules which reference it, which are all using "Solidity", not "solidity".

Given the break you report, the correct fix will be to fix all the references instead, so they switch to lower-case.    If you want to JUST DO THAT, please do, and we'll ditch this PR.

Those are:   soltest, soljson, solc, web3jsonrpc.

ie.

eth_use(${EXECUTABLE} OPTIONAL Solidity)

**Comment by bobsummerwill** [comment]
This is the only Ethereum-authored module which uses mixed case.   Everything else is all lower-case, except external packages.   Case is always consistent everywhere else.

I suspect that we got away with this because of some platform-conditional logic in the CMake which was forcing things to lower implicitly on Linux.

**Comment by bobsummerwill** [comment]
Like this ...

https://github.com/ethereum/webthree-helpers/blob/develop/cmake/FindPackageHandleStandardArgs.cmake#L225

**Comment by LefterisJP** [comment]
@chriseth Would like your take on this too. All module names, including Solidity, should be lower-case right?

**Comment by chriseth** [comment]
The problem here is that the name of the module and the name of one of its libraries coincide except for their case. Module names are always uppercase where library names are always lowercase. I will investigate further.
@bobsummerwill It would be great if you could give a pointer to the actual error your get. Thanks!

**Comment by bobsummerwill** [comment]
The error is purely that the inconsistency in this one case was resulting in errors in my automated dependency graph generation.

If we can iron out the inconsistency at the root, I thought that would be 'a good thing'.

I can add another tolower() hack if necessary, but wanted to avoid that lameness if this was just a mistake.

**Comment by bobsummerwill** [comment]
OK - @chriseth and @LefterisJP - Let's try this (see above).    I'll make another PR for the OPTIONAL dependency in web3jsonrpc too - to make that eth_use scope-qualified too.

**Comment by bobsummerwill** [comment]
web3jsonrpc fixed added to https://github.com/ethereum/webthree/pull/88.

**Comment by bobsummerwill** [comment]
So this one looks like another "it was broken before I touched it, honest!" one:

[  2%] Building CXX object solc/CMakeFiles/soljson.dir/jsonCompiler.cpp.o
[  2%] Built target solidity_BuildInfo.h
/var/jenkins_home/sharedspace/solidity/label/master/solidity/solc/jsonCompiler.cpp:25:23: fatal error: json/json.h: No such file or directory

Again - I will investigate further.

**Comment by bobsummerwill** [comment]
OK - I suspect this one is more nefarious, and that the simple change from Solidity to Solidity::solidity has changed the path of implicit dependency adding within the CMake files, knocking JsonCpp out of play and breaking the build.    Gotta run now, but will look again later.

**Pull request merged**
