### PR TITLE
Fix storebytecode.sh for bytecode comparison

### LINKED ISSUE #5426: Fix emscripten bytecode report

### PR DESCRIPTION
**Pull request by axic**
Fixes #5426.

### CODE REVIEW

**Comment by axic** [comment]
Finally we have an error here:
```
/tmp/tmp.tvpR06Ijh9/solc:32
                    console.log(contractName + ' ' + result['contracts'][filename][contractName].evm.bytecode.object)
                                                                                                 ^
TypeError: Cannot read property 'evm' of undefined
    at Object.<anonymous> (/tmp/tmp.tvpR06Ijh9/solc:32:98)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
The command "test $SOLC_STOREBYTECODE != On || (cd $TRAVIS_BUILD_DIR && scripts/bytecodecompare/storebytecode.sh)" exited with 1.
```

**Comment by axic** [comment]
I think I'll also add `exit(1)` next to `console.log(... ERROR)` so that failures are caught here.

**Comment by chriseth** [comment]
Note that some inputs are expected to report an error - this is also called on inputs that cannot be compiled.

**Comment by axic** [comment]
@chriseth please review

**Review by chriseth — APPROVED** [review]

**Comment by axic** [comment]
Waiting for travis to confirm 🤞

**Comment by chriseth** [comment]
I'll just merge it without waiting for travis. It cannot get worse.

**Comment by chriseth** [comment]
Or shall we? argh...

**Comment by axic** [comment]
Travis succeeded. The bytecode comparison repo fails however, perhaps emscripten did break things after all ?

**Comment by axic** [comment]
Merging this because it seems to be an improvement.

**Comment by chriseth** [comment]
You know that you can actually run these tests locally, do you? :)

**Pull request merged**
