### PR TITLE
Make semantics tests use the proper via-IR-pipeline and make yul optimizer requirements explicit.

### PR DESCRIPTION
**Pull request by ekpyron**
Not sure we want to do this like that and this will still break in the non-extracted tests as is, but we should probably do something like this.

### CODE REVIEW

**Comment by ekpyron** [comment]
[The remaining test failures are weird and potentially due to buggy library handling in our tests, need to have a closer look]

**Comment by ekpyron** [comment]
Closing this... I still think we should do this, but since nobody picked it up in the past half year, I don't expect anyone will any time soon...

**Comment by ekpyron** [comment]
Opened https://github.com/ethereum/solidity/issues/12668 instead.

**Comment by Assawal** [comment]
Opened #12668 instead.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitH­ub Mobile for iOS or Android.
You are receiving th­is because you are subscribed to this th­read. Monday, 14 February 2022, 11:26pm +05:00 from Daniel Kirchner  ***@***.*** :

**Pull request closed without merging**
