### PR TITLE
[WIP] docs: ``var x = 1/4`` is not working, so remove description about it

### PR DESCRIPTION
**Pull request by pirapira**

### CODE REVIEW

**Comment by chriseth** [comment]
There is a pending pull request to make it work, so I would not remove it from the documentation.

**Comment by pirapira** [comment]
That sounds fine, but let me maintain zero tolerance against inconsistencies (this means I take a note whenever I notice differences between the documentation and the implementation).

**Comment by pirapira** [comment]
The removed paragraphs assume the binary representation, so these paragraphs will be wrong when the fixed point types are implemented.

**Comment by axic** [comment]
Since the fixed point PRs were closed, is there any timeline in getting them done?

Meanwhile, since we have a couple of places in the documentation mentioning fixed point types, I think we could either:
a) remove all references
b) keep all references, but with a comment / warning stating they are not supported yet

**Comment by pirapira** [comment]
The existing descriptions assume the binary representation.  The implementation is going to be decimal.  So I guess "a) removing all references" causes less confusion.

**Review by chriseth — APPROVED** [review]

**Pull request merged**
