### PR TITLE
Update jsoncpp to v1.9.5.

### PR DESCRIPTION
**Pull request by aarlt**

### CODE REVIEW

**Comment by ekpyron** [comment]
failing CI so far - is that the unrelated windows stuff @nikola-matic is looking at, though?

**Comment by ekpyron** [comment]
Apart from that: we did include these bumps in the changelog at least a few times in the past - maybe not the craziest thing to do...

By the way: do we still want to switch to nlohmann-json any time soon :-D?

**Comment by nikola-matic** [comment]
> failing CI so far - is that the unrelated windows stuff @nikola-matic is looking at, though?

Could be, but I doubt it; the previous fixes were for providing a python3 symlink and pulling in the missing `request` library dependency. This doesn't look any of those. I'll spin `b_win` again with SSH to see what's going on.

**Comment by nikola-matic** [comment]
This is basically a copy of axic's previous PR - so the same error occurs - failed to find jsoncpp.dll. Take a look at the comment from said PR: https://github.com/ethereum/solidity/pull/14132#issuecomment-1512842057.

@ekpyron said to set `BUILD_SHARED_LIBS` to `OFF`. Could also try setting the windows static runtime to `ON`.

**Comment by aarlt** [comment]
Closing this in favour to #14877.

**Pull request closed without merging**
