### PR TITLE
Update faq with exceptions examples.

### PR DESCRIPTION
**Pull request by lastperson**
I've been struggling to understand how exactly exceptions are behave, I think this will help someone get it faster.

### CODE REVIEW

**Comment by ConsentDevelopment** [comment]
I have to disagree with adding this to the documents as I feel it just confuses the issue of explaining exceptions in Solidity contracts.

There is only one exception in the EVM and that is a Out Of Gas exception which is what the solidity 'throw' instruction activates. Bad / invalid EVM opcodes are also treated as Out Of Gas exceptions.

When a 'throw' instruction is activated then all caller gas is consumed even if there is gas remaining from the caller gasLimit value.

**Comment by lastperson** [comment]
Doesn't your third statement contradicts with the second example, and thus not true for every case?

**Comment by ConsentDevelopment** [comment]
Your second contract function example (internalException()) has a throw statement if a condition is true so this will throw a exception and use all of the available gas.

Where do you see the contradiction?

**Comment by lastperson** [comment]
`call` by default passes all tge available gas to the target, then the throw happens, if it would burn all that gas, than the calling function would run out of gas too, but it is not. As the example shows, caller will just receive `false` in response, and all the unspent gas will available to continue execution.

If it was not clear: `this.call(0xc10d9bbc)` will result in an `internalException()` being called with `msg.sender == address(this)` and thus will trigger a throw.

**Comment by ConsentDevelopment** [comment]
Yes, I understand that send and the low-level call functions return false in case of a exception (this was explained in the documents - exceptions)

What I wrote above - 'When a 'throw' instruction is activated then all caller gas is consumed even if there is gas remaining from the caller gasLimit value.' is still correct with the exception of send and the low-level call functions being called.

If your example contract functions there self contract calls made to return false as a bool parameter to the event functions. There is no need for this as these event functions do not need a parameter. The event name by itself has enough information for logging / event catching.

I feel these example contract functions will just confuse people that are starting to learn contract programming in Solidity.

**Comment by VoR0220** [comment]
in the wake of the DAO, I think this is a VERY bad idea to be adding to the docs, especially if we were to teach this to a beginner...there really isn't an exception system in solidity...it's just throws...that's it.

**Comment by chriseth** [comment]
@lastperson I think the code does not really explain what happens. Could you add some more comments? Also I'm not sure whether using events is the best way to explain exceptions.

**Comment by chriseth** [comment]
Closing this PR, the list is getting too long.

**Pull request closed without merging**
