### PR TITLE
add STATICCALL instruction

### PR DESCRIPTION
**Pull request by winsvega**

### CODE REVIEW

**Comment by axic** [comment]
Need to update `GasMeter` and `SemanticInformation` also.

**Review by axic — CHANGES_REQUESTED** [review]
Need to update GasMeter and SemanticInformation also.

**Comment by axic** [comment]
Depends on #2275.

**Review by pirapira — APPROVED** [review]
Looks good to me.

**Review by axic — APPROVED** [review]

**Pull request merged**
