### PR TITLE
Remove unneeded assert

### LINKED ISSUE #9948: ICE in CompilerStack: contract redefined to inherit from a non-existent type not detected as name clash
## Description

This contract:
```solidity
contract X {}
library test {
}
contract X is A {
}
```

produces:

```
Internal compiler error during compilation:
/home/user/solidity/libsolidity/interface/CompilerStack.cpp(1131): Throw in function void solidity::frontend::CompilerStack::storeContractDefinitions()
Dynamic exception type: boost::exception_detail::clone_impl<solidity::langutil::InternalCompilerError>
std::exception::what: Contract already present (name clash?), but no error was reported.
[solidity::util::tag_comment*] = Contract already present (name clash?), but no error was reported.
```

when compiled with solc.

On master, using AFL fuzzing.  Another discovery using https://github.com/agroce/afl-compiler-fuzzer.

## Environment

- Compiler version:  0.7.3-develop.2020.10.2+commit.756e21a8.Linux.clang
- Target EVM version (as per compiler settings): N/A
- Framework/IDE (e.g. Truffle or Remix): N/A
- EVM execution environment / backend / blockchain client: N/A
- Operating system: Ubuntu 18.04 in docker

## Steps to Reproduce

Above shows pretty clearly, I think.

### PR DESCRIPTION
**Pull request by Marenz**
An error will trigger later in the name resolve phase

fixes #9948

### CODE REVIEW

**Comment by ekpyron** [comment]
Hm... this seems a bit dangerous now... can you easily tell, if and why ``storeContractDefinitions()`` has to be run before name and type resolution (which supposedly generates the error required here)?

**Comment by Marenz** [comment]
Because if the `--stop-after parsing` option is used, we never run the resolve phase or anything following it, but the information of that map is required before that map to output the AST (when used in combination with that flag)

**Comment by ekpyron** [comment]
For what exactly is this map needed for the "stop after parser" output?
The thing is that the contents of the map are incorrect (or at least disputable) in these cases...

**Comment by Marenz** [comment]
I'd say "incomplete" is more accurate than "incorrect" :P
In this case it is used through the function `contractNames()` in `StandardCompiler.cpp:1057` to iterate through the contracts and output information for each.

**Comment by ekpyron** [comment]
Will there be any information in ``StandardCompiler.cpp:1057`` that will be valid in the "stop after parsing" case? To me it looks like all of that should just be skipped in that case instead - especially if we can then keep the assert.
I mean: that iteration is even guarded by ``analysisPerformed``...

**Comment by chriseth** [comment]
I would say this is fine to merge.

**Comment by ekpyron** [comment]
I'd say we should run ``storeContractDefinitions`` only after name resolution and properly guard ``CommandLineInterface.cpp`` against analysis information not being available (so far I haven't found *any* information that will actually end up in the output that would depend on that contract list that won't be empty, in case we don't have successful analysis).
But I'm also fine with merging this as is and revisiting when the CommandLineInterface is cleaned up some more.

**Review by chriseth — APPROVED** [review]

**Pull request merged**
