### PR TITLE
[WIP] CompilerStack Test Fixtures

### PR DESCRIPTION
**Pull request by ksolo**
**WIP** This is jus the beginning of this work. It is not intended to be merged at this time **WIP**

References Issue #3584 

Creating a SharedInstances class to manage pieces that can be re-configured in test runs. Tests will not need to create these instances per test.

_NOTE_ The [coding standards link](https://raw.githubusercontent.com/ethereum/cpp-ethereum/develop/CodingStandards.txt) gave me a 404. I will likely need to update these files to conform to those.

### CODE REVIEW

**Comment by ksolo** [comment]
@chriseth I'm just getting started but is the shared instances ok, or would you prefer this be restricted to just CompilerStack at this time?

**Comment by chriseth** [comment]
Thanks for the pull request! I need a little more code to be able to review this. You should not return CompilerStack by value for one. Please take a look at how it is done in AnalysisFramework and just extract some of the common functionalities into another class.

**Comment by chriseth** [comment]
For the coding style, you can take a look at https://github.com/ethereum/solidity/pull/3657

**Comment by chriseth** [comment]
@ksolo do you intend to work more on this? If not, I would like to close this.

**Comment by ksolo** [comment]
@chriseth Yes, I'd like to get back to this. I'm sorry I let this so for so long.

**Pull request closed without merging**
