### PR TITLE
LLL: Full set of test cases for the built-in compiler macros.

### PR DESCRIPTION
**Pull request by benjaminion**
As per @axic's suggestion.

I've basically considered only happy flows, but the coverage should be reasonable. An improvement, anyway.

Note,
 - test msg_six_args will fail to compile until Issue #2400 is dealt with.
 - tests create_one_arg and create_two_args will fail until PR #2415 is merged.

Note too that PR #2417 also contains the ecrecover test and #2415 also contains tests that are in here. So some rebasing will be needed at some point depending on what's merged and when. Let me know.

### CODE REVIEW

**Comment by axic** [comment]
I think we could:
- merge #2417
- fix & merge #2415
- comment out `msg_six_args` and merge this PR
- start a new PR fixing set/get/ref and enabling `msg_six_args`

**Comment by axic** [comment]
The test cases look good, so I am in favour merging it (following the plan above I guess).

Also happy that writing these tests uncovered some bugs.

**Comment by axic** [comment]
Once #2439 is merged, this can be rebased.

Having looked at `msg_six_args` I think it will fail as it doesn't seem correct. It will need to be fixed as part of this PR perhaps.

**Comment by benjaminion** [comment]
> Having looked at msg_six_args I think it will fail as it doesn't seem correct. It will need to be fixed as part of this PR perhaps.

Yes, I'm working on it now.  TBH, I can't fathom out the original `msg` with 6 args macro at all - I've rewritten it along the lines of the create macros (i.e. with no `alloc`) and it works fine with my original test code. I'm deeply suspicious of the `alloc` built-in; I can't figure it out at all.

I think I'll submit a proposed new `msg` macro as a separate PR, and we can deal with that. Then the final commit of all the test cases can be nice and clean.

**Comment by axic** [comment]
So you want to comment the test out in this PR and fix it in a separete one?

**Comment by benjaminion** [comment]
> So you want to comment the test out in this PR and fix it in a separete one?

I'm shortly going to send a PR for teh `msg_six_args` macro with its own test code. Let's decide first what to do with that, and afterwards I'll rebase this PR and it should all merge nice and cleanly.

**Comment by benjaminion** [comment]
Rebased. All tests working against current develop branch.

**Review by chriseth — CHANGES_REQUESTED** [review]
Parse error and invalid deposit exception in clang but not in gcc.

**Comment by benjaminion** [comment]
> Parse error and invalid deposit exception in clang but not in gcc.

Hmm. Cannot reproduce.

Compiler version:

```
build> clang --version
clang version 4.0.0-1ubuntu1 (tags/RELEASE_400/rc1)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

Confirmation Cmake is using this version (clean build done):

```
build> cmake -D_CMAKE_TOOLCHAIN_PREFIX=llvm- ..
-- The C compiler identification is Clang 4.0.0
-- The CXX compiler identification is Clang 4.0.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
...
```

Test output:

```
build> ./test/soltest -t LLLEndToEndTest/makeperm -- --ipcpath /tmp/testeth/geth.ipc
Running 1 test case...

*** No errors detected
```

**Comment by axic** [comment]
Travis uses:

clang version 3.5.0 (tags/RELEASE_350/final)
Target: x86_64-unknown-linux-gnu

And it fails on `makeperm`.

**Comment by benjaminion** [comment]
Yes. It smells like a compiler bug in that version of clang since v4.0.0 and all the other compilers are ok.

Shall we remove the makeperm test until this can be addressed? I don't think there's anything wrong with the test itself. What do you advise?

**Comment by axic** [comment]
I can reproduce it on:

Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0

**Comment by axic** [comment]
Added some debugging and it results in:

[dev::tag_comment*] = Expected 1 items, but deposited 0

at https://github.com/ethereum/solidity/blob/develop/liblll/CodeFragment.cpp#L427.

We should figure out why it fails, need to leave now, but will check later again.

**Comment by axic** [comment]
So it came down to this example:
```
(perm 'x)
```

Which in turn simplified out it to:
```
(def 'permcount (+ permcount 1))
```

And the bug was:
```
_s.defs[n] = CodeFragment(i, _s);
```

Where `_s.defs[n]` was updated before executing `CodeFragment` and thus the `permcount` lookup resulted in an empty item in the `+`.

**Comment by axic** [comment]
@benjaminion can you rebase this on #2462 so we can see this branch passes all tests? (We need to rebase again to develop one #2462 is meged though)

**Comment by benjaminion** [comment]
Have rebased onto branch lll-fix-def as requested. All tests are succeeding in my environment - we'll see about the travis CI environment...

**Comment by axic** [comment]
@benjaminion cool, it seems to have solved the problem for `makeperm` too.

**Comment by axic** [comment]
@benjaminion please rebase 😉

**Comment by benjaminion** [comment]
Rebase done, and Travis CI checks all passed. :-)

**Review by axic — APPROVED** [review]

**Comment by axic** [comment]
@chriseth is your change request review still valid?

**Review by chriseth — APPROVED** [review]

**Pull request merged**
