### PR TITLE
Update aleth for testing

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by axic** [comment]
Hashes need to be updated.

**Review by ekpyron — DISMISSED** [review]

**Comment by axic** [comment]
I think this new `aleth` binary may not work properly:
```
Testing library checksum...(B
Testing long library names...(B
Testing overwriting files...(B
Testing assemble, yul, strict-assembly...(B
Testing standard input...(B
Testing soljson via the fuzzer...(B
--> Running tests using  --evm-version homestead...(B
Commandline tests successful.
Too long with no output (exceeded 10m0s)
```

**Review by ekpyron — APPROVED** [review]
I think the issue with the new aleth binaries was fixed in #4347 and the tests should now run through and this can be merged.

**Comment by chriseth** [comment]
fingers crossed!

**Pull request merged**
