### PR TITLE
Extract name and type tests

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by axic** [comment]
Hand compared the extracted expectations with the original ones. I do not want to do that again :)

However, there seems to be a non-determinism bug (it seems to be in ViewPureChecker). Some test cases report two warnings in different order sometimes.

This is one of the affected tests:
```
syntaxTests/nameAndTypeResolution/055_inheritance_diamond_basic.sol: FAIL
  Contract:
    contract root { function rootFunction() public {} }
    contract inter1 is root { function f() public {} }
    contract inter2 is root { function f() public {} }
    contract derived is root, inter2, inter1 {
        function g() public { f(); rootFunction(); }
    }

  Expected result:
    Warning: (16-49): Function state mutability can be restricted to pure
    Warning: (129-151): Function state mutability can be restricted to pure
  Obtained result:
    Warning: (129-151): Function state mutability can be restricted to pure
    Warning: (16-49): Function state mutability can be restricted to pure

```

**Review by chriseth — DISMISSED** [review]

**Comment by chriseth** [comment]
I haven't fully reviewed this, but I'm still fine to merge it.

**Comment by chriseth** [comment]
The tests fail due to expectations depending on the VM version. Is this fixable in the isoltest framework?

**Comment by chriseth** [comment]
This is hopefully the final fix now.

**Comment by chriseth** [comment]
Appveyor is green apart from the know problem and bytecode comparison push.

**Review by chriseth — APPROVED** [review]

**Comment by axic** [comment]
> Move "create2_as_variable" back to non-isoltest tests.

Ah I was sure I kept all of those in the C++ file, but seems like missed this one.

**Comment by chriseth** [comment]
The code did not show that it depended on the EVM version and the error message was shortened (those only perform a partial match).

**Pull request merged**
