### PR TITLE
Remove obsolete flag --optimize-yul from scripts

### LINKED ISSUE #8713: Remove the --optimize-yul run on soltest
The soltest.sh script make multiple passes, some with `--optimize-yul` and some without. Since 0.6.0, ``--optimize`` includes ``--optimize-yul``, so that case can be removed from the loop.

### PR DESCRIPTION
**Pull request by Marenz**
fixes #8713

### CODE REVIEW

**Review by axic — DISMISSED** [review]

**Comment by chriseth** [comment]
tests fail.

**Comment by Marenz** [comment]
Hmm not sure why this fails.. gas cost changes..

**Comment by Marenz** [comment]
Turns out we didn't remove that flag for `soltest`. Fixed now.

**Review by christianparpart — APPROVED** [review]
I remember Chris talked about this oddity in the language summit. Nice.

**Pull request merged**
