### PR TITLE
[COC] Update contact section in Code of Conduct

### PR DESCRIPTION
**Pull request by franzihei**
Updates the ``Enforcement`` section of the Code of Conduct to reflect the current contact email address for the team leads.

### CODE REVIEW

**Comment by ekpyron** [comment]
I think it's conceptually important to keep two disjoint points of contact (for complaints regarding the points of contact themselves).

**Review by NunoFilipeSantos — DISMISSED** [review]
Thank you. Merge it.

**Comment by NunoFilipeSantos** [comment]
> I think it's conceptually important to keep two disjoint points of contact (for complaints regarding the points of contact themselves).

We should, yes. It is ok to merge for now. Who would you suggest that would not be part of that list?

**Comment by ekpyron** [comment]
> > I think it's conceptually important to keep two disjoint points of contact (for complaints regarding the points of contact themselves).
> 
> We should, yes. It is ok to merge for now. Who would you suggest that would not be part of that list?

Somebody in the EF outside our team, that's how Hudson ended up in there as well - we have to ask around who'd be up for it there.

**Comment by franzihei** [comment]
updated it to include our people ops contact as a neutral second contact person

**Review by ekpyron — APPROVED** [review]

**Pull request merged**
