### PR TITLE
Test to check whether FixedHash implementation seg faults

### PR DESCRIPTION
**Pull request by bshastry**
I created this PR to demo the seg fault in issue #10436

### CODE REVIEW

**Comment by axic** [comment]
So it seems not to be a problem on macos, likely due to libstdc++ vs. stdc++ differences.

**Comment by bshastry** [comment]
> So it seems not to be a problem on macos, likely due to libstdc++ vs. stdc++ differences.

Hmm... the local version I have is compiled against clang 12 and libc++ from llvm trunk

**Comment by bshastry** [comment]
It looks like the test added in this draft PR fails on Windows and Ubuntu CLI

**Comment by leonardoalt** [comment]
Can you move the test under `test/libsolidity/smtCheckerTests` instead of syntaxTests?

**Comment by bshastry** [comment]
> Can you move the test under `test/libsolidity/smtCheckerTests` instead of syntaxTests?

@leonardoalt would you like for this PR to be eventually merged as a test case only PR? I was thinking of closing it since the original issue was now resolved through https://github.com/ethereum/solidity/pull/10494

**Comment by ekpyron** [comment]
I'd say we can close this - but maybe we should open an issue for https://github.com/ethereum/solidity/issues/10436#issuecomment-739785974 ... (at least, if no-one will look into it right away). I.e. running the smt-checker tests as compile-only tests (while ignoring the actual expectations) in the absense of SMT solvers. That would have caught https://github.com/ethereum/solidity/issues/10436 and would catch similar issues in the future.

**Comment by leonardoalt** [comment]
Sure, also fine with closing.

**Comment by ekpyron** [comment]
> Sure, also fine with closing.

Yeah - in case you didn't read that: the thing is that moving the test to the smtchecker tests, where it would conceptually belong, would have prevented the test from being run in the cases in which it'd actually trigger the issue, so not much point in putting it there :-). On the other hand not moving it there will have it fail whenever there *is* an SMT solver... so we need to solve this differently anyways...

**Comment by leonardoalt** [comment]
Yes, that makes sense. The windows builds don't have solvers, but they also run only with `--no-smt` I think. Maybe one easy way to solve that is adding one run with smt to the windows tests

**Comment by ekpyron** [comment]
Even if ``--no-smt`` is not given, the test logic will still skip the tests, if there's no solvers, I think :-).

**Pull request closed without merging**
