### PR TITLE
update smt tests z3 4.8.16

### PR DESCRIPTION
**Pull request by leonardoalt**
I have NO IDEA why the new version is outputting so many new invariants

### CODE REVIEW

**Review by blishko — COMMENTED** [review]
@leonardoalt , there is something weird about all this invariants.
From what I have seen in the diff, it looks like it adds `|| true` to the invariants it discovered Which is weird because if you add `or true` to a formula you basically get just `true`. Which is an invariant but not very useful.
Are you sure this should be happening?

Also there are contract invariants now that look like `true || true || true`, which again, does not seem very useful...

**Comment by leonardoalt** [comment]
> @leonardoalt , there is something weird about all this invariants. From what I have seen in the diff, it looks like it adds `|| true` to the invariants it discovered Which is weird because if you add `or true` to a formula you basically get just `true`. Which is an invariant but not very useful. Are you sure this should be happening?
> 
> Also there are contract invariants now that look like `true || true || true`, which again, does not seem very useful...

Yea also noticed that they look weird. I haven't yet checked if the weirdness is coming from the solver or a bug on our side. However the `|| true` stuff is not coming only from this version, many invariants in our tests already had that stuff before.

**Review by hrkrshnn — APPROVED** [review]

**Review by Sticknmove — COMMENTED** [review]
Wow thanks

**Comment by Sticknmove** [comment]
Thanks

**Comment by Sticknmove** [comment]
Thanks

**Pull request merged**
