### PR TITLE
Appveyor prerelease release - PR to release branch

### PR DESCRIPTION
**Pull request by chriseth**
This is a pull request to the release branch in order to test the new code (it will also be executed for pull requests against release, not only commits on release).

### CODE REVIEW

**Review by axic — DISMISSED** [review]

**Comment by chriseth** [comment]
It did not work, windows is still reporting `-nightly` (all other platforms report a release build).

**Comment by chriseth** [comment]
Had a look at the binary with a hex editor and could not find the word `nightly` except in an error that nightly versions are strictly less than released versions.

**Comment by axic** [comment]
@chriseth does this needs to be merged into develop?

**Comment by chriseth** [comment]
Eventually yes, but it is not important.

**Pull request merged**
