### PR TITLE
Removed "using namespace util" directive from ASTAnnotations.h #12743

### PR DESCRIPTION
**Pull request by YashAtwal**
removed "using namespace util;"

### CODE REVIEW

**Comment by chriseth** [comment]
Thank you for your pull request! Did you try to compile it? It seems that `SetOnce` now needs to be qualified.

**Comment by YashAtwal** [comment]
How would SetOnce be qualified?

**Comment by chriseth** [comment]
I would assume using `util::SetOnce`

**Review by nishant-sachdeva — COMMENTED** [review]
I tried removing the "using namespace util" line from the file "ASTAnnotations.h" . Looks like this change spawns errors down the line in many files and we'll have to individually pick and fix all of those changes.

Are we sure if this removal is worth it?

**Comment by cameel** [comment]
Looks like we got a similar PR just merged: #12746.

This one was first but the other one addresses the problem fully, passes tests and is already merged so I'm going to close this one.

**Pull request closed without merging**
