### PR TITLE
Run solc-js tests in parallel on circleci.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by leonardoalt** [comment]
But this won't help if the smtchecker tests run sequentially anyway, right?

**Comment by chriseth** [comment]
I hope it helps at least a little. It splits based on filename, so if you split the smt chekcer tests into multiple files, it will also help there.

**Comment by chriseth** [comment]
41 seconds - did it run all tests?

**Comment by chriseth** [comment]
Ah, it was just the first run that took 41 seconds, the other tests are still running.

**Comment by leonardoalt** [comment]
> I hope it helps at least a little. It splits based on filename, so if you split the smt chekcer tests into multiple files, it will also help there.

Not sure how that would go: the slow smtchecker tests are basically a single JS test that traverses `test/smtCheckerTests/*` and runs the compiler on them.

**Comment by chriseth** [comment]
Is in probably that a small number of smt checker tests fail via solc-js while they are all green via solc? Does it make sense to test on a pseudo-random sample?

**Comment by leonardoalt** [comment]
This timeout thing is unrelated to solc vs solcjs. The issue there is Circle CI's timeout without any output. So even though solc and solcjs agree on the results of the smtchecker tests, circle CI complains about its own timeout.

**Comment by leonardoalt** [comment]
The reason why this test takes so much longer on circle CI could be that it runs via soljson's integrated z3 but it actually disagrees with solc, taking much longer. Besides, if it times out, solcjs also runs z3 or cvc4 on the cli, taking even longer. We could reduce the smtchecker's rlimit even more, at the cost of some tests having worse results.

**Comment by chriseth** [comment]
Closing since we will probably find a different solution and there is quite some overhead in setting up the executors.

**Pull request closed without merging**
