### PR TITLE
Added a Gitpod configuration file to install dependencies and build Solidity

### LINKED ISSUE #12112: Consider adding Gitpod support for contributors to the codebase
## Abstract

This is not so much a problem but a way to enable more folks to potentially contribute to Solidity. The proposal is to give contributors the option to work on the Solidity codebase in a cloud-based IDE. Gitpod is cloud-based IDE development environment that would enable this.

## Motivation

Potentially enable more folks to be able to contribute to the codebase.

## Specification

Gitpod would be configured to install the necessary dependencies for Solidity and build it. I've already configured Gitpod as I was looking to contribute to the codebase through Gitpod. See https://github.com/nickytonline/solidity/tree/nicktyonline/add-gitpod-to-solidity.

image

If the maintainers think this is a good idea, I'd love to put up a pull request from my branch.

## Backwards Compatibility

N/A

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Adds a [Gitpod configuration](https://www.gitpod.io/docs/config-gitpod-file) to the project to allow potential contributors to work in [Gitpod](https://gitpod.io/), a cloud based IDE.

Solidity in a Gitpod environment

## Related Tickets & Documents

Closes #12112

## [optional] What gif best describes this PR or how it makes you feel?

A kid dressed as a cowboy doing finger guns

### CODE REVIEW

**Comment by nickytonline** [comment]
As per discussions in the linked issue, I just need to modify the compilation so it builds for debug and not release mode.

**Comment by nickytonline** [comment]
The CI failures are not related to the changes in this PR. It looks like the cache files could not be untarred.

```
Found a cache from build 875765 at dependencies-osx-m4IPuOF6AzBveJ0ODA9CgZesqDrXf8kaIqcSHSF9C9k=
Size: 1.1 GiB
Cached paths:
  * /usr/local/bin
  * /usr/local/sbin
  * /usr/local/lib
  * /usr/local/include
  * /usr/local/Cellar
  * /usr/local/Homebrew

Downloading cache archive...
Unarchiving cache...

Failed to unarchive cache

Error untarring cache: Error extracting tarball /var/folders/1b/gl7yt7ds26vcyr1pkgld6l040000gn/T/cache4155664040 : usr/local/Homebrew/Library/Homebrew/shims/scm: Can't remove already-existing dir tar: Error exit delayed from previous errors. : exit status 1
```

**Comment by cameel** [comment]
You need to rebase on latest `develop`. This was fixed in #12131.

**Comment by nickytonline** [comment]
I've been having trouble with Ubuntu taking the PPA or maybe it's something I'm misunderstanding.

```
sudo add-apt-repository -y ppa:ethereum/ethereum
sudo apt-get -y update
sudo apt-get -y install build-essential libboost-all-dev libz3-dev
```

These are the versions that get installed after running the above.

```
sudo apt-get -y install build-essential libboost-all-dev libz3-dev

Reading package lists... Done
Building dependency tree       
Reading state information... Done
libboost-all-dev is already the newest version (1.71.0.0ubuntu2).
libz3-dev is already the newest version (4.8.7-4build1).
build-essential is already the newest version (12.8ubuntu1.1).
0 upgraded, 0 newly installed, 0 to remove and 109 not upgraded.
```

> We normally require the latest stable version (4.8.12) because that's the only version where SMT tests will pass. We maintain a PPA that provides this version (see Installing the Solidity Compiler > Linux Packages).

https://github.com/ethereum/solidity/issues/12112#issuecomment-944402060

I'm still getting this when trying to compile

```
-- Found Z3: /usr/lib/x86_64-linux-gnu/libz3.so (found version "0.0.0") 
CMake Error at CMakeLists.txt:74 (message):
  SMTChecker tests require Z3 4.8.12 for all tests to pass.

  Build with -DSTRICT_Z3_VERSION=OFF if you want to use a different version.
  You can also use -DUSE_Z3=OFF to build without Z3.  In both cases use
  --no-smt when running tests.
```

So I'm not sure why it's not installing 4.8.12 for libz3-dev. I did take a peek in ppa:ethereum/ethereum and it doesn't appear to reference libz3-dev unless It's in another dependency.

**Comment by ekpyron** [comment]
The build dependencies are not in the official release PPA repository (you don't need them if you just want to install the compiler binary), but in a separate dependency repository: https://launchpad.net/~ethereum/+archive/ubuntu/cpp-build-deps. The required z3 package in that repository is called ``libz3-static-dev``.

So maybe try
```
sudo add-apt-repository ppa:ethereum/cpp-build-deps
sudo apt-get update
sudo apt-get -y install build-essential libboost-all-dev libz3-static-dev
```
?

**Comment by nickytonline** [comment]
> The required z3 package in that repository is called `libz3-static-dev`.
> 
> So maybe try
> 
> ```
> sudo add-apt-repository ppa:ethereum/cpp-build-deps
> sudo apt-get update
> sudo apt-get -y install build-essential libboost-all-dev libz3-static-dev

Thanks @ekpyron! I'll give that a go. 😎

**Comment by nickytonline** [comment]
Thanks @ekpyron. That ppa definitely fixes the z3 version issue. 😎

@cameel, I don't think it makes sense to build the source when the container pre-builds as that might not be the action a contributor wants to take. I would assume they'd want to investigate the issue/feature first and then compile when they feel it's necessary. This way as well, it does not force them into a specific compilation, i.e. flags passed to build.

I think having gitpod as an environment with the appropriate dependencies in place for someone to contribute on the project makes the most sense, and not bothering with building source right away, but would love your feedback.

Once we've decided what makes sense for gitpod, I will also update documentation so that folks are aware that gitpod is an option for contributing to the project.

**Comment by chriseth** [comment]
I know that you put a lot of effort into this, but we discussed it again in the team and concluded that we do not want specialized configuration files inside the repository. If gitpod starts a general standardization effort that is used across many IDEs we might reconsider this. Otherwise, we feel that the configuration file should better be stored with gitpod instead of inside the repository itself.

**Pull request closed without merging**
