### PR TITLE
functionCallKindChecker implemented, checks which type of functioncal is in context

### PR DESCRIPTION
**Pull request by Meshugah**
This is my first PR here, I'll delete the comments once I add all the requisite functions. Besides that, please point out anything I can do better!

### Your checklist for this pull request

Please review the [guidelines for contributing](http://solidity.readthedocs.io/en/latest/contributing.html) to this repository.

Please also note that this project is released with a [Contributor Code of Conduct](CONDUCT.md). By participating in this project you agree to abide by its terms.

### Checklist
- [ ] Code compiles correctly
- [ ] All tests are passing
- [ ] New tests have been created which fail without the change (if possible)
- [ ] README / documentation was extended, if necessary
- [ ] Changelog entry (if change is visible to the user)
- [ ] Used meaningful commit messages

### Description
Please explain the changes you made here.

Thank you for your help!

### CODE REVIEW

**Comment by chriseth** [comment]
Thanks for your contribution! Please avoid adding unnecessary whitespace and read about the coding style. Also I would suggest to name functions in verbal form and use substantives only for classes.

**Comment by axic** [comment]
Thanks! Can you please explain the reason for this change?

**Comment by Meshugah** [comment]
@axic I was assigned to it [here](https://github.com/ethereum/solidity/issues/4894#issuecomment-424043517). I hope I'm going about submitting PRs and handling my issue correctly, if not, please advise.

**Comment by chriseth** [comment]
@Meshugah I'm sorry, but I fear we cannot accept pull requests in such a form. Please either clean up the pull request so that it does not touch any unrelated lines (and squash) and explain why you decided to split it up like this or close the pull request.

**Comment by Meshugah** [comment]
@chriseth I will clean it up before I submit my next pull request with reasons why i chose to split it up.

**Pull request closed without merging**
