### PR TITLE
Disable bytecode upload on AppVeyor builds on PRs.

### PR DESCRIPTION
**Pull request by ekpyron**
Let's see what happens...

### CODE REVIEW

**Comment by ekpyron** [comment]
Travis pushed everything correctly to https://github.com/ethereum/solidity-test-bytecode/tree/master/2020-02-07-73bc433b8c46c56bd46b193ae481ceac7a597897 now with a matching sha512 hash of the report, but https://ci.appveyor.com/project/ethereum-free/solidity/builds/30647484 remains queued at the time of writing. If that ends up pushing to the same directory and - given the python script change for the line endings - produces the same hash, then this PR should be fine.

EDIT: yes all seems fine!

**Comment by leonardoalt** [comment]
Still WIP?

**Comment by ekpyron** [comment]
Nope, this works and is theoretically done - but @chriseth doesn't want it and wants to instead have the bytecode comparisons *also* disabled for the appveyor runs on PRs :-).

**Comment by chriseth** [comment]
I want this to run all on circleci only at some point in the future.

**Comment by ekpyron** [comment]
I repurposed this for disabling the bytecode upload on appveyor runs on PRs.
I'm rather blindly editing the appveyor script, though, so we should verify that it does in fact *not* push bytecode in https://ci.appveyor.com/project/ethereum-free/solidity/builds/30789276 and - if we merge - that it *does* upload bytecode on the merge to develop.

**Comment by ekpyron** [comment]
Ok the test run in this PR looks good, so as far as I'm concerned we can merge this and then check the runs on develop.

**Review by chriseth — APPROVED** [review]

**Pull request merged**
