### PR TITLE
Jumps with annotations cannot be functional.

### PR DESCRIPTION
**Pull request by chriseth**
Split out from https://github.com/ethereum/solidity/pull/5404/files

Did not add tests because this component has zero tests and is not fully specified anyway.

### CODE REVIEW

**Comment by axic** [comment]
The `jump // in(tag_2)` is the old way.

```
   swap1
-  jump // in(tag_2)
+  tag_2
+  jump // in
 tag_1:
```

**Comment by chriseth** [comment]
@axic I don't understand your comment. Is it a review or not? Do you want me to change anything?

**Comment by axic** [comment]
I do not know enough about this part of the assembler to judge it.

This is the difference in the output after the change.

**Comment by chriseth** [comment]
Right. The `(tag_2)` is the argument for the `jump`, and it should be `jump(tag_2)`, but since there is a jump annotation, it adds it as a comment - `// in`. But this means that the line cannot really continue here, i.e. you cannot really add the arguments anymore. Because of that, it cannot be functional.

**Comment by leonardoalt** [comment]
What does `cannot be functional` mean?

**Comment by chriseth** [comment]
Instructional: `1 2 add`

Funcitonal: `add(2, 1)`

**Review by leonardoalt — APPROVED** [review]

**Pull request merged**
