### PR TITLE
Allow frameworks to filter warnings.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Review by axic — APPROVED** [review]

**Comment by axic** [comment]
Fails with
```
Running 1573 test cases...
unknown location(0): fatal error in "function_no_implementation": memory access violation at address: 0x00000000: no mapping at fault address
/home/travis/build/ethereum/solidity/test/libsolidity/AnalysisFramework.cpp(93): last checkpoint
```

**Comment by chriseth** [comment]
This should fix it.

**Comment by axic** [comment]
```
c:\program files (x86)\microsoft visual studio 14.0\vc\include\type_traits(1468): error C2220: warning treated as error - no 'object' file generated [C:\projects\solidity\build\test\soltest.vcxproj]
c:\program files (x86)\microsoft visual studio 14.0\vc\include\type_traits(1468): warning C4172: returning address of local variable or temporary [C:\projects\solidity\build\test\soltest.vcxproj]
c:\program files (x86)\microsoft visual studio 14.0\vc\include\functional(212): warning C4172: returning address of local variable or temporary [C:\projects\solidity\build\test\soltest.vcxproj]
```

**Comment by chriseth** [comment]
Argh, this looks like it compiles fine on the version that actually does take the address of a temporary but complains on the version that does not...

**Pull request merged**
