### PR TITLE
clang-tidy: Apply modernize-use-nodiscard.

### PR DESCRIPTION
**Pull request by aarlt**

### CODE REVIEW

**Comment by chriseth** [comment]
I really think this is not useful and clutters a lot.

**Comment by aarlt** [comment]
I see this quite neutral, but it definitely clutters a lot. Should I close this PR?

@ekpyron any opinions?

**Comment by ekpyron** [comment]
I'd also weakly vote for not doing this in general, but only in special cases like ``Result<T>``.

**Comment by aarlt** [comment]
Ok, will close this.

**Pull request closed without merging**
