### PR TITLE
Piper/style guide function modifiers

### PR DESCRIPTION
**Pull request by pipermerriam**
### What was wrong

The style guide had a `TODO` for function declarations.
### How was it fixed.

I took some of the recommendations from the previous [pull request](https://github.com/ethereum/solidity/pull/196) from @chriseth @rabbit as well as general practices seen in other codebases and my own and tried to cover the most general cases for function declarations.

This addition tries to cover.
- General declaration and placement of parenthesis on simple short functions
- Ordering of modifiers
- Wrapping of arguments for long declarations
- Wrapping of modifiers for long declarations
- Wrapping of base constructors.
- Parenthesis placement for situations where the constructor spans multiple lines.

_I also took the liberty of fixing a few indentation issues with the other code blocks._
#### Cute animal picture

tumblr_mnvcbijrtk1qf47bgo1_500

### CODE REVIEW

**Comment by rabbit** [comment]
It helps me to type it out to see how it feels. I'm ok with these changes. If this gets merged I'll adopt. Are these examples correct?

```
contract Example {

    function foobar(address one, address two, address three, address four,
                    address five, address six)
        modifierOne
        modifierTwo(withArgs)
        modifierThree
        modifierFour
        modifierFive
        returns (bool)
    {

    }

    function foobar(address one, address two, address three, address four,
                    address five, address six)
        returns (bool)
    {

    }

    function foobar(address one, address two, address three, address four,
                    address five, address six)
    {

    }

    function foobar(address one, address two)
        modifierOne
        modifierTwo(withArgs)
        modifierThree
        modifierFour
        modifierFive
        returns (bool)
    {

    }

    function foobar(address one, address two) returns (bool) {

    }

}
```
- if the prototype fits on one line, use one line that includes the open bracket
- if the prototype needs more than one line, place bracket on its own line (?)
- (imho) visibility specifiers (public/private/internal/external) should always appear immediately after the arguments list

**Comment by rabbit** [comment]
Might need to address the inheritance since it can also contain args...

```
contract SomethingReallyGreat is ThisOtherThing("https://long.example.uri/used/for/protocol/namespace", "https://long.example.uri/used/for/desired/endpoint?"), SomethingElse, AndOneLastThing {
}
```

```
contract SomethingReallyGreat is
    ThisOtherThing(
        "https://long.example.uri/used/for/protocol/namespace",
        "https://long.example.uri/used/for/desired/endpoint?"),
    SomethingElse,
    AndOneLastThing
{
    // very edge case, probably won't come up much
}
```

**Comment by pipermerriam** [comment]
@rabbit 

> Are these examples correct?

Yes, I think all of the examples you typed out are good.  There are so many permutations that I struggled with what level of detail to go into.  Do you think it adds to the document to include some or all of these?  Potentially in an addendum section at the end of the **Function Declarations** section?

**Comment by rabbit** [comment]
ya, it runs the risk of inviting bikeshedding the deeper down the rabbit hole one goes. It would probably be smart to have an edge cases section that also invites the reader to submit their recommendation to the guide.

**Comment by pipermerriam** [comment]
@rabbit 

> Might need to address the inheritance since it can also contain args...

It seems very similar to lots of the function stuff.  Do you think it's worth adding as it's own section or as part of the Function Declaration section?  I sort of want people to derive the intent rather than a set of rules and it already feels pretty overly specific.

Maybe taking some time rewording the paragraphs to address the readability component and to try to talk about them as guiding principles rather than hard rules.

**Comment by rabbit** [comment]
I leave it to you. My brain wants to be verbose, so I can't tell what's appropriate. 😅

**Comment by pipermerriam** [comment]
> I leave it to you.

After spending a few minutes trying to fit it into the document and failing I'm going to opt to leave the bit about contracts out.  If someone feels strongly that it should be included speak up.  This section already feels a bit bike-sheddy so I'm hoping it can get a little love an care as we iterate on the document.

**Comment by chriseth** [comment]
Suggestion for another way to use brackets and braces (taken from cpp-ethereum coding style):

```
function f(
    unit a,
    uint b,
    uint c
)
    mod1,
    mod2,
    mod3
{
   CODE
}
```

i.e. closing bracket / brace always starts a new line and is at the same indentation level as the opening bracket / brace (but not necessarily aligned with it).
Without modifiers:

```
function f(
    unit a,
    uint b,
    uint c
) {
   CODE
}
```

**Comment by pipermerriam** [comment]
> Suggestion for another way to use brackets and braces (taken from cpp-ethereum coding style):

I really like this.  I've adjusted the guide to use this style.

**Comment by chriseth** [comment]
Any comments? Good to be merged?

**Comment by pipermerriam** [comment]
I'm :+1: on this as a starting point.

**Pull request merged**
