### PR TITLE
BREAKING: Remove after

### LINKED ISSUE #815: Remove `after`
Because of ambiguities in its use, the `after` keyword (which is currently undocumented) should be removed.

### PR DESCRIPTION
**Pull request by Denton-L**
I would like to issue a compiler error stating that `after` is deprecated if someone attempts to use it but I'm not quite sure which file I should put that in. @chriseth, could I have a little bit of help?

Resolve #815

### CODE REVIEW

**Comment by VoR0220** [comment]
I don't think you necessarily need to add an error to it, it never was really in use, just was reserved in the token list. A simple removal should do. 

Edit: Okay it was in use...but a warning should suffice instead of an error.

**Comment by Denton-L** [comment]
Sorry, just noticed your comment.

I think @chriseth wanted `after` completely removed from the compiler in #815, though, so I don't think a warning would suffice.

**Comment by VoR0220** [comment]
@Denton-L just treat it as an identifier from now on. In order to throw an error for it, you'd have to reserve it as a keyword which is exactly what we're eliminating...so I'm not sure what the procedure would be for this unless you were to specify the identifier "after" in the context in which it was previously used and then throw an error for that.

**Comment by chriseth** [comment]
looks good apart from build breaks

**Comment by Denton-L** [comment]
Hmmm, it builds locally on my machine... Not sure why it's failing the CI.

**Comment by bobsummerwill** [comment]
HEAD is showing as broken in Appveyor, so all the PRs are broken too.

I am investigating right now, @Denton-L.

Broken was introduced at https://ci.appveyor.com/project/ethereum/solidity/build/0.3.5.88

**Comment by bobsummerwill** [comment]
Could you `git push --force` it, @Denton-L?
Or just merge/rebase your PR?   Should work now against current HEAD, I think.

**Comment by Denton-L** [comment]
Alright, I rebased it.

**Comment by bobsummerwill** [comment]
Ooh - green.   Nice, @Denton-L :-)

**Pull request merged**
