### PR TITLE
Suppress a warning in LLL parser on MSVC 2015

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Please could you do a pragma push/pop pair around just the problem lines?   Thanks!

**Comment by chriseth** [comment]
@bobsummerwill not too bad,because it is a cpp file. What is the warning about?

**Comment by bobsummerwill** [comment]
Yeah, @chriseth - better to bracket it, though, rather than just rely on the end of the compilation unit.

I imagine it's the same as this, eh, @chfast?

http://stackoverflow.com/questions/34709284/how-do-i-deal-with-warnings-generated-by-boost-spirit

**Comment by chfast** [comment]
Yes. This warning. Also boost complains about using some deprecated
headers.

As long as push/pop is considered I'm in favor of @chriseth's opinion. It's
like `using namespace`.

**Comment by bobsummerwill** [comment]
There are two reasons I prefer the push/pop:
1. Because it minimizes the warning suppression to only the "bad code" which we can't fix.
2. Because if we do https://github.com/ethereum/webthree-umbrella/issues/415 (which I do plan to attempt), the compilation unit boundaries change, and this warning can then end up spanning huge chunks of code.

Also, it's easy to do.   Just like an #ifdef/#endif conditional.    The symmetry makes sense.    Yes, you can probably "get away" with no doing it, but why be lazy?

**Comment by bobsummerwill** [comment]
PS.   Should have a comment explaining the warning suppression too.   What the warning is, and where the failures show up without the suppression.

We should probably report the issue to the Boost team too, if it's a legitimate problem in their code.

**Pull request merged**
