### PR TITLE
Prefix EIP-615 opcodes with EIP615 in Instructions

### PR DESCRIPTION
**Pull request by axic**
This is in preparation of #8809, I think it would make that PR nicer.

This can be closed too if unwanted.

### CODE REVIEW

**Comment by chriseth** [comment]
I actually think we should remove those not used in the PR

**Comment by axic** [comment]
> I actually think we should remove those not used in the PR

You mean some of the non-used opcodes or the entire thing?

**Comment by chriseth** [comment]
only those not part of the new reduced-scope eip.

**Comment by axic** [comment]
> only those not part of the new reduced-scope eip.

The goal of this PR is to decouple #8809 and the existing "evm1.5" target. After this renaming, it is possible to merge #8809 without any blockers and we can opt to remove this old "evm1.5" code separately. At least that is my goal.

**Comment by axic** [comment]
@chriseth is that reasoning understandable?

**Review by chriseth — APPROVED** [review]

**Pull request merged**
