### PR TITLE
Issue warning for using public visibility for interface functions

### LINKED ISSUE #3442: Interfaces: require external visibility
The [Ethereum ABI specification](https://solidity.readthedocs.io/en/develop/abi-spec.html) does not make a distinction between `external` and `public` functions. Therefore the `Interface` keyword likewise should not so distinguish.

Currently `private` and `internal` are disallowed in `interfaces`s.

For clarity, only `external` functions should be allowed in `interface`s.

### PR DESCRIPTION
**Pull request by axic**
Fixes #3442.

### CODE REVIEW

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
Test failures

**Comment by axic** [comment]
Should be fixed now.

**Comment by axic** [comment]
Zeppelin tests fail and it seems unrelated or the messages it outputs are very misleading if they are related.

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
Failures are weird, but I cannot see any way they could be related.

**Pull request merged**
