### PR TITLE
[SMTChecker] Fix internal error when increment/decrement is applied on a result of push().

### LINKED ISSUE #9744: [SMTChecker] ICE in unaryoperator end visit
## Description

```
pragma experimental SMTChecker;
contract C {
  int[][] array2d;
  function s() internal returns (int[] storage) {
    delete array2d.push();
    return array2d[2];
  }
}
```

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

## Steps to Reproduce

```
$ solc test.sol
```

### PR DESCRIPTION
**Pull request by blishko**
Fixes #9744.

### CODE REVIEW

**Review by leonardoalt — CHANGES_REQUESTED** [review]
Can you please also add the example from https://github.com/ethereum/solidity/issues/9744#issuecomment-740548425

**Review by leonardoalt — DISMISSED** [review]

**Comment by blishko** [comment]
Added the test. But I think I should remove the changelog entry, because this was not crashing in 0.7.5, it was merely unsupported. Right?

**Comment by leonardoalt** [comment]
Wasn't it crashing in the issue?

**Comment by blishko** [comment]
> Wasn't it crashing in the issue?

It was, but the issue was not for v0.7.5, but for develop (at that time). Since the changelog captures the changes between releases of the compiler, this probably should not be in the changelog, since the problem has been introduced after the last release, and hopefully will be fixed before this next release.

**Comment by leonardoalt** [comment]
Ah right, yea then I agree

**Review by leonardoalt — APPROVED** [review]

**Pull request merged**
