### PR TITLE
isoltest: WhiskersError and YulException treated differently when enforcing viaYul

### PR DESCRIPTION
**Pull request by mijovic**

### CODE REVIEW

**Review by ekpyron — APPROVED** [review]
Actually, I think we could even be stricter and *only* allow "unimplemented exceptions" to go, through, and throw for anything else... at least it'd be interesting how often that happens.
But doing things like this for now is fine with me as well!

**Comment by mijovic** [comment]
> Actually, I think we could even be stricter and _only_ allow "unimplemented exceptions" to go, through, and throw for anything else... at least it'd be interesting how often that happens.
> But doing things like this for now is fine with me as well!

I can also check if that would be OK as well. I am not sure if all Sol->Yul unimplemented features are throwing unimplementedAssert

**Comment by mijovic** [comment]
> > Actually, I think we could even be stricter and _only_ allow "unimplemented exceptions" to go, through, and throw for anything else... at least it'd be interesting how often that happens.
> > But doing things like this for now is fine with me as well!
> 
> I can also check if that would be OK as well. I am not sure if all Sol->Yul unimplemented features are throwing unimplementedAssert

I tried, and not all of the unimplemented features are throwing with solUnimplementedAssert...

**Comment by ekpyron** [comment]
> > > Actually, I think we could even be stricter and _only_ allow "unimplemented exceptions" to go, through, and throw for anything else... at least it'd be interesting how often that happens.
> > > But doing things like this for now is fine with me as well!
> > 
> > 
> > I can also check if that would be OK as well. I am not sure if all Sol->Yul unimplemented features are throwing unimplementedAssert
> 
> I tried, and not all of the unimplemented features are throwing with solUnimplementedAssert...

Yeah, I expected as much... it's probably too early to investigate those cases, but we should do so at some stage.

**Pull request merged**
