### PR TITLE
Document `after` keyword

### PR DESCRIPTION
**Pull request by Denton-L**

### CODE REVIEW

**Comment by chriseth** [comment]
`after` was not documented on purpose because I think its syntax is grossly misleading, especially if used together with timestamps. Take for example `if (now > after deadline)` - it does not do what you would expect it to do.

On the other hand, the meaning of `now + 1 day` is much easier to understand.

**Comment by Denton-L** [comment]
Hmmm, should we just close this and leave it undocumented, then?

**Comment by axic** [comment]
If the keyword is ambiguous, shouldn't it be removed from the language instead?

**Comment by chriseth** [comment]
Yes, please feel free to take this task: https://github.com/ethereum/solidity/issues/815

It will go into the next breaking release.

**Pull request closed without merging**
