### PR TITLE
Fix AST JSON converter type lookup

### PR DESCRIPTION
**Pull request by axic**

### CODE REVIEW

**Comment by axic** [comment]
Solidity doesn't compiles for me on Mac with clang without this.

**Comment by chriseth** [comment]
On the other hand, this does not compile for emscripten:
```
/src/libsolidity/ast/ASTJsonConverter.cpp:181:35: error: comparison of constant 18446744073709551615 with expression of type 'size_t' (aka 'unsigned int') is always true [-Werror,-Wtautological-constant-out-of-range-compare]

        solAssert(_info.second.valueSize <= std::numeric_limits<Json::LargestUInt>::max(), "");
```
Perhaps you could use a static_assert?

**Comment by axic** [comment]
This is the error on Emscripten:

```
/src/libsolidity/ast/ASTJsonConverter.cpp:181:35: error: comparison of constant 18446744073709551615 with expression of type 'size_t' (aka 'unsigned int') is always true [-Werror,-Wtautological-constant-out-of-range-compare]
        solAssert(_info.second.valueSize <= std::numeric_limits<Json::LargestUInt>::max(), "");
                  ~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

That constant is 64 bit which seems to be wrong, given Javascript can only handle 53 bits without loss (as it considers them float).

Seems like RFC7159 and RFC7493 mention that 53 bits is safe, but ECMA404 doesn't care about such details.

Assuming we rely on jsoncpp, we could remove the assert as is:
```
config.h:typedef unsigned int LargestUInt;
config.h:typedef UInt64 LargestUInt;
```

**Comment by chriseth** [comment]
Emscripten does support 64 bits perfectly without loss (https://kripken.github.io/emscripten-site/docs/porting/guidelines/portability_guidelines.html), it is just slow.

**Comment by axic** [comment]
I mean numbers in JSON can only be parsed without loss within Javascript if they do not exceed 53 bits. Though any large number can be stored in JSON, it may be just truncated after parsing :)

**Comment by axic** [comment]
Keep getting the invalid object stuff:
```
$ test $SOLC_STOREBYTECODE != On || (cd $TRAVIS_BUILD_DIR && scripts/bytecodecompare/storebytecode.sh)
Compiling all test contracts into bytecode...
Agent pid 16687
Identity added: deploy_key (deploy_key)
fatal: bad object 66ab4a203124f0eb7f5304fb63af09acd332e7dd
```

**Comment by chriseth** [comment]
This is the number of stack slots, so there should not be a problem. You can put in an assert to check that it is not larger than 20.

**Comment by axic** [comment]
I think it fine without an assert as the types are the same width?

**Review by chriseth — APPROVED** [review]

**Pull request merged**
