### PR TITLE
Disallow using overloaded functions as literal suffixes

### PR DESCRIPTION
**Pull request by cameel**
Part of #13718.
Depends on #12656.

The PR removes the two bits of code added in #12656 to handle overloading for suffixes that require fractional decomposition. It also blocks overloading for all other cases that already just worked.

I decided to make it a separate PR because I stand by my opinion that this feels very artificial and unnecessary. Apart from the single case that requires special handling (because it has no equivalent for functions) overloading just works. It's forbidding it requires introducing extra checks and increases complexity. Especially if we decide to disallow more - here I only disallowed the bare minimum:
- Overloaded calls to suffixes using the normal function call syntax are **not** disallowed.
- Overloaded suffix definitions are **not** disallowed.

### CODE REVIEW

**Comment by nikola-matic** [comment]
This is gonna need a changelog entry.

**Comment by cameel** [comment]
Not really. If we do merge it, it has to go together with the main PR and will be covered by its changelog entry. If it does not go into the same release, we may just as well close it because it'll be a breaking change.

**Comment by cameel** [comment]
Closing. The changes have now been added to #13718.

**Comment by cameel** [comment]
Oh, and the implementation of course has been changed to remove the `m_currentFunctionCall` variable and remove `arguments` so that the suffix is processed as a variable for the purpose of overload resolution.

**Pull request closed without merging**
