### PR TITLE
Removes support for old OS versions in install_deps.sh and adds support for new ones...

### PR DESCRIPTION
**Pull request by tqpcharlie**
I know that with #9582, this file will probably get removed, but still...

### CODE REVIEW

**Comment by cameel** [comment]
Looks good overall but I wonder if we really do want to remove all those old Ubuntu versions. Out of all systems, Ubuntu is probably the easiest for us to support since we use it a lot in CI and if they're not broken, we could just keep them there.

Also, not sure why Windows jobs are failing in CI. Its only in some PRs. I've restarted them and hopefully they will pass. The failure is definitely not related to the PR anyway.

**Comment by leonardoalt** [comment]
I think this PR makes sense. IMO we should remove even more :p
@ekpyron wdyt?

**Comment by cameel** [comment]
In any case this needs a rebase on `develop` for CI to pass. The windows/boost problem is fixed there.

These removed versions are very old so I don't have all that much against merging this but overall I think the next step in this task should be listing these dependencies in the docs (https://github.com/ethereum/solidity/issues/9582#issuecomment-900265173).

**Comment by ekpyron** [comment]
As for ubuntu versions: we also don't support building on Trusty, Xenial and Bionic (we do provide static PPA builds for those, but we don't support building on them)... but yeah, as mentioned elsewhere, I think we should remove the entire script anyways and I'm not sure why we don't just do that :-). But if we don't, reducing the versions here is fine, but yeah: Trusty, Xenial and Bionic are also unsupported.

**Comment by chriseth** [comment]
I'm also voting for removing the script.

**Comment by cameel** [comment]
@chriseth Do we want to at least get a list of deps for each platform in the docs before removing the file?

If we're just going to remove the script then I guess we can just close this PR.

**Comment by chriseth** [comment]
I kind of have the impression that if you compile yourself, you should also know how to install basic dependencies. Since we don't test the script, I don't think it makes sense to keep it. We can give some recommendations in the documentation, but not sure if we should be too detailed, like we should not tell how to use the package manager, but that you need boost and z3 and here is where you can get z3 and so on.

**Comment by leonardoalt** [comment]
Ok so do we just remove the script?

**Review by cameel — DISMISSED** [review]

**Comment by cameel** [comment]
Rebased on latest `develop`.

@leonardoalt I think you said you're going to remove the whole script. Are you still working on that?

**Review by cameel — APPROVED** [review]

**Pull request merged**
