### PR TITLE
Per project versioning

### PR DESCRIPTION
**Pull request by arkpar**

### CODE REVIEW

**Comment by arkpar** [comment]
https://github.com/ethereum/webthree-helpers/pull/18
https://github.com/ethereum/libweb3core/pull/6
https://github.com/ethereum/libethereum/pull/19
https://github.com/ethereum/mix/pull/75
https://github.com/ethereum/solidity/pull/79
https://github.com/ethereum/webthree/pull/41
https://github.com/ethereum/alethzero/pull/63
These PRs go together

**Comment by debris** [comment]
looksgood for umbrella

**Comment by arkpar** [comment]
Tested to work with split repos, just need other PRs merged

**Comment by chriseth** [comment]
Please merge as soon as all the others can be merged.

**Pull request merged**
