### PR TITLE
compile time reporting tool for solidity (as discussed on gitter)

### PR DESCRIPTION
**Pull request by raphael-s-norwitz**
This pull requests brings a compile time benchmarking feature into solidity, as discussed on the gitter channel https://gitter.im/ethereum/solidity-dev between @raphael-s-norwitz and @chriseth. It adds two new command line flags, `--ftime-report` and `--ftime-report-no-tree`. These flags do not alter any core compiler functionality, but provide a function call trace and time readings for each function call in the call stack. They are very similar to gcc's `--ftime-report` flag. See the following sample output:

```
raphael@raphael-laptop:~/solidity/scripts/docsSolidity$ ../../build/solc/solc --ftime-report-no-tree test_05a1405cae10eee3dd74ef31bc3cd541b3e5ba1d17816b47c6b2c92ee4d3e8b3.sol 
Warning: This is a pre-release compiler version, please do not use it in production.
namespace/function name                                               unix begin time(μs)    time elapsed(μs)   
--------------------------------------------------------------------------------------------------------------
CLI::readInputFilesAndConfigureRemappings                             469                     284                 
CompilerStack::setRemappings                                          760                     4                   
CompilerStack::setEVMVersion                                          796                     0                   
CompilerStack::compile                                                798                     3478                
 \_CompilerStack::parse                                               799                     100                 
 \_CompilerStack::analyze                                             900                     1124                
 \_CompilerStack::compileContract: StateMachine                       2027                    2246                
 \_CompilerStack::createMetadata                                      2043                    128                 
 \_Compiler::compileContract                                          2247                    1821                
 \_ContractCompiler::compileContract                                  2251                    600                 
 \_ContractCompiler::initializeContext                                2252                    17                  
 \_ContractCompiler::appendFunctionSelector                           2271                    235                 
 \_ContractCompiler::appendMissingFunctions                           2508                    341                 
 \_ContractCompiler::initializeContext                                2858                    8                   
 \_ContractCompiler::appendMissingFunctions                           2901                    0                   
 \_ContractCompiler::appendMissingFunctions                           2902                    0                   
 \_CompilerContext::optimse                                           2904                    1163                
 \_ContractCompiler::initializeContext                                4144                    8                   
 \_ContractCompiler::appendMissingFunctions                           4195                    0                   
CommandLineInterface::actOnInput                                      4320                    86                  
raphael@raphael-laptop:~/solidity/scripts/docsSolidity$ ../../build/solc/solc --ftime-report test_05a1405cae10eee3dd74ef31bc3cd541b3e5ba1d17816b47c6b2c92ee4d3e8b3.sol 
Warning: This is a pre-release compiler version, please do not use it in production.
namespace/function name                                               unix begin time(μs)    time elapsed(μs)   
--------------------------------------------------------------------------------------------------------------
CLI::readInputFilesAndConfigureRemappings                             356                     101                 
CompilerStack::setRemappings                                          464                     3                   
CompilerStack::setEVMVersion                                          498                     0                   
CompilerStack::compile                                                499                     3487                
 \_CompilerStack::parse                                               500                     93                  
 \_CompilerStack::analyze                                             595                     1032                
 \_CompilerStack::compileContract: StateMachine                       1629                    2354                
     \_CompilerStack::createMetadata                                  1644                    121                 
     \_Compiler::compileContract                                      1843                    1865                
         \_ContractCompiler::compileContract                          1846                    507                 
             \_ContractCompiler::initializeContext                    1847                    18                  
             \_ContractCompiler::appendFunctionSelector               1867                    182                 
             \_ContractCompiler::appendMissingFunctions               2051                    301                 
         \_ContractCompiler::initializeContext                        2359                    8                   
         \_ContractCompiler::appendMissingFunctions                   2402                    0                   
         \_ContractCompiler::appendMissingFunctions                   2403                    0                   
         \_CompilerContext::optimse                                   2405                    1301                
     \_ContractCompiler::initializeContext                            3787                    12                  
     \_ContractCompiler::appendMissingFunctions                       3860                    0                   
CommandLineInterface::actOnInput                                      4033                    89  

```

These debugging statements are added in the code by putting a `t_stack.push(<argument>);` function call before the section of code you wish to debug, where <argument> is the string you wanted printed, and a `t_stack.pop()` call immidiately after. Remember that if you are putting a t_stack.push() and pop() around a section of code with multiple return statements, you must add a t_stack.pop() call before each return statements.

As of now we have added these sparingly, and only around core functions in the compiler execution. 

See the main implementation in `libsolidity/interface/FTime.h` and `libsolidity/interface/FTime.cpp`. The boost test cases are located in `test/libsolidity/FTimeTest.cpp`.

Please contact us or comment if you have thoughts or other requests.

### CODE REVIEW

**Comment by axic** [comment]
Wow, this looks great! Have you run it on some bigger contracts to see what takes a long time?

**Comment by raphael-s-norwitz** [comment]
Of the function we profile here, for larger files, the three longest generally are `parse`, `analyze` and `appendMissingFunctions`. This shouldn't really be a surprise since they are very high level, but we are working on a more granular report, which we will share.

Suggestions of where to profile more would be very welcome!

**Comment by axic** [comment]
The (original) Parity wallet and "the DAO" are quite big chunks of code with large contracts and functions. Then again they may use outdated constructs which are suboptimal.

Other examples I think tend to have a lot more abstraction and bite-size chunks so perhaps a lot of those would need to be profiled to draw proper conclusions.

**Comment by chriseth** [comment]
I know we talked about that before, but at that time I thought this would just be a preliminary step to find the bottlenecks, but: What is the advantage of doing it like this over user an instrumented profiler?

Also, why didn't you use RAII to call `pop()`?

**Comment by raphael-s-norwitz** [comment]
I personally am not very familiar with instrumented profiling. For our class we were taught that the best way to perform profiling in C++ is to use chrono high_resolution clock. We thought our solution was simple and flexible, and we didn't know about any details existing libraries could provide us with that we couldn't get with chrono. I see there are a few different instrumentation profiling libraries for C++ around, and if there is one you would like us to use, we have time to incorporate it. 

In terms of RAII, we thought the push/pop approach was more flexible in terms of what could be profiled. If we used RAII, it would be harder to put multiple profiles within the same block. If you would rather push() only semantics where only a block is profiled at once, we can change it.

**Comment by chriseth** [comment]
I know you put a lot of effort into this, but I hope you understand that we don't merge it, since a similar effect can be achieved using profiling instrumentation.

**Pull request closed without merging**
