### PR TITLE
External test for Uniswap v3

### PR DESCRIPTION
**Pull request by cameel**
Part of #5956.
~Depends on #12531. Don't merge until that PR is merged.~ Merged.

This adds an external test for [Uniswap v3 core](https://github.com/Uniswap/v3-core). Still work in progress - I got it to compile but tests do not pass.

Hooking up Uniswap required quite a few workarounds:
- It's still on 0.7.6 so there were some missing explicit conversions. I patched them all with `sed` but I need to review them more carefully to make sure they keep the code working as intended. Some tests might be failing because of that.
- The code crashes the compiler due to a bug in Natspec. Reported in #12528.
- The config file exports settings without giving them a named variable. Because of this I cannot easily change settings. I had to add a helper for giving the variable a name (I've seen this in ElementFi too so It'll be useful).
- Tests run into the contract size limit just like in #12529 and #12530 and so this is another PR that has a copy of the commit that adds a helper for `allowUnlimitedContractSize`.
- This is yet another project that cannot be compiled via IR at all (#12343).

Even with these workarounds, over 150 tests fail for various reasons. Some due to checked math, some on unexpected values, some on JS errors (accessing `undefined`), which might be the symptom of Hardhat's heuristic not being prepared for IR.

The PR has some value even in the current form though so we might want to merge it anyway. Thanks to #12397 I can mark presets with failing tests as compile-only so they won't fail in CI. Then we could merge it as is and work on fixing the tests later.

### CODE REVIEW

**Comment by cameel** [comment]
Looking closer at failing tests - most of the ones where we get unexpected values are checking gas usage for exact values. I think we could ignore those. There are overall just a few kinds of errors so fixing them might actually not be all that hard.

**Comment by cameel** [comment]
Uniswap actually has an automatic update mechanism for these gas expectations (https://github.com/Uniswap/v3-core/issues/473):
```bash
UPDATE_SNAPSHOTS=1 yarn test
```

I'm going to add it to the test.

**Comment by hrkrshnn** [comment]
It might be possible that wrapping everything in unchecked would make the tests pass. I believe their math libraries rely on wrapping behaviour.

**Comment by cameel** [comment]
Right, but there seems to be a lot that need to be wrapped. Someone even already did that and the diff looks pretty large: https://github.com/Uniswap/v3-core/pull/505.

I wonder it it makes sense to use that PR here. It's not in the official repo and even the submitter says that it's not intended to be merged.

**Comment by cameel** [comment]
Uniswap test is working!

- With so many patches needed I decided to create a fork: https://github.com/solidity-external-tests/uniswap-v3-core
    - My patches are in [`main_080`](https://github.com/solidity-external-tests/uniswap-v3-core/tree/main_080).
    - I submitted part of the branch in a PR to Uniswap: https://github.com/Uniswap/v3-core/pull/527. It contains only explicit conversions and even then only those that don't make tests fail. Other changes unfortunately break backwards-compatibility with 0.7.6 so I don't think they would accept them.
        - One conversion unfortunately affects code generation (adds an extra `SIGNEXTEND` that is not getting optimized out) so it breaks tests on 0.7.6.
        - The only other thing needed were the `unchecked` blocks. Lots of `unchecked` blocks.
- I am using `UPDATE_SNAPSHOT=1` when running tests to silence failures due to different gas expectations.
- Some test expectations work only with older Hardhat. On the other hand we need newer Hardhat to handle Panics. Version 2.4.3 seems to be the sweet spot.
- Even with that there were issues with missing methods on newer `@ethereumjs/tx`. Had to force downgrade it to 3.1.3.

**Review by ekpyron — DISMISSED** [review]
Looks good, but again a (probably trivial) conflict with the last one I merged.

**Comment by cameel** [comment]
Yeah. Same thing as the last time - all of these PRs are appending to the end of the list of tests concurrently :) Resolved.

I also noticed that I forgot to remove the compile-only run for Uniswap. Removed it now. It's superfluous now that the run that includes tests is working.

**Comment by cameel** [comment]
Looks like the test is failing. It's because of the `??=` I used in `common.sh` in another ext test PR that's now merged. The operator is only available in Typescript 4 but Uniswap is on 3.7.3 and upgrading it breaks tests. I fixed it by replacing the operator with `??` which was already available in Typescript 3.7.

**Review by ekpyron — APPROVED** [review]

**Pull request merged**
