### PR TITLE
Create Complementary Strand in a DNA.cpp

### PR DESCRIPTION
**Pull request by arnav784**

### CODE REVIEW

**Comment by cameel** [comment]
Spam.

**Comment by Felixoid** [comment]
I kindly suggest adding a `spam` label here, it seems related to `hacktoberfest`

**Comment by cameel** [comment]
It was not merged so it should not count anyway. But we could add one if it actually has some effect. Is this something Hacktoberfest takes into account like `hacktoberfest-accepted`?

**Comment by Felixoid** [comment]
https://hacktoberfest.com/participation/

image

**Comment by cameel** [comment]
Thanks! So it seems that does have interesting effects, especially regarding disqualification. Added the label.

**Pull request closed without merging**
