### PR TITLE
Support multiple assignment in inline assembly

### LINKED ISSUE #2923: multiple assignment for IULIA

### PR DESCRIPTION
**Pull request by chriseth**
Fixes #2923.

### CODE REVIEW

**Comment by axic** [comment]
Added changelog and fixed travis.

**Review by chriseth — COMMENTED** [review]
Wonderful, thanks!

**Comment by axic** [comment]
Added tests for the parser errors and managed to crash:
```
unknown location:0: fatal error: in "JuliaParser/recursion_depth": memory access violation at address: 0x7fff54b11f50: invalid permissions
/Users/alex/Projects/solidity/test/libjulia/Parser.cpp:240: last checkpoint: "recursion_depth" entry.
```

**Comment by chriseth** [comment]
This probably means we incorrectly estimated the stack frame size on one of the architectures.

**Comment by axic** [comment]
It seems like going to a vector was enough to tip it over:
```diff
 -			assignment.variableName = identifier;
 +			assignment.variableNames.emplace_back(identifier);
```

**Review by axic — APPROVED** [review]

**Comment by axic** [comment]
Added more tests and fixed the stack limit for Mac.

**Comment by chriseth** [comment]
Good to merge!

**Comment by axic** [comment]
This crashes on travis:
```
/home/travis/build/ethereum/solidity/libsolidity/codegen/ContractCompiler.cpp(562): fatal error in "auto dev::solidity::ContractCompiler::visit(const dev::solidity::InlineAssembly &)::(anonymous class)::operator()(const assembly::Identifier &, julia::IdentifierContext, julia::AbstractAssembly &) const": std::exception: 
/home/travis/build/ethereum/solidity/test/RPCSession.cpp(324): last checkpoint
```

**Comment by axic** [comment]
This code is triggering it:
```
               contract C {
                        function f() pure returns (bytes32 ret) {
                                assembly {
                                        ret := keccak256(0, 0)
                                }
                        }
                        function g() pure returns (bytes32 ret) {
                                assembly {
                                        0
                                        0
                                        keccak256
                                        =: ret
                                }
                        }
                        function h() pure returns (bytes32 ret) {
                                assembly {
                                        ret := sha3(0, 0)
                                }
                        }
                        function i() pure returns (bytes32 ret) {
                                assembly {
                                        0
                                        0
                                        sha3
                                        =: ret
                                }
                        }
                }
```

Out of this, the stack assignment (`=: ret`) parts fail.

**Comment by chriseth** [comment]
Ok, should be working now.

**Comment by axic** [comment]
@chriseth please merge if tests pass

**Pull request merged**
