### PR TITLE
Change m_bytes to unsigned in FixedBytesType

### LINKED ISSUE #3965: Change m_bytes to unsigned in FixedBytesType
The member variable `m_bytes` is signed, although it can never be negative. We should change its type to be unsigned.

### PR DESCRIPTION
**Pull request by dbogs425**
Fixes #3965.

Changed m_bytes to an unsigned int

### CODE REVIEW

**Comment by axic** [comment]
Can you please cooperate with @danieljoonlee on #4012 ?

**Comment by dbogs425** [comment]
Sure, as long as I receive the bounty reward, I’ll allow him to take the clout.  I’ve never heard of “dibs” before on a bounty. Very disappointed. @danieljoonlee @axic

**Comment by axic** [comment]
I am not sure how it works on gitcoin, but it seems both of you've started at the same time.

Note that both PRs are far from complete.

**Comment by djl-gg** [comment]
@dbogs425 I've brought this up in the gitcoin slack community.  This isn't the first time I've seen this and people getting angry.  Generally it's not about who finishes a project first, for example, what if it's a 3-6 month project, probably want to communicate in that instance or poke to collaborate.

We can just split the PR and the bounty in this case.  I mainly just want to contribute to solidity since I'm a big fan of the ethereum ecosystem.

**Comment by dbogs425** [comment]
@danieljoonlee thanks for bringing up the issue with gitcoin, I'm a bit new to the OSS community sorry if I came off hotheaded.

**Pull request closed without merging**
