### PR TITLE
AsmAnalysis: Fix out of bounds read due to incorrect bounds checking …

### LINKED ISSUE #10609: [AsmAnalysis] Out of bounds read in operator()(FunctionCall const& _funCall)
## Description

```
{
  function f(a,b) {}
  f(x,1)
}
```

makes an invalid read here

https://github.com/ethereum/solidity/blob/4e86390e40e829a2121d0f913739479787cc3aad/libyul/AsmAnalysis.cpp#L335

because there are fewer literal arguments than total number of arguments

## Environment

- Compiler version: latest develop
- Target EVM version (as per compiler settings):
- Framework/IDE (e.g. Truffle or Remix):
- EVM execution environment / backend / blockchain client:
- Operating system:

## Steps to Reproduce

```
$ solc --strict-assembly test.yul
```

### PR DESCRIPTION
**Pull request by bshastry**
…on literal arguments

Fixes https://github.com/ethereum/solidity/issues/10609

### CODE REVIEW

**Review by chriseth — APPROVED** [review]

**Comment by chriseth** [comment]
The change looks good, but I was not able to reproduce the bug.

**Comment by bshastry** [comment]
> The change looks good, but I was not able to reproduce the bug.

I had to comment out the `catch` clauses in `CommandLineInterface` to make the exception throw on the command line.

**Comment by chriseth** [comment]
Can you explain why this problem can happen? Especially for a non-builtin function, ilteralArguments should always be nullptr.

**Comment by bshastry** [comment]
> Can you explain why this problem can happen? Especially for a non-builtin function, ilteralArguments should always be nullptr.

Ah, sorry. The tests added don't correspond to the fix. As you said, I incorrectly assumed literal arguments are non null for user defined functions. Please see the new PR with the missing test case that fixes the out of bounds read.

PR https://github.com/ethereum/solidity/pull/10613

**Pull request merged**
