### PR TITLE
[WIP] Constructor keyword for version 0.5.0

### PR DESCRIPTION
**Pull request by christianparpart**
This is removing the old behaviour of how contructors are declared and introduces the constructor keyword instead.

one test is failing though, which I'd appreciate feedback for.

### CODE REVIEW

**Comment by axic** [comment]
Can this be combined with #4215?

**Comment by christianparpart** [comment]
@axic yes it can. this PR exists for feedback on how to tackle this one particular issue (i.e. requesting for suggestions). OTOH, @chriseth told me also, that this check might valid anymore. The check failing is:

```
syntaxTests/constructor/overriding_constructor.sol: FAIL
  Contract:
    // It is fine to "override" constructor of a base class since it is invisible
    contract A { constructor() public { } }
    contract B is A { constructor() public { } }

  Expected result:
    Warning: (135-178): This declaration shadows an existing declaration.
  Obtained result:
    Success
```

I struggle finding both ctors in `B` (`B.constructor` and its inherited `A.constructor`) the way the check was coded before (`NameAndTypeResolver.cpp` in function `registerDeclaration(...)`).

**Comment by christianparpart** [comment]
@axic Eric will merge my work into his PR soon (we're in communication).

**Comment by erak** [comment]
This PR can probably be closed since we combined it with PR #4215. @christianparpart Please see my comment on the other PR regarding ``overriding_constructor.sol`` :) I think it should not report a warning anymore.

**Comment by christianparpart** [comment]
my work has been merged into the other PR. Thanks.

**Pull request closed without merging**
