### PR TITLE
Force commit hash to 8 digits.

### LINKED ISSUE #1094: Solc 0.4.1 throws an exception on a library compilation
Hi,

I have a library:

```
library ConvertLib{
    function convert(uint amount,uint conversionRate) returns (uint convertedAmount)
    {
        return amount * conversionRate;
    }
}
```

And solc fails if I try to compile the library:

```
root@ce27cd0e9bf7:~/workspace/my-truffle-project/contracts# solc ConvertLib.sol 
Internal compiler error during compilation:
/build/solc-24Vd54/solc-0.4.1/libsolidity/interface/Version.cpp(68): Throw in function dev::bytes dev::solidity::binaryVersion()
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: std::exception
[dev::tag_comment*] = 
```

Solc version:

```
root@ce27cd0e9bf7:~/workspace/my-truffle-project/contracts# solc --version
solc, the solidity compiler commandline interface
Version: 0.4.1+commit.4fc6fc2.Linux.g++
```

### PR DESCRIPTION
**Pull request by chriseth**
Fixes #1094

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Github shows only 7 digits for the short-hash.

I don't know if that is a Github-ism, or something coming from a git-de-facto standard?

But 7 seems to be the standard in my experience.

**Comment by axic** [comment]
@bobsummerwill it is git and not github. (`--short` rev).

**Comment by bobsummerwill** [comment]
Right, @axic.

Just looking at git docs, it is a little unclear whether it always sticks to 7, or extends further to make it non-ambiguous.     I don't think I have every seen Github UI extend from 7.

**Comment by chriseth** [comment]
@bobsummerwill the default is 7, yes, but we need 8 because we store it in a 4-byte fingerprint.

**Pull request merged**
