### PR TITLE
[BREAKING] drop opcodes

### PR DESCRIPTION
**Pull request by molecula451**
```
./solc --opcodes
unrecognised option '--opcodes'
```

#14033

### CODE REVIEW

**Comment by molecula451** [comment]
some other tests seems to be breaking but totally unrelated with this PR changes @cameel  @nikola-matic @ekpyron

**Comment by ALIR86** [comment]
The first pleasure I wanna install extension browser metamask and blockscreen in YouTube  for my 2 layer transaction  in official website WBTC:wrote:its monitoringed by  person from BTC 2 transactionin a 4 transaction  and next my assest labale on official website ://blockstream.com wrote confimation inmy addresses  BTC coins are in addresses difference front any address write :amount value pricein;the first  transaction that wrote addresses  WBTC click button any address address  or transaction confim its monitored  by BTC also ;company https://. www.WBTC .coming layer 1 wrote my assest WBTC I does taked screenshot for have ducoment  team token WBTC  finance wrote  
Screenshot_۲۰۲۳۱۱۱۶_۰۰۵۹۳۰_Edge
Screenshot_۲۰۲۳۱۱۱۶_۰۰۴۸۱۹_Edge
Screenshot_۲۰۲۳۱۱۱۶_۰۰۴۹۳۲_Edge
Screenshot_۲۰۲۳۱۱۱۶_۰۰۵۹۳۹_Edge
Screenshot_۲۰۲۳۱۱۱۴_۰۵۴۹۱۸_Edge
Screenshot_۲۰۲۳۱۱۲۴_۲۲۴۰۰۰_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۲۴۰۲۱_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۲۴۰۳۷_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۲۴۰۴۷_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۲۴۱۰۰_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۲۴۱۰۹_Microsoft 36
![Screenshot_۲۰۲۳۱۱۲۴_۲۳۱۱۵۰_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۲۴۴۵۴_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۳۱۶۰۴_Microsoft 365 (Office)
5 (Office)](https://github.com/ethereum/solidity/assets/119627571/6ed817f0-6d22-402d-9030-0b17551638c1)
Screenshot_۲۰۲۳۱۱۲۴_۲۲۴۱۱۸_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۲۴۱۲۷_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۲۴۱۴۰_Microsoft 365 (Office)
addresses only taked 2 screenshot for claimed now why datanot in avaliable and 0 befor 2 transaction by company or platform my finance WBTC  ihave 2 BTC that Uniswap.financial claimed use of my BTC coins but 1 BTC else who get of me without authorize  me I am a legalize and follow  Legal the means to means truly words I know you got it that .but Mr:Elon musk  in half near sended me of a pvt message I try really itself him was you will ask of him told me you are that somone !&that hodying  does several  yeas ago without any  transaction or trading a token  but harding  working  but had goal: I wanna my desire a day told me this Bitcoin.com;you're in a fined region ;I have 3 token in coinflex.com we cannot  support &you are in fined region and I deside had financial problems but keep value and hodying and hope  to future now some of they don't like growth me in had top assest BTC  .2 ducoment else is I can sent of company WBTC  for me ;a option as financial investor and gove and I am a validator accepted my account platform explorer ethereum ethescan.io;I have service to people and community 1 year due bugs hadnot wallet my ETH balance has help to miner ethereum;
Screenshot_۲۰۲۳۱۱۲۴_۲۳۱۵۵۸_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۳۱۵۵۲_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۳۱۵۴۶_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۳۱۵۳۶_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۳۱۵۲۸_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۳۱۵۱۹_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۳۱۵۱۲_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۳۱۵۰۵_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۳۱۴۴۶_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۳۱۴۵۶_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۳۱۴۴۶_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۳۱۴۳۹_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۳۱۱۵۹_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۳۱۱۵۰_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۳۱۴۳۴_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۲۴۴۵۴_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۲۴۴۴۶_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۲۴۴۳۷_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۲_۲۲۱۹۳۴_Chrome
Screenshot_۲۰۲۳۱۱۲۲_۲۲۱۸۵۸_Chrome
Screenshot_۲۰۲۳۱۱۲۲_۲۲۱۷۴۳_Chrome
Screenshot_۲۰۲۳۱۱۲۲_۲۲۱۸۴۹_Chrome
Screenshot_۲۰۲۳۱۱۲۲_۲۲۱۷۱۷_Chrome
Screenshot_۲۰۲۳۱۱۲۲_۲۲۱۷۳۶_Chrome
TV
Screenshot_۲۰۲۳۱۱۲۲_۲۲۱۶۱۹_Chrome
Screenshot_۲۰۲۳۱۱۲۲_۰۱۱۵۲۹_Discord
Screenshot_۲۰۲۳۱۱۲۴_۲۳۳۴۴۴_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۱۹_۲۰۵۳۰۴_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۰_۲۳۵۱۵۲_Chrome
Screenshot_۲۰۲۳۰۸۲۱_۱۸۰۶۲۴_Edge
Screenshot_۲۰۲۳۰۸۲۰_۲۳۳۱۱۵_Edge
Screenshot_۲۰۲۳۰۸۲۰_۲۳۳۰۴۰_Edge
Screenshot_۲۰۲۳۰۸۲۰_۲۳۳۰۰۷_Edge
Screenshot_۲۰۲۳۰۸۱۰_۰۳۲۸۳۵_Word
Screenshot_۲۰۲۳۰۸۲۰_۲۳۲۹۳۹_Edge
Screenshot_۲۰۲۳۰۸۰۵_۱۳۵۰۱۹_Edge
Screenshot_۲۰۲۳۰۸۰۵_۰۱۴۰۵۰_Edge
Screenshot_۲۰۲۳۰۸۰۵_۰۱۴۰۳۲_Edge
Screenshot_۲۰۲۳۰۸۰۵_۰۱۴۰۲۸_Edge
Screenshot_۲۰۲۳۰۸۰۵_۰۱۴۰۲۴_Edge
Screenshot_۲۰۲۳۰۸۰۵_۰۱۴۰۲۱_Edge
Screenshot_۲۰۲۳۰۸۰۵_۰۱۴۰۰۹_Edge
Screenshot_۲۰۲۳۰۸۰۵_۰۱۴۰۰۳_Edge
Screenshot_۲۰۲۳۱۱۲۴_۲۳۳۵۱۳_Microsoft 365 (Office)
Screenshot_۲۰۲۳۰۸۰۵_۰۱۳۹۴۴_Edge
Screenshot_۲۰۲۳۱۱۲۴_۲۳۳۵۲۴_Microsoft 365 (Office)
Screenshot_۲۰۲۳۰۸۰۵_۰۱۳۹۳۸_Edge
Screenshot_۲۰۲۳۰۸۰۵_۰۱۳۸۵۳_Edge
Screenshot_۲۰۲۳۱۱۲۴_۲۳۳۵۱۹_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۳۳۵۳۸_Microsoft 365 (Office)
Screenshot_۲۰۲۳۰۸۰۵_۰۱۳۷۲۱_Edge
Screenshot_۲۰۲۳۱۱۲۴_۲۳۳۵۳۲_Microsoft 365 (Office)
Screenshot_۲۰۲۳۰۸۰۵_۰۱۳۷۱۴_Edge
Screenshot_۲۰۲۳۱۱۲۴_۲۳۲۳۲۲_Microsoft 365 (Office)
Screenshot_۲۰۲۳۰۸۰۴_۱۷۳۲۳۰_Edge
Screenshot_۲۰۲۳۱۱۲۴_۲۳۲۳۱۴_Microsoft 365 (Office)
Screenshot_۲۰۲۳۰۷۲۷_۲۲۵۱۳۳_Gmail
Screenshot_۲۰۲۳۱۱۲۴_۲۳۲۳۴۱_Microsoft 365 (Office)
Screenshot_۲۰۲۳۱۱۲۴_۲۳۲۳۳۳_Microsoft 365 (Office)
Screenshot_۲۰۲۳۰۷۲۷_۲۲۵۱۲۶_Gmail
Screenshot_۲۰۲۳۱۱۲۴_۲۳۲۳۰۸_Microsoft 365 (Office)
Screenshot_۲۰۲۳۰۷۲۷_۲۲۵۱۰۹_Gmail
Screenshot_۲۰۲۳۱۱۲۴_۲۳۲۳۰۰_Microsoft 365 (Office)
Screenshot_۲۰۲۳۰۷۲۵_۲۳۳۵۰۹_Edge
Screenshot_۲۰۲۳۱۱۲۴_۲۳۲۲۴۳_Microsoft 365 (Office)
Screenshot_۲۰۲۳۰۷۲۶_۰۰۰۳۲۰_Edge
Screenshot_۲۰۲۳۱۱۲۴_۲۳۲۲۵۳_Microsoft 365 (Office)
Screenshot_۲۰۲۳۰۷۲۷_۰۱۴۷۲۲_Edge
Screenshot_۲۰۲۳۰۷۲۷_۰۱۴۷۰۵_Edge
Screenshot_۲۰۲۳۰۷۲۰_۰۸۳۰۴۷_YouTube
Screenshot_۲۰۲۳۰۷۲۰_۰۸۳۰۲۶_YouTube
Screenshot_۲۰۲۳۰۷۲۰_۰۸۳۰۲۱_YouTube
Screenshot_۲۰۲۳۰۷۲۰_۰۸۳۰۳۵_YouTube
Screenshot_۲۰۲۳۰۷۱۷_۰۱۱۵۵۰_Edge
Screenshot_۲۰۲۳۰۷۱۷_۰۱۱۵۴۴_Edge
Screenshot_۲۰۲۳۰۷۱۷_۰۱۱۶۰۳_Edge
Screenshot_۲۰۲۳۰۷۱۷_۰۱۱۵۵۷_Edge
Screenshot_۲۰۲۳۰۷۱۷_۰۱۱۶۱۵_Edge
Screenshot_۲۰۲۳۰۷۱۷_۰۱۱۶۰۹_Edge
Screenshot_۲۰۲۳۰۷۱۷_۰۱۱۵۳۷_Edge
Screenshot_۲۰۲۳۰۷۱۷_۰۱۱۵۲۹_Edge
Screenshot_۲۰۲۳۰۷۱۷_۰۱۱۵۲۰_Edge
Screenshot_۲۰۲۳۰۷۰۸_۲۳۳۲۴۸_Gallery
Screenshot_۲۰۲۳۰۷۰۸_۲۳۲۹۵۵_Gallery
Screenshot_۲۰۲۳۰۷۰۸_۲۳۰۵۴۸_Edge
Screenshot_۲۰۲۳۰۷۰۶_۲۳۱۳۴۱_Twitter
Screenshot_۲۰۲۳۰۷۰۶_۲۳۰۲۲۶_Twitter
Screenshot_۲۰۲۳۰۷۰۶_۲۳۰۰۴۹_Twitter
Screenshot_۲۰۲۳۰۷۰۴_۲۲۲۵۲۲_Edge
Screenshot_۲۰۲۳۰۷۰۴_۲۲۲۴۲۸_Edge
Screenshot_۲۰۲۳۰۷۰۳_۲۳۳۴۴۵_Edge
Screenshot_۲۰۲۳۰۶۰۱_۰۱۵۰۱۸_Chrome
Screenshot_۲۰۲۳۰۶۰۱_۰۱۴۸۲۵_Chrome
Screenshot_۲۰۲۳۰۶۰۱_۰۱۴۷۲۲_Chrome
Screenshot_۲۰۲۳۰۶۰۱_۰۱۴۷۴۵_Chrome
Screenshot_۲۰۲۳۰۶۰۱_۰۱۴۴۳۹_Chrome
Screenshot_۲۰۲۳۰۶۰۱_۰۰۳۰۳۵_Chrome
Screenshot_۲۰۲۳۰۶۰۱_۰۰۲۸۱۴_Chrome
Screenshot_۲۰۲۳۰۶۰۱_۰۰۳۰۴۷_Chrome
Screenshot_۲۰۲۳۰۶۰۱_۰۱۱۴۱۰_Edge
Screenshot_۲۰۲۳۰۶۰۱_۰۱۰۹۱۰_Edge
Screenshot_۲۰۲۳۰۶۰۱_۰۰۲۲۱۳_Chrome
Screenshot_۲۰۲۳۰۶۰۱_۰۰۲۱۲۷_Chrome
Sor
Screenshot_۲۰۲۳۰۵۲۸_۲۳۰۹۳۰_Edge
Sorry 
Screenshot_۲۰۲۳۰۵۲۶_۰۲۵۶۳۹_Outlook
![Uploading Screenshot_۲۰۲۳۰۵۲۵_۰۷۲۰۵۰_Edge.jpg…](sorry about teamthat sended to me with the all my heart ❤️  github.com. Thank you somuch that sent new ducoment thus dear collection only is a issue concern and worried install for my assest token in a hardware wallet offer and install team for me in blockscreen.com shared to YouTube  of 2 device please discover about issuse 12 recover pharse and like USB  connect to laptop  but if off wallet ledger you can hodying my BTC crypto coins coldwall please have a request like pro API write price I think of liquidity but no wanna throught contact the first install my wallet extension browser creditcard ;github.com for new team that sent to my account please now install extension browser trust wallet for me please contact  I will not get 10million USDT Fiat currency  due havnot wallet I swear I am worried and concern to GOD times connect wallet and transfer  to my wallet if install extensio browser 
to get airdrops in page Lido.fi ,ETH.curve.fi.compound and other my financial donot end  thank you please keep my private privacy and keep of my ducoment and amount value price BTC coinon database  blochair ;BTC on marketplace data confime and avaliable data my assest BTzc coin and I forget about liquidity  please help me to get my USDT liquidity  my fund BCH in zsite difa site is ference hasnot no address 32 orc43 by code or not transaction  on blockstream.com .pleasure Requesting discover information  a site to get liquidity  is Address of github.com

**Comment by ALIR86** [comment]
Please privacy privacy policies of my funds and a question why you came to blockstream and delete  amount  value price my addresses confimed wrute:confidential and in the end that leave wrote a addresses personaly security me confidential who was your means that automatically green wallet they had downloaded fast of Google play that stiped download and your means about assest a one not correct write an delect amount value  price and interest  word :*(confidential )*this is illlegal transaction legall and officialy and am owner if you only for information to BTC or ads or sale my information github.com  and give me a address  that wrote to name :(assest now I sent my pvt ducoments to you true to you please donot break use or any think !!!wasnot correct I was so sad of  this behavior your   good night this team make.com sign  protect of my private  privacy safe and any things about my assest okay I. true to github.com?! ALI ROSTAM  ABADI the ownership

**Comment by nikola-matic** [comment]
> some other tests seems to be breaking but totally unrelated with this PR changes @cameel @nikola-matic @ekpyron

Hi @molecula451, the PR looks good, but unfortunately, our `breaking` branch has not been kept up to date for quite a while now, and until we get it up to scratch, we'll not be accepting any breaking changes, so I'll close the PR. Once we fix the base branch (`breaking`), I'll ping you and we can re-open this PR.

Sorry again, I know this is the second PR you've opened regarding the dropping of `--opcodes`.

**Comment by molecula451** [comment]
the branch is available in the fork so that when reopen happens

**Pull request closed without merging**
