### PR TITLE
Make msize constant in yul interpreter.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Comment by leonardoalt** [comment]
Test failing

**Comment by chriseth** [comment]
Updated.

**Review by bshastry — APPROVED** [review]
LGTM

**Comment by chriseth** [comment]
We might not want to merge this and use the other "fix" instead.

**Comment by chriseth** [comment]
Superseeded by https://github.com/ethereum/solidity/pull/6840

**Pull request closed without merging**
