### PR TITLE
Remove ReasoningBasedSimplifier from libyul

### PR DESCRIPTION
**Pull request by blishko**
Due to a design decision to move away from a bundled SMT solver (#14325), ReasoningBasedSimplifier in its current form cannot be use any longer. This is a necessary step to allow a unified way to call solvers using only SMTLIB interface.

Since this optimization pass has always been marked as highly experimental and never turned on by default, it should be OK to remove it.

### CODE REVIEW

**Review by ekpyron — DISMISSED** [review]
Looks good to me - I'm pinging @cameel about the phaser tests - they shouldn't be affected by the PR, not sure what's going on with them here.

**Comment by blishko** [comment]
That was my bad, I forgot to delete the letter `R` from the chromosome test, after I removed `ReasoningBasedSimplifier`.

**Comment by blishko** [comment]
Should we add an entry to the changelog about this?

**Comment by ekpyron** [comment]
Yeah, a changelog entry would be nice, then we can merge!

**Comment by blishko** [comment]
@ekpyron , entry added. Can you check it and re-approve if it is OK?

**Review by ekpyron — APPROVED** [review]

**Pull request merged**
