### PR TITLE
Dropping --opcodes support

### PR DESCRIPTION
**Pull request by molecula451**
Relates: #14033

No surprises
Compiler output PR build
```
./solc --opcodes
unrecognised option '--opcodes' 
```

### CODE REVIEW

**Comment by molecula451** [comment]
@nikola-matic @cameel

**Comment by nikola-matic** [comment]
I have a feeling some tests are about to start failing :) Did you run `./tests/cmdlineTests.sh`?

**Comment by nikola-matic** [comment]
It's also gonna need a changelog entry.

**Comment by molecula451** [comment]
> 

i had that same feeling, looking at the shell files

**Comment by ekpyron** [comment]
The problem is that I'd say we'd have to consider this a breaking change, so we can't just drop it on ``develop`` (and we currently don't keep the ``breaking`` branch up to date)

**Comment by molecula451** [comment]
> The problem is that I'd say we'd have to consider this a breaking change, so we can't just drop it on `develop` (and we currently don't keep the `breaking` branch up to date)


Didn't read that, should I point the PR to `breaking` branch?

I'm making last touches to shell tests, and adding entry log as pointed by niko-matic


maybe you can fetch the PR to `breaking` after merges?

**Comment by molecula451** [comment]
> > The problem is that I'd say we'd have to consider this a breaking change, so we can't just drop it on `develop` (and we currently don't keep the `breaking` branch up to date)
> 
> Didn't read that, should I point the PR to `breaking` branch?
> 
> I'm making last touches to shell tests, and adding entry log as pointed by niko-matic

maybe you can fetch the PR to `breaking` after merges?

**Comment by molecula451** [comment]
Alright best thingy here, it's i will finish touching the tests, then make pass CI and I will re-open another PR pointing to `breaking`, you guys decide which one to merge

**Comment by ekpyron** [comment]
We cannot merge this as is since this is a breaking change.

**Pull request closed without merging**
