### PR TITLE
Add Solidity alias to Module in the Emscripten build

### LINKED ISSUE #8536: Introduce "Solidity" alias for emscripten module
Transitional issue for https://github.com/ethereum/solidity/issues/8157

### PR DESCRIPTION
**Pull request by axic**
Fixes #8536.

### CODE REVIEW

**Comment by axic** [comment]
@ekpyron here's the change. Need to locally verify this in Remix. (Can't verify in solc-js as browser loading is not tested there.)

**Comment by ekpyron** [comment]
We could, of course, also already set the ``EXPORT_NAME`` option for the build and add a reverse alias ``Module = Solidity`` to the file. That might be better, don't you think?

**Comment by axic** [comment]
> We could, of course, also already set the EXPORT_NAME option for the build and add a reverse alias Module = Solidity to the file. That might be better, don't you think?

Yes, that actually sounds like a better strategy. Will do it here.

**Comment by ekpyron** [comment]
Yeah, I was afraid that this isn't that easy with javascript scoping and globals and stuff...

Before the change soljson.js did this in the beginning:
```
"use strict";var Module=typeof Module!=="undefined"?Module:{};
```
After changing the setting it wraps everything in a function and does this in the beginning:
```
var Solidity = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(Solidity) {
  Solidity = Solidity || {};

"use strict";var Module=typeof Solidity!=="undefined"?Solidity:{};
```
and additionally this in the end
```


  return Solidity
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = Solidity;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return Solidity; });
    else if (typeof exports === 'object')
      exports["Solidity"] = Solidity;
    ;/* backwards compatibility */var Module = Solidity;
```

**Comment by ekpyron** [comment]
I mean: since it's possible to predefine ``Module`` and set configuration fields in it, I'm generally not sure we'll get around with a simple alias...

**Comment by leonardoalt** [comment]
ping @axic

**Comment by axic** [comment]
> since it's possible to predefine Module and set configuration fields in it

@ekpyron I'm not sure I follow, what configuration fields?

I'd also suggest to wait for the emscripten update and see if that changes any of this.

**Comment by ekpyron** [comment]
@axic For the record here again what I wrote in the channel. I'm basically talking about this:
https://emscripten.org/docs/api_reference/module.html#affecting-execution

You can e.g. define ``Module = {} Module['onAbort'] = ...`` *before* loading ``soljson.js`` to affect its execution. We may figure out that none of the options available this way make any sense for ``soljson.js``, but e.g. ``onAbort`` might, so we should think about it in any case.

If we just change it, so that ``Module`` is just an alias *after* the fact, then we'll break any such use.

**Comment by chriseth** [comment]
I'm closing this because the benefits are not clear and it will lead to serious disruption in the tooling.

**Pull request closed without merging**
