### PR TITLE
Add aragon to external tests.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Review by axic — DISMISSED** [review]

**Comment by axic** [comment]
Needs the version replacement hack:
```
Replace Truffle's Assert.sol with a known good version
Error parsing /tmp/tmp.8o7Hhkolbp/contracts/acl/ACL.sol: ParsedContract.sol:3:1: ParserError: Source file requires different compiler version (current compiler is 0.5.4-develop.2019.1.31+commit.eb2128de.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
import "../apps/AragonApp.sol";
^----^
Compilation failed. See above.
Exited with code 1
```

**Comment by chriseth** [comment]
Weird - the error seems to cite the wrong line in the source file...

**Comment by axic** [comment]
Unfortunately it isn't 0.5 compatible:
```
Replaced fixed-version pragmas...
Replace Truffle's Assert.sol with a known good version
Error parsing /tmp/tmp.CB1Ry48xQw/contracts/lib/ens/AbstractENS.sol: ParsedContract.sol:5:42: ParserError: The state mutability modifier "constant" was removed in version 0.5.0. Use "view" or "pure" instead.
    function owner(bytes32 _node) public constant returns (address);
                                         ^------^
Compilation failed. See above.
Exited with code 1
```

**Comment by chriseth** [comment]
oh wow, I didn't know that!

**Pull request closed without merging**
