### PR TITLE
Only use yulAssert and not solAssert in libyul

### PR DESCRIPTION
**Pull request by axic**
Repeated what was done in #7884.

### CODE REVIEW

**Comment by hrkrshnn** [comment]
I think replacing `#include <liblangutil/Exceptions.h>` by `#include <libyul/Exceptions.h>` should fix the CI issues.

**Comment by axic** [comment]
> I think replacing #include <liblangutil/Exceptions.h> by #include <libyul/Exceptions.h> should fix the CI issues.

Thanks, fixed!

**Review by hrkrshnn — APPROVED** [review]

**Review by ekpyron — APPROVED** [review]
I actually thought this had already been done!

**Comment by axic** [comment]
> I actually thought this had already been done!

Was done once but then people kept adding things using `solAssert`.

**Pull request merged**
