### PR TITLE
Refactor error ID checker script

### PR DESCRIPTION
**Pull request by a3d4**
Added `--fix` option to the script to separate checking and fixing error IDs.

### CODE REVIEW

**Review by hrkrshnn — DISMISSED** [review]
LGTM!

**Review by mijovic — DISMISSED** [review]

**Review by Marenz — DISMISSED** [review]
The code looks good, the only thing I wonder about is, shouldn't we make the action that we'll do most the default (that is, fixing), just from a UX perspective?

**Comment by a3d4** [comment]
@Marenz 

> shouldn't we make the action that we'll do most the default (that is, fixing), just from a UX perspective?

I had the same argument and asked the same question myself.

I think that `check_error_ids --fix` is more conventional than `fix_error_ids --nofix`.

If the command line is too verbose for everyday use we can go for a one-liner script `fix_error_ids.sh` == `python check_error_ids.py --fix --noconfirm`. Another minor convenience could be to use **[script-dir]/..** as the root, so one could run it from any directory.

**Comment by Marenz** [comment]
> I think that check_error_ids --fix is more conventional than fix_error_ids --nofix.

Well, you could have instead `fix_error_ids --check` ;)

A oneline is also fine by me though.

**Comment by chriseth** [comment]
I agree, the default option should be fix.
Maybe we should even run this from `cmdlinetsts.sh`? It currently auto-fixes problems with the bug list in a similar way - it fails if there was something to fix.

**Comment by a3d4** [comment]
@Marenz @chriseth 
OK, fixing by default. (Although I believe this is not how `fsck` works, for instance. :) )

> Maybe we should even run this from cmdlinetsts.sh?

That would be fine for initial assignments (`0000_error` to `3141_error`). But I am not sure about fixing duplicates automatically. They might require special care.

**Review by chriseth — APPROVED** [review]

**Pull request merged**
