### PR TITLE
[Yul] Remove side-effect-free statements.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Review by leonardoalt — DISMISSED** [review]

**Comment by chriseth** [comment]
@leonardoalt sorry, did some changes to the readme and the header file doc string, because they did not reflect the changes.

**Comment by leonardoalt** [comment]
Windows compilation is failing

**Comment by chriseth** [comment]
@leonardoalt this is a problem in develop (already fixed). Do you want me to rebase?

**Review by leonardoalt — DISMISSED** [review]
No, it's fine, had approved it before already.

**Pull request merged**
