### PR TITLE
Add workaround to support pop() in inline assembly

### LINKED ISSUE #1118: Inline assembly: include function style pop
`pop` currently cannot be used in function-style: `pop()`

### PR DESCRIPTION
**Pull request by axic**
Fixes #1118.

I'm a bit torn whether we should have it this way or not.

### CODE REVIEW

**Comment by pirapira** [comment]
I think it's clear what `pop()` means.

(Perhaps, we can even think about a generalization where `add(3)` adds 3 to the topmost stack element...?)

**Comment by axic** [comment]
I'm leaning towards that we don't need this, because every functional instruction should be balanced. Either assigned or popped:

```
let a := div(1, 2)
let b = call(...)
pop(call(...)) // don't care about the return value
```

**Comment by pirapira** [comment]
@axic That's a sane judgment.  (I saw strange behavior when I left stack elements after inline assembly....)  Close?

**Comment by chriseth** [comment]
This change looks strange, why does pop need special handling? How is it different from `sstore(x,y)`? In the documentation, pop is marked by `*`, where sstore is marked by `-`, that should also be fixed.

I agree that we should not allow a non-zero number of items on the stack for functional style notation, but I would actually prefer to have an explicit `pop` in that case and create a warning if that is not the case.

**Comment by chriseth** [comment]
Ok, it might be that I misunderstood the PR :-)

`pop()` should not be allowed, because it takes an argument. On the other hand, things like `pop(sload(2))` should be allowed, and also `2 sload pop`, but not `2 sload pop()`.

**Review by chriseth — CHANGES_REQUESTED** [review]
`pop()` should not be valid.

**Comment by pirapira** [comment]
Nobody really wants this one.  I'm closing this.

**Pull request closed without merging**
