### PR TITLE
Redundant store eliminator.

### LINKED ISSUE #6728: [YulOpt] Redundant Store Elimination
This optimizer step is the equivalent of the RedundantAssignEliminator, but for storage and memory. It could use https://github.com/ethereum/solidity/issues/6727 as a dependency.

Since the RedundantAssignEliminator does not use the DataFlowAnalyzer, we could also make it a little easier, though: Eliminate two stores if they store at the same symbolic location, i.e. variable, and that variable has not been reset in the meantime.

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/6728

### CODE REVIEW

**Comment by chriseth** [comment]
This turns 
```
contract C {
  struct S { uint16 a; uint16 b; uint16 c;}
  S s;
  function f() public {
    s = S(1,2,3);
  }
}
```

into
```
sstore(_1, or(and(or(and(or(and(sload(_1), not(65535)), 0x01), not(0xffff0000)), 131072), not(0xffff00000000)), 0x0300000000))
```

(The unoptimized IR has three function calls that each perform an sstore)

The single sload is still needed. I'm not sure how it would look if the storage slot would be completely filled, but I guess it would not be able to reason that all bits are overwritten.

**Comment by chriseth** [comment]
The good thing here is also that, in contrast to the old codegen/optimizer, it does not matter whether you use `s = S(1,2,3)` or `s.a = 1; s.b = 2; s.c = 3;` or even `s.a = 1; s.b = aFunctionThatDoesNotAccessStorage(); s.c = 3;`

**Comment by chriseth** [comment]
Should check https://github.com/ethereum/solidity/issues/9831

**Comment by mijovic** [comment]
I can check if it helps with #9831

**Comment by chriseth** [comment]
I checked copying storage structs, and it does not always work because the inliner fails to inline the right functions. We might put a weight to enforce inlining of functions that are expensive to execute but small in comparison.

**Comment by mijovic** [comment]
I did a rebase to latest develop, wanted to rebase one of my branches over this one to check gas costs

**Comment by chriseth** [comment]
I have the feeling that this is horribly slow due to the data flow analyzer.

**Comment by chriseth** [comment]
I think `DataFlowAnalyzer` is not too slow if everything is in SSA.

The main problem with this PR is that it is wrong - see one of the new tests: We cannot remove stores if there was an `sload` from it after it has been overwritten, and this is not tested here.

**Comment by chriseth** [comment]
Closing this in favour of the mechanism described in https://hackmd.io/jWoLK7ccTHeIYXEGMayHXQ?both

**Pull request closed without merging**
