### PR TITLE
Create code bugger

### PR DESCRIPTION
**Pull request by mehulk99**
use of crc with additional data writes is not necessary

### CODE REVIEW

**Comment by chriseth** [comment]
Thanks for your pull request! Could you explain a little more what it wants to achieve?

**Comment by mehulk99** [comment]
> Thanks for your pull request! Could you explain a little more what it wants to achieve?

this is cyclic redundancy check code it binary bits

**Review by mehulk99 — COMMENTED** [review]
no it will give wrong answer check it by taking example

**Comment by chriseth** [comment]
Thanks for your answer! Since I do not really see how this relates to the Solidity compiler, I will have to close this pull request. If I misunderstood you, please feel free to re-open it.

**Pull request closed without merging**
