### PR TITLE
use rst syntax highlighting

### PR DESCRIPTION
**Pull request by morenoh149**

### CODE REVIEW

**Comment by morenoh149** [comment]
CI seems to fail, enabling solidity syntaxhighlighting must require using `Solidity` or updating pygments. Skimming https://github.com/ethereum/solidity/search?utf8=%E2%9C%93&q=pygments&type=

**Comment by chriseth** [comment]
Can you explain what you wanted to do here? We have our (well not very up to date) lexer set as default for all code here: https://github.com/ethereum/solidity/blob/develop/docs/utils/SolidityLexer.py

**Comment by chriseth** [comment]
Oh now I see, somehow the highlighting has been switched off on readthedocs...

**Comment by chriseth** [comment]
It seems to still work locally.

**Comment by chriseth** [comment]
Seems to be a bug on readthedocs: https://github.com/rtfd/readthedocs.org/issues/4072

**Comment by chriseth** [comment]
Hm, now it seems to be working again...

**Comment by morenoh149** [comment]
my goal was to enable syntax highlighting on https://solidity.readthedocs.io/en/v0.4.23/solidity-by-example.html I'll have to clone the repo and see how to enable it. Sadly the fix wasn't as easy as doing what would work on github (which is what I tried).

**Comment by chriseth** [comment]
I think this was an error on the readthedocs side. It is working for https://solidity.readthedocs.io/en/develop/ now. I wonder at which point the old versions stopped working and whether we can get them back somehow...

**Comment by morenoh149** [comment]
ok, I'll subscribe to that issue

**Pull request closed without merging**
