### PR TITLE
Move note on decompiling

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
As discussed wit @axic here's the moved decompiling note, I ended up removing quite a lot, I'm starting to wonder if we include it at all.

### CODE REVIEW

**Comment by axic** [comment]
I think you forgot to add porosity after evmdis?

**Comment by ChrisChinchilla** [comment]
@axic It's not maintained any more, so we removed it. So yeah, wonder if this is worth mentioning at all now.

**Comment by axic** [comment]
> It's not maintained any more, so we removed it.

Oh I see, I guess we can argue for both, but if we do mention it, it should state it is unmaintained.

I'm not keen on mentioning it.

**Comment by ChrisChinchilla** [comment]
@axic Cool, then I think this PR is complete :)

**Review by axic — APPROVED** [review]

**Pull request merged**
