### PR TITLE
Add SPDX license identifier if not present already in source file

### LINKED ISSUE #9220: Add SPDX license identifier to the compiler source code
Since we advocate for this in Solidity programs, we should bite the bullet and also include it in all the compiler source code 🙊

### PR DESCRIPTION
**Pull request by sacgrover**
Fixes: #9220

### CODE REVIEW

**Comment by sacgrover** [comment]
@leonardoalt Could you please rerun the fail one. Seems like failed without reason.

**Comment by christianparpart** [comment]
@sacgrover looking at all 569 files manually and visually string-check iff the license values match is really challenging. How did you create the diff? Did you use a small helper script (with a technique described in the prior PR) or did you touch them all manually?

**Comment by sacgrover** [comment]
@christianparpart Obviously, not manually :) I used VS Code my favorite editor to find the string and replace it with (search string + extra licence line). A mentioned in last PR, I changed only GPL licensed files.

**Review by chriseth — APPROVED** [review]
Thanks a lot!

**Pull request merged**
