### PR TITLE
Push images to docker hub.

### PR DESCRIPTION
**Pull request by aarlt**
I think the `DOCKERHUB_TOKEN` secret was not set yet.

### CODE REVIEW

**Comment by aarlt** [comment]
@chriseth @ekpyron @cameel I'm not sure whether we can really use this solution. I think everyone will then be able to overwrite our docker images. 

Ah, it seem to depend on what properties are set for that secret, right?

**Comment by aarlt** [comment]
Ah probably thats the problem here and my user can not read the secret because of permissions?

**Comment by ekpyron** [comment]
As long as we use sha256 digests to refer to the images, permissions don't really matter.

**Comment by ekpyron** [comment]
Can you try pushing a branch in the repo instead? I don't think secret tokens will be available from PRs from forks (that'd be literally anyone having access to it).

**Comment by ekpyron** [comment]
Closing in favour of https://github.com/ethereum/solidity/pull/9430 (which is exactly the same just from a branch in our repo, not from a fork, which makes it work)

**Comment by aarlt** [comment]
Nice! So that was also a good test :)

**Pull request closed without merging**
