### PR TITLE
[buildsystem] Improve solidity embeddability.

### PR DESCRIPTION
**Pull request by aarlt**

### CODE REVIEW

**Comment by aarlt** [comment]
I just created a repository showing how solidity can be easily embedded: [cmake_vcpkg_solidity](https://github.com/aarlt/cmake_vcpkg_solidity).

**Review by r0qs — APPROVED** [review]
LGTM

**Comment by r0qs** [comment]
> I just created a repository showing how solidity can be easily embedded: [cmake_vcpkg_solidity](https://github.com/aarlt/cmake_vcpkg_solidity).

I approved, although I couldn't test using your example:
```
Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/liblzma/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:170 (include)


error: building liblzma:x64-linux failed with: BUILD_FAILED
Elapsed time to handle liblzma:x64-linux: 500 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+liblzma
  ```
  
  The error seems to be related with the recent problems in `liblzma`: https://github.com/microsoft/vcpkg/issues/37893 and https://tukaani.org/xz-backdoor/

**Comment by cameel** [comment]
I wonder why it tries to pull in liblzma in the first place. I hope none of our dependencies depends on it?

**Pull request merged**
