### PR TITLE
[SMTChecker] Fix fixed point inc/dec

### LINKED ISSUE #8817: [SMTChecker] ICE in SMTEncoder::mergeVariables because "trueIndex == falseIndex"
## Description

```
pragma experimental SMTChecker;
contract C {
  fixed x;
  address owner;
  modifier onlyOwner {
    if (msg.sender == owner) _;
  }
  function f() public onlyOwner { x--; }
}
```

throws

https://github.com/ethereum/solidity/blob/602b29cba782bae83769c1723e2b9cae2221d05d/libsolidity/formal/SMTEncoder.cpp#L1456

```
/Users/alex/Projects/solidity/libsolidity/formal/SMTEncoder.cpp(1481): Throw in function void solidity::frontend::SMTEncoder::mergeVariables(const set<const solidity::frontend::VariableDeclaration *> &, const smt::Expression &, const solidity::frontend::SMTEncoder::VariableIndices &, const solidity::frontend::SMTEncoder::VariableIndices &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: 
[solidity::util::tag_comment*] = 
```

## Environment

- Compiler version: latest develop

### PR DESCRIPTION
**Pull request by leonardoalt**
Fixes https://github.com/ethereum/solidity/issues/8817

by allowing the arithmetic operations to be computed on FixedPoint variables as well.

### CODE REVIEW

**Review by mijovic — APPROVED** [review]

**Comment by leonardoalt** [comment]
We can't add a test for this one because it will fail code generation.

**Comment by ekpyron** [comment]
> We can't add a test for this one because it will fail code generation.

That's a lie, isn't it :-)? The same is true for https://github.com/ethereum/solidity/pull/9067/files, isn't it? Those throw in codegen as well and it's still fine to add them - apparently the smt tests don't call codegen...

**Comment by leonardoalt** [comment]
Yes, that's true!
Only figured out later that if the function is internal it's fine, because of no codegen

**Comment by leonardoalt** [comment]
As in: if it's an internal function that is never used

**Pull request merged**
