### PR TITLE
Require ";" after "_"

### PR DESCRIPTION
**Pull request by chriseth**
Fixes https://github.com/ethereum/solidity/issues/535

### CODE REVIEW

**Comment by walter-weinmann** [comment]
This should also be considered in grammar.txt.

**Comment by chriseth** [comment]
@walter-weinmann actually I think it is already like that in grammar.txt

**Comment by walter-weinmann** [comment]
The current grammar.txt says:

```
Statement = IfStatement | WhileStatement | ForStatement | Block | PlaceholderStatement |
            ( Continue | Break | Return | Throw | SimpleStatement | ExpressionStatement ) ';'
```

and

`PlaceholderStatement = '_'
`

So I think it is not considered.

**Comment by chriseth** [comment]
@walter-weinmann sorry, mis-read the parentheses.

**Comment by pirapira** [comment]
The changes make sense and I think this can close #535.

**Pull request merged**
