### PR TITLE
Include visibility level for functions in AST

### LINKED ISSUE #1328: AST output should contain visibility levels for functions
(Follow up from #1325.)

### PR DESCRIPTION
**Pull request by federicobond**
Closes #1328

### CODE REVIEW

**Review by pirapira — APPROVED** [review]
Looks good to me.

**Comment by axic** [comment]
Assuming nobody is using the AST - if they do, this was a breaking change 😉

**Comment by federicobond** [comment]
AST changed with #1497 too, so it would be wise to add an entry to the changelog.

**Comment by pirapira** [comment]
OK.  I'll add a changelog entry.  I guess #1497 was a bug fix.  Maybe this one too.

**Pull request merged**
