### PR TITLE
Sort yul functions by creation time.

### PR DESCRIPTION
**Pull request by chriseth**
Still todo:
- [x] check for nondeterminism in IR code generator (all files)
- [x] check optimizer stages to run in call-order.

### CODE REVIEW

**Comment by chriseth** [comment]
This results in higher gas costs :)

**Comment by ekpyron** [comment]
> This results in higher gas costs :)

Crazy :-).

**Review by ekpyron — DISMISSED** [review]

**Comment by ekpyron** [comment]
It affects ABIv2 code in old codegen as well, doesn't it? Might be worth a changelog entry then...

**Comment by chriseth** [comment]
Yes it does. I would also like to wait for the bytecode comparison :)

Also there is still a todo box to be ticked.

**Comment by chriseth** [comment]
@ekpyron what would you suggest for the changelog?

**Comment by ekpyron** [comment]
Something like ``Bugfixes: Code Generation: Use stable source order for ABI coder v2 helper functions.`` or the like?
Maybe ``, fixing potential non-determinism.``?

**Review by ekpyron — DISMISSED** [review]

**Comment by ekpyron** [comment]
Changelog conflict and unrelatedly breaking CI...

**Review by ekpyron — APPROVED** [review]

**Comment by chriseth** [comment]
Waiting for https://github.com/ethereum/solidity/pull/11911 before merging this.

**Comment by ekpyron** [comment]
> Waiting for #11911 before merging this.

Not sure why we have to wait, but #11911 should also be fine to merge.

**Pull request merged**
