### PR TITLE
[Sol->Yul] Fix mapping conversion.

### PR DESCRIPTION
**Pull request by chriseth**

### CODE REVIEW

**Review by cameel — APPROVED** [review]
It works so I'm marking as accepted but I have two remarks:
- We do not have many semantic tests covering tuple assignments. I think we should have at least one for each type. I checked manually and all types I tried other than mappings fortunately seem to work with the new codegen (even nested tuples do) but would be better to have that as a regression test.
- Wouldn't it be better to generate a simple assignment rather than a conversion function when types match for a specific tuple component? That would be more consistent with what we're doing in case of simple assignments (in `declareAssign()`).

**Comment by chriseth** [comment]
Why do you think it would be better to generate an assignment without a conversion function?

**Comment by cameel** [comment]
Because the conversion is a no-op.

**Comment by chriseth** [comment]
There are many conversions that are no-ops.

**Comment by cameel** [comment]
ok, not just because it's a no-op but because it's a no-op and different from what a simple assignment does. I.e. `uint x = 1` does not add a conversion while `(uint x, uint y) = (1, 1)` does.

I'm actually not 100% sure a conversion between things of the same type is always equivalent to an assignment, I haven't analyzed the conversion function for all types that closely. If it is, the conversion just makes it harder to figure that out. It it's not - why? I'd expect it to behave the same way with and without a tuple.

**Pull request merged**
