### PR TITLE
Fix changelog for the bugfix about immutables with return in base constructor

### PR DESCRIPTION
**Pull request by chriseth**
@Marenz @ekpyron please check if this change is correct.

### CODE REVIEW

**Comment by chriseth** [comment]
Also please turn test/libsolidity/syntaxTests/immutable/base_ctor_return_no_immutables.sol  into a semantic test if there is not already one. We need to check that the immutable is properly initialized.

**Review by cameel — APPROVED** [review]

**Comment by cameel** [comment]
Looking at the test case in #12523, it's correct:
https://github.com/ethereum/solidity/blob/2c4c8264e4428ff45cfd5f8f9b5458f1044ba8aa/test/libsolidity/syntaxTests/immutable/base_ctor_return_no_immutables.sol#L1-L10

**Review by ekpyron — APPROVED** [review]
Yeah, looks like that's what it should have said.

**Review by Marenz — APPROVED** [review]
That is indeed what it should have said

**Pull request merged**
